### ISSUE TITLE
Replace $ entity prefix with underscore symbol

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1000]
It is required for Kotlin adoption

**Comment by alexbudarov** [comment]
What are you going to do with all entity names inserted to database by previous versions?

**Comment by jreznot** [comment]
Probably, we will use compatibility layer that will recognize both separators and migrate old records if possible.

**Comment by knstvk** [comment]
What about the following:
- Framework properly recognizes both `ns_Name` and `ns$Name` names
- Existing entities remain `ns$Name` to avoid data migration
- New entities are created with `ns_Name`
- Existing entities migration is delayed to a future version, possibly when we extract security and other to app components.

**Comment by andreysubbotin** [comment]
For QA: 
Check delete policy localization messages for old and new entity names (https://doc.cuba-platform.com/manual-6.9/delete_policy.html)
Check security constraint localization messages for old and new entity names (https://doc.cuba-platform.com/manual-6.9/exceptionHandlers.html)
