### ISSUE TITLE
"Login failed" is shown when the screen is opened by external link and unexistent view is defined in parameters

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1010]
### Environment

- Platform version: 6.9.1 
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example
1) Start application server
2) Do not login to the application
3) Open URL http://localhost:8080/app/open?screen=sec$User.edit&item=sec$User-60885987-1b61-4247-94c7-dff348347f93-user.edit1 in browser (view "user.edit1" does not exist)
4) Press the Submit button in  the application login form

- Actual behavior
System error
![изображение.png](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/4fad7b67-52ad-4fbd-bd2a-23f7284d54c6)
However the user is successfully authenticated

**Comment by dtsaryov** [comment]
Related to [PL-10608 Improve link handling extension mechanism](https://youtrack.cuba-platform.com/issue/PL-10608)
