### ISSUE TITLE
Autocomplete concatenates strings instead of replacing prefix

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1015]
#### Environment
- Platform version:  6.9.2
- Browser: all browsers

#### Description of the bug or enhancement

1. Open group constraints screen
2. Select any entity
3. Go to the `Where clause` field
4. Write some letters after {E}
5. Press CTRL+SPACE
6. Select one of the options from the drop-down list

**A.R.**
Strings will be concatenated

![autocomplete-cucustomer.gif](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/41ee66ab-624b-4ab7-aa65-86bdea60418d)

**Comment by soraksh** [comment]
https://github.com/cuba-platform/cuba/commit/23c1102a8f43cfab7594f74991a3f754749a621b
