### ISSUE TITLE
Improvement of the FTS components and API for showing search results

### ISSUE THREAD

**Issue by devmix** [cuba-platform/cuba#1020]
### Environment
- Platform version: 6.9.1
- Client type: Web
- Component: FTS

#### Minimal reproducible example
Any browser screen with FTS search.

#### Actual behavior
The founded hits shows in the tooltips for each row of the table. In this case I can only view a founded entities plus some information via tooltips, but that not always comfortable for an users. For example, when I want to see not only founded entities but also information which entity field or attached file (FileDescriptor) contains a search word then there only small tooltip and no any way to open that file.

#### Expected behavior
The first, it good to have ability to work not only with a table and tooltips but have some mechanism to show hits in a custom components, e.g. DataGrid with custom DetailsGenerator which will be opened for each row or new and configurable component for showing FTS results. That all for a standard browser screens.

The second one, there is some missed information in the hits, e.g. I can't create a link to related entity (for example FileDescriptor) because the hit does not contains such information (only name of file).

**Comment by knstvk** [comment]
Issue moved to [cuba-platform/fts #31](https://github.com/cuba-platform/fts/issues/31) via [**ZenHub**](https://www.zenhub.com/)
