### ISSUE TITLE
Disable REST v1 by default

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#1027]
It's enabled in web / portal modules though not documented.

Check:

- http://localhost:8080/app/dispatch/api/login?u=admin&p=admin&l=ru 
- http://localhost:8080/app-portal/api/login?u=admin&p=admin&l=ru

**Comment by jreznot** [comment]
In order to enable REST v1 in project developers have to define it explicitly:
```
<context:component-scan base-package="com.haulmont.cuba.restapi"/>
```

Web: `dispatcher-spring.xml`
Portal: `portal-dispatcher-spring.xml`
