### ISSUE TITLE
Mask REST API tokens in logs

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#1028]
REST API tokens appear in logs ([on each request](https://github.com/cuba-platform/cuba/blob/master/modules/rest-api/src/com/haulmont/restapi/auth/CubaRestLastSecurityFilter.java#L117) in [other places](https://github.com/cuba-platform/cuba/blob/master/modules/rest-api/src/com/haulmont/restapi/auth/ClientProxyTokenStore.java#L116)) which may be harmful since logs are available from UI/can be accidentally copied.

**Comment by gorbunkov** [comment]
Masking may be disabled by setting the **cuba.rest.tokenMaskingEnabled** application property value to **false**
