### ISSUE TITLE
Separate cubaId for testMode and debug id for performanceTestMode

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1053]
### Environment
- Platform version: 6.9.1 
- Client type: Web

### Description of the bug or enhancement
`cuba.performanceTestMode` does not set debugIds for UI components. For this we have to set `cuba.testMode`.

----
### QA
`cuba.testMode` is used for generating cuba-id (you can see in the HTML DOM)
`cuba.performanceTestMode` is used for generating id (you can see in the HTML DOM)

*cuba.testMode*
1. Launch application with `testMode`
2. Open dev-tools in your browser
3. Look at the components that have cuba-id: they must have _only_ cuba-id (don't forget about menu)
4. For more confidence you can compare with 6.9 version in cubadev (used both test modes)

Components that especially affected by changes and must be checked:
**FtsField, UserIndicator, FieldGroup, PopupButton, TabSheet, Window, LogWindow, BreadCrumbs, ExceptionDialog**  

*cuba.performanceTestMode*
1. Launch application with `performanceTestMode`
2. Open dev-tools in your browser
3. Look at the components: they must have _only_ id (don't forget about menu)
4. For more confidence you can compare with 6.9 version in cubadev (used both test modes)

Also, try to record some scenario with jmeter, for instance:
1. login
2. open menu -> open users
3. try to do something
4. close screen
5. logout  

Then play scenario. In jmeter look at responses (they can be a little bit different but should do the same things)

**Comment by natfirst** [comment]
"cuba-id" format in the field group was changed
