### ISSUE TITLE
TokenList remove buttons misaligned in case token captions are wider than TokenList

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1062]
Source: https://www.cuba-platform.com/discuss/t/tokenlist-width-hides-the-individual-remove-entry-button-if-instance-name-is-longer/5787

![image](https://user-images.githubusercontent.com/6077149/42811628-2c5050c0-89cc-11e8-9a0a-a83b92992238.png)

**Comment by myatlevEvg** [comment]
There is no scrollbar for long tokens in havana for 6.10 platform


![image](https://user-images.githubusercontent.com/33958996/45754772-95f1c480-bc2d-11e8-8d6f-29b879942c21.png)
