### ISSUE TITLE
REST-API authentication does not work

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1065]
### Environment

- Platform version: 7.0.0

### Description of the bug or enhancement

See https://stackoverflow.com/questions/49122867/spring-boot-2-0-0-oauth2?rq=1

**Comment by gorbunkov** [comment]
See: https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/#troubleshooting
