### ISSUE TITLE
Provide replacement for havana theme with similar visual look and feel

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1067]
Variables already described in: Migration from Havana to feature-rich Halo theme 

https://doc.cuba-platform.com/manual-6.9/web_theme_extension.html#web_theme_migration

Improve the following aspects:

- hover color for Table rows
- editable / non-editable fields differences: #522 
- disable all animations
---
### Changes

Reworked following styles:
- DataGrid, TreeDataGrid
- Table
- Notification
- Dialog window
- Menu Bar
- Tab Sheet in Main window
- Login window

Migrated almost all png icons in components. Following components use FontAwesome:
- LookupField, PopupButton and other with dropdown list:
![image.png](https://images.zenhubusercontent.com/5ae335354b5806bc2bd0e9be/c73f5219-dace-43ac-81c7-b9f432ff8591)
- DateField
![image.png](https://images.zenhubusercontent.com/5ae335354b5806bc2bd0e9be/2a5ee5f3-b6e5-4a8c-8b7d-d9f9d9777987)
- Table column with ascending and descending sorts
![image.png](https://images.zenhubusercontent.com/5ae335354b5806bc2bd0e9be/0adb1671-b7c5-49d7-9f1b-44b70d3fe75f)
- Tree
![image.png](https://images.zenhubusercontent.com/5ae335354b5806bc2bd0e9be/ffc61219-0dbc-4bbe-ba8f-57d59090344d)
- Dialog window icons:
![image.png](https://images.zenhubusercontent.com/5ae335354b5806bc2bd0e9be/81e82fe2-96df-4a8d-874c-0c4f31e6c513)
- Close icon in the Tab:
![image.png](https://images.zenhubusercontent.com/5ae335354b5806bc2bd0e9be/91d402a6-85f9-4b53-9da0-72e6673f2720)
- ResizableTextArea:
![image](https://user-images.githubusercontent.com/22093943/46806198-0d6fcb00-cd78-11e8-94df-0d2e83c3ba75.png)

#### Table
* `$c-table-selected-row-cell-border-color` - cell border color of selected row;
* `$c-table-header-background-color` - background of header cell in table
* `$c-table-header-hover-background-color` - hover background of header cell in table
#### DataGrid
* `$c-datagrid-selected-row-cell-border-color` - cell border color of selected row
* `$c-datagrid-header-cell-background-color`  - header cell background color
* `$c-datagrid-header-cell-hover-background-color` - header cell hover background color

#### Table and DataGrid
* `$c-row-selection-background-color` - Table and DataGrid selection row color
* `$c-row-selection-text-color` - Table and DataGrid selection row text color

#### Window
* `$c-window-header-background-color` - Window header background color

#### Notifications
* `$c-notification-border-radius` - notification border radius

#### MenuBar
* `$c-menubar-submenu-outline-color` - outline color of submenu
* `$c-main-menu-popup-text-color` - text color of main popup menu

#### Main Window
* `$c-main-tabsheet-tab-caption-text-color` - caption color of tab in main tabSheet
* `$c-tabsheet-tab-close-text-color-hover` - hover color of close font-icon
* `$c-tabsheet-tab-close-text-color` - close font-icon color of tab in tabSheet
* `$c-app-workarea-background` - background color of application work area

**Comment by sukhova** [comment]
The font size is too small in Edge browser

**Comment by sukhova** [comment]
Some separators are missing from the menu in Edge browser
![56](https://user-images.githubusercontent.com/40686909/45488368-3d748000-b772-11e8-8c1a-44f3e6bd8991.jpg)

**Comment by sukhova** [comment]
The styled table does not display color in cell

![57](https://user-images.githubusercontent.com/40686909/45488894-e1126000-b773-11e8-84be-7d8850d60ba4.JPG)

**Comment by sukhova** [comment]
Checkboxes are not drawn correctly in the table in Edge browser

![59](https://user-images.githubusercontent.com/40686909/45489033-39e1f880-b774-11e8-906e-b185ee278874.JPG)

**Comment by sukhova** [comment]
The table header is drawn incorrectly in Edge browser

![13](https://user-images.githubusercontent.com/40686909/45489220-c8ef1080-b774-11e8-9c42-05cad987a93f.gif)

Such behavior occurs in “Users”, “Roles”, “External Files” browsers

**Comment by sukhova** [comment]
The styled tree does not appear stylized, but appears normal

**Comment by sukhova** [comment]
PickerField, LookupPickerField, SearchPickerField are drawed incorrectly in the Edge browser:

![14](https://user-images.githubusercontent.com/40686909/45489882-ac53d800-b776-11e8-9954-0ff558bc5613.gif)

**Comment by sukhova** [comment]
The DataGrid’s header style differs from Table’s header style

![63](https://user-images.githubusercontent.com/40686909/45490630-ad860480-b778-11e8-91da-d880cee69ff4.jpg)

**Comment by sukhova** [comment]
The right border of OptionsList is not drawn in Edge browser

![62](https://user-images.githubusercontent.com/40686909/45490780-140b2280-b779-11e8-9db2-2eaae26ff55d.JPG)

**Comment by jreznot** [comment]
Let's not fix button icons alignment, is default alignment in Vaadin

**Comment by Flaurite** [comment]
For QA:
For all brosers (IE11, Edge, Chrome, Opera, Firefox, Safari) check:
1. ResizableTextArea - resizable corner
2. DataGrid and TreeDataGrid styles.
Fon size isn't fixed, cause in old Havana theme was exactly the same font size.
