### ISSUE TITLE
Expand matched app properties after filtering with the "Refresh" button

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1076]
### Environment

- Platform version: 6.9-SNAPSHOT
- Client type: Web

### Description of the bug or enhancement

1. Open "Application Properties" screen
2. Enter some value into the property value text field
3. Click "Refresh"

A.R. Table is still collapsed.
But if user unfocuses textfield the table is expanded correctly.
In described case you can notice that the table is expanded and immediately collapsed

It is UX issue and probably we should "unlink" the text field and the "Refresh" button

![image](https://user-images.githubusercontent.com/6183810/42954156-14117e7c-8b8d-11e8-87b1-c88b554a9bf5.png)

**Comment by SemenSofronov** [comment]
There is no need to press the refresh button to perform a search, the search is performed by defocusing the search field or pressing Enter. Added some changes to the behavior of the refresh function. Now, after clicking the refresh button, the table expands if the search field is not empty or the item was selected.
