### ISSUE TITLE
App menu sub items don't have rounded corners in Firefox

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1078]
### Environment

- Platform version: 6.9-SNAPSHOT

- Client type: Web
- Browser: Firefox

### Description of the bug or enhancement

The `border-radius` rule doesn't work for submenu items due to `display: table-row` for item wrapper

Firefox:
![menu_ff](https://user-images.githubusercontent.com/6183810/42994096-2bc8d3bc-8c1e-11e8-8b1f-9cd5ec2fa630.png)

Chrome:
![menu_ch](https://user-images.githubusercontent.com/6183810/42994183-665730a0-8c1e-11e8-9346-893237481239.png)

**Comment by jreznot** [comment]
It is not supported by Firefox, TD elements cannot have rounded corners

**Comment by dtsaryov** [comment]
> It is not supported by Firefox, TD-like elements cannot have rounded corners
Yes, it is. But we have not consistent appearence now. We could try to find some workaround for it.

**Comment by jreznot** [comment]
It is not supported in Edge by the way and we have no rounded corners there from 5.4 version. And there is no such requests from community to fix this.
