### ISSUE TITLE
Group rows of GroupTable should have additional CSS class

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1087]
### Description of the bug or enhancement

- Minimal reproducible example

1. Group by column in GroupTable.
2. Open Developer Tools in web browser

![group-row](https://user-images.githubusercontent.com/1066152/43136882-1e12bb08-8f5b-11e8-80a0-f71d7d11b654.png)

- Expected behavior

Group row should have additional class name on TR element

- Actual behavior

Group row has the same CSS classes as regular rows

**Comment by SemenSofronov** [comment]
Now, group rows in GroupTable have the additional CSS class `c-group-row`
![image.png](https://images.zenhubusercontent.com/5b4d9e85edf0570a96a14fa2/c1bfda81-1d35-4c56-81ab-f97314dcc123)
