### ISSUE TITLE
Incorrect query generated when applying filter on query with left join

### ISSUE THREAD

**Issue by kaberc** [cuba-platform/cuba#1089]
### Environment

- Platform version: 6.8.5

### Description of the bug or enhancement
Query filter: when the base query contains JOIN, applied filter condition erases original WHERE.

[demo.zip](https://github.com/cuba-platform/cuba/files/2223595/demo.zip)
#### Steps to reproduce:
1. Open Application -> Shops.
1. Put something in search field.
1. Open app.log and find produced query.

The query in shop-browse.xml:
```
            <query>
                <![CDATA[select s from demo$Shop s
                left join fetch s.employees e
                where s.status <> 'deleted' and e.status <> 'deleted']]>
                <filter>
                    <c>s.name like :component$searchField</c>
                </filter>
            </query>
```
with not empty searchField should produce:
**EB:** `select s from demo$Shop s left join fetch s.employees e where (s.status <> 'deleted' and e.status <> 'deleted') and s.name like :component_searchField, max=10000`
but instead produces:
**AB:** `select s from demo$Shop s left join fetch s.employees where s.name like :component_searchField, max=10000`

**Comment by andreysubbotin** [comment]
FETCH JOIN doesn't support alias for path variable, e.g. `s.employees e` -> `s.employees`
System should be throw exception in that case.
Fixed in cuba-platform/cuba#496
