### ISSUE TITLE
Not localized Create action in the dynamic attribute screen visibility table

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1090]
### Environment

- Platform version: 6.9-SNAPSHOT
- Client type: Web

### Description of the bug or enhancement

![image](https://user-images.githubusercontent.com/6183810/43183395-0b53cc78-8ff6-11e8-87cf-444e5503516a.png)

**Comment by SemenSofronov** [comment]
Now for the create and remove actions, the same captions are used as for the action buttons above the table.

![image.png](https://images.zenhubusercontent.com/5b4d9e85edf0570a96a14fa2/fbdffd73-09d6-4b57-a278-a05d91877082)
