### ISSUE TITLE
Use short notation of 'where' clause to filter entities by the dynamic attribute value

### ISSUE THREAD

**Issue by cad3nc3** [cuba-platform/cuba#1093]
### Environment

- Platform version: 6.9.2

### Description of the bug or enhancement
Use 
`{E}.+dynamicAttribute = ?` 
instead of join
`sys$CategoryAttributeValue attr`
where
`attr.code = 'dynamicAttribute' and
{E}.id = attr.entity.entityId and 
attr.entityValue.entityId = ?`

**Comment by jreznot** [comment]
I believe it is impossible in JPQL constraints, requires overly complex query transformation

**Comment by andreysubbotin** [comment]
It's impossible to do in JPQL. EclipseLink doesn't support such query transformations.
