### ISSUE TITLE
Rework events listeners of UI components with new EventObject approach

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1108]
Relates to #196

Please note:
If an existing listener receives non-event object argument we should introduce new methods with new signature while deprecating old ones.

**Comment by glebfox** [comment]
# Altered

## HasValue

* addValueChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeValueChangeListener
  * accepts `Consumer`
  * Deprecated

## FrameContext

* addValueChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeValueChangeListener
  * accepts `Consumer`
  * Deprecated

## Accordion

* addSelectedTabChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeSelectedTabChangeListener
  * accepts `Consumer`
  * Deprecated

## TabSheet

* addSelectedTabChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeSelectedTabChangeListener
  * accepts `Consumer`
  * Deprecated

## Collapsable

* addExpandedStateChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeExpandedStateChangeListener
  * accepts `Consumer`
  * Deprecated

## EditableChangeNotifier

* addEditableChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEditableChangeListener
  * accepts `Consumer`
  * Deprecated

## UploadField

* addFileUploadStartListener
  * accepts `Consumer`
  * returns `Subscription`
* removeFileUploadStartListener
  * accepts `Consumer`
  * Deprecated
* addFileUploadFinishListener
  * accepts `Consumer`
  * returns `Subscription`
* removeFileUploadFinishListener
  * accepts `Consumer`
  * Deprecated
* addFileUploadErrorListener
  * accepts `Consumer`
  * returns `Subscription`
* removeFileUploadErrorListener
  * accepts `Consumer`
  * Deprecated

## FileUploadField

* addFileUploadSucceedListener
  * accepts `Consumer`
  * returns `Subscription`
* removeFileUploadSucceedListener
  * accepts `Consumer`
  * Deprecated
* addBeforeValueClearListener
  * accepts `Consumer`
  * returns `Subscription`
* removeBeforeValueClearListener
  * accepts `Consumer`
  * Deprecated
* addAfterValueClearListener
  * accepts `Consumer`
  * returns `Subscription`
* removeAfterValueClearListener
  * accepts `Consumer`
  * Deprecated

# Image

* addClickListener
  * accepts `Consumer`
  * returns `Subscription`
* removeClickListener
  * accepts `Consumer`
  * Deprecated

## LayoutClickNotifier

* addLayoutClickListener
  * accepts `Consumer`
  * returns `Subscription`
* removeLayoutClickListener
  * accepts `Consumer`
  * Deprecated

## ListEditor

* addEditorCloseListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEditorCloseListener
  * accepts `Consumer`
  * Deprecated

## ListEditorDelegate

* addEditorCloseListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEditorCloseListener
  * accepts `Consumer`
  * Deprecated

## PopupButton

* addPopupVisibilityListener
  * accepts `Consumer`
  * returns `Subscription`
* removePopupVisibilityListener
  * accepts `Consumer`
  * Deprecated

## PopupView

* addPopupVisibilityListener
  * accepts `Consumer`
  * returns `Subscription`
* removePopupVisibilityListener
  * accepts `Consumer`
  * Deprecated

## ResizableTextArea

* addResizeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeResizeListener
  * accepts `Consumer`
  * Deprecated

## ResourceView

* addSourceChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeSourceChangeListener
  * accepts `Consumer`
  * Deprecated

## SplitPanel

* addSplitPositionChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeSplitPositionChangeListener
  * accepts `Consumer`
  * Deprecated

## DataGrid

* addEditorPreCommitListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEditorPreCommitListener
  * accepts `Consumer`
  * Deprecated
* addEditorPostCommitListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEditorPostCommitListener
  * accepts `Consumer`
  * Deprecated
* addEditorCloseListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEditorCloseListener
  * accepts `Consumer`
  * Deprecated
* addEditorOpenListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEditorOpenListener
  * accepts `Consumer`
  * Deprecated

* addColumnCollapsingChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeColumnCollapsingChangeListener
  * accepts `Consumer`
  * Deprecated
* addColumnReorderListener
  * accepts `Consumer`
  * returns `Subscription`
* removeColumnReorderListener
  * accepts `Consumer`
  * Deprecated
* addColumnResizeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeColumnResizeListener
  * accepts `Consumer`
  * Deprecated
* addSelectionListener
  * accepts `Consumer`
  * returns `Subscription`
* removeSelectionListener
  * accepts `Consumer`
  * Deprecated
* addSortListener
  * accepts `Consumer`
  * returns `Subscription`
* removeSortListener
  * accepts `Consumer`
  * Deprecated
* addContextClickListener
  * accepts `Consumer`
  * returns `Subscription`
* removeContextClickListener
  * accepts `Consumer`
  * Deprecated
* addItemClickListener
  * accepts `Consumer`
  * returns `Subscription`
* removeItemClickListener
  * accepts `Consumer`
  * Deprecated
* setRendererClickListener
  * accepts `Consumer`
  * returns `Subscription`

## TextInputField.TextChangeNotifier

* addTextChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeTextChangeListener
  * accepts `Consumer`
  * Deprecated

## LookupComponent

* addLookupValueChangeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeLookupValueChangeListener
  * accepts `Consumer`
  * Deprecated

## Calendar

* addDateClickListener
  * accepts `Consumer`
  * returns `Subscription`
* removeDateClickListener
  * accepts `Consumer`
  * Deprecated
* addEventClickListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEventClickListener
  * accepts `Consumer`
  * Deprecated
* addEventResizeListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEventResizeListener
  * accepts `Consumer`
  * Deprecated
* addEventMoveListener
  * accepts `Consumer`
  * returns `Subscription`
* removeEventMoveListener
  * accepts `Consumer`
  * Deprecated
* addWeekClickListener
  * accepts `Consumer`
  * returns `Subscription`
* removeWeekClickListener
  * accepts `Consumer`
  * Deprecated
* addForwardClickListener
  * accepts `Consumer`
  * returns `Subscription`
* removeForwardClickListener
  * accepts `Consumer`
  * Deprecated
* addBackwardClickListener
  * accepts `Consumer`
  * returns `Subscription`
* removeBackwardClickListener
  * accepts `Consumer`
  * Deprecated
* addRangeSelectListener
  * accepts `Consumer`
  * returns `Subscription`
* removeRangeSelectListener
  * accepts `Consumer`
  * Deprecated

## Table

* addColumnCollapsedListener(ColumnCollapseListener columnCollapsedListener)
  * Deprecated
* removeColumnCollapseListener(ColumnCollapseListener columnCollapsedListener)
  * Deprecated
* void setClickListener(String columnId, CellClickListener<? super E> clickListener)
  * Deprecated
  
## PickerField

* addFieldListener
  * Deprecated
* interface FieldListener
  * Deprecated

## Timer

* addActionListener
  * Deprecated
* removeActionListener
  * Deprecated
* addStopListener
  * Deprecated
* removeStopListener
  * Deprecated
* interface ActionListener
  * Deprecated
* interface StopListener
  * Deprecated
  
## FileMultiUploadField

* interface QueueUploadCompleteListener
  * Deprecated
* addQueueUploadCompleteListener
  * Deprecated
* removeQueueUploadCompleteListener
  * Deprecated
  
# Added

* class TableCellClickListenerWrapper
* class TableColumnCollapseListenerWrapper
* class PickerFieldFieldListenerWrapper
* class TimerStopListenerWrapper
* class TimerActionListenerWrapper

## Table

* class CellClickEvent
* void setClickListener(String columnId, Consumer<CellClickEvent<E>> clickListener)
* class ColumnCollapseEvent
* Subscription addColumnCollapseListener(Consumer<ColumnCollapseEvent> listener)
* void removeColumnCollapseListener(Consumer<ColumnCollapseEvent> listener)

## PickerField

* class FieldValueChangeEvent
* Subscription addFieldValueChangeListener(Consumer<FieldValueChangeEvent<V>> listener)

## Timer 

* class TimerActionEvent
* class TimerStopEvent
* Subscription addTimerActionListener(Consumer<TimerActionEvent> listener)
* void removeTimerActionListener(Consumer<TimerActionEvent> listener)
* Subscription addTimerStopListener(Consumer<TimerStopEvent> listener)
* void removeTimerStopListener(Consumer<TimerStopEvent> listener)

## FileMultiUploadField

* class QueueUploadCompleteEvent
* Subscription addQueueUploadCompleteListener(Consumer<QueueUploadCompleteEvent> listener)
* void removeQueueUploadCompleteListener(Consumer<QueueUploadCompleteEvent> listener)

# Removed

* class CompatibleAccordionSelectedTabChangeListener
* class CompatibleTabSheetSelectedTabChangeListener
* class ComponentExpandCollapseListenerWrapper
* class MultiUploadFieldListenerWrapper
* class FileUploadFieldListenerWrapper
* class ResizeListenerWrapper
* interface ResizeListener
* class TimerListenerWrapper
* interface ValueListener
* class ComponentValueListenerWrapper
* interface DatasourceListener
* interface CollectionDatasourceListener
* class CollectionDsListenerAdapter
* class CompatibleDatasourceListenerWrapper
* class DsListenerAdapter
* interface LazyCollectionDatasourceListener

## Datasource.java

* void addListener(DatasourceListener<T> listener)
* void removeListener(DatasourceListener<T> listener)

## HasValue

* addListener(ValueListener listener)
* removeListener(ValueListener listener)
* interface ValueChangeListener

## FrameContext

* void addValueListener(String componentName, ValueListener listener)
* void removeValueListener(String componentName, ValueListener listener)

## Accordion

* void addListener(TabChangeListener listener)
* void removeListener(TabChangeListener listener)
* interface TabChangeListener
* interface SelectedTabChangeListener

## TabSheet

* void addListener(TabChangeListener listener)
* void removeListener(TabChangeListener listener)
* interface TabChangeListener
* interface SelectedTabChangeListener

## Collapsable

* interface ExpandListener
* interface CollapseListener
* interface ExpandedStateChangeListener

## EditableChangeNotifier

* interface EditableChangeListener

## FileMultiUploadField

* addListener(UploadListener listener)
* void removeListener(UploadListener listener)
* class UploadListener

## UploadField

* interface FileUploadStartListener
* interface FileUploadFinishListener
* interface FileUploadErrorListener

## FileUploadField

* void addListener(Listener listener)
* void removeListener(Listener listener)
* interface Listener
* interface FileUploadSucceedListener
* interface AfterValueClearListener

# Image

* interface ClickListener

## LayoutClickNotifier

* interface LayoutClickListener

## ListEditor

* interface EditorCloseListener

## PopupButton

* interface PopupVisibilityListener

## PopupView

* interface PopupVisibilityListener

## ResizableTextArea

* void addResizeListener(com.haulmont.cuba.gui.components.ResizeListener resizeListener)
* void removeResizeListener(com.haulmont.cuba.gui.components.ResizeListener resizeListener)
* interface ResizeListener

## ResourceView

* interface SourceChangeListener

## SplitPanel

* interface SplitPositionChangeListener
* interface PositionUpdateListener
* void setPositionUpdateListener(PositionUpdateListener positionListener)
* PositionUpdateListener getPositionUpdateListener()

## VisibilityChangeNotifier

* interface VisibilityChangeListener

## Timer

* void addTimerListener(TimerListener listener)
* void removeTimerListener(TimerListener listener)
* interface TimerListener

## DataGrid

* interface EditorPreCommitListener
* interface EditorPostCommitListener
* interface EditorCloseListener
* interface EditorOpenListener
* interface ColumnCollapsingChangeListener
* interface ColumnReorderListener
* interface ColumnResizeListener
* interface SelectionListener
* interface SortListener
* interface ContextClickListener
* interface ItemClickListener

## TextInputField

### TextChangeNotifier

* interface TextChangeListener

### EnterPressNotifier

* interface EnterPressListener

## LookupComponent

* interface LookupSelectionChangeListener

## Calendar

* interface CalendarBackwardClickListener
* interface CalendarDateClickListener
* interface CalendarEventClickListener
* interface CalendarForwardClickListener
* interface CalendarEventResizeListener
* interface CalendarWeekClickListener
* interface CalendarRangeSelectListener
* interface CalendarEventMoveListener

# Bugs

* `EnterPressListener` doesn't work - a separate issue
