### ISSUE TITLE
Misinformed message "Bean has @Service annotation but no interfaces named '*Service'. Ignoring it."

### ISSUE THREAD

**Issue by febelectron** [cuba-platform/cuba#1109]
- Platform version: 6.8.10

TC:
1. Create bean like
```
@Service
public class ProductRegistryServiceForZones {
...
}
```
2. Start app
AR:
ERROR [localhost-startStop-1] [] [c.h.c.c.s.r.RemoteServicesBeanCreator] Bean productRegistryServiceForZones has @Service annotation but no interfaces named '*Service'. Ignoring it. 

ER:
1) Actually it is not an error, as Service can be successfully injected, it work. I suggest to change logging level to WARN
2) "Ignoring it" - it is not correct as Service successfully loaded.

**Comment by jreznot** [comment]
`@Service` has very special meaning in CUBA. It is bean exposed for clients. Moreover, there is a special aspect that is applied for all `@Service` classes. If you need simple bean - use `@Component` instead.

If you don't need this inspection. I'd recommend that you disable it.

**Comment by febelectron** [comment]
My case - I need to inject bean in the screen. And this bean is very simple to be a Component. Interface would be overhead here.

1) Why it is ERROR if nothing is broken?
2) How to disable the message?

**Comment by jreznot** [comment]
If you need beans in UI, simply define them as `@Component`. For `@Component` interface is not required

**Comment by jreznot** [comment]
There is no way to disable this message. `@Service` is reserved in CUBA only for middleware services you should not use it as `simple bean`.
