### ISSUE TITLE
Remove unused fonts from vaadin-themes

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1114]
Artifact vaadin-themes has 8MB size, but we do not use its fonts.

Remove lato, lora, roboto, source-sans-pro font files from vaadin-themes artifact. 

**Do not remove .scss files, keep them for normal theme build.**

**Comment by glebfox** [comment]
Check that **vaadin-themes** dependency contains no font files:

![Screen Shot 2018-09-04 at 11.51.43.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/21151db4-cc56-4621-89a0-9245b57a717a)
