### ISSUE TITLE
The last column of GroupTable has sorting indicator glitches

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1117]
#### Environment

- Platform version: 6.8 - 6.10

#### Description of the bug or enhancement

Last column sorting indicator is shifted for few pixels while switching sorting type

![glitch](https://user-images.githubusercontent.com/6183810/43645544-4d7da16a-9743-11e8-8a9f-40bbbbb9e024.gif)

**Comment by dtsaryov** [comment]
Unable to reproduce the problem.

@natfirst please check whether issue is reproduced or not
