### ISSUE TITLE
HierarchicalPropertyDatasource should support remove several items from datasource when you remove parent item and @DeletePolicy cascade

### ISSUE THREAD

**Issue by ikuchmin** [cuba-platform/cuba#1120]
### Environment

- Platform version: 6.9.4
- Client type: Web
- Browser: Chrome
- Database: PostgreSQL, HSQL
- Operating system: macOS

### Description of the bug or enhancement

User creates entries tree (B1 -> B2 -> B3 -> B4), see the picture below.

<img width="953" alt="cuba_application" src="https://user-images.githubusercontent.com/1442202/43685812-0ee1b124-98cb-11e8-944a-f0cab82024d3.png">

After that, he deletes entity B2 and he realises that entities B3 and B4 aren't removed.

<img width="954" alt="cuba_application" src="https://user-images.githubusercontent.com/1442202/43685892-81dfc2b4-98cc-11e8-8761-18ee5c1c9303.png">

I create reference project where you can reproduce the issue  

[cascadeDeletion.zip](https://github.com/cuba-platform/cuba/files/2260288/cascadeDeletion.zip)

**Comment by andreysubbotin** [comment]
Not a bug. Deletion policy works when you commit entity. You use composition in the screen, so deletion policy will work when you commit editor.

**Comment by andreysubbotin** [comment]
`HierarchicalPropertyDatasource` should support remove several items from datasource then you remove parent item.
