### ISSUE TITLE
There are no differences between the enabled and disabled CheckBox in IE and Edge

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1128]
#### Environment

- Platform version: 6.10, 7.0
- Browser: IE9-IE11, Edge
- `halo` and `hover` themes

#### Description of the bug or enhancement
1. Open the filter editor
2. `Global default` checkbox is disabled by default
3. Set the `Available for all users` to true
4. `Global default` property is now enabled

**A.R.**  There are no differences between the enabled and disabled CheckBox

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/9e7144c8-e6d2-40eb-bf8d-5261e318c149)

### QA

Please check also editable property. For readonly checkbox only its tick should be semitransparent:

![изображение.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/f94f7dd4-9098-4a6d-9d28-43d82596bd98)

**Comment by dtsaryov** [comment]
It looks the same also for `halo` theme:

![edge_checkbox_halo](https://user-images.githubusercontent.com/6183810/43831590-b07d3a8e-9b15-11e8-9734-65db913aa7c7.png)
