### ISSUE TITLE
The language selector is misaligned if 'remember me' checkbox is hidden by app property

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1133]
### Environment

- Platform version: 7.0-SNAPSHOT
### Description of the bug or enhancement

Define `cuba.web.rememberMeEnabled = false`

AR:

![image.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/a6b03fda-3787-4422-8eaf-cf458908615a)

Related issue: #932

**Comment by dtsaryov** [comment]
@natfirst please also check a case when login form doesn't contain both "remember me" checkbox and locale select field.
