### ISSUE TITLE
Introduce single BeforeClose event for Window

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1138]
### Environment

- Platform version: 7.0.0
- Client type: Web

### Description of the bug or enhancement

Now we have BeforeCloseWithCloseButtonListener, BeforeCloseWithShortcutListener and we have no listener for window breadcrumbs navigation yet.

Let's introduce single BeforeClose event for Window with `source` parameter.

**Comment by glebfox** [comment]
We already have such an event - `com.haulmont.cuba.gui.components.Window.BeforeCloseEvent`.

**Comment by glebfox** [comment]
Added:
* addBeforeWindowCloseListener
* removeBeforeWindowCloseListener (a compatibility method, deprecated) 

Deprecated:

* BeforeCloseWithShortcutEvent
* addBeforeCloseWithShortcutListener
* removeBeforeCloseWithShortcutListener
* BeforeCloseWithCloseButtonEvent
* addBeforeCloseWithCloseButtonListener
* removeBeforeCloseWithCloseButtonListener

The `closeOrigin` field has been added to the `Window.BeforeCloseEvent`.
`CloseOrigin` - marker interface for all window close types, which describes the way a window was closed.
There is the default implementation - `CloseOriginType` with three types:
* `BREADCRUMBS` - a screen is closed by clicking on the breadcrumbs link
* `CLOSE_BUTTON` - a screen is closed with one of the following approaches: screen's close button, TabSheet tabs' close actions (Close, Close All, Close Others)
* `SHORTCUT` - a screen is closed with `ClientConfig.getCloseShortcut()`

The `BeforeCloseWithShortcutEvent` always returns `CloseOriginType.SHORTCUT`
The `BeforeCloseWithCloseButtonEvent` always returns `CloseOriginType.CLOSE_BUTTON`
