### ISSUE TITLE
Old value is not set to Desktop PickerField

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#114]
Воспроизвелось в Такси, у пикер филда указан датасорс, на датасорсе висит valueChangedListener в котором происходит валидация нового значения, если значение не валидно, то в item датасорса проставляется старое значение, но десктоп компонент не обновляется (остается новое значение)

---
Original issue: https://youtrack.haulmont.com/issue/PL-4749

**Comment by jreznot** [comment]
Check after we implement new data binding API in 7.0
