### ISSUE TITLE
Add the scroll box to the template editor screen

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1153]
#### Environment

- Platform version: 6.9, 6.10, 7.0

#### Description of the bug or enhancement
1. Create a simple report with the CSV type
2. Open the report template for edit
3. Change the report type to the Chart
4. Select Serial chart

**A.R.** The scroll box does not appear on the screen, Save and Cancel buttons are not available

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/17b4981f-34e2-4cd8-ac80-0312f00a4dbd)

**Comment by knstvk** [comment]
Move it to an appropriate project.

**Comment by Flaurite** [comment]
moved to: cuba-platfom/repots#95
