### ISSUE TITLE
Sequence for number Id is not incremented when cache size is reached

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#1156]
Possibly caused by #1151

### Environment

- Platform version: 6.9-snapshot

### Description of the bug or enhancement
1) Create a project
2) Set cuba.numberIdCacheSize = 10 in app.properties
3) Create a NumberIdEntity and standard screens for it
4) Start the application
5) Create 11(or more) instances of the entity
6) Restart the application
7) create one more instance of the entity
AR: 
![image](https://user-images.githubusercontent.com/19840141/44152613-0b565ef8-a0b7-11e8-950d-5185275ffbd4.png)

**Comment by IskandarovRost** [comment]
When cuba.numberIdCacheSize = 0 after the application restart - the same problem. Sequence is incorrectly incremented

**Comment by andreysubbotin** [comment]
Setup `cuba.numberIdCacheSize = 10` for core and web application properties
