### ISSUE TITLE
NPE if a query contains more than one parameter with implicitConversion disabled

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#1163]
### Environment

- Platform version: 6.9.4 

### Description of the bug or enhancement

Method `com.haulmont.cuba.core.global.LoadContext.Query#setParameter(java.lang.String, java.lang.Object, boolean)` does not handle parameters properly. 

```java       
public Query setParameter(String name, Object value, boolean implicitConversions) {
            parameters.put(name, value);
            if (!implicitConversions) {
                // this is a rare case, so let's save some memory by using an array instead of a list
                if (noConversionParams == null)
                    noConversionParams = new String[0];
                noConversionParams = new String[noConversionParams.length + 1];
                //BUG:WE DO NOT COPY PREVIOUS VALUES TO NEW ARRAY HERE
                noConversionParams[noConversionParams.length - 1] = name;
            }
            return this;
        }
```

**Comment by EmYar** [comment]
If we use an array to optimize memory consumption, it may be better to use something like that:
```java
noConversionParams = noConversionParams == null
    ? new String[1]
    : Arrays.copyOf(noConversionParams, noConversionParams.length + 1);
noConversionParams[noConversionParams.length - 1] = name;
```

**Comment by alexbudarov** [comment]
Optimizing memory consumption before executing a JPA query looks unnecessary.
Inside of Query.getResultList() EclipseLink and JDBC driver create tons of objects and collections anyway.

**Comment by knstvk** [comment]
@alexbudarov It's not JPA query but LoadContext.Query which is created on clients and passed through communication channels. So saving memory here makes perfect sense.
