### ISSUE TITLE
Drop built-in Mybatis integration

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1171]
There is no CUBA specifics in this integration except `UUIDTypeHandler`.

Let's simply document this integration and remove mybatis dependencies.

**Comment by alexbudarov** [comment]
Will you retain mybatis configuration /  tests in refapp, to ensure that mybatis-spring is still compatible with CUBA?

**Comment by andreysubbotin** [comment]
Documentation: cuba-platform/documentation#249
RefApp sample: cuba-platform/refapp#13
