### ISSUE TITLE
Extract cuba-front to a separate project

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1175]
It is updated rarely. There is no need to release it every platform release

Relates to #933

**Comment by andreysubbotin** [comment]
For QA: smoke test front with polymer for single uber JAR and single WAR

**Comment by myatlevEvg** [comment]
Reopen.
SingleWar does not work in 7.0
See the attached demo project
[fronto.zip](https://github.com/cuba-platform/cuba/files/2663201/fronto.zip)
