### ISSUE TITLE
In Filter component, ability to use ? placeholder multiple times in one clause

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#1188]
### Environment

- Platform version: 6.9.5

### Description of the bug or enhancement

Would be great to allow users to create custom conditions with the following `where` clauses:
```
{E}.num = ? or {E}.saveNum = ?
```
A single parameter should be put in both places.

See also See https://www.cuba-platform.ru/discuss/t/filter-component-vozmozhnost-ispolzovaniya-parametrov-drugih-komponentov-v-uslovii-where-mnozhestvennoe-ispolzovanie-parametra-filtra/2013/2

**Comment by gogosofta** [comment]
Would be great indeed!
my use case with no luck:
({E}.orderItem.paused = ? or {E}.orderItem.order.paused = ?)

**Comment by gogosofta** [comment]
Here's what just came out to my mind and it works for me:
( cast( (cast({E}.orderItem.paused integer) + cast({E}.orderItem.order.paused integer)) boolean) = ? )

**Comment by invviz** [comment]
The case described in this issue works correctly with the current implementation.

**Comment by gogosofta** [comment]
I'm using platform-6.10.9 and it doesn't work correctly. What's the current implementation anyway?

**Comment by andreysubbotin** [comment]
@gogosofta could you provide sample project and test case?

**Comment by gogosofta** [comment]
It's ok, my bad. Sorry for that.
I just realized that both expressions I've cited before are totally different in terms of the logic they implement and the second one does the trick for me.
