### ISSUE TITLE
Improve the TokenList remove buttons alignment in Safari in case token captions are wider than TokenList

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1194]
#### Environment

- Platform version: 6.10
- macOS
- Safari
#1062

#### Description of the bug or enhancement

Scrollbox does not displayed in Safari by default, so it's a little confusing when the remove buttons are not displayed at all

![photo_2018-08-23_15-42-27.jpg](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/e123dc68-5fdf-4027-a4eb-b0fcbc0734f5)

**Comment by dtsaryov** [comment]
Let's try to implement custom scrollbar in Safari:

https://css-tricks.com/custom-scrollbars-in-webkit/
