### ISSUE TITLE
Atmosphere initialization failed for UberJAR deployment

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1201]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

- Minimal reproducible example

1) Checkout RefApp 7.0
2) Build UberJARs or single UberJAR
3) Run assembled JARs

- Expected behavior

Everything is ok

- Actual behavior

Huge error output related to JSR356 and Atmoshpere for web app:

[jsr356_log.txt](https://github.com/cuba-platform/cuba/files/2318731/jsr356_log.txt)

**Comment by jreznot** [comment]
Relates to #1118

**Comment by jreznot** [comment]
Important part of the fix - support for PUSH / WebSocket in Jetty 9.3. Please check if Background Tasks work correctly in various web browsers.
