### ISSUE TITLE
Notify listeners of read-only transient property when related properties change

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#1210]
### Environment

- Platform version: 6.9.5

### Description of the bug or enhancement

See this [forum discussion](https://www.cuba-platform.com/discuss/t/update-gui-for-metaproperty-with-related-fields/6288).

**Comment by invviz** [comment]
Feature branch: https://github.com/cuba-platform/cuba/tree/feature/notify_listeners_when_related_properties_changed
