### ISSUE TITLE
Implement word wrap for LinkButton caption

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba#1212]
Current platform version: 6.9.5
```
<groupBox id="groupBox"
          width="400"
          height="200"/>
```

```
LinkButton button = componentsFactory.createComponent(LinkButton.class);
button.setCaption("Добрый день команда Кубы! У меня возникла такая проблема. Не могу настроить внешний вид компонентов.");
button.setAction(new BaseAction("linked") {
    @Override
    public void actionPerform(Component component) {
        App app = App.getInstance();
        WebWindowManager windowManager = app.getWindowManager();
        windowManager.showWebPage("https://www.cuba-platform.ru/discuss/t/nastrojka-vneshnego-vida-komponentov-sozdannyh-programmno/2030", null);
    }
});
groupBox.add(button);
```

Result:
![image](https://user-images.githubusercontent.com/11287637/44704883-06357c00-aaae-11e8-917e-510aa9c6db4b.png)

Suggestion: make LinkButton multiline, i.e. add line breaks to fit the parent container.

[Forum issue
](https://www.cuba-platform.ru/discuss/t/nastrojka-vneshnego-vida-komponentov-sozdannyh-programmno/2030)

### Multiple rows
The user can choose the way how the caption for `LinkButton` will be displayed: in one row or can wrap onto multiple rows. 
The default value is to display `LinkButton` caption with wrapping into multiple rows.
If link button caption does not fit horizontal space words are wrapped to the next line. The caption is centered in the middle of the button.
```
$cuba-link-button-caption-wrap: true !default;
```

1) Width and height for LinkButton are undefined
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/42abb63b-aa3d-4916-b6c4-ffd4e26b686f)

2) Width = 200px
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/71974e6c-5cde-4ee7-af03-5c391741cae2)

3) Height = 40px
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/855ba45c-cc31-4d3c-89d9-6d98c9f263c0)

4) Width = 200px and Height = 200px
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/7b5d5611-9150-4db6-97fe-1bfd1dbe9357)

## One row
The user can change this behavior to display `LinkButton` caption in one row:
1) Create a theme extension
2) Override variable `$cuba-link-button-caption-wrap: false`

## Test project
[linkbutton-word-wrap.zip](https://github.com/cuba-platform/cuba/files/3309957/linkbutton-word-wrap.zip)

## QA
* Check for different values of the width and height of the link button
* Check for different containers (`GroupBox`, `VBox`, etc.)
* Check for different values of the variable `$cuba-link-button-caption-wrap`

**Comment by jreznot** [comment]
Please check if we can fix it when `LinkButton` has fixed width.
