### ISSUE TITLE
Layout glitch in Access Group -> Constraints

### ISSUE THREAD

**Issue by zudba** [cuba-platform/cuba#1218]
### Environment

- Platform version: 6.8.12 
- Client type: Desktop
- Operating system: Windows

### Description of the bug or enhancement

1. Open the Access Groups screen
2. Go to the Constrains tab
3. Click on Create button

**AR**
Incorrect layout of components in the open screen

**Comment by jreznot** [comment]
Could you please attach a screenshot? What is incorrect?

**Comment by natfirst** [comment]
The Clause fields are very small
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/277f728b-258e-4298-b9fc-d7c108b60823)

Add some text to the field, it will be overlapped by the scroll
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/0c7a7ffc-6c9f-467c-8964-0b8d4ede8ce7)

**Comment by jreznot** [comment]
Caused by https://youtrack.cuba-platform.com/issue/PL-10145
