### ISSUE TITLE
AppContext.getProperty() uses poorly-scaling System.getProperty inside

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1222]
### Environment
- Platform version: 6.8.12

### Description of the bug or enhancement
Have been performing performance testing with JVisualVM.
One of CPU profile method chains shows interesting info:
![image](https://user-images.githubusercontent.com/6158807/44774059-3569ed00-ab83-11e8-9b84-f397a5e87c65.png)

AppContext.getProperty() uses System.getProperty() inside. 
But System.getProperty() is implemented via Hashtable class. Every get() call enters a global synchronized block and therefore is poorly scalable in multithread environment.

I think that all platform code assumes that AppContext.getProperty() is cheap and highly scalable. So depending on System.getProperty() is a problem.

**Comment by knstvk** [comment]
### Solution

System properties are read on startup and cached in a ConcurrentHashMap. Consequently, changes in system properties made at runtime do not affect  the system. If you need to read the new value of a system property, reset the cache using the `clearSystemPropertiesCache()` methods of the `CachingFacadeMBean` JMX beans available in the `core` and `web` modules.

**Comment by knstvk** [comment]
For manual testing: try to [redefine](https://doc.cuba-platform.com/manual-6.9/system_properties.html) an app property with a system property.
