### ISSUE TITLE
Transient fields are not shown on Entity Inspector however they are included to the corresponding view

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#1225]
### Environment

- Platform version: 6.8-snapshot, 6.10-snapshot. etc
### Description of the bug or enhancement

- Minimal reproducible example
1) create an entity with a transient field
```java
@NamePattern("%s %s|intFld,strFld")
@Table(name = "BESTCRM_REF_ENTITY")
@Entity(name = "bestcrm$RefEntity")
public class RefEntity extends StandardEntity {
    private static final long serialVersionUID = -2777424179140283955L;

    @Column(name = "STR_FLD")
    protected String strFld;

    @Transient
    @MetaProperty
    protected String npFld;

    @Column(name = "INT_FLD")
    protected Integer intFld;

    public void setNpFld(String npFld) {
        this.npFld = npFld;
    }

    public String getNpFld() {
        return npFld;
    }


    public void setStrFld(String strFld) {
        this.strFld = strFld;
    }

    public String getStrFld() {
        return strFld;
    }

    public void setIntFld(Integer intFld) {
        this.intFld = intFld;
    }

    public Integer getIntFld() {
        return intFld;
    }
```
2) Start the application
3) Open *Restore Deleted Entities* and chose the entity. Check the table columns
4) Open *Entity Inspector* and chose the entity. Check the table columns

- Actual behavior
The transient field is not shown in *Entity Inspector* however, it is included in the view which is used in the corresponding datasource.

**Comment by invviz** [comment]
According to the issue  [PL-9597](https://youtrack.haulmont.com/issue/PL-9597) transient attributes should not be displayed on the "Entity Inspector" screen.
It was also decided to change the behavior of the "Restore Deleted Entities" screen. This screen should not contain transient attributes as well.
