### ISSUE TITLE
Strange behavior of components TextField and PasswordField

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1229]
### Environment

- Platform version: 7.0
- Browser: Firefox
- Operating system: Windows

### Description of the bug or enhancement

Steps for refapp:

1. Add to any screen the next components:
```<textField/>```
```<passwordField/>```
2. Run the application

ER:
The TextField and The PasswordField components are blank

AR:
The TextField has "admin" value and the PasswordField has "admin" value

**Comment by glebfox** [comment]
A screenshot of a bug is appreciated. I suppose that it's something about your browser instance autocomplete feature.

**Comment by sukhova** [comment]
Yes, the problem really was in my browser
