### ISSUE TITLE
Email local part validation problems

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1231]
A topic on support forum: [link](https://www.cuba-platform.com/discuss/t/errors-in-e-mail-addresses-validation/6381).

### Description of the bug or enhancement

- Minimal reproducible example

Try to validate the following emails:
1. `Jhon..Doe@myDomain.com`
2. `Jhon.Doe+cuba.platform@gmail.com`

- Expected behavior

1. The first email should be rejected
2. The second should be accepted

- Actual behavior

1. The first email is accepted
2. The second email is rejected

## Updates

Hibernate EmailValidator is used now instead of custom regular expressions. It has less strict check so some cases can be considered as correct. It's intended to decrease false negative cases.

## QA

Make sure that EmailValidator doesn't reject correct emails.

**Comment by jreznot** [comment]
It seems that we have to switch to RFC validation regular expression, see Hibernate Validator.

**Comment by tdeleeuw** [comment]
You can have a look at https://github.com/cuba-platform/cuba/compare/master...tdeleeuw:ValidateEmail_%231231?expand=1

I will do the paper work tomorrow.
Please note that I am relying Guava and the classes used are annoted with "GwtIncompatible". Is this an issue when using validation with only a String?
Thanks
Thierry

**Comment by jreznot** [comment]
Hi,
Unfortunately, this is just cosmetic fix for the actual problem. We are planning to get rid of custom regex there and use mechanism of `@Email` validation from Hibernate Validator instead.

**Comment by tdeleeuw** [comment]
Any ETA, as it is an annoying bug. In that while maybe merge the proposed fix and change to Hibernate validation later on?
Thanks

**Comment by jreznot** [comment]
Do you know that you can use your own validator on any screen ? I think it is not major problem so far because you can switch to your own validator at any time.

**Comment by dtsaryov** [comment]
Hi,

You're right. It's exactly basic splitting by commas and/or semicolons and this behavior is the same as previous implementation of "splitting".

This validator is intended only for validating fields in UI so we decide to fully rely on Hibernate validation while checking email addresses and support only basic cases. 

As Yuriy said before you can always create your own implementation and replace the default.
