### ISSUE TITLE
Text input components show "null" in notifications when required="true" but there is no attribute requiredMessage

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1235]
### Environment

- Platform version: 7.0
- Client type: Web
- Browser: Chrome
- Operating system: Windows

### Description of the bug or enhancement

All components except OptionsList and TwinColumn show "null" in notifications when required="true" but there is no attribute requiredMessage.

OptionsList shows the blank notification.

**Comment by glebfox** [comment]
@jreznot, instead of reverting the default *empty* message, I suggest providing a more meaningful message in case the required message is `null`, for instance `the field is required`.

**Comment by glebfox** [comment]
The new `validationFail.defaultRequiredMessage` message key was introduced in the main message pack.

**Comment by sukhova** [comment]
OptionsList and OptionsGroup show the blank notification.
```
<optionsGroup id="optionsGroup1" required="true"/>
<optionsList id="optionsList1" required="true"/>
```
