### ISSUE TITLE
Constraints constructor incorrectly handles not persistent entities

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#1237]
### Environment

- Platform version: 6.9.5

### Description of the bug or enhancement

- Minimal reproducible example
1. create _Some entity_
2. create a NotPersistent entity with a _link to another entity_ and a couple of local fields
3. start the application
4. create an access group 
5. select the entity
6. Try to adjust "Join Clause" and "Where Clause". type "{E}."

- Actual behavior
Completion in Join Clause does not work but in Where clause we can choose "id"

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/143314db-742c-461e-802b-d20682b56628)

And wizard also sees the ID property
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/c7f41e25-96d3-422f-9a7f-563b1af86401)

**Comment by IskandarovRost** [comment]
probably caused by #499

**Comment by andreysubbotin** [comment]
Autocompletion works only for persistent properties (e.g properties with annotations: Id, Column, ManyToOne, OneToMany, ManyToMany, OneToOne, Embedded, EmbeddedId)
