### ISSUE TITLE
TextField should support Entity value

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1244]
`com.haulmont.cuba.web.gui.components.WebTextField#convertToPresentation`:

```
EntityValueSource entityValueSource = (EntityValueSource) valueBinding.getSource();
Range range = entityValueSource.getMetaPropertyPath().getRange();
if (!range.isDatatype()) {
    throw new IllegalStateException(String.format(
            "Property '%s' has %s. TextField can be bound only to a simple data type",
            entityValueSource.getMetaPropertyPath().getMetaProperty().getName(), range));
}
```

We should prevent binding on non-simple property in this case

**Comment by alexbudarov** [comment]
Why? What workaround do you suggest for read-only text fields which display instance's name pattern?

**Comment by jreznot** [comment]
It is currently broken, that's why I've created the issue. We have to either fix this or provide replacement for such a use case

**Comment by knstvk** [comment]
For QA: see Test Samples > Text components > TextField bound to reference property
