### ISSUE TITLE
Broken table headers layout after sorting and updating

### ISSUE THREAD

**Issue by ignatiev-lesha** [cuba-platform/cuba#1247]
### Environment
- Platform version: 6.8.10
- Client type: Web
- Browser: Chrome 68.0.3440.106
- Operating system: Windows

### Description of the bug or enhancement
- Visual theme - havana
- Tests -> Combined Screens -> Car Combined Screen
- Create Car and fill VIN -> Repairs tab
- Create Repairs until table's scroll appears (Fill description and date only)
- Enable sorting of repairs table by any column and click OK
- Create another car

**Expected behavior**
Table headers look good
**Actual behavior**
![problem](https://user-images.githubusercontent.com/4007863/45280694-77c9ed00-b4e6-11e8-84e7-773bfd889ca4.png)

**Comment by dkz** [comment]
I believe the it is same issue that is experienced with web version of group table. Empty table has these weirdly aligned headers (Platform 6.8.12).
![screenshot from 2018-09-11 13-22-26](https://user-images.githubusercontent.com/1571386/45351000-2b55de80-b5c6-11e8-98b4-67378b8c7a6e.png)

**Comment by dtsaryov** [comment]
Because the `GroupTable` component is also used in the entity combined screen sample mentioned in issue. Will be fixed soon.
