### ISSUE TITLE
An abrupt change in the width of the fields when initializing SplitPanel

### ISSUE THREAD

**Issue by leonnash23** [cuba-platform/cuba#1256]
### Environment

- Platform version: 6.8.12
- Client type: Desktop
- Operating system: Windows

### Description of the bug or enhancement

- The essence of the problem is described in the title and I created a small demo to show it. You can find a video in rep. Rep is [here](https://github.com/leonnash23/cuba-split-panel-bug)
- In the small view like in the demo, it happened from time to time. But in more complicated view it happens every time and goes on slower. It's happening on the "face" of our product, therefore it's very unpleasant.

Demo project:
[splitTest.zip](https://github.com/cuba-platform/cuba/files/2434141/splitTest.zip)

**Comment by jreznot** [comment]
Please check position change in Desktop SplitPanel and settings saving. Also, check reports ReportEditor, it has 2 SplitPanel s.
