### ISSUE TITLE
Application property’s edit dialog has incorrect size

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1262]
### Environment

- Platform version: 7.0
- Client type: Web
- Browser: all
- Operating system: Windows

### Description of the bug or enhancement
![5.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/7cc90c3d-5883-458e-8c60-a1acac2a282c)

**Comment by natfirst** [comment]
**For QA** Check all dialog windows:
- Access Group creating
- BPM Process Models creating
- Table system information
- Users additional actions (reset password, copy settings, etc.)
- Reports group creating
