### ISSUE TITLE
Filter custom condition editor is opened with an incorrect size

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#1263]
### Environment

- Platform version: 7.0-snapshot. Default theme

### Description of the bug or enhancement

- Minimal reproducible example

1) create a project or use refapp
2) add the "reports" premium component
3) start the application
4) open reports browse screen
5) in _Filter_ add search condition - Create new

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/5ae31991-ce54-4c66-9ab0-b267028ece01)

- Actual behavior
Condition editor 
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/9510d39e-dfe6-412d-883d-df1251b5933c)

**Comment by jreznot** [comment]
Fixed in #1262
