### ISSUE TITLE
The table header broken after resizing columns

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1266]
### Environment

- Platform version: 6.9, 6.10, 7.0
- Client type: Web
- Browser: any
- Operating system: Windows

### Description of the bug or enhancement
1) Any theme
2) Open screen browser with a Table component
3) Make the last column as small as possible
4) Make another column so wide to display scrolling

**Expected behavior**

Table headers looks good

**Actual behavior**

In **6.9** and **6.10** such behavior appears with Table component (test _Administration -> Roles_)

![tableheader.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/0681b043-7cc6-4c7b-9ca6-1aed3cfb1211)

In **7.0** such behavior appears with Table (test _Administration -> Roles_) and GroupTable (see _Administration -> Users_) components

![gtableheader.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/7d900ca2-37b1-47d9-af3f-56aa0d6c23cf)

**Comment by dtsaryov** [comment]
Reproduces for `Table` & `GroupTable` only with 7.0
