### ISSUE TITLE
The DataGrid's header broken after resizing the last column

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1267]
### Environment

- Platform version: since 6.7 and above
- Client type: Web
- Browser: any
- Operating system: Windows

### Description of the bug or enhancement
![datagrid.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/77efe8e9-64f4-4ff0-96f3-d53018a66331)

**Comment by godlevskiy** [comment]
The same in our project

   * Platform version: 6.10.13
   * Client type: Web
   * Browser: Chrome, Firefox, Edge
   * Operating system: Windows, Linux

![image (10)](https://user-images.githubusercontent.com/24581407/91410341-d44f7f80-e857-11ea-8241-211fdba931bb.png)

**Comment by skatova** [comment]
This problem is not reproducible

**Comment by natfirst** [comment]
1. Open demo browser
2. Resize the last column until it disappeared
[data-grid-test.zip](https://github.com/cuba-platform/cuba/files/5142589/data-grid-test.zip)
