### ISSUE TITLE
Required LookupPickerField stays the required even after you select a value from the list

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1268]
### Environment

- Platform version: 7.0
- Client type: Web
- Operating system: Windows

### Description of the bug or enhancement
But if you select a value with lookup  ![lookupBtn.png](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/160ca93b-1e45-47a1-9c48-30f2bf219636) button, the LookupPickerField will not be required

![lookuppickerfield.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/3d3a4e0c-70e7-4cd7-a64e-1ea1d83d23db)

**Comment by glebfox** [comment]
It's a part of #1119
