### ISSUE TITLE
Unexpected behaviour of table

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#129]
Воспроизводится в проекте timesheets https://git.haulmont.com/company/timesheets.git
Revision: c72c35a201b70ae43521ed20424d1c81f70b7799

Предварительная подготовка:
1) Создать проект (Проекты -> Проекты | Projects -> Projects)
2) Создать для проекта участника (Проекты -> Проекты -> Вкладка "Участники проекта" справа | Projects -> Projects -> Tab "Project participants")
3) Создать ДВЕ задачи для проекта (Проекты -> Проекты -> Вкладка "Задачи" справа | Projects -> Projects -> Tab "Tasks")
3.1) Во время создания задач, перейти во вкладку "Расширенные" (Advanced) и выбрать добавленного участника
4) Перейти на экран недельных отчетов (Таймшиты -> Недельные отчеты | Timesheets -> Weekly reports)
5) Заполнить две строки с недельными отчетами (Две задачи нужны, т.к. дял одной задачи может быть только одно вхождение недельного отчета)

case 1:
1) Закрываем все вкладки
2) Открываем недельные отчеты

AR: Все хорошо отображается и готово к дальнейшей работе

case 2:
1) открываем еще одну вкладку программы строго после вкладки с недельными отчетами
2) Перезагружаем (переоткрываем) вкладку с недельными отчетами

AR: Есть проблемы с отображением первой строки, она пустая и при выборе ее, выделяется две строки
ER: Как в case 1

---
Original issue: https://youtrack.haulmont.com/issue/PL-5411

**Comment by jreznot** [comment]
Obsolete
