### ISSUE TITLE
Fix drag'n'drop functionality in the Access Groups screen

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1290]
https://vaadin.com/docs/v8/framework/advanced/advanced-dragndrop.html

### Changes

In order to support drag and drop from v7 Table in v8 new API created extension for Table:
```
CubaTableDragSourceExtension<T extends Table & CubaEnhancedTable>
```
### How it use
By the following code we enable draggable rows in the table and invoke drag event in the client side:
```
Table<User> usersTable;
CubaTable vTable = usersTable.unwrap(CubaTable.class);
new CubaTableDragSourceExtension<>(vTable);
```
Then, for instance, in `TreeGridDropTarget` drop listener we can get dragged ids from event:
```
treeGridDropTarget.addTreeGridDropListener(event -> {
    if (event.getDragSourceExtension().isPresent() &&
            event.getDragSourceExtension().get() instanceof CubaTableDragSourceExtension) {
        CubaTableDragSourceExtension<CubaTable> sourceExtension =
                (CubaTableDragSourceExtension<CubaTable>) event.getDragSourceExtension().get();
        List<Object> itemIds = sourceExtension.getLastDraggedItemIds();
    }
});
```

### For QA
1. Please, check that DnD works in all browsers.
2. Especially check DnD in Edge and IE11 in Tree component.

**Comment by natfirst** [comment]
DnD in Tree component does not work in Chrome, FF, Safari
