### ISSUE TITLE
SearchPickerField value is sporadically cleared

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#130]
Очищается значение поля в search picker field

Суть в следующем, допустим у нас поле search picker field - поле заказ. 
Копируем в него номер, полю проставляется зеленый background(происходит изменение) в этот момент нажимаем enter значение поля отчищается, сделать это надо все очень быстро.

Я лично ловлю эту проблему на 1 раз из 5-10 попыток.

---
Original issue: https://youtrack.haulmont.com/issue/PL-5489

**Comment by jreznot** [comment]
Obsolete
