### ISSUE TITLE
Implement buffered mode for HasValue components

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1307]

**Comment by glebfox** [comment]
Components that support the buffered mode (as that was in Platform 6):

* TextField
* TextArea
* CheckBox
* CurrencyField
* DateField
* LookupField
* MaskedField
* PasswordField (and inheritors)
* PickerField
* RichTextArea
* TimeField
* SearchField
* DatePicker (new)

Components that will support the buffered mode after migration to Vaadin 8:

* FileUploadField

**Comment by natfirst** [comment]
See https://youtrack.cuba-platform.com/issue/PL-8777
