### ISSUE TITLE
Declarative JMX Bean registration

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#131]
All MBeans objectName have the same format:

$wcn.$module:type=$mbeanAlias

We could create an annotation for MBeans where to specify mbeanAlias.

---
Original issue: https://youtrack.haulmont.com/issue/PL-5520

**Comment by andreysubbotin** [comment]
Introduced `JmxBean` class-level annotation for automatic registration of the class instances with a JMX server, according to the {@link #module} and {@link #alias} attributes.
