### ISSUE TITLE
Add to current set action should open browser screen if the lookup screen is not defined

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1324]
#### Environment
- Platform version: 6.9.6
- Forum link https://www.cuba-platform.com/discuss/t/add-to-current-set-with-browse-view/6714
#### Description of the bug or enhancement

1. Enable folder pane in the project `cuba.web.foldersPaneEnabled = true`
2. Create an entity with the standard screens (browser and editor)
3. Run the app
4. Create an entity instance and add it to the set from the browser screen (click **Add to set** button)
5. Open the created set, click the **Add to current set** button

**A.R.** No such screen exception will appear
**E.R.** Browser screen should be opened if the lookup screen is not defined

**Comment by Flaurite** [comment]
Can't reproduce in 7.0+
