### ISSUE TITLE
Typo in the `youSelectedEmbedded` filter notification for the Russian locale

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1330]
#### Environment

- Platform version:6.9.3

#### Description of the bug or enhancement

1. Create Persistent and Embedded entities
2. Add the embedded entity to the Persistent
3. Create screens for the persistent entity
4. Add the Russian locale, run the app
5. Open the Persistent screen, add a new filter condition
6. In attributes tree select the embedded attribute and click **Select** 

**A.R.**
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/d650b329-0cbf-4345-bcae-803a0eeb6b6b)

**E.R.** Text should be "Выбранный элемент является встраиваемой сущностью"

[embEn.zip](https://github.com/cuba-platform/cuba/files/2447089/embEn.zip)

**Comment by Flaurite** [comment]
Easier way to reproduce on 6.9 - 6.10:
1. Start refapp;
2. Open EntityInspector
3. Choose "CategoryAttributerValue"
4. Try to add property "CategoryAttrbiteValue.entity" in filter's condtion

7.0
1-3. The same
4. Try to add property "CategoryAttrbiteValue.entity" by right click on it:
![image](https://user-images.githubusercontent.com/22093943/46520441-17cc2980-c88d-11e8-98b8-f420826b07d0.png)
