### ISSUE TITLE
ValueChangeEvent userOriginated for PickerField actions

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1334]
### Environment

- Platform version: 7.0.0
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example

Now, userOriginated is always false for ValueChangeEvent of PickerField, since actions set value programmatically.

Probably, we should introduce separate `setValueFromUser()` for PickerField* components that will be called from LookupAction / OpenAction.

**Comment by glebfox** [comment]
Invoking `LookupAction` and `ClearAction` considered as `userOtiginated=true`.
