### ISSUE TITLE
Cannot edit non-persistent entity using standard browser-editor screens

### ISSUE THREAD

**Issue by kosotd** [cuba-platform/cuba#1341]
### Environment
- Platform version: 6.10.0
- Client type: Web

**Description of the bug or enhancement**
Steps to reproduce:
1. Create not persistent entity (TestEntity<UUID,>).
2. Create screen with CollectionDatasource<TestEntity, UUID> and Table<TestEntity,> (table).
3. Add two buttons (create, edit) to the screen and assign them actions: table.create, table.edit respectively.
4. Run application -> open screen -> click create -> click ok -> select added record -> click edit -> Access denied.

[untitled.zip](https://github.com/cuba-platform/cuba/files/2450535/untitled.zip)

Caused by #1148.

**Comment by knstvk** [comment]
In order to use standard browser-editor screens with non-persistent entities, create a special DataSupplier and register it in the editor screen, for example:

```
package com.company.untitled.web.testentity;

import com.haulmont.chile.core.model.MetaClass;
import com.haulmont.cuba.core.entity.Entity;
import com.haulmont.cuba.core.global.View;
import com.haulmont.cuba.gui.data.impl.GenericDataSupplier;

import javax.annotation.Nullable;

public class NonPersistentDataSupplier extends GenericDataSupplier {

    @Override
    public <E extends Entity> E reload(E entity, View view, @Nullable MetaClass metaClass, boolean loadDynamicAttributes) {
        return entity;
    }
}
```

```
<window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
        class="com.company.untitled.web.testentity.TestEntityEdit"
        ...
        dataSupplier="com.company.untitled.web.testentity.NonPersistentDataSupplier">
    <dsContext>
...
```

**Comment by kosotd** [comment]
In version 6.9.2 everything worked. Now, in version 6.10.0, in order to work, do I need to change all my code?
