### ISSUE TITLE
The Change password dialog has an incorrect caption

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1343]
### Environment

- Platform version: 7.0
- Operating system: Windows

### Description of the bug or enhancement

1) Open **refapp->Help->Settings**
2) Click on the **Change Password** button

*AR:*
![69.JPG](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/d6d87b19-f3f5-46c2-9151-f52f080ceb85)

**Comment by jreznot** [comment]
We will fix FreeMarker usages and document a breaking change: caption / description of Window will no be preprocessed by FreeMarker anymore.
