### ISSUE TITLE
Dynamic attribute editor should display only screens that refer to the selected entity type

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1356]
#### Environment

- Platform version: 7.0

#### Description of the bug 

1. Create a new dynamic category 
2. Set up the name and the entity type 
3. Create new attribute
4. Open the Visibility tab, add the target screen

**A.R.** The drop-down list will contain all screens from the app

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/ade87c10-a1f6-4360-b11a-c8163b84c8d7)

**E.R.** The drop-down list should contain only screens that refer to the selected entity type

**Comment by glebfox** [comment]
It seems that the issue is not relevant
![image.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/26474500-5a7c-47c1-a747-4686dc20fc5a)

**Comment by glebfox** [comment]
The New screens are not displayed

![image.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/67fe4121-c827-4adf-b7cb-fa9d84d29288)
