### ISSUE TITLE
Sorting does not work correctly in the TreeTable component

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1361]
### Environment

- Platform version: 7.0
- Operating system: Windows

### Description of the bug or enhancement
![treetablesorting.gif](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/a3e1f2a5-b70f-4643-b447-950621a54158)

**Comment by sukhova** [comment]
It doesn't work

**Comment by glebfox** [comment]
It works
