### ISSUE TITLE
Add flexible positioning and aligning for the Form component

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1375]
* Support colspan/rowspan and other features from Grid
* Align for field and caption

**Comment by glebfox** [comment]
**Caption Alignment**

The new `childrenCaptionAlignment` attribute is added. It defines the alignment of child component captions: `LEFT` (default) and `RIGHT` and applicable only when captions position is `CaptionPosition.LEFT`

It can be set both for the form itself and for a specific column.

* `setChildrenCaptionAlignment(CaptionAlignment alignment)` - Sets alignment of child component captions in all columns.
* `setChildrenCaptionAlignment(int column, CaptionAlignment alignment)` - Sets alignment of child component captions for a column with the given index.

```
<form childrenCaptionAlignment="RIGHT">
    <column width="250px">
        <textField caption="Text Field"/>
        <textField caption="Very long description for Text Field"/>
    </column>
    <column width="250px">
        <textField caption="Text Field"/>
        <textField caption="Very long description for Text Field"/>
    </column>
</form>
```

![Screenshot 2019-11-15 at 19 22 59](https://user-images.githubusercontent.com/6077149/68955639-de7c2200-07df-11ea-802f-e2132a8dcfe2.png)

```
<form>
    <column width="250px">
        <textField caption="Text Field"/>
        <textField caption="Very long description for Text Field"/>
    </column>
    <column width="250px" childrenCaptionAlignment="RIGHT">
        <textField caption="Text Field"/>
        <textField caption="Very long description for Text Field"/>
    </column>
</form>
```

![Screenshot 2019-11-15 at 19 23 05](https://user-images.githubusercontent.com/6077149/68955661-e8058a00-07df-11ea-8b33-77b0396face8.png)

**Col/Row Span**

Similarly to `GridLayout`, `Form`supports the `colspan` and `rowspan` attributes and provides corresponding Java API:

* `add(Component childComponent, int column, int colSpan, int rowSpan)`
* `add(Component childComponent, int column, int row, int colSpan, int rowSpan)`

```
<form>
    <column width="250px">
        <textField caption="Field 1" colspan="2" width="100%"/>
        <textField caption="Field 2"/>
    </column>
    <column width="250px">
        <textField caption="Field 3"/>
    </column>
</form>
```

![Screenshot 2019-11-15 at 19 48 14](https://user-images.githubusercontent.com/6077149/68956140-e8525500-07e0-11ea-8332-37d29591d809.png)

```
<form>
    <column width="250px">
        <textField caption="Field 1" rowspan="2" height="100%"/>
    </column>
    <column width="250px">
        <textField caption="Field 2"/>
        <textField caption="Field 3"/>
    </column>
</form>
```

![Screenshot 2019-11-15 at 19 48 20](https://user-images.githubusercontent.com/6077149/68956153-ee483600-07e0-11ea-91a0-7bdbe9fb0f9d.png)

**Comment by glebfox** [comment]
Client-side exception when switching _lock type_ in **LockEditor**.

![Screenshot 2019-11-18 at 12 52 33](https://user-images.githubusercontent.com/6077149/69037966-5164e300-0a02-11ea-894f-4338c2f47617.png)

**Comment by natfirst** [comment]
```
<form id="form" childrenCaptionAlignment="LEFT">
            <column width="250px" childrenCaptionAlignment="RIGHT">
                <textField caption="Text Field" rowspan="2" height="100%"/>
                <textField caption="Very long description for Text Field" colspan="2" width="100%"/>
            </column>
            <column width="250px">
                <textField caption="Text Field" />
                <textField caption="Very long description for Text Field" />
            </column>
        </form>
```

IllegalArgumentException: Given coordinates [1, 2] - [1, 2] overlap existing component: [0, 2] - [1, 2]
