### ISSUE TITLE
Abilty to clear ClientCacheManager config cache on web client through jmx

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1382]
### Environment
- Platform version: 6.8.13

### Description of the bug or enhancement
Problem was discovered during writing integration auto tests.

If you change DB-stored configuration setting through jmx (ConfigStorage - setDbProperty) - changed settings values often aren't applied to logic on web client layer.
Because web client has its own caching - ClientCacheManager.

Currently this cache can't be reset from outside (by jmx).

Solution: add another jmx method to web and portal modules which clears or refreshes data cached in com.haulmont.cuba.client.sys.cache.ClientCacheManager or its ConfigCacheStrategy.

**Comment by soraksh** [comment]
Use clearConfigCache() method from web/portal CachingFacade beans
