### ISSUE TITLE
Set default field width for the Hover theme 

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1391]
`halo-defaults.scss` contains the following variable:

```
$v-default-field-width: $v-unit-size * 8;
```
As the result the default width of the fields is `240px`.

Even though the **Hover** theme extends **Halo** it doesn't inherit its defaults so we can see the following differences in the UI:

`<textField/>` in Halo:

![image.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/8d110aa8-2c7a-4d05-a04f-e58e053afb81)

`<textField/>` in Hover:

![image.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/4e003b42-e971-4797-aa63-12a0295b2f73)

**Comment by jreznot** [comment]
Relates to #979
