### ISSUE TITLE
Table and tree styles are not applied

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1394]
The styled table does not display color in cell
The styled tree does not appear stylized, but appears normal

### Environment

- Platform version: 7.0
- Client type: Web
- Operating system: Windows

### Description of the bug or enhancement

The styled table does not display color in cell in themes 

_havana_
_hover_
_hover-dark_.

In themes:

_halo-facebook_
_halo-dark_
_halo_
it's all right.

The styled tree does not appear stylized, but appears normal in themes

_havana_
_hover_
_hover-dark_
_halo-facebook_
_halo-dark_

In the _halo_ theme it's all right.

**Comment by Flaurite** [comment]
Table and Tree don't have styles in:
1. Hover
In other themes should work
