### ISSUE TITLE
Performance issue in ItemTrackingAction 

### ISSUE THREAD

**Issue by pavel-grigorev** [cuba-platform/cuba#1445]
- Platform version: 6.8.12
- Client type: Web

### The use case:
A table with a custom action that extends RemoveAction. The table has 1000+ rows. The user selects all rows and runs a logic that updates a field in all selected rows. It takes tens of seconds to finish.

### The cause:
ItemTrackingAction.isApplicable() method invokes target.getSelected().isEmpty() to check if something is selected. Internally, getSelected() invokes datasource.getItem() for each selected row. This is inefficient and causes significant slowdown in some cases like the one above when you need to update a large number of rows. The datasource.getItem() method gets called N^2 times, where N is the number of selected rows.

### The possible solution:
Add a "hasSelection" method to the ListComponent interface. Implementation should not pull items from the data source and simply check the selected item ids collection.
In the ItemTrackingAction.isApplicable() method implementation, replace "!target.getSelected().isEmpty()" with "target.hasSelection()".

### The workaround I currently use in my project:
```java
public class SelectionChecker {
  private final AbstractSelect select;

  public SelectionChecker(ListComponent<?> target) {
    this.select = getNestedComponent(target);
  }

  private static AbstractSelect getNestedComponent(ListComponent<?> listComponent) {
    return (AbstractSelect) ((WebAbstractComponent) listComponent).getComponent();
  }

  public boolean hasSelection() {
    return isNotEmpty(getSelectedKeys());
  }

  private Set<?> getSelectedKeys() {
    return (Set<?>) select.getValue();
  }
}

public abstract class EfficientRemoveAction extends RemoveAction {
  private final SelectionChecker selectionChecker;

  public EfficientRemoveAction(ListComponent<?> target) {
    super(target);
    this.selectionChecker = new SelectionChecker(target);
  }

  @Override
  protected boolean isApplicable() {
    return selectionChecker.hasSelection();
  }
}
```

**Comment by jreznot** [comment]
> The user selects all rows and runs a logic that updates a field in all selected rows. It takes tens of seconds to finish.

Additionally, I'd recommend that you to suspend datasource before such a bulk changes using:
```
((Suspendable)ds).setSuspended(true);
```

It will not fire value change events during the bulk operation. But when you resume ds it will reload data.

**Comment by pavel-grigorev** [comment]
> Additionally, I'd recommend that you to suspend datasource before such a bulk changes using:
Tried that but when I suspend value change events the ds does not get marked as modified and I can not commit changes. I usually suspend ds listeners using CollectionDatasource.suspendListeners() but it's a different thing and does not help with the issue.
