### ISSUE TITLE
Define filter layout template for particular filter

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#145]
Define filter layout template for particular filter

---
Original issue: https://youtrack.haulmont.com/issue/PL-5878

**Comment by gorbunkov** [comment]
In the screen xml descriptor it is possible to define a controls layout template for a particular filter:
```xml
<filter id="someFilter"
     applyTo="someTable"
     controlsLayoutTemplate="[add_condition] [spacer] [settings |edit, clear_values] [max_results]"
     dataLoader="someDl">
```

See the [cuba.gui.genericFilterControlsLayout](https://doc.cuba-platform.com/manual-7.1/app_properties_reference.html#cuba.gui.genericFilterControlsLayout) for layout format description
