### ISSUE TITLE
Editable table selects the previously selected row on focus of a field in another row

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1464]
### Environment
- Platform version: 6.10.0;
- Client type: Web.
### Description of the bug or enhancement
- Steps to reproduce:
1. Make some table and column editable
3. Try to type some text
4. Then try to select a field on another row
- Expected behavior
Other row is selected
- Actual behavior
Previous row will be selected

**Comment by dtsaryov** [comment]
It's a known issue that doesn't have any easy fix.

Solution for the problem is to use generated columns with Labels for non-editable columns. In this case focus will be switched correctly.
