### ISSUE TITLE
Add ability to switch off the first component focusing

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1472]
Currently, if no `focusComponent` is set, then the first possible component is focused, excluding buttons. 

It would be useful to have a possibility to disable this feature in case we want to focus a component by a custom logic. 

1. Implement **focusComponent** options: `AUTO`, `OFF`
2. Remove the code that excludes buttons from the default focusing logic

----
### Changes
**In v7 screen xml** added new attribute:
* `focusMode` with one option `NO_FOCUS`
  
- `focuseMode` is not defined. It means that window will focus components as it is defined in default logic:
if `focusComponent` is defined it will be focused, if `focusComponent` is not defined window will focus fisrt founded component.
- **NO_FOCUS**. it means that window will not focus components. Even if `focusComponent` is defined.

Note, now buttons can be focused if window wll try to find first component to focus. (if `focusComponent` is not specified and `focusMode` is AUTO)

### How to test
1. Check above-mentioned options are worked correctly.

**Comment by Flaurite** [comment]
Improve API for focus mode
