### ISSUE TITLE
NEW_TAB window is shown as DIALOG if opened from option dialog

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#1477]
Platform 7.0

See demo project in attachments

1) Open project from attachments
2) Open any browser screen from the Application menu
3) Do not select any item from the table and click Show Pivot button. The pivot table will be displayed in the new tab.
4) Select any item from the table and click Show Pivot button. In dialog window click "Selected Rows" or "All rows" it does not matter.

AR: Pivor table will be displayed in the dialog window instead of the new tab
[pivotAction.zip](https://github.com/cuba-platform/cuba/files/2533146/pivotAction.zip)

**Comment by jreznot** [comment]
Fixed in #715
