### ISSUE TITLE
Strange behavior of "Close Others" tab action

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#1481]
Platform 7.0

1) Open project based on Platform version 7.0
2) Open the two tabs
3) Right-click on the inactive tab
4) Click "Close others"

AR: The inactive tab has been closed, but should be closed the active tab.

At the screenshot below Roles tab will closed.
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/e7a9ba17-3b4b-421f-ae7b-2b6e86f88a90)

## Updates
Clicking the button "Close others" will close all tabs except the selected tab.

## QA
Checklist
* Check the above case
* Check that if the default screen is selected using the properties `cuba.web.defaultScreenId`, and `cuba.web.defaultScreenCanBeClosed  = false`, then the default screen will not close.
* Check that if the editor is open and changes are made (the editor is dirty), then the editor will not close.

**Comment by Mihail063** [comment]
Case 1
1. Create a new project
2. Open the first five screens in the administration menu
3. Open Roles tab
4. Start to create a new role
5. Enter a value in the Name field
6. Move the cursor to the Users tab and select Close other option

Actual behavior: Dynamic Attribute tab not closed 

Case 2
1. Create a new project
2. Open the first five screens in the administration menu
3. Open Roles tab
4. Start to create a new role
5. Enter a value in the Name field
6. Move the cursor to the Users tab and select Close all option

Actual behavior: All tabs to the right of the Roles tab were not closed

**Comment by dtsaryov** [comment]
@Mihail063 

Please create a new issue related to your cases as a regression and assign to me.
