### ISSUE TITLE
@Future and @Past validations have wrong invalidValue in the response body in the REST API

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#1491]
### Environment

- Platform version: 6.10, 7.0
- Operating system: Windows

### Description of the bug or enhancement
1) Set the _@Past_ annotation for some date field
2) Try to create new instance with invalid date using REST API
3) See the response body:
**AR:**

```
    {
        "message": "must be in the past",
        "messageTemplate": "{javax.validation.constraints.Past.message}",
        "path": "dateOfBirth",
        "invalidValue": 1572617541047
    }
```

**ER**
"invalidValue" param must have the _Date_ type

**Comment by knstvk** [comment]
Issue moved to [cuba-platform/restapi #40](https://github.com/cuba-platform/restapi/issues/40) via [**ZenHub**](https://www.zenhub.com/)
