### ISSUE TITLE
Distribute aggregation value mechanism for Table / GroupTable

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1494]
### Environment

- Platform version: 6.10
- Client type: Web

### Description of the bug or enhancement

Improve the standard GroupTable component to allow developers to implement algorithms for distribution of data between rows. It means that if a user enters a value to an aggregated cell, the value is distributed to the constituting cells according to a custom algorithm. An algorithm can consider existing values. The work doesn't include functionality for freezing some cells or making them non-editable.

---
### Changes
Now total and group aggregations are editable and we can handle their changes.
![image](https://user-images.githubusercontent.com/22093943/48624590-36622c00-e9c6-11e8-82d1-1e0097de7605.png)

### Limitations
Supports only `TOP` aggregation style.

#### API info
**AggegationInfo** can be editable:
```
<column id="estimation" editable="true">
    <aggregation editable="true" type="SUM"/>
</column>
```
**Table**, **GroupTable** and **TreeTable**
```
void setAggregationDistributionProvider(AggregationDistributionProvider<E> distributionProvider);
AggregationDistributionProvider<E> getAggregationDistributionProvider();
```
For **Table** and **TreeTable**
`AggregationDistributionContext<E>` contains:
- `Column column` where total or group aggregation was changed;
- `Object value` new aggregation value;
- `Collection<E> scope` collection of entities that will be affected by changed aggregation;
- `boolean isTotalAggregation` shows total aggregation changed or it was group aggregation

For **GroupTable**
`GroupAggregationDistributionContext<V>` extends `AggregationDistributionContext` and contains:
- `GroupInfo groupInfo` info about group row:  properties of grouped columns, their values.

### How to use
Configuration of table shoud be following
```
<groupTable id="groupTable"
            aggregatable="true"
            editable="true"
            showTotalAggregation="true">
    ...
    <column id="estimation" editable="true">
        <aggregation editable="true" type="SUM"/>
    </column>
    ...
</groupTable>
```
In the controller:
```
groupTable.setAggregationDistributionProvider(provider -> {
    // do your own logic here
});
```

### How to test
Test project you can find in gitlab, project name `distribute-table-aggregation`
In project check `GroupTable`.
1. Check that there is no exception in client side, server side.
2. Try to set showTotalAggregation=false, check client side errors.
3. Try to enter not valid value - tray notification should be shown

Do your own Table and TreeTable.
1. Check all above cases;

Also, check all browsers.

**Comment by natfirst** [comment]
1. Open the app in the ?debug mode
2. Reload Task browser screen with the aggregation table
3. Client side exception occurs

**Comment by myatlevEvg** [comment]
1) Open the demo project in IE (does not matter which version is)
2) Create some tasks in Task Browser screen
3) Click Plan
4) The carriage is missing for aggregation row and field is cannot be edited
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/482ed9f3-dfa4-4841-95cc-0e85d6e1b26d)
