### ISSUE TITLE
Expose SideMenu size style variables

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1510]
All size rules are hardcoded now:
- default width
- width ranges
- min "visible" width

It is suggested to expose SCSS variables to provide an ability to customize `SideMenu` in theme extensions

### Environment

- Platform version: 7.0
- Client type: Web

See forum: [SideMenu view for smaller desktop screen](https://www.cuba-platform.com/discuss/t/sidemenu-view-for-smaller-desktop-screen/6945)

**Comment by Flaurite** [comment]
### Changes

Now Responsive SideMenu has new SCSS variables:
```
$cuba-responsive-sidemenu-togglebutton-caption-disappeared-max-width-range: 500px !default;
$cuba-responsive-sidemenu-togglebutton-appeared-max-width-range: 800px !default;
$cuba-responsive-sidemenu-small-style-max-width-range: 1100px !default;
$cuba-responsive-sidemenu-use-custom-width: false !default;
$cuba-responsive-sidemenu-width: auto !default;
$cuba-responsive-sidemenu-small-width: $v-unit-size * 3 !default;
$cuba-responsive-sidemenu-toggled-menu-width: $cuba-responsive-sidemenu-small-width !default;
```
**Note!**
To enable following variables:
```
$cuba-responsive-sidemenu-width: auto !default;
$cuba-responsive-sidemenu-small-width: $v-unit-size * 3 !default;
$cuba-responsive-sidemenu-toggled-menu-width: $cuba-responsive-sidemenu-small-width !default;
```
You neet to set:
```
$cuba-responsive-sidemenu-use-custom-width: true;
```
----
### Variables description
*Responsive sidemenu width*
**$cuba-responsive-sidemenu-width: 300px;**
![resposnsive_sidemenu_width](https://user-images.githubusercontent.com/22093943/53741738-746d5800-3eb0-11e9-859c-0c7906ef11a2.png)

*Responsive sidemenu width when it is in range between $cuba-sidemenu-togglebutton-appeared-max-width-range and $cuba-sidemenu-small-style-max-width-range*
**$cuba-responsive-sidemenu-small-width: 150px;
![resposnsive_sidemenu_small-width](https://user-images.githubusercontent.com/22093943/53742019-1ee57b00-3eb1-11e9-908c-a769223859a1.png)

*Responsive sidemenu width when it is opened using a toggle menu button*
**$cuba-responsive-sidemenu-toggled-menu-width: 200px;**
![cuba_responsive_sidemenu_toggled_menu_width](https://user-images.githubusercontent.com/22093943/53742267-b0ed8380-3eb1-11e9-85b6-e4086006861b.png)

*Sets max width of range when "Menu" toogle button is shown*
**$cuba-responsive-sidemenu-togglebutton-appeared-max-width-range: 700px !default;**

![cuba_responsive_sidemenu_togglebutton_appeared_max_width_range](https://user-images.githubusercontent.com/22093943/53742761-d3cc6780-3eb2-11e9-89f8-62df4b4a3d7e.png)

*The max width of range when "Menu" toggle button caption is not shown*
**$cuba-responsive-sidemenu-togglebutton-caption-disappeared-max-width-range: 550px;

![cuba-responsive-sidemenu-togglebutton-caption-disappeared-max-width-range](https://user-images.githubusercontent.com/22093943/53743151-974d3b80-3eb3-11e9-8591-379b151b1d60.png)

*The max width of range when small style sidemenu is shown*
**$cuba-responsive-sidemenu-small-style-max-width-range: 1100px !default;**

*Whether use custom width for sidemenu, small sidemenu and toggled sidemenu*
**$cuba-responsive-sidemenu-use-custom-width: false !default;**

### For QA
Please, check these variables in all themes in all browsers.
