### ISSUE TITLE
DELETE_TS may be not included in SQL query depending on cuba.useInnerJoinOnClause property value

### ISSUE THREAD

**Issue by ym-shepelev** [cuba-platform/cuba#1513]
### Environment
- Platform version: 6.8-SNAPSHOT

### Description of the bug
See the patch for refapp (release_6_8 branch): [use-inner-join.zip](https://github.com/cuba-platform/cuba/files/2556574/use-inner-join.zip)

UseInnerJoinTest performs the following JPQL query:
`select count(hde) from refapp$HardDeleteEntity hde where hde.softDeleteEntity.name = :name`
Then it removes this SoftDeleteEntity and tries to perform this query again.

1) If cuba.useInnerJoinOnClause=true, it will be transformed into the following SQL query:
`SELECT COUNT(t0.ID) FROM {oj REF_HARD_DELETE_ENTITY t0 JOIN REF_SOFT_DELETE_ENTITY t1 ON (t1.ID = t0.SOFT_DELETE_ENTITY_ID)} WHERE (t1.NAME = 'sdEntity.test')`

2) If cuba.useInnerJoinOnClause=false (by default), then we have a different query:
`SELECT COUNT(t0.ID) FROM REF_HARD_DELETE_ENTITY t0, REF_SOFT_DELETE_ENTITY t1 WHERE ((t1.NAME = 'sdEntity.test') AND ((t1.ID = t0.SOFT_DELETE_ENTITY_ID) AND (t1.DELETE_TS IS NULL)))`

As we see, if cuba.useInnerJoinOnClause=false, DELETE_TS IS NULL check will be appended to query. In the first case, the test will fail; but with default property value, it will pass.

### Incorrect behaviour analysis
With cuba.useInnerJoinOnClause=false, DELETE_TS is appended here:
QueryKeyExpression:845
`normalizer.addAdditionalExpression(mappingExpression.and(additionalExpressionCriteria()).and(this.onClause));`

But when we use cuba.useInnerJoinOnClause=true, this line will not be executed because the following condition (QueryKeyExpression:819)
`else if ((shouldUseOuterJoin() && (!getSession().getPlatform().shouldPrintOuterJoinInWhereClause()))
                    || (!getSession().getPlatform().shouldPrintInnerJoinInWhereClause()))`
has 'true' value, and thus, the expression will be returned in QueryKeyExpression:830 without appending the additional expression.

**Comment by andreysubbotin** [comment]
See cuba-platform/cuba/#332
