### ISSUE TITLE
Update kryo to receive a memory leak fix

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1517]
### Description of the bug or enhancement
Kryo 4.0.2: https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-4.0.2

This release has a fix for a memory leak described here: https://github.com/EsotericSoftware/kryo/issues/549
(famous problem when you clear a collection but don't shrink backing array).
We have observed this problem in Sherlock production. See mat screenshot:
![image](https://user-images.githubusercontent.com/6158807/48137038-95cf8600-e2ba-11e8-889e-7d9c1885222d.png)
2-million writtenObjects collection never frees occupied memory.

However I don't agree with this default value:
https://github.com/EsotericSoftware/kryo/issues/549#issuecomment-356943532

They re-initialize writtenObjects collection every time when it's larger than 2048 elements.
I've checked in test environment and in Sherlock it is a very often situation when writtenObjects is larger than 30000.
I think at least for Sherlock optimal resize threshold should be 65536 - otherwise we will get increased memory allocation by Kryo.

**Comment by andreysubbotin** [comment]
For QA: smoke test for serialization with KRYO
