### ISSUE TITLE
Ability to use shortened URLs without /1/ state mark for initial opening of page

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1526]
### Environment

- Platform version: 7.0.0
- Client type: Web

### Description of the bug or enhancement

Let's say we want to send `http://localhost:8080/app/#main/users` URL via email instead of `http://localhost:8080/app/#main/0/users`. 

Now it is treated as incorrect URL.

**Comment by dtsaryov** [comment]
It is a bug. Will be fixed in #280.
