### ISSUE TITLE
Double-click isn't fired by the Tree with selectionMode="MULTI"

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1531]
#### Environment

- Platform version: 7.0

#### Description of the bug or enhancement

Case 1:
1. Open any screen
2. Add filter search conditions
3. Select the condition in the tree and try to select it by the double-clicking

Case 2:
1. Open reports screen
2. Create any report using wizard
3. Try to select attributes for the report by double-clicking

**A.R.** Nothing will be selected

**Comment by glebfox** [comment]
It's a Vaadin bug. See vaadin/framework#9827.
