### ISSUE TITLE
TabSheet retains links to previously removed tabs - leaks memory

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1537]
### Environment
- Platform version: 5.6.23, 6.8
- Client type: Desktop

### Description of the bug or enhancement
When you keep open screen with a tabsheet and dynamically load, add and remove tabs.
Desktop tabsheet does not remove all links to removed tabs on removeTab() call.
Collections: `tabs`, `tabContents` still contain links to old tabs.

It leads to memory leak if the screen is opened for a long time.

See attached patch for refapp 5.6:
[tabsheet-remove-tab.patch.txt](https://github.com/cuba-platform/cuba/files/2579652/tabsheet-remove-tab.patch.txt)

- Open RefApp.
- Application -> Drivers -> Create.
- Keep clicking "Add/Remove Tab".
- Every time a new tab is added and then removed.

You can watch in JVisualVM how used heap memory grows:

![image](https://user-images.githubusercontent.com/6158807/48467723-30701d80-e803-11e8-81fb-389eabb6ef36.png)

#### Test project

[desktop-ts-memory-leak.zip](https://app.zenhub.com/files/54624511/0c174414-ba34-4011-a904-116c6968c8ac/download)

- Run desktop App from test project
- Run Java VisualVM (from the "Start" Win menu or from JDK directory)
- Connect to desktop app:
![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/2bacd87f-bb42-4bcb-9760-b33c6092c362)
- Open "Monitor tab" and see for "Heap" chart (top right corner)
- Open "Test screen" and add tabs with buttons - heap size will be increased:
![jvvm_added.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/5e978da4-2c94-4c00-8bb2-3f5c1372ef5e)
- Click "Remove all Tabs" and wait until GC will be performed or click "Perform GC" in Visual VM - heap size should be decreased:
![jvvm_removed.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/5370e4ee-1c75-4bc4-b2b4-3adf22770b8a)

**Comment by alexbudarov** [comment]
The problem is deeper. It can also be reproduced on web client.
If addTab / removeTab argument is a frame - window-level DsContext does not de-register child dsContext instances:
![image](https://user-images.githubusercontent.com/6158807/48471253-ed1aac80-e80c-11e8-8d74-be802fedced8.png)

**Comment by alexbudarov** [comment]
Changing code from application side and manually removing child dsContext solves dsContext's part of problem:
```
            mainTabsheet.removeTab("tab" + counter);
            getDsContext().getChildren().remove(tab3.getDsContext());
```
Thanks to CUBA returning original unprotected collection.

**Comment by dtsaryov** [comment]
Problem with `DsContext` is moved to other issue: #1865
