### ISSUE TITLE
Unnecessary memory allocations by CoreAttributeGroup / GlobalPersistentAttributesLoadChecker

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1542]
### Environment
- Platform version: 6.8.13

### Description of the bug or enhancement
1) 
Method com.haulmont.cuba.core.global.GlobalPersistentAttributesLoadChecker#isLoadedByFetchGroup
uses this call to check that entity's fetch group contains given attribute:
```
com.haulmont.cuba.core.global.GlobalPersistentAttributesLoadChecker#isLoadedByFetchGroup

   boolean inFetchGroup = fetchGroup.getAttributeNames().contains(property);
```
If you navigate to getAttributeNames() implementation:
```
org.eclipse.persistence.core.queries.CoreAttributeGroup#getAttributeNames

    public Set<String> getAttributeNames() {
        Set<String> attributes = new HashSet<String>();
        
        if (this.superClassGroup != null && this.superClassGroup != this){
            attributes.addAll(this.superClassGroup.getAttributeNames());
        }
        attributes.addAll(getItems().keySet());
        return attributes;
    }
```
You will see that for every call - every time fetch group allocates, fills and returns a new HashSet object to caller. Just to be used once for one contains() call.

This implementation itself is not a big deal - it's just one HashSet after all.
But.

2) 
Mentioned GlobalPersistentAttributesLoadChecker#isLoadedByFetchGroup method is actually a hot spot in the code because it is used in inner recursive cycle from RdbmsStore#loadList:

com.haulmont.cuba.core.app.RdbmsStore#loadList
-> com.haulmont.cuba.core.app.AttributeSecuritySupport#onLoad(Collection, View)
-> com.haulmont.cuba.core.app.AttributeSecuritySupport#onLoad(Entity, View)
-> com.haulmont.cuba.core.global.MetadataTools#traverseLoadedAttributesByView
-> com.haulmont.cuba.core.global.MetadataTools#internalTraverseAttributesByView
which walks the whole loaded graph and calls PersistentAttributesLoadChecker#isLoaded for every entity property.

For example, if you put breakpoint in the code, and open standard RefApp User browser with 50 entities.
You can count that during opening of the screen:
- GlobalPersistentAttributesLoadChecker#isLoadedByFetchGroup - called 1208 times
- CoreAttributeGroup#getAttributeNames - called 1441 times. Some of calls are from inside of EclipseLink.

So org.eclipse.persistence.core.queries.CoreAttributeGroup#getAttributeNames is a hot spot and it produces sensitive amount of excessive memory allocations.

**Comment by alexbudarov** [comment]
Also if you put PerfStat-s to measure RdbmsStore#loadList steps, you can see that it takes noticeable time to execute attributeSecuritySupport#onLoad(entities) on large entity lists, from 50 entities or more (starting from several milliseconds, the larger list the longer time)

For our project we have just overridden AttributeSecuritySupport bean and added app property to disable onLoad actions:
<details>
 <summary>Click to expand</summary>
 
```js
public class MyAttributeSecuritySupport extends AttributeSecuritySupport {

    @Inject
    private CoreModuleConfig coreModuleConfig;

    @Override
    public <T extends Entity> void setupAttributeAccess(T entity) {
        if (coreModuleConfig.isDisableExpensiveDynamicPermissions()) {
            return;
        }
        super.setupAttributeAccess(entity);
    }

    @Override
    public boolean isAttributeAccessEnabled(MetaClass metaClass) {
        if (coreModuleConfig.isDisableExpensiveDynamicPermissions()) {
            return false;
        }
        return super.isAttributeAccessEnabled(metaClass);
    }

    @Override
    public void onLoad(Collection<? extends Entity> entities, View view) {
        if (coreModuleConfig.isDisableExpensiveDynamicPermissions()) {
            return;
        }
        super.onLoad(entities, view);
    }

    @Override
    public void onLoad(Entity entity, View view) {
        if (coreModuleConfig.isDisableExpensiveDynamicPermissions()) {
            return;
        }
        super.onLoad(entity, view);
    }
}
```
</details>

**Comment by knstvk** [comment]
@andreysubbotin Let's introduce a similar toggle and make it disabled by default since 7.0.

**Comment by andreysubbotin** [comment]
Disable logic for dynamic permissions if no handler exists
