### ISSUE TITLE
LookupField nullName shoud be added to options list if it is empty

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#156]
Now you can see the option specified as nullName only if the Lookupfield has optionsDatasouruce or options/map  list. 

---
Original issue: https://youtrack.haulmont.com/issue/PL-6094

**Comment by jreznot** [comment]
Should be fixed with 7.0

**Comment by jreznot** [comment]
It seems that already fixed with Vaadin 8
