### ISSUE TITLE
Change default TextField TextChangeEventMode to BLUR

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#1575]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

Value change listeners should be fired when the text field loses focus (it worked this way in previous platform versions)

**Comment by jreznot** [comment]
Add TextChangeEventMode BLUR mode and make it default

**Comment by sukhova** [comment]
Please add new TextChangeEventMode to xsd
