### ISSUE TITLE
Entities are not deleted from the new screens

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1577]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

1. Create an entity
2. Create browser and editor screens (new 7.0 version) for this entity
3. In the app create the entity instance
4. Delete the instance, reopen the screen, the instance will be displayed in the table

**A.R.** `delete_ts` and `deleted_by` are not set

**Comment by knstvk** [comment]
Now RemoveAction uses DataManager directly if it works with standalone (not nested) container. It works correctly with any "no-op" DataContext and even for StandardDataContext it is more correct: otherwise the action would commit all changes.
