### ISSUE TITLE
Add ConfirmationResult handler for table RemoveAction

### ISSUE THREAD

**Issue by koca2000** [cuba-platform/cuba#1581]
Hi,

can you please add new handler to RemoveAction which will run when user click ok or cancel in confirmation dialog. It should have boolean with result as argument.

If you need some more informations, let me know.

**Comment by jreznot** [comment]
Hi,

Old actions API is on hold for now, because they have been redesigned in the upcoming 7.0 version. You can inherit `RemoveAction` and override `confirmAndRemove` method if needed.

**Comment by koca2000** [comment]
I forgot to mension that I use RemoveAction in table. It doesn't have confirmAndRemove. I didn't know that there are two RemoveAction classes. In fact for my purpose I only need to separate the dialog result logic: https://github.com/cuba-platform/cuba/blob/65fa207c652984c5602f4773bbd30466d864d571/modules/gui/src/com/haulmont/cuba/gui/actions/list/RemoveAction.java#L153 to function that I can override.

The reason why I want to do that is that I need to remove all the child entities from TreeTable.

**Comment by jreznot** [comment]
What version of the platform do you use? If you are trying to extend RemoveAction logic in 7.0 BETA please wait for official release and documentation, we will clarify this in the manual.

**Comment by koca2000** [comment]
I was trying it in 7.0 BETA. I'll wait then.
