### ISSUE TITLE
Remove extra TokenList paddings

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1586]
![изображение.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/247db9d6-a14c-495a-869e-822829bb2924)

## QA Check list

- [x] `simple` mode
- [x] editor position (LookupPickerField or Add/Clear buttons)

**Comment by natfirst** [comment]
Set margin-bottom to 0px
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/cf063c83-e9a4-44a1-895d-5513628cca28)
