### ISSUE TITLE
Help buttons should look the same as the context help

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1610]
#### Environment

- Platform version: 7.0

### Description of the bug or enhancement

Case 1
1. Open Reports->Reports Editor -> Localizations

Case 2
2. Create a report using wizard.
3. On the save report step see the help button for the output name pattern

Case 3
4. Edit an existing report. Open the template editor tab. Create new or edit existing template.  Help button for the output name pattern
5. Open reports parameter editor, select report, check the help buttons in all tabs.

Help button should look the same as the context help (see, for example, Group constraint editor). It should be black.

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/8420f681-99fb-4c18-9b71-fce7fb2fbad1)

**Comment by andreysubbotin** [comment]
Changeset: https://github.com/cuba-platform/reports/commit/fe36a04fd2f3f8fdbe754f6f2abc266c0f41cc07
