### ISSUE TITLE
Align for image doesn't work in responsive main window template

### ISSUE THREAD

**Issue by alexander-shustanov** [cuba-platform/cuba#1614]
### Environment
- Platform version: 7.0-SNAPSHOT

### Description of the bug

* Create responsive main window with CUBA Studio 7.
* Start application
* Look at logo icon, it is not centered

![изображение.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/e78c7d43-1969-4bfb-a503-fbe1605c7e14)

## Test project

[responsive-sidemenu-logo.zip](https://github.com/cuba-platform/cuba/files/2662831/responsive-sidemenu-logo.zip)

## QA

Cache refresh can be needed to apply changes - use `Ctrl+F5` hotkey.

**Comment by jreznot** [comment]
Apply for img in responsive menu panel:
```
margin-left: auto;
margin-right: auto;
```
