### ISSUE TITLE
FieldGroup fields doesn't support HTML description

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#1636]
### Environment

- Platform version: 7.0
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example
See cuba-platform/reports#131
Screen XML: `com/haulmont/reports/gui/report/wizard/step/first-details-frame.xml`

**Comment by jreznot** [comment]
It seems that we need to provide explicit captionAsHtml and descriptionAsHtml properties for UI components

**Comment by glebfox** [comment]
Possibility to define HTML description has been introduced in #1676
