### ISSUE TITLE
Usability degradation of 'IN' filter in CUBA 6.8.13

### ISSUE THREAD

**Issue by Quicksy** [cuba-platform/cuba#1643]
### Environment

- Platform version: 6.8.13
- Client type: Web, Desktop

### Description of the bug or enhancement
In Cuba 5.6 it was possible to enter several values separated by commas into string filter with 'IN' condition and it used to work perfectly:
![image](https://user-images.githubusercontent.com/34827700/49510007-7cf9c680-f8a0-11e8-9210-540b1daf9bbe.png)

In Cuba 6.8.13 new list editor has been added for such filters that just do not support adding several values at once and you have to enter each value separately. It makes using this filter very difficult in case you have the list of such values:

![image](https://user-images.githubusercontent.com/34827700/49510730-884df180-f8a2-11e8-8869-a602575c2dcb.png)

**Comment by Quicksy** [comment]
Also, same situation applied to Category Attributes with type = 'Enumeration' - you have to manually fill enumeration with elements one-by-one.

**Comment by alexbudarov** [comment]
@jreznot 
It's not an enhancement, it's a usability regression.

**Comment by jreznot** [comment]
I'm not sure that regression label is suitable, and we do not have a separate lable for usability problems

**Comment by alexbudarov** [comment]
The difference is - previously users could prepare a long list of numbers e.g. in Excel and then copy-paste it to the field.

Now they can't do it.

**Comment by gorbunkov** [comment]
Ok, I understood your case. We can do the following:
1. Support both ways of entering data for string and number types (comma-separated string and using the list editor component)
1. Support the standard shortcut (Ctrl + Alt + L) that will open the list editor

**Comment by gorbunkov** [comment]
It should be possible to enter comma-separated values for filter IN condition if entity attribute datatype is one of the following: string, integer, long, double or BigDecimal.
