### ISSUE TITLE
BaseAction.target has no type parameter

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#165]
ListComponent может иметь параметр - тип сущности.
Но в BaseAction он использован без параметра.
Из-за этого все наследники BaseAction обречены на приведение типов при использовании getSingleSelected() и type erasure при использовании getSelected().

см. например несколько экшенов, создаваемых в com.haulmont.reports.gui.report.browse.ReportBrowser#init

---
Original issue: https://youtrack.haulmont.com/issue/PL-6363

**Comment by jreznot** [comment]
Not relevant anymore since 7.0 introduces lightweight action delegation mechanism.
