### ISSUE TITLE
AbstractComponentGenerationStrategy should support new data binding API

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1662]
### Environment
- Platform version: 7.0.0
- Client type: Web

See also FieldFactory interface

**Comment by glebfox** [comment]
For QA: 

Check that the following cases work:

* Editable table in a legacy screen
* Editable table in a new screen
* Editable DataGrid in a legacy screen
* Editable DataGrid in a new screen
* FieldGroup
