### ISSUE TITLE
Table cache rate and page length configs are not propagated to the client

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1666]
See forum:
[Issue: auto-height table in scrollbox shows unused space](https://www.cuba-platform.com/discuss/t/issue-auto-height-table-in-scrollbox-shows-unused-space/7160)

### Environment

- Platform version: 6.10.3
- Client type: Web

### Description of the bug or enhancement

Table doesn't show all rows that leads to empty space at the bottom. Moreover the `cuba.web.table.pageLength` config is not propagated to the client.

- Minimal reproducible example

[test project](https://app.zenhub.com/files/54624511/aad7c40d-a31a-44ed-a6b9-24683ebe1e15/download)

- Actual behavior

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/2ee7f05d-887e-4a60-8520-9df807c201a3)

### QA:

See #1606 for changes

**Comment by jreznot** [comment]
Relates to #1606
