### ISSUE TITLE
FTS improvements

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#167]
основное что долго происходит в полнотекстовом поиске - это поиск hitInfo. это особенно видно когда идет поиск по FileDescriptor.
в тезисе есть реализация ленивой подгрузки hitinfo:
1. для поиска в списках hitinfo ищется только если навели мышкой на строку (см. LazyHitInfoMap)
2. для глобального поиска hitinfo ищется только для отображаемых данных (см. ThesisFtsServiceBean#makeSearchResult)

также при глобальном поиске хотелось бы видеть инфу отсортированную по дате создания в обратном порядке .сейчас инфа о дате создания не хранится в индексе, но может быть стоит хранить?

---
Original issue: https://youtrack.haulmont.com/issue/PL-6375

**Comment by knstvk** [comment]
Issue moved to [cuba-platform/fts #32](https://github.com/cuba-platform/fts/issues/32) via [**ZenHub**](https://www.zenhub.com/)
