### ISSUE TITLE
Make AttributeAccessSupport accept FrameOwner instead of Frame

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba#1677]
Now:
`public void applyAttributeAccess(Frame frame, . . . )`

Should be:
`public void applyAttributeAccess(FrameOwner frameOwner, . . .)`

Thus enabling users pass  `this` when calling `attributeAccessSupport.applyAttributeAccess()` from screens.

Support  dynamic attribute access for new screens

**Comment by andreysubbotin** [comment]
For QA: test support dynamic attribute access for new screens
