### ISSUE TITLE
Optional dependencies for screens

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1683]
### Environment
- Platform version: 6.8.x

### Description of the bug or enhancement
Sometimes in our project developers inject to a screen (or to companion) a datasource, component or even bean which is not always present.
There can be the following reasons for that:
- one controller or companion being used for several similar screens;
- bean can be implemented in desktop but not implemented in web (e.g. telephony)

For example:
```
public class WebIndividualAddressTabCompanion implements IndividualAddressTabCompanion {
    @Inject
    private AddressesRestrictionConfigurationDatasource individualAddressesRestrictionConfigurationDs;
    @Inject
    private AddressesRestrictionConfigurationDatasource pinAddressesRestrictionConfigurationDs;
...
```
This companion is used both in Pin editor and in Individual editor. In first case first dependency is missing; in second case - second dependency is missing.
Of course developers know that particular variable can be null and they handle this case in the code.
But we get nasty warnings in the log like we did something bad:
```
2018-12-14 07:33:30,535 WARN  [http-nio-8080-exec-6/app/alexander.budarov] [com.haulmont.cuba.gui.CompanionDependencyInjector] 
Unable to find an instance of type class com.haulmont.xxx.client.datasource.AddressesRestrictionConfigurationDatasource 
named pinAddressesRestrictionConfigurationDs
```

It would be nice to be able to mark injected dependency as optional:
- to don't get warnings in log
- for documentation purposes

**Comment by jreznot** [comment]
We can support Spring `@Autowired` annotation which has `required` attribute
