### ISSUE TITLE
When CollectionChangeListener is fired, a collection in parent entity is still not updated

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#1691]
See the project attached.
The FormData (not persistent) entity has a collection of FormField (not persistent) entities.
FormData editor screen contains a table for editing form fields.
When we modify one of 
form fields, a CollectionContainer.CollectionChangeEvent is fired. 
The problem is that Inside the collection change handler, the formData instance has a "fields" collection where the edited FormField is still not modified.

[listener-test.zip](https://github.com/cuba-platform/cuba/files/2680176/listener-test.zip)

**Comment by knstvk** [comment]
Fixed in 92e010e6e7450e3d08066413fa88d9c3a7935d3c

**Comment by knstvk** [comment]
For QA: see the server log when saving FormField - the value must be the same as your last entered one.
