### ISSUE TITLE
Support for JSR-310 date/time APIs in entities

### ISSUE THREAD

**Issue by pfurini** [cuba-platform/cuba#17]
Hi, I'm evaluating CUBA and its Studio app, but I'm wondering if it can deal with entity attributes using Java 8 date/time types.
I successfully used them in another project using Spring Data Rest and Hibernate, without any issue, but I don't know if your infrastructure is ready to support them OOB.. I'd prefer avoid using the old & awkward Date/Time types in my codebase.

Thanks!
P.

PS: To clarify, I mean using the `LocalDate`, `LocalTime` and `LocalDateTime` types to store UTC-only values (so "without timezone"), alongside a `ZoneId` associated to a user to make date/time calculations or displaying in the UI..

**Comment by aleksey-stukalov** [comment]
Hi @pfurini,

Thank you for your input. We consider this functionality to be implemented in with major release. You can track the state of this task on our issue tracker [here](https://youtrack.haulmont.com/issue/PL-9007). 

Regards,
Aleksey

**Comment by pfurini** [comment]
Hi @aleksey-stukalov 
thanks for your feedback, but the issue tracker is private, and it asks for authentication credentials..

What's your development model? I see that the license is Apache 2, and that's fine, but to me a project is truly "open" when the dev process is also open..
I mean, it's ok to have an internal governance, but you should actively accept external issues, and let the public community see and participate in active tasks/issues. Not using GH for that is fine, like Spring and others that are on JIRA, but they are all open to the public..

Just my 2c,
Paolo

**Comment by aleksey-stukalov** [comment]
@pfurini ,

Please see this [announcement](https://www.cuba-platform.com/support/announcement/roadmap_1). We accept external issues on our support forum. So, welcome to the forum :)

Regards,
Aleksey

**Comment by pfurini** [comment]
@aleksey-stukalov I see.. Then you posted the wrong link ;) I think the right one is https://youtrack.cuba-platform.com/issue/PL-9007

**Comment by aleksey-stukalov** [comment]
@pfurini ,

Isn't it the same?

**Comment by pfurini** [comment]
No.. the other one is on youtrack.haulmont.com, that I suppose it's your internal tracker..

**Comment by aleksey-stukalov** [comment]
you are absolutely right! Thanks

**Comment by pfurini** [comment]
you're welcome.. just landed on the forum, and wrote this [post](https://www.cuba-platform.com/support/topic/state-of-the-open-source-project-management#comment-6298). I hope to see improvements in the overall process, 'cause the project itself has great potential, but with great power comes great responsibility...
Paolo

**Comment by aleksey-stukalov** [comment]
Thanks for that!
