### ISSUE TITLE
Scrolls appear for a table with height="AUTO" while using Hover theme

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1708]
### Environment

- Platform version: 6.10
- Browser: Chrome
- Operating system: Windows
- Theme: Hover
- Hardware: **Win Book with high dpi (125%)**

### Description of the bug or enhancement

- Minimal reproducible example
```
<table id="parametersTable"
       width="100%"
       height="AUTO">
```
- Expected behavior

![image.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/9e32f9e2-d49e-433e-81c6-507b571e52ed)

- Actual behavior

![image.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/7103e285-d496-4246-8f46-e8c472d095b7)

**Comment by dtsaryov** [comment]
@natfirst 
Unable to reproduce the problem. Check whether problem exists or close the issue.
