### ISSUE TITLE
Add a public method for setting groupbox caption of the Filter component

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#1739]
![image](https://user-images.githubusercontent.com/7888486/50883497-b2468680-1401-11e9-992a-0ff835ed8dc4.png)

See the forum topic: https://www.cuba-platform.com/discuss/t/how-do-i-change-the-name-of-the-tab/7596

**Comment by BryanYin** [comment]
Also we need a method to change tab caption.

**Comment by jreznot** [comment]
> Also we need a method to change tab caption.

You can easily do this:
```
getWindow().setCaption("New caption");
```

**Comment by BryanYin** [comment]
> > Also we need a method to change tab caption.
> 
> You can easily do this:
> 
> ```
> getWindow().setCaption("New caption");
> ```

Yea, that's the simplest case, but not work in screen with filter. If I save a filter, then select this filter, the tab caption will be changed to initialCaption+":"+filterName. If at this time I want the tab name remains as initialCaption, any idea I could do that in a simple way?

**Comment by gorbunkov** [comment]
There is no need to introduce a new public method. The filter caption and the windows tab caption may be modified in the following way:
```java
        filter.addFilterEntityChangeListener(filterEntity -> {
            //to set the filter groupbox caption
            filter.setCaption("My Custom Filter: " + filterEntity.getName());
            ////to remove the name from the window tab caption
            getWindow().setDescription(null);
        });
```

**Comment by gorbunkov** [comment]
For windows caption changing see also: https://github.com/cuba-platform/cuba/issues/2148
