### ISSUE TITLE
Support serialization for NULL values for REST services

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#1742]
https://www.cuba-platform.com/discuss/t/how-to-simply-enable-entityserializationoption-serialize-null/7637

### Environment
- Platform version: 6.10
- Client type: REST

**Comment by knstvk** [comment]
Issue moved to [cuba-platform/restapi #37](https://github.com/cuba-platform/restapi/issues/37) via [**ZenHub**](https://www.zenhub.com/)
