### ISSUE TITLE
Support setting DOM attributes on nested elements in HtmlAttributes

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1755]
### Environment

- Platform version: 7.0.0

### Description of the bug or enhancement

Sometimes, we need to add DOM and CSS attributes on nested html elements. For instance: https://www.cuba-platform.com/discuss/t/adding-attribute-to-html-tag/7769

**Comment by glebfox** [comment]
The following methods have been added to `HtmlAttributes`:
* `setDomAttribute(Component component, String querySelector, String attributeName, String value)` - Sets DOM attribute for all nested elements of UI component corresponding to the given query selector.
* `getDomAttribute(Component component, String querySelector, String attributeName)` - Gets DOM attribute value assigned using `HtmlAttributes`. Does not reflect a real value from DOM.
* `removeDomAttribute(Component component, String querySelector, String attributeName)` - Removes DOM attribute for all nested elements of UI component corresponding to the given query selector.
* `setCssProperty(Component component, String querySelector, String propertyName, String value)` - Sets CSS property value for all nested elements of UI component corresponding to the given query selector.
* `getCssProperty(Component component, String querySelector, String propertyName)` - Gets CSS property value assigned using `HtmlAttributes`. Does not reflect a real value from DOM.
* `removeCssProperty(Component component, String querySelector, String propertyName)` - Clears CSS property value for all nested elements of UI component corresponding to the given query selector.
* `applyCss(Component component, String querySelector, String css)` - Apply CSS properties from CSS string;

Where `querySelector` a string containing one or more selectors to match. This string must be a valid CSS selector string.
