### ISSUE TITLE
Can't build project by gradle-:cuba-plugin-7.0-SNAPSHOT.pom don't exists?

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/cuba#1756]
### Environment

- Platform version: 7.0

- Expected behavior
gradle build pass 
- Actual behavior
encounter some error:
![image](https://user-images.githubusercontent.com/1725996/51080456-eaf2a280-1716-11e9-829e-28cf74336141.png)
` org.gradle.api.resources.ResourceException: Could not get resource 'https://jcenter.bintray.com/com/haulmont/gradle/cuba-plugin/7.0-SNAPSHOT/cuba-plugin-7.0-SNAPSHOT.pom'.`

**Comment by jreznot** [comment]
Please see instructions in README. You have to build and install cuba Gradle plugin from sources.
