### ISSUE TITLE
MetaClass of the KeyValueEntity is not filled when it is added to data container

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#1766]
When a KeyValueEntity is added to the data container in the following way:

```java
KeyValueEntity entity = new KeyValueEntity();
entity.setValue("prop1","value1");
keyValueCollectionDc.getMutableItems().add(entity);
```

Then the metaClass of the KeyValueEntity is not filled. MetaClass is filled only when items are added to the container using the **setItems()** method.

**Comment by knstvk** [comment]
Check also assignment of `idName` in all relevant places.
