### ISSUE TITLE
Enforce entity bean validation rules on the DataStore level

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#1771]
### Environment

- Platform version: 6.10

### Description of the bug or enhancement

Entity bean validation rules must be checked in DataStores by default. Provide a feature toggle to switch off the validation for backward compatibility.

See https://www.cuba-platform.com/discuss/t/entity-validation-when-using-datamanager-commit/7736

**Comment by soraksh** [comment]
Added new application property `cuba.dataManagerBeanValidation` with default value `true` which toggles entity bean validation on `DataManager` level.

**Comment by soraksh** [comment]
Entity bean validation enforced on `DataManager` level instead of `DataStore`.

**Comment by soraksh** [comment]
Added `ValidationType` and `ValidationGroups` for `DataContext.PreCommitEvent` which affects commit associated with event (will be ignored if `DataContext` is child).

**Comment by andreysubbotin** [comment]
Perform bean validation before transaction commit
