### ISSUE TITLE
Script 180312-renameColumns.sql makes backwards incompatible changes to DB schema

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1780]
### Environment
- Platform version: 6.10+

### Description of the bug or enhancement
Script cuba/modules/core/db/update/postgres/18/180312-renameColumns.sql contains column renames.
Renaming column is effectively the same as deleting the old column (and adding a new one) which contradicts CUBA practices.

Deleting old column makes impossible to pre-update database on the fly without stopping old version of the system.
For Sherlock this is very important. If this problem is not changed, we will have to invent some mechanism to shade this script in our project.

**Comment by knstvk** [comment]
To QA: check updating database from version 6.8 to 6.9 on all supported databases.
