### ISSUE TITLE
Embedded attributes should be read-only if the standard entity with this attribute has read-only permission

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1784]
#### Environment

- Platform version: 6.10.6
- Forum link: https://www.cuba-platform.ru/discuss/t/problemy-s-atributom-tipa-embedded-referencetoentity/2408/14

#### Description of the bug or enhancement

1. Create an embedded entity Address, add several fields (e.g city, street)
2. Create a standard entity Citizen, add the embedded attribute
3. Create a role, add read-only permission for the Citizen entity
4. Assign the user for this role
5. Login to the system with the user, open Citizen edit screen

*A.R.* Embedded fields will be editable

Even if the embedded attribute in the Citizen entity has the read-only permission.

The case with adding the embedded attribute to the read-only list in `SetupAttributeAccessHandler` also does not work

[embeddedAttr.zip](https://github.com/cuba-platform/cuba/files/2772833/embeddedAttr.zip)

**Comment by skatova** [comment]
[embeddedAttr.zip](https://github.com/cuba-platform/cuba/files/3835884/embeddedAttr.zip)
If the whole entity is restricted from editing when everything works as expected. 

> The case with adding the embedded attribute to the read-only list in SetupAttributeAccessHandler also does not work

Still doesn't work.

**Comment by skatova** [comment]
If an entity attribute which represents an embedded entity defined read-only via the attribute tab then it will be editable anyway.

![image](https://user-images.githubusercontent.com/53561930/72077176-40549600-3310-11ea-9d50-c32db4413f27.png)

![image](https://user-images.githubusercontent.com/53561930/72077022-fd92be00-330f-11ea-9f01-c10a0deff07c.png)
