### ISSUE TITLE
Align paging counter in RowsCount component in Hover Theme

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#1806]
Reproduced on Platform 6.10 and 7.0 with hover theme
1) Open Entity Inspector
2) Select an entity which has many records (as an example you can generate Colour entity instances by workload JMX bean in Refapp)
3) Click at paging count button
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/760a0cf1-1523-4a0c-bb2d-73770810ed76)
AR: The record count is below the row itself
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/ae817f47-f9a2-4224-8bca-e4dc88f4e6f6)
Halo theme for comparison: 
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/470c148d-9c96-4290-b572-728cf78ae985)

**Comment by myatlevEvg** [comment]
Reopen.
Unnecessary space between text and rows counter.
Hover theme
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/198f4711-9ea7-4f6b-8f98-826fce2bb9db)

**Comment by knstvk** [comment]
@myatlevEvg Are you sure it relates to the initial problem and Hover theme only? If not, close this issue and create another one.
