### ISSUE TITLE
Overwritten (old instead edited) master entity in DataContext if merge child there

### ISSUE THREAD

**Issue by soraksh** [cuba-platform/cuba#1814]
- Cuba version 7.0
- Create entity with link field to this entity type
- Create master (with empty field) instance of entity and some children (with link to master)
- Create editor screen where you merge children of edited entity to DataContext before commit
- Try to save changed master entity

***Actual behavior:***
- Old version of master entity will be saved

See Timesheets (branch framework_v7_commit_problem, class ProjectEdit, method onPreCommit()) for example.

**Comment by knstvk** [comment]
Supposedly fixed in #2176
