### ISSUE TITLE
ItemPropertyChangeListener is invoked twice when we change property from editable table

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1815]
### Environment
- Platform version: 7.0.0
- Client type: Web

### Description of the bug or enhancement
Download demo project: [tabledemo.zip](https://github.com/cuba-platform/cuba/files/2796185/tabledemo.zip)

- Minimal reproducible example

In the attached project:
1. Create two Customer instances
2. In the CustomerBrowse screen: select one of entities and try to change any editable property
- Expected behavior
ItemPropertyChangeListener will be invoked one time
- Actual behavior
ItemPropertyChangeListener is invoked twice

**It is also applies to DataGrid, GroupTable and etc.**

**Comment by knstvk** [comment]
Fixed in #1880
