### ISSUE TITLE
LookupField popup exceeds screen size for a large amount of items

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1819]
### Environment

- Platform version: 6.10
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example

1. Add `LookupField` with big page length:

```XML
<lookupField id="lookupField"
             caption="LookupField"
             pageLength="100000"/>
```

2. Generate a lot of entities, collect them and use as an options list:

```Java
List<User> users = new ArrayList<>(1000);
for (int i = 0; i < 1000; i++) {
    User user = metadata.create(User.class);
    user.setLogin("user" + i);
    user.setName("User #" + i);

    users.add(user);
}

lookupField.setOptionsList(users);
```

- Expected behavior

Component popup has some suitable height

- Actual behavior

![изображение.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/a67fa10f-7eaa-4141-9f3b-f3e08c934e64)

**Comment by jreznot** [comment]
It think it is a misuse and we can postpone it
