### ISSUE TITLE
LookupPickerField doesn't display selected entity if neither datasource or optional datasource is set

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#182]
1. Создаем  embedded сущность Address, обычную сущность AddressBookItem
1. В обычную сущность добавляем embedded, создаем view, создаем single mode экран
1. На другой экран добавляем LoopupPickerField, указываем у него экран, который должен открываться
1. Запускаем приложение, открываем экран с LookupPickerField, выбираем сущность, нажимаем ok
1. В поле LookupPickerField не отобразится выбранный элемент

---
Original issue: https://youtrack.haulmont.com/issue/PL-6709

**Comment by jreznot** [comment]
Will be fixed with Vaadin 8
