### ISSUE TITLE
Support ValueSources in CurrencyField

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1822]
### Environment

- Platform version: 7.0.0

### Description of the bug or enhancement

- Minimal reproducible example

https://demo.cuba-platform.com/sampler/open?screen=annotation-currencyfield

- Expected behavior

![Screenshot 2019-01-28 at 13.52.52.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/99c6f21e-1a20-49f0-ad79-9e20588288c9)

- Actual behavior

![Screenshot 2019-01-28 at 13.53.22.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/56e1234d-b11e-4bcb-a1ce-67a5c360fd41)

### QA

Check that currency configuration is correctly loaded from `CurrencyValue` annotation when

- [ ] `CurrencyField` is used in `FieldGroup`
- [ ] `CurrencyField` is separately used

and when

- [ ] Datasource is used (legacy)
- [ ] New container is used

### Test project

[test project](https://app.zenhub.com/files/54624511/fed3af6e-c9b3-45a7-ac2a-c4ed5b28b975/download)

**Comment by dtsaryov** [comment]
It is not a bug - `ValueSource`s are not supported:

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/b4ddd821-c62c-40d5-8a91-449fb4f3732b)

**Comment by glebfox** [comment]
@dtsaryov here the screen XML of the mentioned sample: 

```
<window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
        class="com.haulmont.sampler.web.ui.components.currencyfield.annotation.AnnotationCurrencyFieldSample">
    <dsContext>
        <datasource id="productDs"
                    allowCommit="false"
                    class="com.haulmont.sampler.entity.Product"
                    view="_local"/>
    </dsContext>
    <layout>
        <fieldGroup datasource="productDs">
            <field property="name"/>
            <field property="price"/>
        </fieldGroup>
    </layout>
</window>
```

As you can see, the `fieldGroup` component and datasource are used, so it really seems to be a regression, because none code has been changed during the migration process from 6.10 version to 7.0.

Also, _Value Sources_ are supported since the component web realization extends `WebV8AbstractField` and the following XML proves this:

```
<window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
        class="com.haulmont.sampler.web.ui.components.currencyfield.annotation.AnnotationCurrencyFieldSample">
    <dsContext>
        <datasource id="productDs"
                    allowCommit="false"
                    class="com.haulmont.sampler.entity.Product"
                    view="_local"/>
    </dsContext>
    <layout>
        <fieldGroup datasource="productDs">
            <field property="name"/>
            <field property="price"/>
        </fieldGroup>
    </layout>
</window>
```

**Comment by dtsaryov** [comment]
@glebfox 

I've managed to check screen layout in Sampler.

You can see in `AbstractComponentGenerationStrategy` that `ValueSource` is explicitly set to component. 

And you can also look at `CurrencyField` web implementation and find out that there is no component specific code - obtaining configuration from `CurrencyValue` annotation from `ValueSource`.

Try to explicitly bind `Datasource` and `CurrencyField`, like this:
```XML
<currencyField datasource="productDs" property="price"/>
```

And you'll see that everything works:

![default](https://user-images.githubusercontent.com/6183810/51890844-a58cd100-23b6-11e9-8fb4-9cbc1cfc0070.png)

The following sample proves this:

[cf-test.zip](https://github.com/cuba-platform/cuba/files/2806448/cf-test.zip)
