### ISSUE TITLE
First line of app.properties file is skipped if the file is in UTF-8 with BOM format 

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#1827]
### Environment

- Platform version: 6.10

### Description of the bug or enhancement

Create a `local.app.properties` file like the attached one, and try to read the property using `AppContext.getProperty()`. The property is null. i.e. not read.

[local.app.properties.zip](https://github.com/cuba-platform/cuba/files/2806746/local.app.properties.zip)

Consider using `org.apache.commons.io.input.BOMInputStream`.

**Comment by jreznot** [comment]
I'm not sure that we should try to support BOM explicitly everywhere.  We are using simple InputStream to load a lot of resources, and usually BOM mark can break file format, such as XML.

**Comment by knstvk** [comment]
@jreznot Yes but it is usually happens only for app.properties files which are edited in various deployment scenarios. So it's enough to support it only when loading properties.
