### ISSUE TITLE
Ability to use SuggestionPickerField similar to the SearchPickerField

### ISSUE THREAD

**Issue by ovchinnikovsp** [cuba-platform/cuba#1829]
### Motivation
As SuggestionPickerField doesn't require hit enter to perform search (in compare to SearchPickerField), it is a good point to use it widely in projects.
In current version it means I need to define search executor for each usage 
### Solution
Use the same way as for SearchPickerField: define query in the datasource of the screen descriptor. 
In this case it will cover most of the simple cases, so custom search executor will be necessary for very specific cases

**Comment by jreznot** [comment]
> define query in the datasource of the screen descriptor.

Datasource is a pure UI state thing that is not compatible with background execution. Check this example in documentation on SuggestionField: https://demo.cuba-platform.com/sampler/open?screen=optionsstyleprovider-suggestionpickerfield

You can specify query and view in XML:
```
        <suggestionPickerField id="suggestionPickerField"
                               captionProperty="name"
                               datasource="orderDs"
                               property="customer">
            <query entityClass="com.haulmont.sampler.entity.Customer"
                   escapeValueForLike="true"
                   searchStringFormat="%$searchString%">
                select c from sampler$Customer c where lower(c.name) like lower(:searchString) escape '\'
            </query>
        </suggestionPickerField>
```
