### ISSUE TITLE
Introduce input dialog builder

### ISSUE THREAD

**Issue by aleksey-stukalov** [cuba-platform/cuba#1831]
Would be great to have some kind of API to create dialogs instead of creating entire screens to request a few parameters. Example of possible use is below

```java
InputDialog inputDialog = inputDialogs.create()
        .addStringParameter("String field for input", /* not mandatory */ false)
        .addBigDecimalParameter("BigDecimal number for input")
        .addCustomParameter("Custom parameter for input", () -> {
            CheckBox checkBox = uiComponents.create(CheckBox.class);
            checkBox.setStyleName("red-checkbox");
            return checkBox;
        })
        .withOutcome("OK", "Cancel");
CompletableFuture<InputDialogResult> inputDialogResult = inputDialog.request();
inputDialog.show().addAfterCloseListener(...);
```

Would be also great to have an option to declare such input dialogs in a declarative way in xml.

----
## Changes
Interface `Dialogs` contains new method for creating input dialogs:
```
InputDialogBuilder createInputDialog(FrameOwner owner);
```
It returns specific builder for configuring input dialog. The main options in this dialog are:
- input parameters
- actions

### Input parameters
`InputParameter` is a simple class that contains information about field:
* id
* caption
* default value
* required
* type (Entity or simple Datatype)  
* `Supplier<Field>` for creating custom field instead of default.  

In order to simplify creating input parameters it has fluent API and predefined static methods for all base Datatypes and Entity type:
```
stringParameter(String id);
intParameter(String id);
...
entityParameter(String id, Class<? extends Entity> entityClass)
```

`InputDialogBuilder` has two methods for adding input parameters:
```
InputDialogBuilder withParameter(InputParameter parameter); // adds one parameter
InputDialogBuilder withParameters(InputParameter... parameters); // adds multiple parameters
```

#### How to use input parameters
1. **Base data types**
```java
@Inject
private Dialogs dialogs;
...
dialogs.createInputDialog(this)
        .withParameters(
                stringParameter("nameField")
                        .withCaption("Name")
                        .withRequired(true),
                booleanParameter("hasInsuranceField")
                        .withCaption("Insurance"),
                bigDecimalParamater("priceField")
                        .withCaption("Price"))
        .withCloseListener(closeEvent -> {
            if (closeEvent.getCloseAction().equals(InputDialog.INPUT_DIALOG_OK_ACTION)) {
                String name = closeEvent.getValue("nameField");
                Boolean hasInsurance = closeEvent.getValue("hasInsuranceField");
                BigDecimal price = closeEvent.getValue("priceField");
            }
        })
        .show();
```
2. **Entity type**
```java
@Inject
private Dialogs dialogs;
...
dialogs.createInputDialog(this)
        .withParameters(
                entityParameter("userField", User.class)
                        .withCaption("User"),
                dateParameter("dateField")
                        .withCaption("Expiration date")
                        .withDefaultValue(new Date()))
        .withCloseListener(closeEvent -> {
            if (closeEvent.getCloseAction().equals(INPUT_DIALOG_OK_ACTION)) {
                User user = closeEvent.getValue("userField");
                Date date = closeEvent.getValue("dateField");
            }
        })
        .show();
```
3. **Custom field**
```java
@Inject
private Dialogs dialogs;
...
dialogs.createInputDialog(this)
        .withParameter(parameter("rateField")
                .withField(() -> {
                    RadioButtonGroup<String> buttonGroup =
                            uiComponents.create(RadioButtonGroup.NAME);
                    buttonGroup.setOptions(new ListOptions<>(
                            Arrays.asList("Limited", "Standard", "Unlimited")));
                    buttonGroup.setCaption("Rate options");
                    buttonGroup.setValue("Limited");
                    buttonGroup.setOrientation(VERTICAL);
                    return buttonGroup;
                })
        )
        .withCloseListener(closeEvent -> {
            if (closeEvent.getCloseAction().equals(INPUT_DIALOG_OK_ACTION)) {
                String rate = closeEvent.getValue("rateField");
            }
        })
        .show();
```

4. **Custom Datatype is not supported by `InputDialog`**. You need to create component and set custom Datatype to it.
```java
@Inject
private Dialogs dialogs;
...
dialogs.createInputDialog(this)
        .withParameter(
                parameter("yearField").withField(() -> {
                    TextField<Integer> yearField = uiComponents.create(TextField.NAME);
                    yearField.setDatatype(new YearDatatype());
                    yearField.setCaption("year field");
                    return yearField;
                })
        )
        .withCloseListener(closeEvent -> {
            if (closeEvent.getCloseAction().equals(INPUT_DIALOG_OK_ACTION)) {
                Integer year = closeEvent.getValue("yearField");
            }
        })
        .show();
```

### Predefined Actions
`InputDialog` uses `DialogActions` enum. It contains following options:
* OK
* OK_CANCEL
* YES_NO
* YES_NO_CANCEL  

By default `InputDialog` uses 'OK_CANCEL' actions. Each dialog action close dialog with its own close action:
```
OK - INPUT_DIALOG_OK_ACTION
CANCEL - INPUT_DIALOG_CANCEL_ACTION
YES - INPUT_DIALOG_APPLY_ACTION
NO - INPUT_DIALOG_REJECT_ACTION
```
OK and YES actions perform validation before closing dialog. And if its failed dialog won't be closed.

`InputDialogBuilder` has two methods to define `DialogActions`:
```java
InputDialogBuilder withActions(DialogActions actions);
InputDialogBuilder withActions(DialogActions actions, Consumer<InputDialog.InputDialogResult> resultHandler);
```
Using second method we can handle buttons click. Handler is invoked after close event and can be used instead of close listener.

`InputDialogResult` contains information about:
- which button was clicked;
- values from fields;
- close action;

#### How to use predefined actions
Example with result handler:
```java
@Inject
private Dialogs dialogs;
...
dialogs.createInputDialog(this)
        .withParameters(
                stringParameter("nameField").withCaption("Name"),
                intParameter("countField").withCaption("Count")
        )
        .withActions(DialogActions.OK_CANCEL, result -> {
            switch (result.getCloseActionType()) {
                case OK:
                    String name = result.getValue("nameField");
                    Integer count = result.getValue("countField");
                    break;
                case CANCEL:
                    // do something
                    break;
            }
        })
        .show();
```

### Custom input dialog actions
`InputDialogAction` special action that can be used in `InputDialog`. `InputDialogAction` will be used instead of predefined `DialogActions` and has following parameters:
- id
- caption
- description
- icon
- shortcut combination
- primary
- validation required - if true handler will be invoked only after succesful validation (true by default)
- Consumer<InputDialogActionPerformed> handler
`InputDialogAction` has fluent API and predefined static method to simplify creating action:
```java
static InputDialogAction action(String id)
```

`InputDialogActionPerformed` is an event class which contains opened `InputDialog`. It means that it is possible to implement custom close logic and custom field validation.

`Dialogs` has following method to set `InputDialogAction`:
```java
InputDialogBuilder withActions(InputDialogAction... actions);
```
#### How to use InputDialogAction actions
Example:
```java
@Inject
private Dialogs dialogs;
...
dialogs.createInputDialog(this)
        .withParameters(
                stringParameter("phoneField").withCaption("Phone"),
                stringParameter("addressField").withCaption("Address"),
                timeParameter("timeField").withCaption("Time"))
        .withActions(
                action("okAction")
                        .withCaption("Ok")
                        .withIcon(CubaIcon.DIALOG_OK)
                        .withHandler(okActionEvent -> {
                            InputDialog dialog = okActionEvent.getInputDialog();
                            String phone = dialog.getValue("addressField");
                            // do something
                            // and close
                            dialog.close(WINDOW_CLOSE_ACTION);
                        }),
                action("cancelAction")
                        .withCaption("Cancel")
                        .withIcon(CubaIcon.DIALOG_CANCEL)
                        .withValidationRequired(false)
                        .withHandler(cancelAction ->
                                cancelAction.getInputDialog().close(WINDOW_CLOSE_ACTION))
        )
        .show();
```
Note, if action handler should be invoked independently from field validation, set `withValidationRequired(false)`.

### Validation
Besides base field validation it is possible to use additional validator:
```java
InputDialogBuilder withValidator(Function<InputDialog.ValidationContext, ValidationErrors> validator);
```
Given validator receives specific context (`InputDialog.ValidationContext`) which contains values and input dialog. This Function must return `ValidationErrors` instance which contains descriptions for errors. These errors will be shown in a notification with other validation exceptions.

#### Example
```java
@Inject
private Dialogs dialogs;
...
dialogs.createInputDialog(this)
        .withParameters(
                stringParameter("phoneField").withCaption("Phone"),
                stringParameter("addressField").withCaption("Address"),
                timeParameter("timeField").withCaption("Time"))
        .withValidator(context -> {
            String phone = context.getValue("phoneField");
            String address = context.getValue("addressField");
            if (Strings.isNullOrEmpty(phone) && Strings.isNullOrEmpty(address)) {
                return ValidationErrors.of("Phone or Address must be filled");
            }
            return ValidationErrors.none();
        })
        .show();
```
#### How to test
Try to create input dialog with different configurations and check how it works:
1. Use all predefined parameters like: `stringParameter()` and so on. Try to use all options from `InputParameter`.
1.1 Special case. When we use `entityParameter()` by default InputDialog can generate `PickerField` and `LookupPickerField`. It depends from `lookupScreenThreshold`
1.2 Create e.g. 3 instances of some Entity.
1.3 Open `JMX console`, find `PersistenceManager` and invoke `refreshStatistics()` with `all` value
1.4 Open `Entity Inspector` find your entity, edit it and set `Lookup screen threshold`  4
1.5 Open again `JMX console` find `app.cuba:type=CachingFacade` invoke `clearPersistenceManagerClientCache()`
1.6 Open dialog with `entityParameter` -> we should see `LookupPickerField`
2. Use all methods `withAction()`
2.1. Use `InputDialogAction` with all available configuration (icon, caption, etc)
3. Use closeListener
4. Use `withValidator`
5. Try to use custom datatype with `InputParameter` it should invoke an exception.
5. Use other cases.

**Comment by Flaurite** [comment]
Relates to #1833

**Comment by knstvk** [comment]
Plz rename INPUT_DIALOG_APPLY_ACTION and INPUT_DIALOG_REJECT_ACTION to `INPUT_DIALOG_YES_ACTION` and `INPUT_DIALOG_NO_ACTION` respectively.
