### ISSUE TITLE
Provide datatype property for DateField / DatePicker / TimeField components

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1844]
### Environment

- Platform version: 7.0
- Client type: Web

### Description of the bug or enhancement

There is no way to specify datatype of DateField, TimeField and DatePicker declaratively.

We should be able to set LocalDateTime / LocalDate types using XML declaration.

Also, add LocalTime / LocalDate / LocalDateTime to datatypeEnum in layout.xsd.

See also https://www.cuba-platform.com/discuss/t/datefield-localdatetime-not-working-in-p7/8015

**Comment by glebfox** [comment]
`DateField`, `DatePicker` and `TimeField` now have the `datatype` attribute.

`DateField` and `DatePicker` support the following datatypes:
* date
* dateTime
* localDate
* localDateTime
* offsetDateTime

`TimeField` supports the following datatypes:
* localTime
* offsetTime
* time

The following datatypes was added to the common `datatype` attribute:
* localDate
* localDateTime
* localTime
* offsetDateTime
* offsetTime
