### ISSUE TITLE
Double-click property in Filter editor is not working

### ISSUE THREAD

**Issue by sergeev-ms** [cuba-platform/cuba#1851]
### Environment

- Platform version: 7.0.0
- Client type: Web
- Browser: Chrome, etc. 

### Description of the bug or enhancement

Click _Add search condition_, then double-click some property
Expected behavior: property will be added to the filter frame (6.10 is OK).
Actual behavior: Double-click will select the property. You have to click select button to add it to the filter frame.

**Comment by glebfox** [comment]
Duplicates #1531.
