### ISSUE TITLE
DataGrid editor doesn't take into account an entity attribute LookupType

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1854]
### Description of the bug or enhancement

- Minimal reproducible example

1. Create an entity with **m-t-o** association to an another entity
2. Define the following for the association attribute
```
@Lookup(type = LookupType.DROPDOWN)
``` 
3. Create a browser screen with `DataGrid`
4. Make `DataGrid` editable
5. Run the app, open the screen and open the `DataGrid` editor

- Expected behavior

`LookupField` is created for the association attribute

- Actual behavior

`PickerField` is created for the association attribute

**Comment by kgeis** [comment]
I'm seeing the same on Table.

**Comment by knstvk** [comment]
> I'm seeing the same on Table.

In what framework version?

**Comment by kgeis** [comment]
7.1. Sorry, I noticed after commenting that this is closed, and I should start a new issue.

**Comment by kgeis** [comment]
I found the relevant issue #490 related to Table.
