### ISSUE TITLE
Mark string query methods parameters with @Language("JPAQL") from JetBrains Java Annotations

### ISSUE THREAD

**Issue by alexander-shustanov** [cuba-platform/cuba#1863]
Example

```java
class LoadContext {
    public static LoadContext.Query createQuery(@Language("JPAQL") String queryString) {
...
    }
}
```

This automatically enables jpaql language injection at caller site

**Comment by jreznot** [comment]
Also, check if it can be done with only commend without annotations.

**Comment by jreznot** [comment]
We cannot do this until IDEA bug if fixed: https://youtrack.jetbrains.com/issue/IDEA-163803

**Comment by knstvk** [comment]
@alexbudarov Check if it makes sense.

**Comment by jreznot** [comment]
Also, it can be implemented in Studio as injection config with PSI patterns:

`plugin.xml`:
```xml
<extensions defaultExtensionNs="org.intellij.intelliLang">
    <injectionConfig config="javaInjections.xml"/>
```

`javaInjections.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="LanguageInjectionConfiguration">

  <injection language="JPAQL" injector-id="java">
    <display-name>JpaOperations (org.springframework.orm.jpa)</display-name>
    <place><![CDATA[psiParameter().ofMethod(0, psiMethod().withName("find").definedInClass("org.springframework.orm.jpa.JpaOperations"))]]></place>
    <place><![CDATA[psiParameter().ofMethod(0, psiMethod().withName("someMethodName").definedInClass("YourJpaApiClassName"))]]></place>
  </injection>
```

In this case there is no need to add annotations to the framework.

**Comment by alexbudarov** [comment]
Not necessary.
a) It is already implemented in Studio
b) Studio support can be applied to all projects regardless of CUBA version.
c) We plan to implement another JPQL language in the future

**Comment by alexbudarov** [comment]
Such annotations can be used in a project that has its own classes / methods accepting JPQL strings as parameters.
