### ISSUE TITLE
DsContext does not de-register child dsContext instances

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1865]
Initial issue: #1537

### Environment

- Platform version: 5.6.23, 6.8
- Client type: Web, Desktop

### Description of the bug or enhancement

1. Apply patch to RefApp 5.6
[tabsheet-remove-tab.patch](https://app.zenhub.com/files/54624511/5b5e3c96-d902-4e79-9c77-c38f231e092a/download)
2. Open RefApp.
3. Application -> Drivers -> Create.
4. Keep clicking "Add/Remove Tab"

Every time a new tab is added and then removed. You can watch in JVisualVM how used heap memory grows.

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/9588883d-57d5-4d30-9417-a0bde073701e)

If `addTab` / `removeTab` argument is a frame - window-level `DsContext` does not de-register child `dsContext` instances:

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/7a69a16b-2050-4ac2-8b5e-6bdd317a3344)

Changing code from application side and manually removing child dsContext solves dsContext's part of problem:

```Java
getDsContext().getChildren().remove(tab.getDsContext());
```

**Comment by knstvk** [comment]
I can only imagine a solution with explicit disposing a frame, like this:
```
mainTabsheet.removeTab("tab" + counter);
tab3.dispose();
tab3 = null;
```
@alexbudarov What do you think?

**Comment by alexbudarov** [comment]
@knstvk good solution
