### ISSUE TITLE
Provide simple way to set custom conversion error message for UI fields

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1873]
### Environment

- Platform version: 7.0
- Client type: Web

### Description of the bug or enhancement

If we input incorrect data type into TextField, it shows default `Input error` message. We need simple way to set customized error message and default messages for standard datatypes if custom error message is not set.

See topic: https://www.cuba-platform.com/discuss/t/how-to-override-alert-message-in-integer-only-textfield-textfield-addvaluechangelistener-does-not-work/8099

### Changes

Affected components:
- TextField
- TextArea
- CurrencyField

#### Default messages
Default conversion error messages are added and used when a datatype is set for a field.

Localization keys have the following template `databinding.conversion.error.<type>`, e.g.
`databinding.conversion.error.int = Must be Integer`

**Example:**
```XML
<textField datatype="int"/>
```

Result:
![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/ef820e4f-86d0-472d-b0fc-18483d36f4fa)

#### Custom conversion error message

Two methods are added for affected components:
- `void setConversionErrorMessage(String conversionErrorMessage)`
- `String getConversionErrorMessage()`

**Example:**
```Java
textField.setConversionErrorMessage("This field can work only with Integers");
```

And the corresponding XML attribute is added.

**Example:**
```XML
<textField conversionErrorMessage="This field can work only with Integers"/>
```

Result:
![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/10a35ebe-b507-4757-af1b-8693a413be89)

### QA

Checklist:

- [x] Check default message case ("Incorrect value type") - no datatype, no custom message
- [x] Check default datatype message case - datatype is set for field
- [x] Check declarative and programmatic ways to set custom conversion error message

**Comment by dtsaryov** [comment]
6.10 support is moved to #1878
