### ISSUE TITLE
Introduce different conversion error messages depending on type of field

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1878]
### Environment

- Platform version: 6.10
- Client type: Web

### Description of the bug or enhancement

Add default messages for standard data types that will be used in notification:

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/14b42db6-7952-4da8-a6e5-12862ee56639)

### Updates

Default messages for default data types are added. Their localization keys have the following template - `validationFail.<data_type>`

where <data_type> is data type id (int, string, etc), for example: `validationFail.uuid`

Full list of supported data types:
- boolean
- int
- long
- double
- decimal
- string
- uuid
- dateTime
- date
- time

As a result if a field has some datatype and entered value cannot be converted to it, notification will be shown with a message that corresponds to the datatype:

Integer data type example:
![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/bf00af92-0f1f-4104-b212-16edc906699f)

If datatype is not registered (via `metadata.xml` or via `DatatypeRegistry`) the default message will be used ("Input error").

### QA

Check available registered datatypes and try to set some custom datatype to a field, like this:
```Java
textField.setDatatype(new Datatype() {
    @Override
    public String format(@Nullable Object value) {
        return null;
    }

    @Override
    public String format(@Nullable Object value, Locale locale) {
        return null;
    }

    @Nullable
    @Override
    public Object parse(@Nullable String value) throws ParseException {
        if (StringUtils.isNotEmpty(value)) {
            throw new ParseException("", 0);
        }
        return null;
    }

    @Nullable
    @Override
    public Object parse(@Nullable String value, Locale locale) throws ParseException {
        if (StringUtils.isNotEmpty(value)) {
            throw new ParseException("", 0);
        }
        return null;
    }
});
```

**Comment by natfirst** [comment]
Boolean datatype considers true/false strings not as boolean values
