### ISSUE TITLE
CollectionChangeListener is invoked twice if table sorting is saved in settings

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1885]
### Environment
- Platform version: 7.0.1

### Description of the bug or enhancement
Probably, it applies also to DataGrid and Table inheritors.
Attached project: [demo.zip](https://github.com/cuba-platform/cuba/files/2875978/demo.zip)

- Minimal reproducible example
In the attached project:
1. Create some customers;
2. In the CustomerBrowse screen set sorting to some column; close screen;
3. Open CustomerBrowse screen again.
- Expected behavior
Only one notification with "CollectionChange" should be shown.
- Actual behavior
Two notifications are shown.

**Comment by knstvk** [comment]
In order to have only one CollectionChangeEvent when screen is opened with saved sorting, you should remove the `LoadDataBeforeShow` annotation and load data in `AfterShowEvent` listener:

```
@UiController("demo_Customer.browse")
@UiDescriptor("customer-browse.xml")
@LookupComponent("customersTable")
//@LoadDataBeforeShow
public class CustomerBrowse extends StandardLookup<Customer> {

    @Subscribe
    private void onAfterShow(AfterShowEvent event) {
        getScreenData().loadAll();
    }

```
