### ISSUE TITLE
FluentValueLoader changed methods 

### ISSUE THREAD

**Issue by pctF** [cuba-platform/cuba#1893]
Just finished migration from 6.10.* -> 7.* . Seems like fluent loader changed api 
6.10: ```public FluentValueLoader<T> softDeletion(boolean softDeletion)```
7.0:  ```public FluentValueLoader softDeletion(boolean softDeletion)``` 
etc

Is it intentional or we can expect changes in future versions? 

- Platform version: 7.0.1

expected behavior (old one):
```
Long salary = dataManager.loadValue("select u.salary  from ...", Long.class)
    .parameter("id", id)
    .one();
```
actual:
```
Long salary = (Long) dataManager.loadValue("select u.salary  from ...", Long.class)
    .parameter("id", id)
    .one();
```

**Comment by knstvk** [comment]
Thank you for reporting.
It was a bug due to improper merging of an old fix.
