### ISSUE TITLE
Incorrect behavior while fetching @Basiс property

### ISSUE THREAD

**Issue by leonnash23** [cuba-platform/cuba#1894]
### Environment

- Platform version: 6.8.14
- Database: PostgreSQL

### Description of the bug or enhancement

- Minimal reproducible example:
There is an Entity with two properties: one is an entity(first), the other(second) is noted by @Basic annotation with fetch type "LAZY". When you load Entity by com.haulmont.cuba.core.TypedQuery#getResultList, you going deeper into  com.haulmont.cuba.core.sys.QueryImpl#getResultFromCache and everything going well(entity-property are loaded) until calling fetcher.accept(result). This call leads you to com.haulmont.cuba.core.sys.EntityFetcher#fetch and in "for" statement while calling getter for the second(see the beginning of my explanation) property, the new database request is generated and after this, you will get null instead entity-property.
Notice that if fetch type is "EAGER" — everything will be ok.
- Entity property is loaded
- Entity property is null

**Comment by andreysubbotin** [comment]
EclipseLink doesn't work with views and basic lazy fields as expected. We don't recommend to use `@Basic(LAZY)` fields. Use views instead of `@Basic(LAZY)`.
