### ISSUE TITLE
Support tooltips for items of for RadioButtonGroup and CheckBoxGroup

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#190]
Implement `itemDescriptionGenerator` property for `RadioButtonGroup` and `CheckBoxGroup` UI components.

It should be `Function<? super I, String>` that can be set using declarative `@Install` method

### Updates
The `RadioButtonGroup` and `CheckBoxGroup` have new methods to support tooltips for items:
* `Function<? super I, String> getOptionDescriptionProvider()` - returns option description provider:
* `void setOptionDescriptionProvider(Function<? super I, String> optionDescriptionProvider)` - sets the option description provider.

### QA
Check that the user can define different descriptions for component values using optionDescriptionProvider

**Comment by natfirst** [comment]
Check list:

- [ ] Set using Install Delegate
- [ ] Set by the method
- [ ] Get descriptions
- [ ] Check that Studio works correctly with both methods
