### ISSUE TITLE
URL generator for screen links based on URL routing

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1903]
### Environment

- Platform version: 7.1
- Client type: Web

### Description of the bug or enhancement

Provide API for URL links generation:

- Link to editor of entity instance
- Link to screen by screen id or screen class
- Link to screen with provided parameters

Generate proper URL that can be send via email or shown to user.

## Updates

The `UrlRouting` component has the new method:
- `RouteGenerator getRouteGenerator()` - it provides API to generate routes for screens with optional URL parameters.

### New `RouteGenerator` API:

- `String getRoute(String screenId)` - returns a route for screen with given `screenId`, example:
```Java
// route == "http://host:port/context/#main/users"
String route = urlRouting.getRouteGenerator().getRoute("sec$User.browse");
```

- `String getRoute(Class<? extends Screen> screenClass)` - returns a route for screen with given `screenClass`, example:
```Java
// route == "http://host:port/context/#main/users"
String route = urlRouting.getRouteGenerator().getRoute(UserBrowser.class);
```

- `String getEditorRoute(Entity entity)` - returns a route for editor with given `entity`, example:
```Java
// default "admin" user
User admin = ...;

// route == "http://host:port/context/#main/users/edit?id=30h1cre6v1893s9hyzyd438zwk"
String route = urlRouting.getRouteGenerator().getEditorRoute(admin);
```

- `String getEditorRoute(Entity entity, String screenId)` - returns a route for editor with given `screenId` and `entity` (enables to specify custom editor screen)

- `String getEditorRoute(Entity entity, Class<? extends Screen> screenClass)` - returns a route for editor with given `screenClass` and `entity` (enables to specify custom editor screen)

- `String getRoute(String screenId, Map<String, String> urlParams)` - returns a route for screen with given `screenId` and `urlParams` (second variant of the first method)

- `etc`

### Usage example

(Extended Role Browser is used here)

1. Let's add a button into table panel:
```XML
<!-- Table buttons panel -->
<buttonsPanel>
    ...
    <button caption="Get a link" invoke="generateRoute"/>
    ...
</buttonsPanel>
```

2. Let's implement `generateRoute` method:

```Java
@Inject
private UrlRouting urlRouting;

public void generateRoute() {
    Role selectedRole = rolesTable.getSingleSelected();
    if (selectedRole != null) {
        String routeToSelectedRole = urlRouting.getRouteGenerator()
                .getEditorRoute(selectedRole, ImmutableMap.of("someParam", "someValue"));

        UiControllerUtils.getScreenContext(this)
                .getDialogs()
                .createMessageDialog(Dialogs.MessageType.CONFIRMATION)
                .withCaption("Generated route")
                .withMessage(routeToSelectedRole)
                .withWidth("710")
                .show();
    }
}
```

3. Click the new button - a dialog with generated route will be shown

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/a65bd681-db9e-4b97-b246-a46fe2eca68a)

4. Copy the route and paste it into browser address bar - selected role will be opened in editor in the same tab

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/417e89ac-e164-427c-a242-3fc3bc22226c)

**Comment by sukhova** [comment]
Please, remove the word "class" from this notification:
![47](https://user-images.githubusercontent.com/40686909/58473593-07d5c280-815a-11e9-94e4-e00dca6bf68f.PNG)
