### ISSUE TITLE
`Remember me` checkbox  is unreachable by Tab in Safari

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#1910]
#### Environment

- Platform version: 6.10
- Browser: Safari
- Operating system: macOS

#### Description of the bug or enhancement

Initially reproduced on 6.5.7. It's also reproduced on 6.8 and 6.10

1. Open login screen in Safari
2. Try to reach the `Remember me` checkbox using `Tab` key

*A.R.* Component is unreachable

**Comment by Flaurite** [comment]
Enable the following setting in order to move focus using tab:
_Safari -> Prefernces -> Adnvanced_
See **Accesibility**: press check box with **"Press Tab to highlight each item on a webpage"**
