### ISSUE TITLE
Dynamic field in Form

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1911]
### Environment

- Platform version: 7.1

### Description of the bug or enhancement

Implement untyped `<field>` tag for Form that will be translated into a correct type at runtime. Studio should not try to infer its type and should inject it as `Field` instance. 

It should have only standard XML attributes: caption / width / height / icon / visible / enable. No custom XML attributes.

Example:
```xml
<form>
  <lookupField property="myLookupFieldProperty1" />
  <dateField property="myDateProperty1" />
  <field property="myProp1" />
  <field property="myProp2" /> 
  <field property="myProp3" />
  <field property="myProp4" />
</form>
```

**Comment by glebfox** [comment]
The `<field>` element has the following attributes:
* id
* property - **required**
* dataContainer
* optionsContainer
* editable
* enable
* visibile
* caption
* captionAsHtml
* description
* descriptionAsHtml
* icon
* contextHelpText
* contextHelpTextHtmlEnabled
* width
* height
* responsive
* stylename
* css

**Example**

Xml
```
<form dataContainer="usersDc">
	<field property="login"/>
	<field property="group" optionsContainer="groupsDc"/>
</form>
```

Result
![image](https://user-images.githubusercontent.com/6077149/57851110-d02d5900-77f0-11e9-923b-e79d521ee962.png)
