### ISSUE TITLE
Cannot shift ButtonsPanel content to the right side

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#192]
This code doen't work:
```
<buttonsPanel width="100%" expand="spacer">
    <label value="msg://searchByName" align="MIDDLE_LEFT"/>
    <textField id="searchField" />

    <label id="spacer"/>

    <button action="paramsTable.refresh" icon="icons/refresh.png"/>
    <button action="paramsTable.editValue" icon="icons/edit.png"/>
    <button id="exportBtn" invoke="exportAsSql" caption="msg://export"/>
</buttonsPanel>
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-6846

**Comment by dtsaryov** [comment]
Since `expand` feature does not work like this we should provide custom solution.

@GlebDurygin please check if we can implement this behavior via css flex features

**Comment by dtsaryov** [comment]
Unable to implement this feature, because component expanding works only for layouts with specified width. Buttons panel gets wider due to its inner components.

**Comment by knstvk** [comment]
> Buttons panel gets wider due to its inner components.

What if i set `<buttonsPanel width="100%"` as in the issue description?
