### ISSUE TITLE
Add an ability to manage TwinColumn items reordering

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1921]
A topic on support forum: [link](https://www.cuba-platform.com/discuss/t/twincolumn-and-results-ordered/8310)

### Environment

- Client type: Web

### Description of the bug or enhancement

`TwinColumn` component always reorders its items, and there is no way to disable this behavior now. 

## Updates
The component `TwinColumn` has a new attribute `reorderable`. The attribute `reorderable` allows you to configure whether items should be reordered after selection. Reordering is enabled by default. The order of the elements will be the same as that of the data container.

* You can set the attribute value either in XML descriptor or using the method:
`setReorderable(boolean reorderable)`

* You can get the attribute value using:
`boolean isReorderable();`

#### Reorderable
If the attribute value is true, then the items should be reordered after selection. 
#### Not reorderable
If the attribute value is false, the elements will be added in the order in which they are selected.

### Test project
[twin-column-reodered.zip](https://github.com/cuba-platform/cuba/files/3313609/twin-column-reodered.zip)

## QA
* Check for different values of the attribute `reorderable`
* Check for different data sources (dataContainer, Map, List)

**Comment by barser** [comment]
Please consider adding attribute for showing additional "UP"/"DOWN" buttons - to move items up and down (as it done in some similar visual toolkits i.e. ExtJs)

**Comment by dtsaryov** [comment]
> Please consider adding attribute for showing additional "UP"/"DOWN" buttons - to move items up and down (as it done in some similar visual toolkits i.e. ExtJs)

Hello @barser 

Please create a new issue to request this feature. This behavior will not be implemented here.
