### ISSUE TITLE
Non-visual components in screen XML

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1925]
### Environment

- Platform version: 7+
- Client type: Web

### Description of the bug or enhancement

Provide new XML element - `<facets>` that can be used to define non-visual objects in a screen in a generic way. For instance, timers, UI component extensions, additional declarative objects, etc.

Introduced 2 new facets:

- timer
- clipboardTrigger

Facets are available in XSD only for new screens and fragments.

#### Examples

Timer:
```xml
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd">
    <facets>
        <timer id="testTimer" delay="2000" autostart="true" repeating="true"/>
    </facets>

    <layout>
    </layout>
</window>
```

ClipboardTrigger - Client-side component that connects a Button and TextField / TextArea input. Copies the text content to the clipboard on button click.
```xml
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd">
    <facets>
        <clipboardTrigger id="copyTrigger"
                          input="textField"
                          button="copyButton"/>
    </facets>

    <layout>
        <textField id="textField"/>
        <button id="copyButton"/>
    </layout>
</window>
```

We assume that facets should be used as declarative way to provide some features. 

Facets support dependency injection to screens (using `@Inject`) and event handling (using `@Subscribe`). `@Install` also supported, but current facets do not have such properties.

Example:
```java
@UiController
@UiDescriptor("screen-with-timer.xml")
public class ScreenWithTimer extends Screen {
    @Inject
    private Timer testTimer;

    @Subscribe("testTimer")
    private void onTimerTick(Timer.TimerActionEvent event) {
    }

    @Subscribe("testTimer")
    private void onTimerStop(Timer.TimerStopEvent event) {
    }
```

Application components may provide additional facets. They should implement `FacetProvider` interface in a Spring Bean and provide the corresponding XSD for screens.

Minimal example:
```java
@Component("cuba_ClipboardTriggerFacetProvider")
public class ClipboardTriggerFacetProvider implements FacetProvider<ClipboardTrigger> {
    @Override
    public Class<ClipboardTrigger> getFacetClass() {
        return ClipboardTrigger.class;
    }

    @Override
    public ClipboardTrigger create() {
        return new WebClipboardTrigger();
    }

    @Override
    public String getFacetTag() {
        return "clipboardTrigger";
    }

    @Override
    public void loadFromXml(ClipboardTrigger facet, Element element, ComponentContext context) {
        String id = element.attributeValue("id");
        if (isNotEmpty(id)) {
            facet.setId(id);
        }
    }
}
```

**Comment by jreznot** [comment]
Relates to #2046

**Comment by jreznot** [comment]
For instance, BulkEditor can be a non-visual component

**Comment by knstvk** [comment]
Timer defined in facets does not stop when the screen is closed:

    <facets>
        <timer id="myTimer" delay="3000" autostart="true" repeating="true"/>
    </facets>

    @Inject
    private Notifications notifications;

    @Subscribe("myTimer")
    private void onTimer(Timer.TimerActionEvent event) {
        notifications.create(Notifications.NotificationType.TRAY).withCaption("on timer").show();
    }

**Comment by knstvk** [comment]
Rename `@Nullable Facet getFacet()` to `@Nullable getFacetOrNull()`, `getFacetNN()` to `getFacet()`. Add Javadocs.

**Comment by jreznot** [comment]
> Rename `@Nullable Facet getFacet()` to `@Nullable getFacetOrNull()`, `getFacetNN()` to `getFacet()`. Add Javadocs.

I'd better not do this because we already have `getComponent` and `getComponentNN` in Window. Why should we introduce one more API pattern in this place?

**Comment by knstvk** [comment]
> I'd better not do this because we already have getComponent and getComponentNN in Window.

OK.

**Comment by jreznot** [comment]
Studio ticket https://youtrack.cuba-platform.com/issue/STUDIO-6185
