### ISSUE TITLE
Execute deployment environment sanity checks on server start

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1927]
### Goal
To help developer and system administrators with deploying applications and discover environment misconfigurations.

Many environment problems don't disclose themselves right after server start, but lead to errors later. Some of misconfigurations are indicated with non-intuitive error messages from non-core application components.

Example: if database connection URL is wrong - first exception we get is from DbUpdaterEngine or even from BPM classes. Exception message depends on JDBC driver.

### Proposal
Run various environment checks on server start.
In case of problems - emit an understandable error message.
Abort server start if checks fail??

- JVM version is supported by CUBA. Translating infamous "unsupported major.minor version" would be insanely great (I personally has been asked about it a dozen times).
- Connecting to database succeeds
- Main database looks like CUBA DB
- Work dir and temp dir are write accessible.
- ...

**Comment by soraksh** [comment]
Added JVM version check on core, web and portal modules. Version should be 1.8 or higher.
Added check that work dir and temp dir are writable and readable.
Added data stores check (connection for main and additional stores, cuba-like check for main store if `cuba.automaticDatabaseUpdate` disabled).

**Comment by alexbudarov** [comment]
Related forum topic: https://www.cuba-platform.com/discuss/t/unable-to-start-uberjar-application/9460/3

UberJar + Java 12 = non-informative error messages on application start.

**Comment by myatlevEvg** [comment]
1) If datastore doesn't look like CUBA database show message with something like "datastore doesn't look like CUBA database" instead of "Some of environment sanity checks failed on core module: Main Data Store checked but SEC_USER table is not found"

2) Add sanity check for the case of using JAVA greater than v11.

**Comment by knstvk** [comment]
I would keep the more specific message about SEC_USER table. But I would remove the word "sanity".
