### ISSUE TITLE
Standard PickerField actions do not have tooltips

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1928]
### Environment

- Platform version: 7.1
- Client type: Web

### Description of the bug or enhancement

Provide tooltips for standard PickerField actions: Clear / Open / Lookup

PickerField should show descriptions as: `<description> (<shortcut if set>)`.

----
### Changes
Now default actions (Lookup, Open, Clear) for `PickerField` have default description. If there is no description is set to action it will use default description:
`description + (shortcut combination)`

### How to test
1. Check deafult description when nothing is set:
```
<pickerField id="pickerField">
    <actions>
        <action id="lookup" type="picker_lookup"/>
        <action id="open" type="picker_open" />
        <action id="clear" type="picker_clear"/>
    </actions>
</pickerField>
```
2. Try to define your own description. It should replace default description.
3. Check Russian locale also.

**Comment by natfirst** [comment]
Add space between <description> and (<shortcut if set>) in default descriptions

**Comment by jreznot** [comment]
Reopened. Do not introduce new `defaultDescription` property for actions. Just assign description right after creation
