### ISSUE TITLE
DataGrid header is misaligned

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1933]
### Environment

- Platform version: 7.0
- Client type: 
- Browser: Firefox
- Operating system: Windows (probably doesn't matter)

### Description of the bug or enhancement

- Minimal reproducible example

Screen layout:

```XML
<dataGrid dataContainer="names"
          height="300px" width="300px">
    <columns>
        <column property="name"/>
    </columns>
</dataGrid>
```

Result:

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/34de867a-7e81-47a4-a434-55597ff7bead)

**Comment by glebfox** [comment]
Checked:

Windows: **Chome 74.0.3729.131**, **FireFox 66.0.5, IE 11**
macOS X: **Safari 12.1**

**Comment by dtsaryov** [comment]
Please check on Windows with system zoom 125%
