### ISSUE TITLE
Ability to load entities by collection of ids in DataManager and TransactionDataManager

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1936]
### Description of the bug or enhancement

If we need to reload list of selected instances in Client (for instance, selected in Lookup window) we cannot do it using single transaction with DataManager. There is a workaround, we could use `load()` instead with `x.id IN (:ids)` query, but this way does not work in case of entities with composite IDS.

Let's add `DataManager.reload(Collection<Entity>, View)` and `TransactionDataManager.reload(Collection<Entity>, View)`.

Relates to #1875

**Comment by alexbudarov** [comment]
Things to consider:
- preserving order of entities after reload (useful when you do complex native sql with unions etc but finally want to get list of entities ordered the same way)
- what to do if one or more entities no longer exist

**Comment by knstvk** [comment]
> what to do if one or more entities no longer exist

I vote for throwing `com.haulmont.cuba.core.global.EntityAccessException`.

**Comment by knstvk** [comment]
Introduced `LoadContext.setIds()` method which accepts a collection of ids. It is used by `DataManager.loadList()` method in higher priority than passed query or single id.

Fluent usage:
```
dataManager.load(Customer.class).ids(customer1Id, customer2Id).list();

List<UUID> idList = Arrays.asList(customer1Id, customer2Id);
dataManager.load(Customer.class).ids(idList).list();
```
