### ISSUE TITLE
Duplicated javax.mail classes 

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#1938]
### Environment

- Platform version: 7.0.1

### Description of the bug or enhancement

In javax.mail-1.6.0.jar and javaee-api-8.0.jar of the deployed app.
See also https://www.cuba-platform.ru/discuss/t/javax-mail-versii-1-5-4-i-javaee-api-7-0-jar/2782

**Comment by andreysubbotin** [comment]
Try to remove javaee-api from compile dependencies: 
https://stackoverflow.com/questions/29896491/javaee-api-7-0-with-jsf-2-2-fajax-does-not-submit
https://stackoverflow.com/questions/23211625/cannot-include-javaee-api-7-0-jar-in-android-application
http://www.adam-bien.com/roller/abien/entry/the_only_one_dependency_you
https://stackoverflow.com/questions/28514804/web-inf-lib-javaee-web-api-7-0-jar-jar-not-loaded

**Comment by andreysubbotin** [comment]
7.0 uses correct class versions for javax.mail and  javaee-api. Try to remove javaee-api from 7.1 platform.

**Comment by andreysubbotin** [comment]
Please smoke test email sending
