### ISSUE TITLE
Two "show rows" input fields on Entity Log screen

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1954]
### Environment

- Platform version: 6.10

### Description of the bug or enhancement
Main Menu -> Administration -> Entity Log.
Why there are two "Show rows" fields on this browser?
What will happen if I select 5000 in upper lookup field but specify only 15 in text field below?

![image](https://user-images.githubusercontent.com/6158807/54354549-5d78f380-4670-11e9-8818-f01fefad3d00.png)

**Comment by pribavkindenis** [comment]
Redundant text field and companioning labels have been removed.
See `com.haulmont.cuba.gui.app.core.entitylog.AbstractWindow`.
