### ISSUE TITLE
Store modified instance's name in entity log

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1956]
### Description of the bug or enhancement
When entity is being modified - entity log contains only changed attribute values.
It may be not enough to recognize the entity, without searching browser by entity ID.
Example 1: https://github.com/cuba-platform/cuba/issues/456

Example 2 from RefApp:
![image](https://user-images.githubusercontent.com/6158807/54359316-d2055f80-467b-11e9-96f8-cd6a0a555c0a.png)
Which Car's currency was changed from euro to dollar? We do not know based on this screen.

Suggestion:
Record entity's instance name to EntityLogItem and show it in Entity Log screen.

Example how it looks like in Sherlock's implementation:
![image](https://user-images.githubusercontent.com/6158807/54359447-1e509f80-467c-11e9-9073-5288a300443d.png)
Here we immediately see that this is "OTP rank" whose status was changed to Active.

Complications:
- there are entities without instance name
- if instance name mentions related entities, obtaining instance name can fail with exception

**Comment by soraksh** [comment]
Column "Entity instance name" added to entity log screen.
