### ISSUE TITLE
Custom datatype sets model value instead of formatted to the field in the generated column

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#1957]
### Environment
- Platform version: 7.0

### Description of the bug or enhancement
Donwload attached project: [newProject.zip](https://github.com/cuba-platform/cuba/files/2970013/newProject.zip)

- Minimal reproducible example
1. Open: _Application -> Sales Orders_
2. Click on create button
3. Fill text field in the "Tax rate" column: e.g. 34, you will see 0.34 instead of 34%
4. Try to set this value again and you will see right value

**Comment by glebfox** [comment]
In the above example, `PercentageDatatype` is incorrect. Changing its implementation resolves the problem.
