### ISSUE TITLE
Application freezes if two js components are added to FieldGroup

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#1959]
### Environment

- Platform version: 6.10.8

### Description of the bug or enhancement

- Minimal reproducible example
[Demo project](https://www.cuba-platform.com/discuss/uploads/default/original/2X/6/679f81c01f2e96423a425b33a3f68e6db4ca81ae.zip)

- Expected behavior

Two js component are displayed on a screen

- Actual behavior

Application freezes

---

Related link: https://www.cuba-platform.com/discuss/t/application-hangs-in-browser-when-a-form-with-2-javascript-components-opens/8510

**Comment by glebfox** [comment]
It appears that the issue doesn't relate to FieldGroup. Placing js components within Grid have the same result.

**Comment by Flaurite** [comment]
It is reproduced only in 6.10  and lower versions. So fix will be only in 6.10.
