### ISSUE TITLE
Add annotated methods that should work as a listener

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#196]
e.g. onBeforeDarwCell, onAfterDrawCell for Table; onBeforeClick, onClick (invoke), onAfterClick for Button; onAfterValueChanged, onBeforeValueChanged for PickerField, LookupField; onVisibilityChanged for all and so on.

Example with Map:
```
    //instead of having 
    public init(Map<String, Object> params) {
        map.addMapClickListener(new MapClickListener() {
            @Override
            public void onClick(MapClickEvent event) {
                ....
            }
        });
    }

    //have separate method
    @Subscribe("map1")
    protected void onMapClick(MapClickListener.MapClickEvent event) {
        ...
    }

```

Add those actions to studio as the button invocation method on a separate tab (e.g. Events).

Relates to #327 and #575

Do not forget about:

- [x] Ordering
- [x] Native ordering between parent / child classes
- [x] Button click listener
- [x] Controller / Window events

**Comment by jreznot** [comment]
Relates to #1380
