### ISSUE TITLE
CUBA projects contain duplicated classes in JARs

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1963]
### Environment

- Platform version: 7.0.2

### Description of the bug or enhancement

- Minimal reproducible example

Open cuba-global JAR file using 7z or FileRoller (on Linux). You will see duplicated class files:

![classes](https://user-images.githubusercontent.com/1066152/54516135-80a8e900-4977-11e9-9579-d09ae98d5177.png)

**Comment by dtsaryov** [comment]
Caused by: [Compatibility with Intellij Gradle plugin](https://github.com/cuba-platform/cuba-gradle-plugin/issues/12)
