### ISSUE TITLE
Different value for rowsCount between new and old screens

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#1967]
### Environment

- Platform version: 7.0
- Client type: Web

### Description of the bug or enhancement
- Minimal reproducible example
  - RefApp project. Generate models (about 5), generate cars (more than 400). Use app-core.refapp:type=WorkLoadGenerator for data generation.
  - Clear user settings
  - Open old Car browser. Rows count equals: 200
  - Open new Car browser. Rows count equals: 5000

**Comment by glebfox** [comment]
**Steps to reproduce:**
1. Open the **Sample Sales** project - https://github.com/cuba-platform/sample-sales-cuba7
2. Create DB
3. Open any browser

**Comment by andreysubbotin** [comment]
For QA: create new screens for the same entity.
Fixed in #2283
