### ISSUE TITLE
Make ServiceInterceptor detect "open transaction left" in case of exception

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#1975]
### Description of the bug or enhancement
Currently ServiceInterceptor detects suspicious "Open transaction left" situtations and it's very useful.
But it only detects when service invocation was successful.
Can we detect not closed transactions even when service invocation failed?

**Comment by knstvk** [comment]
QA: create a service with a method which starts transaction and then throws an exception. Call this method from the client. Watch the log.
