### ISSUE TITLE
Required MaskedField doesn't consider empty value

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#1980]
Support forum: [link](https://www.cuba-platform.ru/discuss/t/problema-s-komponentom-maskedfield-pri-svojstve-required-required-true/2813)

### Environment

- Platform version: 6.10
- Client type: Web

### Description of the bug or enhancement

![required_masked_field.gif](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/85c277d0-355b-47ca-9fc7-026aeafeae94)

### Test project

[required_masked_field.zip](https://app.zenhub.com/files/54624511/7a440dc1-ff0a-4c3d-8340-0a9d6be430a8/download)

**Comment by Flaurite** [comment]
In 6.10 it can be managed by `maskedField.setSendNullRepresentation(false);`
in 7.0 MaskedField handle this case by default.
