### ISSUE TITLE
Simplify DataGrid cell renderer usage

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1983]
### Environment

- Platform version: 7.1
- Client type: Web

### Description of the bug or enhancement

At the moment in order to set up UI components generation in DataGrid we have to:

1. Subscribe on init method in UI controller
2. Add generated column programmatically
3. Set type of renderer programmatically

It looks like this:
```java
public class ClientList extends Screen {
    @Inject
    protected DataGrid<Client> clientsDataGrid;
    @Inject
    protected UiComponents uiComponents;

    @Subscribe
    protected void onInit(InitEvent event) {
        clientsDataGrid
                .addGeneratedColumn("generatedCell", new ColumnGenerator<Client, Component>() {
                    @Override
                    public Component getValue(DataGrid.ColumnGeneratorEvent<Client> event) {
                        return generateClientRow(event.getItem());
                    }

                    @Override
                    public Class<Component> getType() {
                        return Component.class;
                    }
                })
                .setRenderer(clientsDataGrid.createRenderer(ComponentRenderer.class));
    }
```

A lot of code! Let's simplify this:

1. Enable developers set up standard renderers in XML inside of `<column>` element.
2. Add `generatedType` attribute to `<column>` so we will not need to provide it with generator
3. Provide SAM interface of generator that can be assigned using install delegate:

Table example:
```java
@Install(to = "clientsTable.stars", subject = "columnGenerator")
protected Component clientsTableStarsColumnGenerator(Client client) {
    return null;
}
```

### Updates

1. `generatedType` is added for the `<column/>` element. It accepts FQN of type of DataGrid column, e.g. `com.haulmont.cuba.gui.components.Component`
2. `<renderer/>` sub-element is added for `<column/>`. The `type` attribute of the element accepts FQN types for DataGrid Renderers, e.g. `com.haulmont.cuba.gui.components.DataGrid$ComponentRenderer`
3. Declarative installing of column generator for DataGrid Column is supported. An example:

```Java
@Inject
private UiComponents uiComponents;

@Install(to = "dataGrid.fullName", subject = "columnGenerator")
protected Component fullNameColumnGenerator(DataGrid.ColumnGeneratorEvent<TestEntity> e) {
    Label<String> label = uiComponents.create(Label.TYPE_STRING);
    label.setValue(e.getItem().getFirstName() + " " + e.getItem().getLastName());
    return label;
}
```

### Studio support

[YouTrack issue](https://youtrack.cuba-platform.com/issue/STUDIO-6509)

### QA

- Check different combinations of generated types and renderers.
- Check usability

**Comment by jreznot** [comment]
Relates to #1972

**Comment by natfirst** [comment]
There are no suggestions for the generated type in xml
The following list of types should be shown:

- Boolean
- Integer
- Double
- String
- Date
- LocalDate
- LocalDateTime
- Icons.Icon

![image](https://user-images.githubusercontent.com/17950251/70516713-e619b700-1b50-11ea-9643-3a144b18d949.png)
