### ISSUE TITLE
Built-in mechanism for declarative linking of data components

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#1988]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

Now linking of data loaders with data containers and components requires too much boilerplate code.

**Comment by MuppetGate** [comment]
So, we’re at 7.0 now, and assuming it gets enough votes, it won’t show up until 7.2. 

I think the main problem I have is that this was existing functionality that was removed in the upgrade from 6.0.

**Comment by knstvk** [comment]
@MuppetGate  We'll think about back-porting it to 7.1 when it is implemented. The 7.2 target is "must have", others will get it if it is safe enough.

**Comment by knstvk** [comment]
For those who are interested, proposed implementation is here: https://github.com/cuba-labs/data-load-coordinator
Your feedback is welcome.

**Comment by MuppetGate** [comment]
Looks good. I was going to suggest not using the $ sign as separator because that'll cause problems with IntelliJ error checking, but it seems that seems to have changed already?
Will this work with fragments in the future?

**Comment by MuppetGate** [comment]
What's a facet? When did that appear?

**Comment by knstvk** [comment]
@MuppetGate Plz see the docs: https://doc.cuba-platform.com/manual-7.1/gui_DataLoadCoordinator.html

**Comment by MuppetGate** [comment]
Yup, looks good!  A little more verbose than the old system, but a little more flexible too. Can this be wired up from Cuba Studio, or will it have to be added manually by editing the raw XML?

**Comment by MuppetGate** [comment]
I take it 7.1 is on its way fairly soon?

**Comment by knstvk** [comment]
@MuppetGate Yes, Studio will have a palette section for facets.
7.1 Beta will be released in a few weeks.

**Comment by MuppetGate** [comment]
One other thing: the old system had built-in parameters for the current user id. Is there an equivalent here?

**Comment by knstvk** [comment]
> One other thing: the old system had built-in parameters for the current user id. Is there an equivalent here?

Not yet. We are thinking about some kind of parameter value providers, but we consider it as a separate issue.

**Comment by MuppetGate** [comment]
> Not yet. We are thinking about some kind of parameter value providers, but we consider it as a separate issue

I could be wrong, but I suspect a key use case for the old system was using the userId to restrict what appeared in a table. Without access to the system parameters then we’re still stuck with coding this stuff by hand.

**Comment by knstvk** [comment]
@MuppetGate 
I'm not saying it's not needed. Please create an issue for that.

**Comment by MuppetGate** [comment]
Will do.

**Comment by myatlevEvg** [comment]
@knstvk In the documentation semi-automatic mode described in a next way: "Semi-automatic configuration. When the auto attribute is set to true and there are some manually configured triggers, the facet will configure automatically all loaders that have no manual configuration."
But for now, if in the presented demo project data-load-coordinator in the ```open-browse``` screen configure dataLoadCoordinator the next way: 
```
        <dataLoadCoordinator auto="true">
            <refresh loader="ownersDl" onScreenEvent="Init"/>
            <refresh loader="ownersDl" param="category" onComponentValueChanged="categoryFilterField"/>
        </dataLoadCoordinator>
```
Pets not being loaded at all. Is that correct behavior?
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/a146e989-4cfb-4fda-9e16-d04c862107b4)

**Comment by knstvk** [comment]
@myatlevEvg Yes that's correct. On BeforeShow there is no value for the parameter used to load pets.
