### ISSUE TITLE
Permanent XSS attack through GroupBoxLayout caption

### ISSUE THREAD

**Issue by bernatgs** [cuba-platform/cuba#1993]
This vulnerability was discovered by @theyiyibest, please contact him for any question or comment.

### Environment

- Platform version: 6.10.7 

- Client type: Web
- Browser: tested in Firefox and Chrome

### Description of the bug or enhancement

- Login and navigate to any page that includes CUBA's filter pane, for example _LDAP Component > LDAP Log_ or _Reports > Reports_
- On the _Filter_ pane, click on the gear icon and _Save as_
![image](https://user-images.githubusercontent.com/5872879/54985905-fd5c4880-4fb1-11e9-8726-3d6fed3b9a0f.png)
- In the filter name field, type `<img src=x onerror="alert('persistent XSS attack');">`
- Click _OK_

- Expected behavior: nothing happens
- Actual behavior: javascript code is executed after saving and any time the page is loaded with the newly created filter selected

![image](https://user-images.githubusercontent.com/5872879/54986194-81aecb80-4fb2-11e9-89b4-cddfc8a9c547.png)

**Comment by jreznot** [comment]
Hi,

Thanks for reporting the problem.

It seems that you specified nonexistent version 6.9.10. What is the correct version used in the project?

**Comment by theyiyibest** [comment]
Hi,

We ve tested over 6.10.7 version.

Cheers.

**Comment by jreznot** [comment]
`GroupBoxLayout` now uses captionAsHtml = false by default. Can be enabled explicitly from XML or using Java API.
