### ISSUE TITLE
Frame must implement SupportsExpandRatio

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1995]
### Environment

- Platform version: 7.0.3
- Client type: Web

### Description of the bug or enhancement

Window and Fragment implement ExpandingLayout but does not provide `setExpandRatio` and `getExpandRatio` methods.

### Changes
`Frame` interface extends `SupportsExpandRatio` with following methods:
```
void setExpandRatio(Component component, float ratio);
float getExpandRatio(Component component);
```
So, `AbstractWindow`, `Fragment` and `Frame` can expand their components.

### How to test
Download attached project: [expanddemo.zip](https://github.com/cuba-platform/cuba/files/3038800/expanddemo.zip)

1. Open "Test Abstract Window" screen - button should be expanded.
2. In the given screen click on button and Dialog screen will be shown - button should be expanded.
3. Open "General shower" - two buttons should be expanded.

**Upd.**
Patch for loading from XML in refapp: [refapp_xmlratio_ptach.zip](https://github.com/cuba-platform/cuba/files/3112629/refapp_xmlratio_ptach.zip)

**Comment by Flaurite** [comment]
Can't set expand ratio from XML descriptor
