### ISSUE TITLE
Provide standard iframe options for BrowserFrame

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#1999]
### Environment

- Platform version: 7.1
- Client type: Web

### Description of the bug or enhancement

Support the standard iframe element options for BrowserFrame UI component:

- sandbox (allow-forms / allow-pointer-lock / allow-popups / allow-same-origin / allow-scripts / allow-top-navigation): https://www.w3schools.com/tags/att_iframe_sandbox.asp
- srcdoc - HTML content that can be set as String: https://www.w3schools.com/jsref/prop_frame_srcdoc.asp
- allow (fullscreen / payment / etc)
- referrerpolicy

## Updates
The component `BrowserFrame` has new attributes:
* allow
* sandbox
* srcdoc
* srcdocFile
* referrerpolicy

The attribute `allow` specifies a feature policy for the component. The value of the attribute can be a space-separated list of allowing features.
You can set the attribute value ether in xml descriptor or using the methods:
* `void setAllow(String value);`
* `void setAllow(Allow allow);` `Allow` - enum of standard values of the attribute.
* `void setAllow(EnumSet<Allow> allowSet);`
You can get this attribute using: `String getAllow();`

The attribute `sandbox` applies extra restrictions to the content in the frame. The value of the attribute can either be empty to apply all restrictions or space-separated tokens to lift particular restrictions
You can set the attribute value ether in XML descriptor or using the methods:
* `void setSandbox(String value);`
* `void setSandbox(Sandbox sandbox);` `Sandbox` - enum of standard values of the attribute.
* `void setSandbox(EnumSet<Sandbox> sandboxSet);`
You can get this attribute using: `String getSandbox();`

The attribute `srcdoc` - inline HTML to embed, overriding the src attribute. The IE and Edge browsers don't support this attribute. 
You can set the attribute value ether in XML descriptor or using the method: `void setSrcdoc(String value);`
And you can get this attribute using: `String getSrcdoc();`

The attribute `srcdocFile` - the path to the file whose contents will be set to the 'srcdoc' attribute. File content is obtained by using the classPath resource.
You can set the attribute value only in XML descriptor.

The attribute `referrerpolicy` indicates which referrer to send when fetching the frame's resource.
You can set the attribute value ether in XML descriptor or using the methods:
* `void setReferrerPolicy(String value);`
* `void setReferrerPolicy(ReferrerPolicy referrerPolicy);` `ReferrerPolicy` - enum of standard values of the attribute.
You can get this attribute using: `String getReferrerPolicy();`

## QA

To check `BrowserFrame`: 
* Try to set different values for above attributes using XML descriptor and new API.
* Try to set custom values for above attributes.
* Try to set multiple values for one attribute
* Set to attribute 'srcdoc' value "&lt;h1&gt; Test&lt;/h1&gt;" and this text should display on the screen.
* Check the consistency of the displayed data -  Set to attribute 'srcdoc' value "&lt;h1&gt; Test&lt;/h1&gt;" and set to source any url resource. Firefox should display content from `srcdoc` . IE and Edge should display content from `src`.
* Try do these actions in different browsers: IE11, Firefox, Chrome

**Comment by GlebDurygin** [comment]
Reopen.
The attribute srcdoc value is set. When you initially load a page in Chrome, the data isn't loaded correctly.
* Expected behavior
Data is loaded using srsdoс
* Actual behavior
Data is loaded using srpsdoс, and then data from the component resource is loaded too.

**Comment by GlebDurygin** [comment]
Reopen:

Fix JavaDocs for `BrowserFrame`.
