### ISSUE TITLE
Exception when setting up Entity Log

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#2023]
### Environment

- Platform version: 7.1-SNAPSHOT

### Description of the bug or enhancement

1) Create a project on the 7.1-SNAPSHOT
2) Set up the entity log using the Administration > Entity Log > Setup for the **User** entity
3) Try to set up the entity log for the User entity again

**AR**:
![Screenshot_2019-04-04 CUBA Application.png](https://images.zenhubusercontent.com/5b360034b46294032187ed9d/e16e99b0-172d-4569-bdef-0a59e633b1df)

**Comment by soraksh** [comment]
There should be an exception, but it should be handled and look like: ![1](https://user-images.githubusercontent.com/23614267/55551480-f63ce500-56eb-11e9-9fd4-18ee0bfa49ce.PNG)
Problems with handling appears only on hsqldb.
