### ISSUE TITLE
Wrong value can be passed to PickerField.setValue()

### ISSUE THREAD

**Issue by GlebDurygin** [cuba-platform/cuba#2025]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

- Minimal reproducible example

```java

try {
    pickerField.setValue("One");
} catch (ClassCastException ignored) {
}

boolean isEmpty = pickerField.unwrap(CubaPickerField.class).getValue() == null; // false
```

- Expected behavior

`isEmpty == true`

- Actual behavior

`isEmpty == false`

![set-value-pickerfield](https://user-images.githubusercontent.com/35256248/55545024-68f29400-56dd-11e9-9e23-3afcf2672a23.gif)

If you invoke setValue second time, then value will be set into PickerField

**Comment by Mihail063** [comment]
When the setValue is called a second time, the value will be set to PickerField
