### ISSUE TITLE
Button associated with the com.haulmont.cuba.gui.actions.list.CreateAction doesn't have the primary style

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2038]
### Environment

- Platform version: 7.0.0
- Theme: **Hover**

### Description of the bug or enhancement

- Minimal reproducible example

In **Refapp** open: _Application_ > _Screens v7_ > _Colours v7_

- Expected behavior

![image](https://user-images.githubusercontent.com/6077149/55730717-e4c84580-5a29-11e9-8454-36a46083e744.png)

- Actual behavior

![image](https://user-images.githubusercontent.com/6077149/55730720-e72a9f80-5a29-11e9-9489-57c021b6c28f.png)

**Comment by pribavkindenis** [comment]
For QR:
See `com.haulmont.cuba.gui.actions.list.CreateAction#CreateAction`
