### ISSUE TITLE
Studio or Runtime can’t found duplicate screen

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/cuba#2042]
- Platform version: 7.0.3
### Description of the bug or enhancement

In a team, two developer created two screen with same id in @UiController,the application can run correctly before code merge. After code commit and merge, the application might occurs error in runtime.
May be framework can check this kind of problem when application starting. 

Discussion in forum : 
https://www.cuba-platform.com/discuss/t/studio-or-runtime-cant-found-duplicate-screen/8738

### QA

Check that `RuntimeException` is thrown while app opening when a project has two or more screens with the same ids (e.g. `@UiController("TestScreen")`)

Check that app works when:

1. App component used in project has a screen with some id (let `@UiController("Boo")`)
2. Project has ext screen with the same id (e.g. `@UiController("Boo")`)

**Comment by jreznot** [comment]
Please do not use issues is there is no precise use case and details. You can ask any question on the forum.

**Comment by jreznot** [comment]
Please note that if we replace a UI controller from app component with the same ID - it is a correct situation. Only screens with the same ID in a single project should be considered as an error.
