### ISSUE TITLE
IllegalStateException while adding a new UI permission item 

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2048]
### Environment

- Platform version: 7.0.3

### Description of the bug or enhancement

- Minimal reproducible example

1. Open an existing role for editing
2. Go to the UI tab
3. Select any screen
4. Try to add any component

- Expected behavior

A new item is added to the table

- Actual behavior

```
IllegalStateException: TableItems is not active
```

**Comment by andreysubbotin** [comment]
For QA: look at #1953
