### ISSUE TITLE
Set auto width of CubaComboBox suggestion popup

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#2049]
### Description of the bug or enhancement
If you try to select specific time zone in _Settings_ screen you can see that time zones are not fitted in the dropdown list.
![image](https://user-images.githubusercontent.com/22093943/55863472-a34fab80-5b8b-11e9-8817-f8b5d7459627.png)

It would be better if we could increase the width or do smth else in order to show full value in the dropdown list.

**Comment by jreznot** [comment]
Let's implement #2096 before this change
