### ISSUE TITLE
Change class loading mechanism for single WAR

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#2060]
cuba-platform/cuba-gradle-plugin#103

### Environment

- Platform version: 7.0

### Description of the bug or enhancement
Any class from `global` module can be loaded `core` class loader and web container class loader. It causes errors in case of class loader implementation (e.g. Drools Project class loader). 
Create dirs `WEB-INF/core_libs` and `WEB-INF/web_libs` and load classes for web and core from the dirs using CubaSingleAppClassloader. Don't put application jars (for `core` or `web` module) to the `WEB-INF/lib` so web container classloader can't load classes from those jars.

**Comment by soraksh** [comment]
`WEB-INF/lib-core` and `WEB-INF/lib-web` dirs created for `core` and `web` jars.
