### ISSUE TITLE
REST API throws Exception java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by jayceewhitman** [cuba-platform/cuba#2072]
### Environment

- Platform version: 7.0.1

### Description of the bug or enhancement

1. Create any project
2. Under web-app.properties add
cuba.rest.client.id = client
cuba.rest.client.secret = secret
3. Access through curl
curl -H "Content-type: application/x-www-form-urlencoded" -H "Authorization: Basic Y2xpZW50OnNlY3JldA==" -d "grant_type=password&username=admin&password=admin" http://localhost:8080/app/rest/v2/oauth/token

Crashes. Exception java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"

**Comment by gorbunkov** [comment]
Not an issue. The answer is on the forum: https://www.cuba-platform.com/discuss/t/geting-token-for-rest-api-throw-exception/8846
