### ISSUE TITLE
Ability to disable browse's autofill for fields

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2075]
### Description of the bug or enhancement

If a field is placed within either `Form` or `FieldGroup` then browse's autofill in shown.

Let's implement an attribute that allows you to disable this functionality.

- Minimal reproducible example

1. Open User Editor
2. Click on any field

- Expected behavior

No Browser's autofill is shown

- Actual behavior

![image](https://user-images.githubusercontent.com/6077149/56344090-a111d080-61cd-11e9-96f4-62aa5f35dde0.png)

**Comment by natfirst** [comment]
For QA: check in different browsers (Chrome, Firefox) that autofill is not shown.
