### ISSUE TITLE
Provide ability to change suggestion popup width for LookupField

### ISSUE THREAD

**Issue by pribavkindenis** [cuba-platform/cuba#2096]
### Environment

- Platform version: 7.X.X
- Client type: Web

### Description of the enhancement

It will be useful to provide `com.vaadin.ui.ComboBox#setPopupWidth` to `LookupField` interface and implement the method in each class excluding desktop client classes.

### Minimal reproducible example

When configuring `LookupField` instance inside a controller:
- Expected behavior:
There is a method named `setPopupWidth` allowing you to set suggestion popup width using relative units. For instance:
`lookupField.setPopupWidth("90%");`
- Actual behavior:
There is no method named `setPopupWidth` allowing you to set suggestion popup width using relative units.

**Comment by Mihail063** [comment]
Try to set invalid argument to the `setPopupWidth ()` 
- Actual behavior:
The size of the popup window becomes 10%. 
- Expected behavior:
Shows an error message (for example, IllegalArgumentException)

**Comment by pribavkindenis** [comment]
According to `com.haulmont.cuba.gui.components.Component#setWidth`, we decided not to validate the width input parameter.

**Comment by pribavkindenis** [comment]
JavaDoc refactored.
