### ISSUE TITLE
Grid height changed if it contains a TokenList

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#210]
1. Create grid layout
1. Add TokenList to the cell
1. Add items to tokenList at runtime

Height of grid will be changing dynamically.

**Comment by dtsaryov** [comment]
@GlebDurygin please check if the issue is still reproducing. It seems that we've already fixed it some time ago

**Comment by GlebDurygin** [comment]
@dtsaryov This case is not reproduced in all browsers. Perhaps this problem was solved in #2450
