### ISSUE TITLE
Add type parameter to LoadContext#getId

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#2107]
### Environment

- Platform version: 7.0.4 

### Description of the bug or enhancement
Now the method returns Object, but should return correct Entity key type
```
public class LoadContext<E extends Entity> implements DataLoadContext, Serializable {
...
    public Object getId() {
...
```
Probably should be 
```
public class LoadContext<E extends Entity<K>, K> implements DataLoadContext, Serializable {
...
    public K getId() {
...
```

**Comment by jreznot** [comment]
It will break API

**Comment by knstvk** [comment]
I can only imaging adding auto-cast like `public <K> K getId()`

**Comment by knstvk** [comment]
LoadContext should not be used in application code since the introduction of fluent API which has no such deficiency.
