### ISSUE TITLE
Exception details are lost in JXErrorPaneExt#sendSupportEmail

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2123]
### Environment
- Platform version: 6.8, 6.10
- Client type: Desktop

### Description of the bug or enhancement
If for some reason sending "exception report" for unexpected error fails - then exception details are lost.
see com.haulmont.cuba.desktop.sys.JXErrorPaneExt#sendSupportEmail
```java
} catch (Throwable e) {
    mainFrame.showNotification(messages.getMainMessage("errorPane.emailSendingErr", locale),
            Frame.NotificationType.ERROR);
}
```
---
### How to test
Refapp 6.10
1. Add property `cuba.supportEmail` to the _desktop-app.properties`_ file
2. Just invoke some exception (e.g. IllegalArgumentException) by button click.
3. In the exception dialog click on "Report".
4. See desktop logs. On Windows for refapp you can find it here: `C:\\Users\username\.haulmont\refapp\logs\app.log`

**Comment by alexbudarov** [comment]
@jreznot What is the reason this was not committed to master?

**Comment by Flaurite** [comment]
@alexbudarov Hi! Sorry, missed a сommit.
