### ISSUE TITLE
ExcelExporter does not consider format strings

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#2128]
A topic on support forum: [link](https://www.cuba-platform.com/discuss/t/excel-export-does-not-use-format-strings-in-localisation/9109)

### Environment

- Platform version: 6.10

### Description of the bug or enhancement

`ExcelExporter` uses hard-coded formats instead of format strings:

```Java
protected void createFormats() {
    timeFormatCellStyle = wb.createCellStyle();
    timeFormatCellStyle.setDataFormat(HSSFDataFormat.getBuiltinFormat("h:mm"));

    dateFormatCellStyle = wb.createCellStyle();
    dateFormatCellStyle.setDataFormat(HSSFDataFormat.getBuiltinFormat("m/d/yy"));

    ...
}
```

It leads to bad-looking output values:

![demo](https://www.cuba-platform.com/discuss/uploads/default/original/2X/2/2b783497d21a2c7e679e0d41a8e31a7bf2a2cef9.png)

**Comment by jreznot** [comment]
Please check MS Office with different locale settings.

**Comment by dtsaryov** [comment]
@myatlevEvg please check if fixed in related issue

**Comment by myatlevEvg** [comment]
Fixed in the related [issue](https://github.com/cuba-platform/cuba/issues/2195)
