### ISSUE TITLE
Immediate mode for Filter component

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#2134]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

Current filter behavior is not intuitive: the user changes filter parameters, but data is not filtered until the user clicks "Search". So the state of the filter is not consistent with the state of data.

I propose to introduce "Immediate" mode when every change of filter parameters automatically reloads data. Make this mode default and provide a component property to turn it to "explicit" mode. Create an app property for default mode.

For "explicit" mode, consider highlighting Search button when parameters were changed since last apply.

---

### Changes
Now 'Filter' has specific mode for immediate searching. It allows you to apply filter immediately after condition field's value changing. General cases when a filter is applied immediately:
- After the field's value changing;
- After changing condition operation;
- After removing a condition from the filter;
- After "max result" changing;
- After filter editor dialog when you click on the "OK" button;
- After clear all values.

Given mode can be configured in the Filter itself and using application property:
```
cuba.gui.genericFilterApplyImmediately=true
```
True is a default value.

**Note, immediately searching does not work if you add a new condition using "Add search condition" button.**

If `cuba.gui.genericFilterApplyImmediately` and `applyImmediately` are set simultaneously, so `applyImmediately` will be applied.

#### XML
`Filter` has new property: `applyImmediately` it has boolean type.
Example:
```
<filter id="filter"
        applyImmediately="false"
        applyTo="table"
        dataLoader="entityDl">
    <properties include=".*"/>
</filter>
```
#### Java
`Filter` has new API:
```
void setApplyImmediately(boolean immediately);
boolean isApplyImmediately();
```
![filter](https://user-images.githubusercontent.com/22093943/60721912-6d2e8780-9f40-11e9-9b84-7f4c1941c1d7.gif)

### For QA
1. Try to add condition from Edit window. Make sure that filter is applied only once (not every time for each condition).
2. Check general cases. Try to create a filter with complicated conditions. Make sure that filter is applied only once for one action (change value, change operation, etc).
3. In 7.1+ `cuba.gui.genericFilterApplyImmediately` property is true by default.
3.1 Create project on 7.1 and set false to the given proeprty manually. Filter should not be applied immediately. 
3.2 Create project on 7.1 and set apply immediately to false in <filter> element. Filter should not be applied immediately.

**Comment by natfirst** [comment]
Case: 'Add entity condition and try to change search operation - filter should be applied. ' does not work
![operation](https://user-images.githubusercontent.com/17950251/61126641-11bf4500-a4be-11e9-9c6e-102c6ac120c1.gif)

**Comment by knstvk** [comment]
@Flaurite @natfirst 
I think we should refresh immediately also after changes in "Show rows" field.

**Comment by Flaurite** [comment]
@natfirst Please pay attention that description of issue was changed

**Comment by sukhova** [comment]
Consider about renaming the "Search" button to the "Refresh" button in the immediate mode.

**Comment by sukhova** [comment]
Case 1: 
1) Add a search condition for the filter
2) Enter some value to the field
3) The filter was applied
4) Click on the **Refresh** -> _Reset filter_

**AR**:
The filter is not reset
![filter_case1](https://user-images.githubusercontent.com/40686909/63918927-c43b6f00-ca4e-11e9-80d4-50badf788e36.gif)

Case 2:
1) Activate FTS
2) Open entity browser and check the **Full-Text Search** checkbox
3) Enter "Adm" to the filter field
 **AR**: 
The filter is applied only after pressing **Enter** or clicking the **Search** button
**ER**:
The filter should apply immediately
4) Apply filter pressing **Enter**
5) Select some value in the **Show rows** list
**AR**:
The search that was performed before is reset
![filter_case2](https://user-images.githubusercontent.com/40686909/63918953-cf8e9a80-ca4e-11e9-8b60-74c4864a51a4.gif)

Case 3:
1) Activate FTS
2) Open entity browser and check the **Full-Text Search** checkbox
3) Enter "Adm" to the filter field
4) Apply filter pressing **Enter**
5) Uncheck the **Full-Text Search** checkbox

**AR**:
The filter is not reset
![filter_case3](https://user-images.githubusercontent.com/40686909/63918960-d2898b00-ca4e-11e9-9b05-cbbf2896cc15.gif)

**Comment by natfirst** [comment]
Add Russian localization for the `Refresh` caption
