### ISSUE TITLE
Links contained Russian letters in RichTextArea is broken in Firefox browser

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#2136]
Platform 6.10+
Reproduces only in Firefox

1) Add RichTextArea to the screen
2) Click "Create Link Button"
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/ae45484b-4306-44e8-8fb5-7eb21689f44e)
3) Type address with Russian language letters (http://тест.рф)
4) Inspect this element in dev console in Firefox

AR: ![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/72d34a9f-a37f-46d5-afa1-5188d40f42a9)

Link is incorrect

## Updates
The `IframeElement` inside the `RichTextArea` has a charset `utf-8`.

## QA
Check the above case

**Comment by jreznot** [comment]
Let's backport this to Release 6.10

**Comment by GlebDurygin** [comment]
Check the above case for Platform version 6.10
