### ISSUE TITLE
Unable to parse the value of TextField with offsetTime/offsetDateTime datatype

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#2139]
### Environment

- Platform version: 7.1

### Description of the bug or enhancement

1) Create a textField:
    ```<textField id="textFieldlocalDate" datatype="offsetTime" caption="textFieldlocalDate"/>```
2)Try to enter values:
    a. 20:20
    b. 20:20:20
    c. 20:20:20+01:00

**AR:**
None of these values are not parsed

**Comment by glebfox** [comment]
Time part has the following format: `HH:mm Z`. The following strings are correct:
```
18:57 +0400
19/07/2019 18:57 +0400
```
