### ISSUE TITLE
Override reserved globals for Firefox 67

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#2146]
### Environment

- Platform version: 6.2-7.2
- Client type: Web

### Description of the bug or enhancement

Check issue https://github.com/vaadin/framework/issues/11597

> The reason is apparently that Firefox has added a feature called U2F, which overrides any variable named u2f.

Corresponding fixes https://github.com/vaadin/framework/pull/11598

Most likely we need this in order to be compatible with Firefox 67

**Comment by jreznot** [comment]
Check if it affects 5.6-5.9 versions too

**Comment by glebfox** [comment]
For QA:

Check that compiled JS files have no functions/variables with either `U2F` or `u2f` names. 

Note that `U2f` and `u2F` are valid names.

<img width="1440" alt="Screenshot 2019-05-27 at 17 46 54" src="https://user-images.githubusercontent.com/6077149/58423984-6ee66f00-80a7-11e9-9f7a-fd0c33d407c5.png">
