### ISSUE TITLE
GenericFilter should have a setting that will disable window caption changing

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#2148]
Right now, the filter name is added to the windows caption when the filter is selected. In some cases this behavior is not required. There must be an option to disable the caption changing.

**Comment by gorbunkov** [comment]
`Filter` interface now contains a `setWindowCaptionUpdateEnabled()` method that will disable window caption change. Usage example:

```java
    @Inject
    protected Filter filter;

    @Subscribe
    protected void onInit(InitEvent event) {
        filter.setWindowCaptionUpdateEnabled(false);
    }
```

**Comment by BryanYin** [comment]
Thanks! I see both 7.1.0 and 7.2.0 added. Can I assume 7.1.0 will contain this change?

**Comment by gorbunkov** [comment]
Yes, that's exactly what this label means:)
