### ISSUE TITLE
Ability to choose FileStorage implementation based on app property

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2149]
### Description of the bug or enhancement
See https://www.cuba-platform.com/discuss/t/file-storage-type-based-on-app-property/9190/2

File storage implementation is a runtime deployment choice.
We can develop, debug and test some project using usual filesystem-based File Storage.
But at the same time have preproduction and production servers running in Amazon Cloud.

Therefore file storage mode should be tunable by runtime settings (local app properties).

**Comment by knstvk** [comment]
Can be implemented using Spring profiles, see cuba#66
