### ISSUE TITLE
Desktop vs Web key differences

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#215]
### Desktop vs Web

1. Desktop имеет меньшее время отклика (тормозит переключение вкладок в Web)
1. Работает TabOrder, есть возможность определять логику фокуса (мелочи)
1. Фокус может вернуться в ненужную позицию
1. (+) Shortcuts (многие шорткаты заняты браузером) (решается в Electron)
1. (+) Failover (сессия и данные в UI) (решается в Electron)
1. (+) Простая интеграция с Desktop API (Телефония) (решается в Electron)
1. (+) Возможность Detach окна из главного TabSheet (легко реализовать на базе открытия новых вкладок по ссылке)
1. (+) Доставка сообщений с сервера на UI (PUSH/WebSockets)
1. (+) SuggestionField (Асинхронные запросы на сервер из компонентов)
1. Проблемы с AutoRefresh
1. (+) Ленивая загрузка данных в таблицах мешает доскроллить до контента (отключается свойством приложения)
1. (+) Потенциальные проблемы с JS Timer (Polling)

(+) - решено для Web

### Замеры перерисовки верстки при переключении между экранами driver editor и booking screen
```
103517ms	Total layout phase time: 1173ms
103517ms	* Dumping state changes to the console
103518ms	UIDL: undefined
103679ms	Processing time was 2284ms for 56052 characters of JSON

140439ms	Total layout phase time: 1374ms
140440ms	* Dumping state changes to the console
140442ms	UIDL: undefined
140611ms	Processing time was 2246ms for 54877 characters of JSON
```

:link: Related links: {"depends on:": "https://youtrack.haulmont.com/issue/PL-8465"}

---
Original issue: https://youtrack.haulmont.com/issue/PL-7214

**Comment by jreznot** [comment]
Closing this as obsolete
