### ISSUE TITLE
Allow S3 FileStorageAPI Implementation to fetch the credentials from AWS metadata service

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/cuba#2152]
### Environment

- Platform version: 6.x, 7.0

### Description of the bug or enhancement

Currently when the S3 implementation for the FileStorageAPI is used, it requires to pass in the AWS credentials via application properties that are stored in the DB (see [AmazonS3Config](https://github.com/cuba-platform/cuba/blob/master/modules/core/src/com/haulmont/cuba/core/app/filestorage/amazon/AmazonS3Config.java).

When using the Java SDK from AWS, they instead have this concept of credentials provider chain: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html

Which in particular allows that **in case the app runs within an AWS service** (like Beanstalk /  Fargate / EC2), the credentials / assumed role are passed in from the outside environment without the need to explicitly create credentials and hardcode it into the application. This is possible through different mechanisms in AWS. 

One of them is the metadata service, that runs inside a EC2 instance and can be utilized from applications within the EC2 instance to get the corresponding credentials: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials

This approach is more flexible in my opinion and also safer, because it can lead to short-lived credentials, which is mostly a good thing.

**Comment by andreysubbotin** [comment]
AWS File storage extracted into a separate application component: cuba-platform/cuba#2397
