### ISSUE TITLE
Missing equals/hashCode methods in MetaClassImpl

### ISSUE THREAD

**Issue by w1nter27** [cuba-platform/cuba#2156]
### Environment

- Platform version: 6.10.9

### Description of the bug or enhancement

Next classes don't have equals/hashCode methods:
* MetaClassImpl
* MetaPropertyImpl
* MetadataObjectImpl

But they are using as key in HashMap collection. See next bean: 
**com.haulmont.cuba.core.sys.AbstractViewRepository**

**Comment by knstvk** [comment]
So what is the problem? These objects can be obtained only from the central registry which maintains their identity.

**Comment by w1nter27** [comment]
Problem is solved. It's our internal bug.
