### ISSUE TITLE
Rework remember me mechanism

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#2163]
### Issues with current approach
* When user logs out - remember me cookies are not cleared, thus user does not have a straightforward way to completely leave an app (apart from clearing browser's cookies). This behavior may be misleading.
* There is no transparent login - user should press login button. This behavior mimics browsers form auto-fill mechanism.
* Internally remember me tokens do not have expiration date.
* Remember me cookies expiration date is undetermined.

### Suggested changes
* Introduce remember me lifetime configuration parameter. Introduce server side token expiration check.
* Log-in user transparently without showing login screen. Do not populate password field with remember me token.

#### Remember me expiration

New configuration property is introduced: `cuba.rememberMeExpirationTimeoutSec`.

It defines expiration time for "remember me" cookies and `RememberMeToken` entity.

The property should be defined both for `core` and `web` modules.

By default expiration time equals to `30 * 24 * 60 * 60` - one month.

#### Login screens

If user has "remember me" cookies the app will try to log in automatically.
In case when cookies or remember me token are expired they will be invalidated.

#### Logout

When user explicitly logs out from application (clicks logout button) all "remember me" cookies are removed.

### QA

Check that:

- [x] user is automatically logged in if "remember me" cookies are valid (restart the app or remove `JSESSIONID` cookie and reopen the app)
- [x] "remember me" cookies are removed when user logs out
- [x] user is not logged in if cookies are expired (set small expiration time)
- [ ] user is not logged and cookies are removed when cookies are not valid (change cookies manually)

Cookies can be access via browser dev tools.

Firefox:
![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/045e4438-ca86-436a-8f94-3c2340f62399)

Chrome:
![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/d1acaaf5-a311-49f1-a28f-9d4b66e46346)

**Comment by IskandarovRost** [comment]
1) Add additional(the second in the list) Russian locale. Enable locale selection during login.
![image](https://user-images.githubusercontent.com/19840141/69796698-e4aecd00-11e7-11ea-8df9-f43e995b00b1.png)

2) Start the application

3) Create a user and set him Language = English
![image](https://user-images.githubusercontent.com/19840141/69796984-64d53280-11e8-11ea-936b-45cadc9a95d9.png)

4) Open UI, select the Russian locale, enable *remember me* and log in by this user
![image](https://user-images.githubusercontent.com/19840141/69796622-c3e67780-11e7-11ea-914c-c7a62087b5f.png)

5) See the Russian locale is applied
![image](https://user-images.githubusercontent.com/19840141/69797310-e4630180-11e8-11ea-94d6-10145ad1460a.png)


6) Close the Browser
7) Restart the browser and open the application URL

AR: the user is logged in, BUT the default (English) locale is applied for the user/ and no way to change the language without re-login
![image](https://user-images.githubusercontent.com/19840141/69797466-2ee47e00-11e9-11ea-870a-95083a62da2f.png)

**Comment by IskandarovRost** [comment]
reopen due to #2654

**Comment by dtsaryov** [comment]
Reported by @IskandarovRost 

### Description of the bug or enhancement

#### Minimal reproducible example

1. Set cuba.rememberMeExpirationTimeoutSec = 60
2. Start the application
3. Login with "Remember me" enabled
4.Close the application Tab
5. immediately remove JSESSIONID cookie
6. Open the application URL

#### Actual behavior

Login screen appears.

Expiration dates for cookies are correct. But Platform logic does not work properly.

![code](https://user-images.githubusercontent.com/19840141/72982563-cab0f580-3df8-11ea-8f15-6da7cc035257.png)
The time in seconds is added to time in millis in the calculation logic.

**Comment by IskandarovRost** [comment]
Reopen.
1) do not redefine ``cuba.rememberMeExpirationTimeoutSec``
Leave it one month by default (Is it Integer?): ``` @DefaultInt(30 * 24 * 60 * 60)```
2) start the appllication
3) login with rememberme enabled
4) restart the application server(to invalidate the session)
5) Open UI once again
**ER:** Main screen
**AR:** Login window

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/20ea3525-ffbe-4a40-9d53-c4c87c827cc9)
