### ISSUE TITLE
Add ability to set item descriptions in Table

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#2168]
### Description of the bug or enhancement
It is already supported in DataGrid, so we need to implement this feature in Table.

See `com.vaadin.v7.ui.Table#setItemDescriptionGenerator()`

### Updates
The `Table` component has an ability to define descriptions for table cells using `ItemDescriptionProvider`:
* `void setItemDescriptionProvider(@Nullable BiFunction<? super E, String, String> provider)` - sets the item description provider that is used for generating tooltip descriptions for items;
* `BiFunction<? super E, String, String> getItemDescriptionProvider()` - gets the item descriptor provider for table.

#### Usage Example for Department table:
The `Department` has three fields: name, active, parentDept.
##### First way
```
@Install(to = "departmentsTable", subject = "itemDescriptionProvider")
protected String departmentsTableItemDescriptionProvider(Department department, String property) {
    if (property == null) {
        // description for row
        if (department.getParentDept() == null) {
            return "Parent Department";
        }
    } else if (property.equals("active")) {
        // description for column "active"
        return department.getActive()
                ? "Active department"
                : "Inactive department";
    }
    return null;
}
```
##### Second way
```
departmentsTable.setItemDescriptionProvider(((department, property) -> {
    if (property == null) {
        // description for row
        if (department.getParentDept() == null) {
            return "Parent Department";
        }
    } else if (property.equals("active")) {
        // description for column "active"
        return department.getActive()
                ? "Active department"
                : "Inactive department";
    }
    return null;
}));
```
#### Test project
[table-description-provider.zip](https://github.com/cuba-platform/cuba/files/4005097/table-description-provider.zip)

### QA
Check that the user can define different descriptions for table cells. (For `Table`, `GroupTable` and `TreeTable` components).

**Comment by natfirst** [comment]
Check list

- [ ] Check first way for all components (For Table, GroupTable and TreeTable)
- [ ] Check second way for all components (For Table, GroupTable and TreeTable)
- [ ] Gets the item descriptor provider for all components 
- [ ] Check that Studio install methods correctly
