### ISSUE TITLE
Design-time security

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/cuba#2172]
Added ability to define roles in the source code. New annotations are used for this purpose.

1) ```com.haulmont.cuba.security.app.role.annotation.Role```
Indicates that an annotated class is a "Role". Such a role will be available in the user interface if the application is running in the corresponding mode (the app property cuba.rolesStorageMode equals SOURCE_CODE or MIXED).

2) ```com.haulmont.cuba.security.role.EntityPermissionsContainer```
Defines permissions to access operations on an entity (read, create, update, delete).

3) ```com.haulmont.cuba.security.role.EntityAttributePermissionsContainer```
Defines permissions to access individual entity attributes.

4) ```com.haulmont.cuba.security.role.SpecificPermissionsContainer```
Defines specific permissions access.

5) ```com.haulmont.cuba.security.role.ScreenPermissionsContainer```
Defines screen access permissions.

6) ```com.haulmont.cuba.security.role.ScreenComponentPermissionsContainer```
Defines permissions to access screen elements.

The easiest way to determine the role in the application source code is to extend your class from AbstractRoleDefinition and mark it with ```@Role``` annotation. Usage example:
```
@Role(name = "My first role", isDefault = true)
public class MyFirstRole extends AnnotatedRoleDefinition {
  
      @EntityAccess(entityClass = SomeEntity.class,
             operations = {EntityOp.DELETE, EntityOp.UPDATE})       
      @EntityAccess(entityName = "app_SomeOtherEntity",
             operations = {EntityOp.CREATE, EntityOp.READ})       
      @EntityAccess(entityName = "*",
             operations = {EntityOp.CREATE})       
       @Override
       public EntityPermissionsContainer entityPermissions() {
           return super.entityPermissions();
       }

       @EntityAttributeAccess(entityClass = SomeEntity.class, 
                view = {"attr1", "attr2"}, 
                modify = {"someAttribute"})
       @EntityAttributeAccess(entityName = "app_SomeOtherEntity", 
               modify = {"someAttribute"})
       @EntityAttributeAccess(entityName = "app_ThirdEntity", modify = "*")
       @EntityAttributeAccess(entityName = "*", view = "*")
       @Override
       public EntityAttributePermissionsContainer entityAttributePermissions() {
           return super.entityAttributePermissions();
       }
  
       @SpecificAccess(permissions = {"my.specific.permission1", "my.specific.permission2"})
       @SpecificAccess(permissions = "*")
       @Override
       public SpecificPermissionsContainer specificPermissions() {
           return super.specificPermissions();
       }
  
       @ScreenAccess(screenIds = {"myapp_SomeEntity.edit", "myapp_SomeEntity.edit"})
       @ScreenAccess(screenIds = "*")
       @Override
       public ScreenPermissionsContainer screenPermissions() {
           return super.screenPermissions();
       }
  
       @ScreenComponentAccess(screenId = "myapp_SomeEntity.browse", 
              deny = {"someGroupBox"}, 
              allow = {"otherGroupBox", "commitButton"})
       @Override
       public ScreenComponentPermissionsContainer screenComponentPermissions() {
           return super.screenComponentPermissions();
       }
   }
```

8) Defines security scope on a role definition #2428. The default security scope is Generic UI. You can set up security scope in a `@Role` annotation, e.g. creation a role for the REST scope 
`@Role(name = "My first role", isDefault = true, securityScope='REST')`

Breaking changes:
* UserSession:
  * Constructor `UserSession(UUID id, User user, Collection<Role> roles, Locale locale, boolean system)` signature changed to `UserSession(UUID id, User user, Collection<RoleDefinition> roles, Locale locale, boolean system)`
  * Constructor `UserSession(UUID id, User user, Collection<Role> roles, Locale locale)` signature changed to `UserSession(UUID id, User user, Collection<RoleDefinition> roles, Locale locale)`
  * Removed `addPermission` and `removePermission` methods. Use `UserSession#getJoinedRole` and `UserSession#setJoinedRole` with `RoleDefinitionBuilder` instead.

**Comment by invviz** [comment]
Added ability to define roles in the source code. New annotations are used for this purpose.

1) ```com.haulmont.cuba.security.app.role.annotation.Role```
Indicates that an annotated class is a "Role". Such a role will be available in the user interface if the application is running in the corresponding mode (the app property cuba.rolesStorageMode equals SOURCE_CODE or MIXED).

2) ```com.haulmont.cuba.security.app.role.annotation.EntityAccess```
Defines permissions to access operations on an entity (read, create, update, delete).

3) ```com.haulmont.cuba.security.app.role.annotation.EntityAttributeAccess```
Defines permissions to access individual entity attributes.

4) ```com.haulmont.cuba.security.app.role.annotation.SpecificAccess```
Defines specific permissions access.

5) ```com.haulmont.cuba.security.app.role.annotation.ScreenAccess```
Defines screen access permissions.

6) ```com.haulmont.cuba.security.app.role.annotation.ScreenElementAccess```
Defines permissions to access screen elements.


The easiest way to determine the role in the application source code is to extend your class from AbstractRoleDefinition and mark it with ```@Role``` annotation. Usage example:
```
@Role(name = "My first role", type = RoleType.STANDARD, isDefault = true)
public class MyFirstRole extends AbstractRoleDefinition {
  
       @EntityAccess(target = SomeEntity.class,
               deny = {EntityOp.DELETE, EntityOp.UPDATE})
       @Override
       public EntityPermissions entityPermissions() {
           return super.entityPermissions();
       }
  
       @EntityAttributeAccess(target = SomeEntity.class, allow = {"someAttribute"})
       @Override
       public EntityAttributePermissions entityAttributePermissions() {
           return super.entityAttributePermissions();
       }
  
       @SpecificAccess(target = "my.specific.permission", access = Access.ALLOW)
       @Override
       public SpecificPermissions specificPermissions() {
           return super.specificPermissions();
       }
  
       @ScreenAccess(deny = {"myapp_SomeEntity.edit"})
       @Override
       public ScreenPermissions screenPermissions() {
           return super.screenPermissions();
       }
  
       @ScreenElementAccess(screen = "myapp_SomeEntity.browse", deny = {"someGroupBox"})
       @Override
       public ScreenElementsPermissions screenElementsPermissions() {
           return super.screenElementsPermissions();
       }
   }
```

**Comment by andreysubbotin** [comment]
Studio issue: https://youtrack.haulmont.com/issue/STUDIO-7233

**Comment by andreysubbotin** [comment]
* UserSession:
  * Constructor `UserSession(UUID id, User user, Collection<Role> roles, Locale locale, boolean system)` signature changed to `UserSession(UUID id, User user, Collection<RoleDefinition> roles, Locale locale, boolean system)`
  * Constructor `UserSession(UUID id, User user, Collection<Role> roles, Locale locale)` signature changed to `UserSession(UUID id, User user, Collection<RoleDefinition> roles, Locale locale)`
  * Removed `addPermission` and `removePermission` methods. Use `UserSession#getJoinedRole` and `UserSession#setJoinedRole` with `RoleDefinitionBuilder` instead.
