### ISSUE TITLE
StyleProvider doesn't work in TreeTable hierarchical column

### ISSUE THREAD

**Issue by w1nter27** [cuba-platform/cuba#2174]
### Environment

- Platform version: 6.10.9
- Client type: Desktop

### Description of the bug or enhancement

1. Create screen with TreeTable component
2. Add some StyleProvider, which will be change background color for all columns in row (also override selected style and check row on selection)
3. Open this screen, hierarchical column doesn't change style

AR: hierarchical column have default background color
ER: all columns have new background color from StyleProvider

NOTE: in web all columns have new background color

**Comment by dtsaryov** [comment]
The first column of `DesktopTreeTable` is just a Tree. Tree doesn't have fixed columns, as a result its "cells" cannot be filled correctly:

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/cbc52525-e0d6-43d1-953c-1c3b2c22b5cf)

**Comment by dtsaryov** [comment]
will check again

**Comment by dtsaryov** [comment]
No suitable solution can be found. First TreeTable column background rendering is hardcoded in `NimbusDefaults` as `"Tree:TreeCell[Focused+Selected].backgroundPainter"`. It means that even if you replace a painter, it will also affect a tree.

Moreover this issue is a duplacate. See #152
