### ISSUE TITLE
Null values of new instances are not merged to parent data context

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#2176]
We have two not-persistent entities: `Order` and `OrderItem`. The `Order` entity has a collection of order items.
OrderItem editor is opened within the Order editor with parent data context:

```java
@Subscribe("orderItemsTable.edit")
protected void onOrderItemsTableEdit(Action.ActionPerformedEvent event) {
    screenBuilders.editor(orderItemsTable)
            .withParentDataContext(dataContext)
            .build()
            .show();
}
```

If in the order item editor some of the fields become NULL then these values are not merged to the parent data context and order item continues to have an old value.

This happens because of these lines of code in the `DataContextImpl.mergeState()` method:

```java
// ignore null values in new source entities
if (srcNew && value == null) {
    continue;
}
```

A sample project that demonstrates the problem: 
[not-persistent-merge-sample.zip](https://github.com/cuba-platform/cuba/files/3256804/not-persistent-merge-sample.zip)

A test case from #2336:
```
def "nested entity merge"() {
    def orderLine = metadata.create(OrderLine)
    orderLine.product = metadata.create(Product)

    def ctx = factory.createDataContext()

    when: 'Entity with non-null property is merged'
    ctx.merge(orderLine)

    then: 'Merged instance has non-null property value'
    ctx.find(orderLine).product != null

    when: 'Same entity with null property merged'
    orderLine.product = null
    ctx.merge(orderLine)

    then: 'Merged instance has null property value'
    ctx.find(orderLine).product == null
}
```

**Comment by knstvk** [comment]
QA: test editing of deep compositions
