### ISSUE TITLE
The error “Java Head Space” occurs while opening scheduled task editor

### ISSUE THREAD

**Issue by trx0eth7** [cuba-platform/cuba#2179]
If there is a large number of users in the database, when admin try to open the ScheduledTaskEditor editing screen, the error 'Java head space' or performance issue may occur.

### Enhancement 
It may be better to use the LookupField ('userNameField') instead of PickerField and
avoid using com.haulmont.cuba.core.app.scheduling.SchedulingServiceBean#getAvailableUsers
```
    @Override
    public List<String> getAvailableUsers() {
        List<String> result = new ArrayList<>();

        Transaction tx = persistence.createTransaction();
        try {
            EntityManager em = persistence.getEntityManager();
            Query query = em.createQuery("select u from sec$User u");
            List<User> userList = query.getResultList();
            for (User user : userList) {
                result.add(user.getLogin());
            }
            tx.commit();
        } finally {
            tx.end();
        }

        return result;
    }
```

### Environment
- Platform version:  6.10.8
- Database: PostgreSQL, 11

**Comment by knstvk** [comment]
Let's replace LookupField with SuggestionPickerField.
