### ISSUE TITLE
Delta translation in app destroys existing translations

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/cuba#2188]
### Environment

- Platform version: 7.0.2

### Description of the bug or enhancement

Currently when a delta translation is provided for a particular message key for a translation that is already provided within an app component, all other keys that are in that message properties file are taken from the app component anymore. Instead the default to english language kicks in.

This basically prevents the possibility to override a particular translation. it is only possible if the complete file from the app component is copied and the adjustments are made afterwards.

But then the problem is that it is not possible to leverage translation updates from the app component.

### Example

An example of this can be seen in the following application: https://github.com/cuba-guides/cuba-petclinic-i18n-messages. It uses the german translation app component: https://github.com/balvi/translation-de

In the branch `error-override-message-of-app-component` the main message pack file for the GUI module is overriden to provide one correction of the app component:

```
com.haulmont.cuba.gui.app.security.user.browse/additional = Zusätzlich
```
see: https://github.com/cuba-guides/cuba-petclinic-i18n-messages/blob/error-override-message-of-app-component/modules/gui/src/com/haulmont/cuba/gui/messages_de.properties

The result is that the key `additional` is correctly displayed as `Zusätzlich` - but all other translations that have been defined in the file in the app component are not used anymore.

The resulting UI lost all german translations except for the overridden one:

<img width="1392" alt="Bildschirmfoto 2019-06-12 um 15 51 18" src="https://user-images.githubusercontent.com/817400/59356861-0abfde00-8d2a-11e9-8797-1d3a02c4f821.png">

**Comment by mariodavid** [comment]
I just tried to do it without the application component. It turns out the same problem ocurs:

### Example: Delta override for english message key
When trying to do a delta override for a message key in the main message key of the gui module like this:

##### modules/gui/src/com/haulmont/cuba/gui/messages.properties
```
com.haulmont.cuba.gui.app.security.user.browse/additional = Additional Actions
```

The resulting application looks like this:
<img width="1392" alt="Bildschirmfoto 2019-06-12 um 16 20 52" src="https://user-images.githubusercontent.com/817400/59359336-75731880-8d2e-11e9-9ad0-f46b7e5b1f5b.png">

It contains the translated values `Additional Actions` but loses all translations. Even the fallback to the english locale does not work.

**Comment by knstvk** [comment]
The correct way to override some translation (as well as any message in general) is to place the message into the main message pack of the application. In your case, you should add 

    com.haulmont.cuba.gui.app.security.user.browse/additional = Zusätzlich

to `com/haulmont/sample/petclinic/web/messages_de.properties` of the `web` module.

The `com/haulmont/cuba/gui/messages_de.properties` file should be removed.
