### ISSUE TITLE
DataGrid ColumnControl overlaps sort icon when no vertical scrollbox

### ISSUE THREAD

**Issue by weborld** [cuba-platform/cuba#2189]
Using the DataGrid control, the right-most column sorting icon is obscured and the sorting status cannot be seen. In addition, the sorting cannot be cancelled (the TABLE control point can cancel the sorting three times).

![111](https://user-images.githubusercontent.com/5875289/59406658-816be280-8de1-11e9-9d9b-0ed1f0866de9.png)

**Comment by glebfox** [comment]
> In addition, the sorting cannot be cancelled (the TABLE control point can cancel the sorting three times).

For the above, there is a separate issue https://github.com/cuba-platform/cuba/issues/369.

**Comment by glebfox** [comment]
Reproduces only if there is no scroll in DataGrid, otherwise, sort icon has a correct position:

![image](https://user-images.githubusercontent.com/6077149/60010728-6faff800-9689-11e9-9c9b-8488ca9ca147.png)

**Comment by glebfox** [comment]
Vaadin issue: https://github.com/vaadin/framework/issues/6894

**Comment by glebfox** [comment]
For QA:

- [ ] Change the `ColumnsControl` button visibility at runtime
- [ ] Make vertical scroll appear and disappear at runtime
- [ ] Check Mac OS with and without scrolls
