### ISSUE TITLE
Ability to specify custom values provider for the dynamic attributes

### ISSUE THREAD

**Issue by ovchinnikovsp** [cuba-platform/cuba#2191]
At the moment you can only use JPQL to filter the values and only for attrs with type Entity.

Need an ability to specify the custom values provider for any type of attribute. Values can be loaded by class, groovy or SQL script

**Comment by andreysubbotin** [comment]
- Calculated values and options tab added
- Here you can specify a script for loading options for a lookup field in the UI.
- Options loader is supported for Double, Integer, Fixed-Point number, String, Entity dynamic attributes types with enabled Lookup field checkbox 
- Options loader loads options using Groovy, SQL or JPQL (JPQL only for Entity type)

**Comment by natfirst** [comment]
1. Create Double/Integer/Fixed-Point number/String attribute 
2. Set Lookup field checkbox to true
3. Switch to Calculated values tab
4. Set Options type
Screen size will increase
5. Switch to another tab and back
Screen size will decrease
The same behavior is observed when Options type is changing
![calc](https://user-images.githubusercontent.com/17950251/63601749-160b7180-c5d7-11e9-975a-b6dc02a16328.gif)

**Comment by natfirst** [comment]
1. Create Entity  type attribute
2. Set Lookup field checkbox to true
In the old screen version Join end Where clause field will appear, but now they displayed in another tab

Add context help to the Lookup field with information about fields location

**Comment by natfirst** [comment]
- Add code highlighting to the `Options loader Script` field
![image](https://user-images.githubusercontent.com/17950251/63766493-51aa8200-c8dc-11e9-876a-cdfa22ebefff.png)
- Maybe, word `Script` in `Options loader Script` field caption should not be started with the capital letter

**Comment by natfirst** [comment]
1. Create Double/Integer/Fixed-Point number/String attribute
2. Set Lookup field checkbox to true
3. Switch to Calculated values tab
4. Set Options type to Groovy
`Options loader script` field with Context Help will be displayed
5. Change Options type to  SQL
 Context Help still be displayed
6. Click on the Context Help button
Nothing happens
7. Switch to another tab then go back to the Calculated values
 Context Help button will disappear
![image](https://user-images.githubusercontent.com/17950251/63768408-2ece9c80-c8e1-11e9-8186-cd80df21f8f1.png)

**Comment by natfirst** [comment]
Word `Type` in `Options Type` field caption should not be started with the capital letter
