### ISSUE TITLE
Cells with decimal type have an incorrect format in Excel

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#2195]
1) Create an Entity with the double or big decimal field
2) Create a few instances
3) Export to excel
4) Open this XLSX file in Microsoft Office

AR: Cells in the XLSX file interpreted as Custom format and it's unavailable to proceeding arithmetic operations

![Capture.PNG](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/3f548236-da3a-44bb-b9e4-15119de02629)

--- 

### Changes
Because of Excel shows comma even if no fraction part in decimal value we changed format of decimal cells to `#,##0.00##############`.
it will work with the following rules:
```
123     -> 123.00
123.1   -> 123.10
123.12  -> 123.12
123.123 -> 123.123

and etc
```

**Comment by Flaurite** [comment]
Related to: cuba-platform/cuba#2128
