### ISSUE TITLE
Notifications shows incorrectly on the tablet

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#220]
Notifications shows incorrectly on the tablet

![фото.PNG](https://images.zenhubusercontent.com/5ae3309c4b5806bc2bd0e8d8/358c1d43-3144-4109-ba52-813c6e2da301)

---
Original issue: https://youtrack.haulmont.com/issue/PL-7301

**Comment by jreznot** [comment]
It might be fixed with Vaadin 8
