### ISSUE TITLE
Invalid encoding of URI containing Cyrillic characters

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#2200]
### Environment

- Platform version: 6.10.10

### Description of the bug or enhancement

cuba 6.10.9 uses this library:
`httpclient-4.5.6-sources.jar!/org/apache/http/client/utils/URIUtils.java`

and 

cuba 6.10.10 uses this one:
`httpclient-4.5.8-sources.jar!/org/apache/http/client/utils/URIUtils.java`

They both implement `public static URI rewriteURI` in a different way - the old library (@line 129) behaves correctly and the new one (@line 171) renders an unusable path when the original URI contains Cyrillic.

This results in the following:

In case of cuba platform 6.10.10:
apache http-access log contains invalid url in the request:
```
192.168.55.1 -   gpetrov [17/Jun/2019:11:17:07 +0300] "MKCOL /remote.php/dav/files/blablabla%20%135%3E@38%20%1F%15%22%20%1E%12 HTTP/1.1" 400 417
```

and in case of cuba platform 6.10.9:
```
192.168.55.1 - gpetrov [17/Jun/2019:12:06:59 +0300] "MKCOL /remote.php/dav/files/blablabla%20%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%20%D0%9F%D0%95%D0%A2%D0%A0%D0%9E%D0%92 HTTP/1.1" 201 -
```

**Comment by dtsaryov** [comment]
`URIUtils` issue is reported: [Apache Jira](https://issues.apache.org/jira/browse/HTTPCLIENT-1996)

**Comment by dtsaryov** [comment]
Since 4.5.7 version of httpclient non-ASCII chars will not be handled to avoid later problems. It seems that we should encode names before.

**Comment by dtsaryov** [comment]
In all cases file names are encoded, so no problems should occur.
