### ISSUE TITLE
Repaint Filter layout when columns count is changed at runtime

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2203]
### Environment

- Platform version: 7.0+

### Description of the bug or enhancement

- Minimal reproducible example

1. Open a screen with a filter and `columnsCount=3`
2. Add several filter conditions (e.g. 3)
3. Change columns count to 1 (e.g. on button click)

- Expected behavior

Filter layout is repainted

- Actual behavior

Filter layout stays the same until conditions count is changed

**Comment by gorbunkov** [comment]
Forum topic: https://www.cuba-platform.ru/discuss/t/kak-obnovit-kolichestvo-kolonok-v-filtre/3168
