### ISSUE TITLE
Images with the same name are not displayed correctly

### ISSUE THREAD

**Issue by linkinek** [cuba-platform/cuba#2205]
### Environment

- Platform version: 6.20.8 
- Browser: Chrome
- Database: PostgreSQL
- Operating system: macOS

### Description of the bug or enhancement

If upload multiple images with same name, images displayed is same.
Gif:
![Запись экрана 2019-06-21 в 11 09 22 720 2019-06-21 12_12_11](https://user-images.githubusercontent.com/14567888/59908200-e648bd80-941d-11e9-856a-00fce7789c49.gif)

**Comment by knstvk** [comment]
Please provide a small test project we the issue is reproduced.

**Comment by GlebDurygin** [comment]
### QA
Check that in version 6.10.9 the above bug does not occur.
Relates to #1922
