### ISSUE TITLE
When trying to save an entity with a relation to another not persisted entity it leads to the wrong exception in terms of CUBA

### ISSUE THREAD

**Issue by aleksey-stukalov** [cuba-platform/cuba#2210]
The exception you get is:

IllegalStateException: During synchronization a new object was found through a relationship that was not marked cascade PERSIST: com.haulmont.cuba.core.entity.FileDescriptor-ba02c666-37b4-149f-dbbf-a0fe4a034afa [new].

However, CUBA doesn't support cascades.

**Comment by invviz** [comment]
Feature branch: https://github.com/cuba-platform/cuba/tree/feature/change_cascade_persist_error_message

**Comment by natfirst** [comment]
Use `not persisted` instead of `non persistent`.
