### ISSUE TITLE
Wrong ordering in database commit causes failure when committing entity containing inherited entity attribute

### ISSUE THREAD

**Issue by jacobmaxsmith** [cuba-platform/cuba#2211]
### Environment

- Platform version: 7.0.7
- Client type: Desktop
- Browser: Chrome, Firefox etc
- Database: PostgresSQL, HSQLDB, did not test with other types
- Operating system: Windows, Linux, did not test with other types

### Description of the bug or enhancement

- Minimal reproducible example
1. Create a new project
2. Add entity named Vegetable, set inheritance to JOINED
3. Add entity named Pumpkin, set parent entity to Vegetable
4. Add entity named Test, add one custom attribute: 1-to-1 association to Pumpkin
5. Create entity edit screen for Test entity
6. Add the following code to TestEdit controller:

    @Inject
    private DataContext dataContext;
    @Inject
    private Metadata metadata;

    @Subscribe
    private void onInitEntity(InitEntityEvent<Test> event) {
        Pumpkin pumpkin = dataContext.merge(metadata.create(Pumpkin.class));
        event.getEntity().setPumpkin(pumpkin);
    }

7. Run app, invoke screen and click OK

- Expected behavior
Test entity created, with attribute pumpkin pointing to Pumpkin entity

- Actual behavior
Error dialog shown with error message "SQLIntegrityConstraintViolationException: integrity constraint violation: foreign key no parent; FK_BUGTEST_TEST_ON_PUMPKIN table: BUGTEST_TEST" in HSQLDB

Similar error message when tested with Postgresql

app.log shows base class Vegetable inserted into database followed immediately by the Test entity. This is incorrect as the Pumpkin entity has not yet been created, Pumpkin should be inserted before Test uses it as a foreign key

Sanitized logs with noise removed:

com.haulmont.cuba.core.app.RdbmsStore - commit: commitInstances=
[com.company.bugtest.entity.Pumpkin-c9b446e0-94be-655
a-4176-37601c56f350 [new],
com.company.bugtest.entity.Test-efb92133-bb8f-6a7b-8b90-b6cb83e165c1 [new]], removeInstances=[]

INSERT INTO BUGTEST_VEGETABLE (ID, CREATE_TS, CREATED_BY, DELETE_TS
, DELETED_BY, UPDATE_TS, UPDATED_BY, VERSION, DTYPE) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [c9b446e0-94be-655a-4176-37601c56f350, 2019-06-25 09:26:31.701, admin, null, null, 2019-06-25 09:26:31.701, null, 1, bugtest_Pumpkin]

INSERT INTO BUGTEST_TEST (ID, CREATE_TS, CREATED_BY, DELETE_TS, DEL
ETED_BY, UPDATE_TS, UPDATED_BY, VERSION, PUMPKIN_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [efb92133-bb8f-6a7b-8b90-b6cb83e165c1, 2019-06-25 09:26:31.701, admin, null, null, 2019-06-25 09:26:31.701, null, 1, c9b446e0-94be-655a-4176-37601c56f350]

Exception: 
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.2-cuba): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: foreign key no parent; FK_BUGTEST_TEST_ON_PUMPKIN table: BUGTEST_TEST
Error Code: -177

**Comment by andreysubbotin** [comment]
Fixed in #293. Set `cuba.hasMultipleTableConstraintDependency` application property to true
