### ISSUE TITLE
Default screen can be closed after manually opening it from the menu

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba#2214]
### Environment

- Platform version: 7.0.8

### Description of the bug or enhancement

1. Create a new screen 
2. Add screen name to the `cuba.web.defaultScreenId` property
3. Add property `cuba.web.defaultScreenCanBeClosed = false`
4. Start project 
5. Open the added screen from the menu 

- Actual behavior
Default screen can be closed

**Comment by knstvk** [comment]
Why shouldn't it be closed in this case? I think it's fine.
