### ISSUE TITLE
AmazonS3FileStorage doesn't work if bucket name contains dots

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#2215]
If using the AmazonS3FileStorage and the bucket name contains dots, e.g. `test.bucket.com` then the exception occurs when accessing the s3 filestorage:
```
ava.security.cert.CertificateException: No subject alternative DNS name matching test.bucket.com.s3.amazonaws.com found.
at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:191) ~[na:1.8.0_25]
at sun.security.util.HostnameChecker.match(HostnameChecker.java:93) ~[na:1.8.0_25]
at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[na:1.8.0_25]
```

The `AmazonS3FileStorage` uses the path-style url to access the file in a bucket, i.e. `https://<bucketName>.s3.amazonaws.com/<filePath>`. If such form is used then AmazonS3FileStorage fails when the bucket name contains dots. If to use use the virtual-hosted url style: `https://s3.<region>.amazonaws.com/<bucketName>/<filePath>`. Then it works fine, I tested it with the following FileStorage implementation:

```java
public class MyAmazonS3FileStorage extends AmazonS3FileStorage {

    @Override
    protected URL getAmazonUrl(FileDescriptor fileDescr) {
        try {
            return new URL(String.format("https://s3.%s.amazonaws.com/%s/%s",
                    amazonS3Config.getRegionName(), amazonS3Config.getBucket(), resolveFileName(fileDescr)));
        } catch (MalformedURLException e) {
            throw new RuntimeException("Unable to parse service endpoint: " + e.getMessage());
        }
    }
}
```

Tested on CUBA version 7.0.7

**Comment by gglcrash** [comment]
Hi!

Amazon AWS has two URL forming styles - path-style and virtual-host style, for example:
path-style - `https://s3.amazonaws.com/<bucket-name>/<file-path>`,
virtual-hosted style - `https://<bucket-name>.s3.amazonaws.com/<file-path>`.
Right now virtual-hosted style is used in the AmazonS3FileStorage implementation.

According to the article (https://aws.amazon.com/ru/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/):
_Support for the path-style model continues for buckets created on or before September 30, 2020. Buckets created after that date must be referenced using the virtual-hosted model.
…
It is important to note that bucket names with “.” characters are perfectly valid for website hosting and other use cases. However, there are some known issues with TLS and with SSL certificates. We are hard at work on a plan to support virtual-host requests to these buckets, and will share the details well ahead of September 30, 2020._

Also, according to the current BucketRestrictions documentation (https://docs.aws.amazon.com/en_us/AmazonS3/latest/dev/BucketRestrictions.html), using dots in the bucket name is not recommended for virtual-hosted style:
_When you use virtual hosted–style buckets with Secure Sockets Layer (SSL), the SSL wildcard certificate only matches buckets that don't contain periods. To work around this, use HTTP or write your own certificate verification logic. We recommend that you do not use periods (".") in bucket names when using virtual hosted–style buckets._

It means that «java.security.cert.CertificateException» for bucket name with dots is known issue and it will be fixed on Amazon’s side not later than 30.09.2020.
