### ISSUE TITLE
Implement responsive layout for BulkEditor

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#222]
Implement responsive layout for BulkEditor with CssLayout:

1. 1-3 columns depending on window width
2. min/max sizes for UI fields
3. auto height for content
4. min / max sizes for window

### Changes
1. BulkEditorWindow supported only two responsive columns. **Default value is TWO_COLUMNS**;
2. BulkEditorWindow is resizable (vertical and horizontal);
3. New methods for setting number of columns.

New getter and setter for old component: `BulkEditor`:
```
ColumnsMode getColumnsMode()
setColumnsMode(ColumnsMode columnsMode)
```
Methods for `BulkEditors` builder:
```
withColumnsMode(ColumnsMode columnsMode)
ColumnsMode getColumnsMode()
```
New enum class `ColumnMode` with two values:
 * ColumnsMode#ONE_COLUMN;
 * ColumnsMode#TWO_COLUMNS;

New attribute for `bulkEditor` element:
```
<bulkEditor for="demoTable" columnsMode="ONE_COLUMN"/>
```

SCSS variables for responsive configuration:
1) $c-bulk-editor-label-min-width: 270px !default; - Defines min width of field caption.
2) $c-bulk-editor-label-max-width: 270px !default; - Defines max width of field caption.
3) $c-bulk-editor-label-width: 100% !default; - Defines width of field caption.
4) $c-bulk-editor-field-min-width: 240px !default; - Defines min width of field.
5) $c-bulk-editor-field-max-width: none !default; - Defines max width of field.
6) $c-bulk-editor-field-width: 100% !default; - Defines field width.

#### Declarative way
v7 screen layout:
```
<groupTable id="demoTable">
    <actions>
        ...
        <action id="bulkEditorAction" type="bulkEdit">
            <properties>
                <property name="columnsMode" value="ONE_COLUMN"/>
            </properties>
        </action>
    </actions>
    <columns> ... </columns>
    <buttonsPanel id="buttonsPanel"
                  alwaysVisible="true">
				  ...
        <button id="overBulkBtn" action="demoTable.bulkEditorAction"/>
    </buttonsPanel>
</groupTable>
```
Legacy screen layout:
```
<groupTable id="demoTable"
            width="100%">
    <actions>...</actions>
    <columns>...</columns>
    <buttonsPanel id="buttonsPanel"
                  alwaysVisible="true">
         ...
        <bulkEditor for="demoTable" columnsMode="ONE_COLUMN"/>
    </buttonsPanel>
</groupTable>
```
#### Usage in screen controller
```
@Inject
private BulkEditors bulkEditors;
@Inject
private GroupTable<Test> testsTable;

@Subscribe("testsTable.bulk")
public void onTestsTableBulk(Action.ActionPerformedEvent event) {
    bulkEditors.builder(metadata.getClassNN(Test.class), new HashSet<>(testsTable.getItems().getItems()), this)
            .withColumnsMode(bulkEditorColumnsField.getValue())
            .withExclude(excludeField.getValue())
            .create()
            .show();
}
```
![bulkedit](https://user-images.githubusercontent.com/22093943/68652948-0c453a80-0544-11ea-9cf5-4eb73142c51b.gif)

### For QA
1. Download attached project: [bulk-responsive.zip](https://github.com/cuba-platform/cuba/files/3835004/bulk-responsive.zip)
2. Check new property from XML layout (for legacy layout and v7) ;
3. Check new property form controller;
4. Check ONE_COLUMN and TWO_COLUMNS mode in all browsers (Chrome, Opera, Firefox, Edge, IE11, Safari);
5. Try to change scss variables. Make sure that they are worked.

**Comment by natfirst** [comment]
Change SCSS variable
`$c-bulk-editor-field-max-width: 250px;`
In Firefox, Edge, IE11, Safari
![bulk](https://user-images.githubusercontent.com/17950251/69138745-a5da9200-0ad8-11ea-8ac8-87d81a7529f8.gif)
