### ISSUE TITLE
Ability to declare view right in the screen descriptor

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#2225]
```
<data>       
    <instance id="productDc" class="com.company.Product">
        <view extends="_local">
            <property name="picture" view="_base"/>
        </view>
        <loader/>
     </instance>
</data>
```

**Comment by IskandarovRost** [comment]
Why the "name" property of the view is forbidden by XSD? It seems to work OK indeed.
![image](https://user-images.githubusercontent.com/19840141/68856131-34c26580-06f9-11ea-9b31-7516c6dfe384.png)

**Comment by web-devel** [comment]
Because it does not make sense to specify it as views defined in a screen are not loaded to the view repository
