### ISSUE TITLE
The platform incorrectly closes the screen after using the Close all and Close other commands

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba#2226]
Case 1

Create a new project
Open the first five screens in the administration menu
Open Roles tab
Start to create a new role
Enter a value in the Name field
Move the cursor to the Users tab and select Close other option
Actual behavior: Dynamic Attribute tab not closed

Case 2

Create a new project
Open the first five screens in the administration menu
Open Roles tab
Start to create a new role
Enter a value in the Name field
Move the cursor to the Users tab and select Close all option
Actual behavior: All tabs to the right of the Roles tab were not closed
Relates to: #1481

**Comment by dtsaryov** [comment]
It is a correct behavior - no fixes required
