### ISSUE TITLE
Desktop search field stops working after pressing ctrl+enter

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#223]
см патч к рефаппу 5.6

Application -> Drivers -> Create
Вводим что-нибудь в поле driver group, например "xx".
Нажимаем Ctrl+Enter.

Показываются уведомления. Поле ввода совсем перестает работать, не воспринимает ввод символов.

---
Original issue: https://youtrack.haulmont.com/issue/PL-7351

**Comment by jreznot** [comment]
Obsolete
