### ISSUE TITLE
Hide dynamic attibutes in categorized entity if they are not include in Category

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#224]
Сейчас если в какой либо категории создать динамический атрибут и привязать его например к экрану редактирования, то атрибут будет показываться в независимости от выбранной категории. Нужно подумать как отображать такие атрибуты для CategorizedEntity

---
Original issue: https://youtrack.haulmont.com/issue/PL-7359

**Comment by andreysubbotin** [comment]
Obsolete
