### ISSUE TITLE
Fix DataGrid vulnerability

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2240]
### Description of the bug or enhancement

**Unauthorized code execution**

Due to missing variable sanitation, the Grid Header Caption could be used to store malicious data and execute unwanted JavaScript in a user's browser e.g. when untrusted users are allowed to add new grid columns that are shown to other users. The vulnerability has been classified as Moderate.

The issue is fixed in the latest versions of the framework. All affected Vaadin versions should be updated to the latest maintenance release. The non-vulnerable versions of the framework are 8.8.5 and Vaadin 10+.

**Comment by jreznot** [comment]
https://github.com/cuba-platform/vaadin/commit/ffbf1b22900e5e4b76dc22e69334a9f6f44c72b3

It is kind of weird that we need to sanitize captions on Server. I'd better use `innerText` on client instead of JSoup on server.

**Comment by glebfox** [comment]
Hi, @jreznot!

Thank you for your comment. As you can see it's just back port of Vaadin fix as they themselves don't provide a proper fix for Vaadin 8.7 and older.
