### ISSUE TITLE
Search panel moves to the left if the filter does not fit on the screen

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba#2252]
### Environment

- Platform version: 7.1.0
- Web Browser: Chrome

### Description of the bug or enhancement

1. Create a new entity
2. Create a new Master-detail screen for the entity
3. Start application and open the screen
4. Add the three search condition

**Important:**

The problem can be reproduced for any screen. Resize a browser to reduce free space and then add conditions. In other words, total width of filter component should me small than total width of all added conditions

- Actual behavior
Search panel has moved to the left
![image](https://user-images.githubusercontent.com/24281695/60982286-df400b80-a348-11e9-8934-84f759536a0e.png)

**Comment by dtsaryov** [comment]
@Mihail063 please specify a browser when reporting UI bugs
