### ISSUE TITLE
Conflict between DesktopLookupField and its inner component - AutoCompleteSupport

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#226]
The result of method DesktopLookupField.restorePreviousItemText depends on setting new value into AutoCompleteSupport but behaviour of AutoCompleteSupport depends on boolean flag 'doNotChangeDocument' which setted as true for process of keyReleased or datasource updating. Accordingly, the behaviour of adding new option for DesktopLookupField is different beetween process of Enter key released and process of focus lost. It creates side-effects such as setting old value as text of component instead added value.

More information in related task.

---
Original issue: https://youtrack.haulmont.com/issue/PL-7374

**Comment by jreznot** [comment]
Obsolete
