### ISSUE TITLE
Add custom handlers for UserActionsButton

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#2260]
### Environment

- Platform version: 7.1
- Client type: Web

### Description of the bug or enhancement

Add an ability to set custom login / logout handlers for `UserActionsButton`:

```Java
userActionsButton.setLoginHandler(() -> {
    // do custom login
});
userActionsButton.setLogoutHandler(() -> {
    // do custom logout
});
```

### Updates

Two methods are added::

- `void setLoginHandler(Consumer<LoginHandlerContext> loginHandler)`
- `void setLogoutHandler(Consumer<LogoutHandlerContext> logoutHandler)`

They accept a consumer of Login/LogoutHandlerContext that has a reference to `source` - `UserActionsButton`

#### Main Screen

A new method is added:

`protected UserActionsButton getUserActionsButton()` - returns `UserActionsButton` instance or `null` if component is not present on a screen

**Comment by jreznot** [comment]
I'd better provide them as event listeners so they can be improved in the next versions of API.
Current Runnable approach is very limited and listeners cannot be used with `@Subscribe` although they are essentially are listeners.
