### ISSUE TITLE
Add property  to fetch the records count automatically  for Rowscount component 

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/cuba#2263]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

Please add a property for Rowscount component to make it fetch records count automatically.

Or provide a method that can be called to fetch the records count.

Discussion in forum:

https://www.cuba-platform.com/discuss/t/can-rowscount-component-fetch-the-records-count-automatically/9565

### Updates

New attribute `autoLoad` is added for `<rowsCount/>` element. It's enables to user manage whether rows count should be automatically loaded or not:

```XML
<rowsCount autoLoad="true"/>
```

This behavior can be also enabled or disabled via `RowsCount` API:

```Java
boolean autoLoadEnabled = rowsCount.getAutoLoad();
// disable auto load
rowsCount.setAutoLoad(false);
```

**Comment by alexbudarov** [comment]
in the background!
