### ISSUE TITLE
Standard "View" action for tables

### ISSUE THREAD

**Issue by Glasch** [cuba-platform/cuba#2270]
It is a very frequent case that we need to open an "editor" screen in read-only mode just to view data. Currently this requires custom coding in screen controller, or creating a separate screen.

It will be very convenient to have a standard "View" action which would open a screen in read-only mode.

**Comment by knstvk** [comment]
Also, consider an action that switches from the read-only mode to edit mode without reopening the screen.

**Comment by glebfox** [comment]
The `ViewAction` opens an entity editor screen in the read-only mode.

The following components and actions change their state:
* All `Editable` components that has a not null `ValueSource`
* All `Action.DisabledWhenScreenReadOnly` (`CreateAction`, `EditAction`, `RemoveAction`, `AddAction`, `ExcludeAction`) actions obtained from `ActionsHolder` components
* All own screen actions except `EditorScreen#WINDOW_CLOSE` and `EditorScreen#ENABLE_EDITING`

**Comment by glebfox** [comment]
```
GuiDevelopmentException: Can't find action enableEditing

Frame ID: procDefinitionDeploy
XML descriptor: com/haulmont/bpm/gui/procdefinition/proc-definition-deploy.xml
```

**Comment by glebfox** [comment]
Edit screens can contain a button with the new `enableEditing` action that makes an editor editable again:

```
<hbox id="editActions"
      spacing="true">
    ...
    <button action="enableEditing"/>
</hbox>
```

![Screenshot 2019-11-29 at 16 31 16](https://user-images.githubusercontent.com/6077149/69869243-b43d6080-12c5-11ea-85c2-482ce89594f7.png)
