### ISSUE TITLE
Wrong @Subscribe target if column name and action id are equal

### ISSUE THREAD

**Issue by glaschenko** [cuba-platform/cuba#2272]
As result, action handler tries to subscribe to column, causing an error. See the image.

![image](https://user-images.githubusercontent.com/17944806/61274806-93b0b600-a7bd-11e9-8a76-6bff1f1272d5.png)

**Comment by aleksey-stukalov** [comment]
From my perspective, this behaviour is absolutely correct, ids are unique names of screen elements. It looks like the only thing is missing is an inspection in Studio.

**Comment by glaschenko** [comment]
Then it should at least a ticket in Studio. Current behaviour is misleading.
