### ISSUE TITLE
Different spacings are used in Form and vbox

### ISSUE THREAD

**Issue by glaschenko** [cuba-platform/cuba#2274]
As result, it is impossible to align them on one screen, see image below.
Form is on the left, vbox on the right.

![image](https://user-images.githubusercontent.com/17944806/61278237-dcb83880-a7c4-11e9-83bd-d32aa9a28a2b.png)

**Comment by glebfox** [comment]
When `captionPossition="TOP"` spacing are the same as for `Grid` and `VBoxLayout` components with `spacing="true"`. When `captionPossition="LEFT"` (by default) spacing remains untouched (i.e. the half of the default value) because it's by design.

**Comment by knstvk** [comment]
So what developer should do to have components aligned in the given case?

**Comment by glebfox** [comment]
> So what developer should do to have components aligned in the given case?

Create a theme extension and set desired spacing for Form inline mode (i.e. `captionPosition="LEFT"`), e.g.

```
.#{$primary-stylename}-inline-caption .#{$primary-stylename}-spacing-on {
  padding-top: $v-layout-spacing-vertical;
}
```
