### ISSUE TITLE
TextField does not consider Double.NaN 

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#2280]
A topic on support forum: [link](https://www.cuba-platform.com/discuss/t/textfield-does-not-handle-nan-correctly/9621)

### Environment

- Platform version: 6.10
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example

```XML
<textField id="testTf" datatype="double"/>
```

```Java
testTf.setValue(Double.NaN);
```

- Expected behavior

Probably we should reduce it to zero or null

- Actual behavior

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/5cbcaf17-a201-4aea-b0a5-407ad741f69f)

Vaadin field is empty when NaN is set to it

## Updates

The Textfield is empty when NaN is set to it.

## QA

Check the above case.

**Comment by BryanYin** [comment]
@dtsaryov May I know how you going to fix this? I don't think show "NaN" or "null" is something understandable to end user. please consider this suggestion.
