### ISSUE TITLE
Search by attribute "desc" in gui results in exception

### ISSUE THREAD

**Issue by jacobmaxsmith** [cuba-platform/cuba#2282]
### Environment

- Platform version: 7.0.9
- Client type: Desktop
- Browser: Chrome, Internet Explorer, Firefox
- Database: Postgresql, HSQL
- Operating system: Windows, Linux

### Description of the bug or enhancement

- Minimal reproducible example

1. Create an entity with attribute named "desc"
2. Create a generic browse screen
3. Go to browse screen and search by "desc" attribute with "contains" operator

- Expected behavior

All applicable matches shown in listing

- Actual behavior

Exception dialog box shown:

JpqlSyntaxException: Errors found for input jpql:[where e.desc like :filter_desc23841 ESCAPE '\']
CommonErrorNode [<unexpected: [@3,7:7='.',<68>,1:7], resync=e.desc like :filter_desc23841 ESCAPE '\'>]

**Comment by invviz** [comment]
Feature branch: https://github.com/cuba-platform/cuba/tree/feature/search_by_attribute_desc
