### ISSUE TITLE
Simplify creating multi-tenant applications

### ISSUE THREAD

**Issue by aleksey-stukalov** [cuba-platform/cuba#2284]
1. Add string attribute to identify a tenant in each platform entity.
2. Add some marker for an entity to manage queries
3. Add some interface to resolve tenant identifier in runtime (from user session, security and so on)
4. Automatically handle tenant identifier on reading and writing operations

**Comment by NikitaShchienko** [comment]
### Changes:
#### Platform
- HasTenant and HasTenantInstance interfaces are portable to the platform.
- In all entities of the platform add the field "tenantId" with the annotation @SystemLevel.
- We transfer the logic of reading and writing the field "tenantId" to the platform.
- The user entity will have a composite login of "tenantId" and "login".

#### Multitenancy:
- Remove the annotation @TenantId.
- In the addon leave the UI addon.
- Add URL parameter "tenantId" for user authentication.

#### Rest API:
- Add optional tenantId parameter for user authentication.
