### ISSUE TITLE
Application hangs after search folder import

### ISSUE THREAD

**Issue by daring2** [cuba-platform/cuba#2286]
### Environment

- Platform version: 7.0.9
- Client type: Web

### Description of the bug or enhancement

The problem could be reproduced in project [sample-library-cuba7](https://github.com/daring2/sample-library-cuba7).
Steps to reproduce:
1. open Books screen
2. create two search folders test1, test2 usgin "Add to set" action
3. select and export folder test1
4. select folder test1 and import arhive Folders.zip created on the previous step

Actual behavior:
Application hangs. Also the application hangs on subsequent login attempts of the current user.

It looks like the import procedure creates an invalid SearchFolder object that contains self reference in the "parent" attribute.

**Comment by Mihail063** [comment]
The problem could be reproduced in project [sample-library-cuba7](https://github.com/daring2/sample-library-cuba7)
Platform version: 7.0.10
Steps to reproduce:
1. Open Books screen
2. Create two search folders test1, test2 usgin "Add to set" action
3. Select and export folder test1 
4. Select and export folder test2
5. Select folder test1 and import archive Folders(1).zip (archive with test2 folder)
6. Select folder test2 and import archive Folders.zip (archive with test1 folder)

Actual behavior:
Application hangs. Also, the application hangs on subsequent login attempts of the current user.
