### ISSUE TITLE
SplitPanel dock button is misplaced when shown in dialog

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#2287]
A topic on support forum: [link](https://www.cuba-platform.com/discuss/t/the-dock-function-of-splitpanel-has-some-problems/9623)

### Environment

- Platform version: 7.0
- Client type: Web

### Description of the bug or enhancement

- Minimal reproducible example

1. Create a screen with dockable split panel
2. Show the newly created screen as dialog

- Expected behavior

Dock button is shown and its functionality is available

- Actual behavior

Dock button is outside of the dialog box

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/ec36a66a-01ee-49d7-b1a5-770839f31dcf)

## Updates
The dock button doesn't use the Vaadin Overlay widget, now button is located inside the `splitPanel` div.
```
<div class="v-splitpanel-horizontal">
    <div>
        <div class="v-splitpanel-first-container"/>
        <div class="v-splitpanel-hsplitter"/>
        <div class="v-splitpanel-second-container"/>
        <div class="c-splitpanel-dock-left"/>
    </div>
</div>
```

### Test project
[splitpanel-dock-button.zip](https://github.com/cuba-platform/cuba/files/3460990/splitpanel-dock-button.zip)

## QA
Check that dock button is displayed correctly when opening the screen in a new tab and in the dialog mode.

**Comment by Mihail063** [comment]
Platform version: 7.0+
Case 1 

1. Create a new screen with SplitPanel in dialog mode
2. Add `dockMode="RIGHT"` and `dockable="true"` for the SplitPanel
3. Start the project
4. Open the added screen from the previous step
5. Press to the SplitPanel dock button

Actual behavior
Dock button displays incorrectly
![image](https://user-images.githubusercontent.com/24281695/62539175-a4f15d80-b865-11e9-9436-6a724de5283c.png)

Platform version: 7.1+
Case 2 

1. Create a new screen with SplitPanel
2. Add `dockMode="RIGHT"` and `dockable="true"` for the SplitPanel
3. Start the project
4. Open the added screen from the previous step
5. Press to the SplitPanel dock button

Actual behavior
Dock button displays incorrectly
![image](https://user-images.githubusercontent.com/24281695/62540596-0666fb80-b869-11e9-82a9-8f45c142a479.png)

Platform version: 7.0+
Case 3 

1. Open the test project from the issue and start it
2. Open the screen
3. Change dockable SplitPanel

Actual behavior
Scroll bar appears after the programmatically changes the dockable SplitPanel property.

Also, scroll bar appears after programmatically changes dockMode SplitPanel property.

**Comment by GlebDurygin** [comment]
Fix incorrect display of the dock button in the right dock mode
