### ISSUE TITLE
Filter component's add search condition action is too slow

### ISSUE THREAD

**Issue by dkz** [cuba-platform/cuba#2292]
### Environment

- Platform version: 6.8.18

### Description of the bug or enhancement

Add search condition action takes up to 20 seconds before showing an ''Add condition'' window. The issue is related to the complexity of the entity graph, i.e. entity is providing approx. one thousand attributes available as conditions on ''Add condition'' window.

The first proposal is to optimize `ConditionDescriptorsTreeBuilder` which is the cause of major time consumption: one property attribute requires almost 20-30ms to prepare, while entity relationships consume at least 200ms each, that sums to 2-5secs even for average entity.

The second proposal is to show a progress bar or loading indicator, because it seems like execution on desktop client is handled in the UI thread and desktop client freezes for a considerable period of time before ''Add condition'' is shown.

**Comment by andreysubbotin** [comment]
+ CUBA 5.9
