### ISSUE TITLE
Add ability to register entity as modified in DataContext

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2295]
### Description of the bug or enhancement
Old datasources API supported the following trick:
```
((DatasourceImplementation) entityDs).modified(entity);
```
It could be used to manually mark entity as modified, e.g. if its modified state is located in non-persistent fields.

If I am not wrong, com.haulmont.cuba.gui.model.DataContext does not have analogue of that method. When we had CUBA 7 demo, it was noted (by Eugene) that this method may be useful and can be added to new API.

**Comment by knstvk** [comment]
See also [forum topic](https://www.cuba-platform.com/discuss/t/how-to-make-screen-aware-data-change-of-a-json-type-in-postgresql/9715).
