### ISSUE TITLE
Buggy dialog layout (expand form to a AUTO height layout)

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2302]
### Environment
- Platform version: 7.0.9
- Browser: Chrome

### Description of the bug or enhancement
Test project attached.  [formdialog.zip](https://github.com/cuba-platform/cuba/files/3450431/formdialog.zip)

Create simple dialog with the following layout:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd"
        caption="msg://caption"
        messagesPack="com.company.formdialog.web">
    <dialogMode forceDialog="true" width="AUTO" height="AUTO"/>
    <layout expand="form">
        <form id="form">
            <textField caption="Caption"/>
            <textField caption="Price"/>
        </form>
        <hbox spacing="true">
            <button caption="OK"/>
            <button caption="Cancel" invoke="closeMe"/>
        </hbox>
    </layout>
</window>

```
There are some conflicting options (layout expands a form but has AUTO height).
Result in the browser is the following:
![image](https://user-images.githubusercontent.com/6158807/62193864-b7f9be80-b389-11e9-86a5-3f1f6f7f0ec2.png)

**Comment by glebfox** [comment]
@alexbudarov, the problem is that you `expand="form"`. In case of `height="AUTO"` it is incorrect.

The following code produces correct result:
```
<layout spacing="true">
    <form id="form">
        <textField caption="Caption"/>
        <textField caption="Price"/>
    </form>
    <hbox spacing="true">
        <button caption="OK"/>
        <button caption="Cancel" invoke="closeMe"/>
    </hbox>
</layout>
```

![Screenshot 2019-08-07 at 16 17 08](https://user-images.githubusercontent.com/6077149/62622202-d4b86800-b92e-11e9-9965-22cb338a15fa.png)
