### ISSUE TITLE
Impossible to use sorting in nested datasources if @Composition field is marked as Set

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#231]
If entity has a @Composition field with type {{Set}}, then related entities listed in a UI table component (for instance on editor screen) cannot be sorted, and there is no workaround except changing the type (which is not convenient or even impossible when entity has third-party roots).

---
Original issue: https://youtrack.haulmont.com/issue/PL-7479

**Comment by knstvk** [comment]
Will be fixed in #474
