### ISSUE TITLE
Problems with removing newly created elements of composition

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2311]
#### Environment

- Platform version: 6.5.7

### Description of the bug or enhancement
- Create 2 level composition (Airport, Terminal, MeetingPoint)
- Run the app
- Create new Airport, add Terminal, add several Meeting Points to Terminal
- Delete one of the meeting points
- Save all changes
- Open Airport for editing

*A.R.* All meeting points will be displayed in Terminal
*E.R.* Deleted meeting point should not be saved

[test project](https://app.zenhub.com/files/54624511/4582ee74-50f9-455b-96e5-dd19b039f195/download)

**Comment by knstvk** [comment]
Is it reproduced on 6.10?

**Comment by knstvk** [comment]
Reproduced on 7.0.9.

Refapp -> Cars v7

### Case 1

- Create and save Car
- Create Repair
- Create Token
- Click OK in Repair
- Edit the Repair, remove the Token, click OK
- Save and close Car
- Edit Car, open Repair

ER: there is no created/removed Token
AR: the Token is there

### Case 2

- Create and save Car
- Create Repair
- Create Token
- Click OK in Repair
- Remove the Repair
- Click OK in Car

ER: the Car is saved without created/removed Repair and Token
AR: IllegalStateException: During synchronization a new object was found through a relationship that was not marked cascade PERSIST: com.haulmont.refapp.core.entity.Repair-ebf2838c-0a6d-ed27-44d2-71df444a5b57 [new].
