### ISSUE TITLE
Support for Kotlin

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#2312]

**Comment by yeras-is** [comment]
any news?

**Comment by alexander-shustanov** [comment]
1. Provide nullability info with JSR 305
2. Add some extension functions such as `fun <reified T:Entity> Metadata.create(): T`
3. Add some kotlin-style DSLs for example, for DataLoader, ViewBuilder etc

**Comment by aleksey-stukalov** [comment]
- Add a reference to KProperty in ItemPropertyChangeEvent and in similar places
- Add backing fields for setters of height and width in UI components
