### ISSUE TITLE
Ability to pass URL parameters to a custom login screen

### ISSUE THREAD

**Issue by pavel-grigorev** [cuba-platform/cuba#2318]
### Environment

- Platform version: 7.1.0.BETA1
- Client type: Web

### Description of the bug or enhancement

Could you add an ability to pass URL parameters to a custom login screen and then catch UrlParamsChangedEvent events?

**Comment by dtsaryov** [comment]
Hello @pavel-grigorev 

No additional changes required to do it:

```Java
@UiController("login")
@UiDescriptor("ext-login-screen.xml")
public class ExtLoginScreen extends LoginScreen {

    @Subscribe
    private void onUrlParamsChanged(UrlParamsChangedEvent event) {
        Map<String, String> urlParams = event.getParams();
        if (MapUtils.isNotEmpty(urlParams)) {
            String paramsString = urlParams.entrySet().stream()
                    .map(this::paramToString)
                    .collect(Collectors.joining(", "));

            notifications.create(Notifications.NotificationType.HUMANIZED)
                    .withCaption("URL Params Passed:")
                    .withDescription(paramsString)
                    .show();
        }
    }

    private String paramToString(Map.Entry<String, String> entry) {
        return entry.getKey() + " = " + entry.getValue();
    }
}
```

Sample project:
[login-screen-params.zip](https://github.com/cuba-platform/cuba/files/3471491/login-screen-params.zip)

The only thing that seems working wrong is that params are removed from URL when screen is opened. Probably we should fix it

**Comment by pavel-grigorev** [comment]
Hey @dtsaryov thanks for the sample project, it helped!

The issue was that I extended the Screen class. After changing the base class to LoginScreen it started catching the URL events.

The only thing that's inconvenient is that you have to explicitly override the standard login form. Consider making it work with the basic Screen class?
