### ISSUE TITLE
Support for custom logback.xml in the project

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2319]
## Problem

Currently there is no standard way to override logback.xml in the project.
Developer has to write his/her own code in build.gradle in order to utilize it.

We need a unified approach:
- where to put logback.xml in the project
- copy it to development tomcat when deploying the project
- copy it to production artifacts such as war or uberJar

## Solution

- Introduced `LogbackConfigurator` that hooks into Logback initialization [procedure](https://logback.qos.ch/manual/configuration.html#auto_configuration) as an implementation of `Configurator`. This configurator performs the following steps to find a source of configuration:
    1. Looks for `logback.xml` in `${app.home}` directory. 
    2. If not found, looks for `app-logback.xml` on classpath root. 
    3. If nothing found, performs basic configuration: output to console with WARN threshold.

    Keep in mind, that this procedure comes into play only if no `logback.xml` is found on the classpath.

- `setupTomcat` task creates `logback.xml` in `deploy/app_home` directory, which means that any development environment gets a default logback config writing logs to `deploy/app_home/logs` directory.

- `deploy` task copies `etc/logback.xml` project file (if it exists) to `deploy/app_home`, so the initialization procedure explained above takes it on the first step.

    So developers can create and customize the logback config in the project and it will be used automatically in development Tomcat.

- `buildWar` and `buildUberJar` tasks can create `app-logback.xml` in classpath root (which is `/WEB-INF/classes` for WAR and `/` for UberJAR) from one of the following source files:
    - From `logbackConfigurationFile` parameter if it is specified.
    - From `logback.xml` in cuba-gradle-plugin if `useDefaultLogbackConfiguration` parameter is set to true (which is default).
    If `logbackConfigurationFile` is not specified and `useDefaultLogbackConfiguration` is set to false, no logback config is created in the archive.

    Due to `LogbackConfigurator` initialization procedure and provided that there is no `logback.xml` in the classpath root, the configuration embedded into WAR/UberJAR can be overridden by `logback.xml` file in the `${app.home}` directory. It enables customization of logging in production environment without rebuilding WAR/UberJAR.

**Comment by belyaev-andrey** [comment]
Please, note that logDir generation is not implemented correctly now:
```
<configuration debug="false">
    <property name="logDir" value="../app_home/logs"/>
```

And we need it to be
```
    <property name="logDir" value="${app.home}/logs"/>
```

**Comment by knstvk** [comment]
To QA:
- Test together with cuba-platform/cuba-gradle-plugin#114
- Create own config in  `etc/logback.xml` - it must be copied to `deploy/app_home/logback.xml` and used by dev Tomcat
- Try to change logs location in `etc/logback.xml`
- Play with different values for `logbackConfigurationFile` and `useDefaultLogbackConfiguration` and run WAR/UberJAR on different OS.
