### ISSUE TITLE
Update jgroups to a modern version

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2325]
### Description of the bug or enhancement
Current version is 3.6.x.

Recent version is 4.1.x (released in May 2019). 
Or at least 4.0.x (4.0 released in 2017).

As a motivation, in recent releases you can notice some improvements and fixes for cloud environments:
http://belaban.blogspot.com/2019/01/jgroups-4016.html
http://belaban.blogspot.com/2019/02/and-4017.html

**Comment by andreysubbotin** [comment]
For UDP configuration replace:
`MERGE2` with `MERGE3`
`pbcast.NAKACK` with `pbcast.NAKACK2` and remove `retransmit_timeout` property
`UNICAST` with `UNICAST3`
`FC` with `MFC`

For TCP configuration replace:

**Comment by andreysubbotin** [comment]
For QA: smoke test cluster (for example user session replication)
