### ISSUE TITLE
Execute DDL scripts for additional data stores

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#2332]
- Design file structure for DDL scripts
- Implement execution of scripts on the app startup depending on some conditions

Relates to [Studio issue](https://youtrack.cuba-platform.com/issue/STUDIO-4835).

**Comment by andreysubbotin** [comment]
Awaiting for [Studio issue](https://youtrack.cuba-platform.com/issue/STUDIO-4835).
