### ISSUE TITLE
Add LocalDate(Time) parameter for InputDialog

### ISSUE THREAD

**Issue by aleksey-stukalov** [cuba-platform/cuba#2345]
Platform Version 7.1

## Updates
The `InputParameter` has new predefined static  methods for date and time Datatypes:
* `localDateParameter`
* `localDateTimeParameter`
* `localTimeParameter`
* `offsetDateTimeParameter`
* `offsetTimeParameter`

**Comment by GlebDurygin** [comment]
Relates to #1831
