### ISSUE TITLE
Support columns count configuration for BulkEditors

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#2355]
### Environment

- Platform version: 7.2+

### Description of the bug or enhancement

It would be nice to have an ability to specify a count of BulkEditor columns when the editor is opened via `BulkEditors` bean.

## Updates
The component `BulkEditor` has the ability to specify the number of editor columns.
The `BulkEditor` has two new methods to get/set the number of editor columns:
* `int getColumns()` - returns the number of editor columns;
* `setColumns(int columns)` - sets the number of editor columns.

Also, the `BulkEditors` bean has two new methods:
* `withColumns(Integer columns)` - sets the number of editor columns;
* `Integer getColumns()` - returns the number of editor columns;

User can set the number of editor columns using a component API or specifying a value in XML descriptor. The default number of editor columns is two.

### Test project
[bulkeditor-columns.zip](https://github.com/cuba-platform/cuba/files/3559296/bulkeditor-columns.zip)

## QA
* Check attribute `columns` setting using a component API or specifying a value in XML descriptor.
* Check attribute `columns` setting using a `BulkEditors` bean.

**Comment by Flaurite** [comment]
Since responsive bulkEditor supports only two columns it was decided to change `setColumns()` methods to setter with enum. See https://github.com/cuba-platform/cuba/issues/222.
