### ISSUE TITLE
Vertically misaligned icons on Chrome, havana theme

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2362]
### Environment
- Platform version: 7.1.0.BETA3
- Browser: Chrome Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

### Description of the bug or enhancement
- Create new project based on CUBA 7.1.0.BETA3
- Launch
- Change theme in settings to havana
- Open users browser.

On Firefox icons are valigned normally.
On Chrome you see this:
![image](https://user-images.githubusercontent.com/6158807/63430714-4f54ad80-c42e-11e9-90df-c08209041890.png)

All button's icons have bad vertical alignment.

## Updates
The icons, such as images, for buttons have fixed width and height defined in styles.
```
img.v-icon {
  height: round($v-unit-size/2);
  width: round($v-unit-size/2);
}
```
## QA
Check that icons for buttons in Havana theme displayed correctly.

**Comment by sukhova** [comment]
Icons have become too small:
![321](https://user-images.githubusercontent.com/40686909/63846431-d65cd500-c99c-11e9-8249-9bd63700d63d.png)

**Comment by GlebDurygin** [comment]
Fix icons position for buttons on Chrome, Havana theme. The icons have the same size as before the changes.
