### ISSUE TITLE
Help to troubleshoot problems with web module not able to connect to core

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2377]
### Description of the bug or enhancement
Often newbie developers meet problems with *-core services not properly registed / found when they deploy applications: single-war, separate wars, fast deployment tomcat etc.

Some forum topics:
1)
https://www.cuba-platform.com/discuss/t/no-mapping-found-for-http-request-with-2-war-files-deploy/9950
```
2019-08-21 14:38:34.072 WARN  [http-nio-9191-exec-113] 
org.springframework.web.servlet.PageNotFound -
 No mapping found for HTTP request with URI [/adaptivego-core/remoting/cuba_TrustedClientService] in DispatcherServlet with name 'remoting'
```
Probably separate WARs, remote server invocation.

2) 
https://www.cuba-platform.com/discuss/t/unable-to-login-as-anonymous-on-tomcat-8-5/9057/6
```
Caused by: java.lang.IllegalArgumentException: 
Service app/cuba_TrustedClientService is not registered in LocalServiceDirectory
```
Single war in tomcat.

### What we can do
1) Analyze previous problems, e.g. in forum. Find the most common reasons (missed ports, forgotten app properties).
Try to reproduce them on local environment.

2) Log debug information on server start or when web layer fails to find registered core services.
Even if not noticed by developers, it can be used to quickly understand what's wrong with settings.

3) Improve documentation on this matter.

**Comment by knstvk** [comment]
To QA:
- Test different deployment options. When web client cannot connect to core, the page with the description must be shown:
![image](https://user-images.githubusercontent.com/5513878/65487003-f9ed3f80-deb6-11e9-8edc-4cfaa93ae1b1.png)
- If `cuba.web.productionMode = true`, the old page with "Please contact system administrator" is shown.
