### ISSUE TITLE
Captions with spaces display in two lines due to multiline property

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2379]
### Environment

- Platform version: 7.1

### Description of the bug or enhancement

- Open dynamic attribute editor for the first time, field captions will be placed  in two lines 
![image](https://user-images.githubusercontent.com/17950251/63751846-33835880-c8c1-11e9-8d1d-3fa6b23fdf92.png)
- Switch between tabs and return to the General.
Captions will be in one line
![image](https://user-images.githubusercontent.com/17950251/63753148-8e1db400-c8c3-11e9-8711-146762769d78.png)

**Comment by knstvk** [comment]
Relates to #2380

**Comment by glebfox** [comment]
The problem isn't related to dynamic attribute editor. In some cases, e.g. by changing CheckBox 'captionManagedByLayout' attribute or custom FieldGroup fields, a slot has no Caption at first iteration of 'maxCaptionWidth' calculation, as the result, for the second and so forth iterations, when the rest of components get their captions, 'caption.getRenderedWidth()' returns an incorrect value.
