### ISSUE TITLE
Health Check URL doesn't work if no REST API included

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2384]
### Environment

- Platform version: 7.1-SNAPSHOT

### Description of the bug or enhancement

- Minimal reproducible example

1. Create a new application with no REST API app component
2. Start the app
3. Open the Health Check URL ( see https://doc.cuba-platform.com/manual-7.1/health_check_url.html)

- Expected behavior

OK

- Actual behavior

Redirected to `main` 

Caused by: https://github.com/cuba-platform/cuba/issues/630

**Comment by knstvk** [comment]
See the updated [docs](https://doc.cuba-platform.com/manual-7.1/health_check_url.html)
