### ISSUE TITLE
Fine-looking annotation or attribute to disable DDL generation in Studio

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2385]
### Description of the bug or enhancement
Requested by Alexey.

Currently "Enable DDL generation" checkbox in Studio Entity Designer creates this code:
```
@DesignSupport("{'generateDdl':false}")
...
public class Bar extends StandardEntity {

```

It does not look pretty and hard to write by hand (e.g. if you don't have subscription).

Suggestion:
Create another annotation (or maybe add attribute to existing one) to disable DDL generation for particular entity by Studio.

**Comment by alexbudarov** [comment]
```
@DDL(generate = false)
```
In the future can add more attributes

**Comment by aleksey-stukalov** [comment]
Support @alexbudarov. Also generate the `value` alias for the `autogenerate` property. The default value is true.

**Comment by knstvk** [comment]
Unfortunately, we already have `com.haulmont.chile.core.annotations.Ddl` annotation which is used on Datatype classes. 
Any other ideas?

**Comment by alexbudarov** [comment]
> @DdlGeneration(enabled = false)

or
> @DbSchemaManagement(enabled = false)

**Comment by knstvk** [comment]
I'm for `@DdlGeneration(enabled = false)`

**Comment by aleksey-stukalov** [comment]
`@DdlGeneration(enabled = false)` sounds good to me
