### ISSUE TITLE
executeUpdate() method does not work in EntityManager on MySQL

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/cuba#2387]
### Environment

- Platform version: 7.0.10
- Database: MySQL

### Description of the bug or enhancement

`executeUpdate()` method does not work in `EntityManager` bean. It happens when Eclipse link trying to create a temporary table with `TL_` prefix. This table creating with incorrect `ID` column type, `UUID` instead of ` varchar(32)`.

**Comment by gorbunkov** [comment]
The error appears when the "update" statement contains a subquery, e.g.:
```java
    @Test
    public void testUpdate() {
        try (Transaction tx = persistence.createTransaction()) {
            EntityManager em = persistence.getEntityManager();
            em.createQuery("update sec$User u set u.lastName = 'Bob' where u.group.id = " +
                    "(select g.id from sec$Group g where g.name = :groupName)")
                    .setParameter("groupName", "Company")
                    .executeUpdate();
            tx.commit();
        }
    }
```
