### ISSUE TITLE
Entered text disappears from DesktopLookupField after moving focus to another application

### ISSUE THREAD

**Issue by leonnash23** [cuba-platform/cuba#2391]
### Environment

- Platform version: 6.9.11
- Client type: Desktop, Web
- Operating system: Windows

### Description of the bug or enhancement

- [TestLookup.zip](https://github.com/cuba-platform/cuba/files/3554463/TestLookup.zip)
Start the desktop application, then open the last item of the application menu. You will see one LookupField. Start writing anything, then move focus to another application. When you return focus to the application - entered text will disappear.
Also attached the video from our customer.
[Missing email 1.zip](https://github.com/cuba-platform/cuba/files/3554509/Missing.email.1.zip)

- EB:
Entered text doesn't disappear. In Option Handler work properly.
- AB:
Entered text disappear. In Option Handler doesn't call.

**Comment by leonnash23** [comment]
It turned out that the same problem on the web

**Comment by knstvk** [comment]
@leonnash23 What do you mean by "Option Handler"?

**Comment by leonnash23** [comment]
@knstvk I mean NewOptionHandler

**Comment by knstvk** [comment]
If value does not match an option, it cannot be set and is erased on focus lost. We cannot change this behavior.

**Comment by leonnash23** [comment]
@knstvk 
If focus moved within the application then NewOptionHolder will be called
But if the focus moved to another application, then entered text will be lost

In the attached example, if you enter some text and then move focus within the application you will see a notification with the entered text. But it won't happen if you move focus out of the application.

**Comment by knstvk** [comment]
Anyway, why it is important? How many users are affected, in what use cases?
