### ISSUE TITLE
Incorrect display of windows when clicking on elements of the Analytics component

### ISSUE THREAD

**Issue by MaxKatyshev** [cuba-platform/cuba#2396]
### Environment

- Platform version: 7.0 
- Client type: Web 
- Browser: Chrome, IE, Firefox, Safari 
- Database: 
- Operating system: Windows, macOS 

### Description of the bug or enhancement

- Incorrect display of windows when clicking on elements of the Analytics component (see gif)

**Comment by glebfox** [comment]
Hi, @MaxKatyshev!

Due to the fact that CUBA PivotTable is based on the external JavaScript library - https://github.com/nicolaskruchten/pivottable, the described issue isn't related to CUBA, hence can't be fixed.
