### ISSUE TITLE
Add application.logoLabel to default generated message bundle

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#2398]
It would be nice to be able to change an application's logo label in addition to other messages exposed by default.

Even if we extend the main window, these properties are not available for changes by default.

Now we have:
```
application.caption=CUBA Application
application.logoImage=branding/app-icon-menu.png
```
It would be nice to have the following properties exposed publicly:
```
application.caption=CUBA Application
application.logoLabel=CUBA Application
application.logoImage=branding/app-icon-menu.png
application.welcomeText=Welcome to CUBA Application!
```

**Comment by GlebDurygin** [comment]
I have created issue for CUBA Studio: https://youtrack.cuba-platform.com/issue/STUDIO-6772
