### ISSUE TITLE
User-friendly handling of optimistic lock exceptions

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#2429]
## Problem
Currently when optimistic lock occurs the following notification is being shown:
![image](https://user-images.githubusercontent.com/3295727/64821121-0f16c400-d5c3-11e9-9bf6-ad3925ba8bee.png)
For end users it looks like an error in application and it's not clear what to do next. However it is correct use case.

## Solution
- Provide user-friendly message i.e.
> It's not possible to commit changes since edited entity has just been changed by another user or by the system. In order to avoid conflicts or loss of data please reopen the screen and reapply your changes.

- (TBD) Provide the reload button straight in the error dialog

## Updates
The optimistic lock exception message is displayed like this:
* **English locale**
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/c76296ca-602a-46ef-95fb-9f1a20078896)
* **Russian locale**
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/4c13fe7d-6a9a-4777-9597-00e316194e9f)

## QA
Check that the correct optimistic lock exception message is displayed for determined and unknown objects.

**Comment by alexbudarov** [comment]
I also have a suggestion that we can extract entity class and ID from the exception.
For entities extending Updatable - automatically load updateTs and updatedBy.
And show message like "the object has been just modified by alexander.budarov 15 seconds ago"

**Comment by knstvk** [comment]
Let's make the message as follows:

### Unable to save the 'Role' object changes

The entity has just been changed by [`updatedBy` at `updateTs` | another user or by the system]. In order to avoid conflicts or data loss please reopen the screen and reapply your changes.
