### ISSUE TITLE
Environment variables as source of application properties

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2432]
## Problem

Please consider to add ability to take values for application properties from environment variables.

It is going to be used primarily on the stage of deployment (specifying in setenv.sh, in systemd unit Environment entries etc., by PaaS).
E.g. database connection parameters, passwords, encryption keys etc.

Arguments why System Properties is not enough:
1) From my perspective, environment variables are more secure:
- System properties are visible in a process launch string (ps ax | grep java). Environment variables are not visible.
- System properties can be modified at runtime, environment variables are immutable.

2) Some PaaS platforms pass parameters through environment variables.
E.g. AWS BeansTalk (Java SE Platform): https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/java-rds.html

3) Adding environment variable to the process is simple and can be done in many ways. Adding a system property - requires to change program command line.

## Solution

Sources of app properties are now considered in the following order:

1. Java system properties
2. OS environment variables
3. `app.properties` files
4. Database (for config interfaces with `@Source(SourceType.DATABASE)`)

Environment variables a bound to app properties using the relaxed rule: the name of the property matches the name of the app property either exactly or after conversion to uppercase and replacing dots with underscores:
`MYAPP_SOMEPROPERTY` matches `myapp.someProperty`
This is necessary as OS disallows environment variables containing dots.

In order to disable the relaxed binding (if you are afraid of accidental override), set `cuba.disableUppercaseEnvironmentProperties = true` in project's `app.properties`.

**Comment by knstvk** [comment]
To QA:
- Create a config interface and check priorities explained above.
