### ISSUE TITLE
Provide information about clicked component in LayoutClickEvent

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2437]
### Description of the bug or enhancement

Vaadin `LayoutClickEvent` has information about the component that was clicked, which is somewhere inside the parent layout on which the listener was registered. It would be useful having the same info in our `LayoutClickEvent`.

**Comment by Flaurite** [comment]
### Changes
Added `clickedComponent` to the `LayoutClickEvent`

From JavaDoc:
`clickedComponent` - component that was clicked, which is somewhere inside the parent layout on which the listener was registered.

### QA
1. Add LayoutClickListener to any: hbox, vbox, cssLayout, grid layout, flowBox
2. Add inside of this layout another layout with some TextField.
3. Click to this textField and check that clickedComponent in the event is not null.
