### ISSUE TITLE
JS imports removed from the head tag when redirection is used

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2439]
### Environment

- Platform version: 7.0.0 (tested on 7.1)

### Description of the bug or enhancement

- Minimal reproducible example

1. Create a login screen that uses a component with the `jquery` dependency and allows you to use credentials from a social networking site such as Facebook, Twitter or Google+, to sign in to a CUBA application.
2. Social login must redirect browser window to the provider page, e.i. completely replace it, and then return back to the CUBA app
3. Open a screen with FileUpload, e.g. Administration > Roles

- Actual behavior

`jquery` import is removed from the page `<head>` tag and isn't added again when a screen with a component that requires `jquery` is opened.

**Comment by dtsaryov** [comment]
Have tested the case with Social Login Demo - everything is ok. More details test case is required
