### ISSUE TITLE
Ability to show multi line result of Scheduled task in Execution history

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#245]
Ability to show multi line result of Scheduled task in Execution history

---
Original issue: https://youtrack.haulmont.com/issue/PL-7668

**Comment by SemenSofronov** [comment]
Could you please describe in more details what exactly should be fixed?

As for now, I can see that long strings are displayed with ability to expand them and the new string symbol is taken into account (see attach.).

![image.png](https://images.zenhubusercontent.com/5b4d9e85edf0570a96a14fa2/b2f3f118-a0a5-46dc-a3b7-b09263dd8c42)

**Comment by jreznot** [comment]
Already fixed
