### ISSUE TITLE
Database join with like operator on null column returns incorrect result

### ISSUE THREAD

**Issue by jacobmaxsmith** [cuba-platform/cuba#2454]
### Environment

- Platform version: 7.1.0
- Client type: Web
- Browser: Chrome
- Database: PostgreSQL
- Operating system: Windows/Linux

### Description of the bug or enhancement

- Minimal reproducible example
1. Create entity "Callsign" and add mandatory string attribute "value"
2. Create entity "Person". Add mandatory string attribute "name". Add an optional many-to-one association with Callsign entity, name the attribute "callSign"
3. Add a new instance of Person with name "John Smith", for instance by creating default browse and edit screens for Person and using those screens
4. Using JXM Console or similar, run the following 2 queries:

select e from testbug_Person e where (e.name like '%mit%')

select e from testbug_Person e where (e.name like '%mit%') or (e.callSign.value like '%mit%')

- Expected behavior
Both queries return the same results, which is one match with "John Smith"

- Actual behavior
First query works, but second query returns no results

**Comment by knstvk** [comment]
When you use reference like `e.callSign.value`, EclipseLink creates an inner join in SQL.
Try to modify the query as follows:
```
select e from testbug_Person e left join e.callSign c 
where (e.name like '%mit%') or (c.value like '%mit%')
```

**Comment by jacobmaxsmith** [comment]
Thanks, I didn't realize EclipseLink would not infer it automatically based on the nullness
