### ISSUE TITLE
Collapse mode in side menu

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#2456]
## Updates

Collapse Mode is supported for side menu main layout:

![sidemenu-collapse-mode.gif](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/fafc6012-f480-4fb6-af4b-587d7b72958a)

### Styling

There are few SCSS variables that enabled to manage behavior of layout:

- `$cuba-sidemenu-layout-collapse-enabled` - Defines whether SideMenu layout is collapsible

- `$cuba-sidemenu-layout-collapsed-width` - The width of collapsed SideMenu panel.

- `$cuba-sidemenu-layout-expanded-width` - The width of expanded SideMenu panel

- `$cuba-sidemenu-layout-collapse-animation-time` - The time of SideMenu panel animation in seconds

When the `$cuba-sidemenu-layout-collapse-enabled` variable is set to `false` the "Collapse" button is hidden

### User Indicator Changes

Now the user indicator component uses user `name` property instead of default instance name. If user name is empty, instance name is used.

### Studio Migration Issue

[YouTrack](https://youtrack.cuba-platform.com/issue/STUDIO-7590)

### QA

Check extending main screen with different templates

**Comment by web-devel** [comment]
Draft design:
![image](https://user-images.githubusercontent.com/3295727/67275064-d8da3780-f4d2-11e9-911c-2179820888a3.png)

**Comment by dtsaryov** [comment]
Reported by @gorbunkov 

Test case:

- Create new project on CUBA 7.2
- Create new user
- Add the new user as a substitution to admin

AR:

The users lookup in the left bottom corner of the screen looks like this:

![72521498-f837f500-3874-11ea-8fef-93a9a4f2ca26.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/498c0f93-3d4a-464c-8bcc-2d57078c8604)

**Comment by dtsaryov** [comment]
Reported from [forum](https://www.cuba-platform.ru/discuss/t/login-screen-with-branding-image/3872/3):

Set timezone for user, collapsed state:

![collapsed](https://www.cuba-platform.ru/discuss/uploads/default/original/2X/5/5e4c58c137b0b5342f4adcb39622181277ab0d27.png)

expanded:

![expanded](https://www.cuba-platform.ru/discuss/uploads/default/original/2X/c/c676dee97191251084cd8ca6d33b3bd89c99f5a7.png)

**Comment by natfirst** [comment]
Set
```
$cuba-sidemenu-layout-collapse-enabled: false;
```

![image](https://user-images.githubusercontent.com/17950251/73654676-c52f9700-46a5-11ea-88d2-40c566d9276a.png)

**Comment by natfirst** [comment]
set longer animation time by default
```
$cuba-sidemenu-layout-collapse-animation-time: .7s;
```

**Comment by dtsaryov** [comment]
Logo disappears in Chrome after app restart:

![image.png](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/ecff1769-2f69-4b71-9f00-437f0035c08b)

**Comment by knstvk** [comment]
Logo is not centered in the collapsed mode:
![image.png](https://images.zenhubusercontent.com/5aacbf4b4b5806bc2bcb3a01/6c0cdeae-8562-4e57-809d-8b6abfcee26e)
