### ISSUE TITLE
Show localized captions in Entity Log

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2457]
### Description of the bug or enhancement
see forum topic https://www.cuba-platform.ru/discuss/t/lokalizacziya-zhurnala-izmeneniya/3501
plus my 2 cents

1) Entity log currently displays Enum IDs in "New value" and "Old value".
It's not a problem to try to display localized caption (There can be cases when old enum constant does not exist anymore, or localized caption is not defined).

2) "Entity" column now displays entity name ("demo_Tariff").
We can also try to display localized entity caption there.

These improvements will make Entity Log screen easier accessible for power users who know nothing about enum constants and entity JPA names.

**Comment by Flaurite** [comment]
Also, see forum topic: https://www.cuba-platform.ru/discuss/t/funkcziya-getdisplayvalue-v-entitylogattr/3524
