### ISSUE TITLE
Automatically put editor in read only mode if entity update is not permitted

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#2459]
Since read only mode was [introduced](https://github.com/cuba-platform/cuba/issues/2270), I think it will be a good idea to put editor in read only mode automatically, if entity update is denied via permissions

### Updates
The editor goes into read-only mode automatically, if the entity update is denied via permissions. Also the pessimistic locking puts the editor in read-only mode.

### QA
* Check that the editor will be in read-only mode if the entity update is denied via permissions.
* Check that the editor will be in read-only mode if pessimistic locking is enabled.

**Comment by kgeis** [comment]
This makes sense to apply to a pessimistically locked entity too, right?

**Comment by GlebDurygin** [comment]
Yes, it is the correct behaviour.

**Comment by kgeis** [comment]
I'd love it if the editor also automatically went into read-only mode when a session expires.

**Comment by knstvk** [comment]
> I'd love it if the editor also automatically went into read-only mode when a session expires.

It's hardly possible - after the session expires the communication with the server-side UI objects is impossible. Besides, in normal setup session never expires while the browser window is open.

**Comment by kgeis** [comment]
> It's hardly possible

That's too bad.

> in normal setup session never expires while the browser window is open.

Sure it does. Try waking your laptop up after it being asleep for an hour! 😄
