### ISSUE TITLE
Use CategoryAttribute OrderNo to sort attributes for FieldGroup and Table

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#246]
Use CategoryAttribute OrderNo to sort attributes for FieldGroup and Table

---
Original issue: https://youtrack.haulmont.com/issue/PL-7681

**Comment by invviz** [comment]
Сhanges:
The order of dynamic attributes in categories affects the order in which these attributes are displayed in web components (tables and field groups).
You can change the order of displaying dynamic attributes on web components by changing the order of the lines on the "Category Editor" page.
