### ISSUE TITLE
Option to completely disable all table actions in the lookup screen

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2472]
### Description of the bug or enhancement

Goal: we want to use the same browser screen (derived from StandardLookup):
a) for browsing and various editing / management actions
b) as a lookup with filter to be used by picker fields

In the (b) use case we often want to completely disable all table actions such as Create, Edit, Remove, Copy etc:
- do not display button panel
- remove or disable actions from context menu, along with shortcuts

Currently existing "alwaysVisible" buttonPanel attribute is not enough.

I suppose that such behavior can be implemented by introducing additional option(s) to all classes in the "lookup chain" OR in the screen class itself: 
- StandardLookup, 
- LookupBuilder,
- parameterized PickerField lookup action for easy enabling in the Studio
AND/OR
- in the lookup screen controller itself (flag or annotation or something else which again can be easily integrated into the Studio screen designer)

to be discussed:
do we disable / remove ALL actions, even "system information" / "Refresh" / "Excel"?

* Expected behaviour - **The context menu should not be displayed when buttonsPanel is not visible in Lookup screen**
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/5bb3be45-5134-45d0-99ed-cc7daa77a7e6)

* Actual behaviour - **The context menu is displayed when buttonsPanel is not visible in Lookup screen**
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/ef398aa3-d97f-4a31-8f2d-e724d9db14be)
### Updates
If `buttonsPanel` has **false** value for `alwaysVisible` attribute, than user cannot call a context menu in Lookup screens.

### QA
Check that user cannot call a context menu in Lookup screens for `Table`, `GroupTable`, `DataGrid`, `Tree`, `TreeTable`, `TreeDataGrid`.

**Comment by knstvk** [comment]
What is the point to disable the actions?
The intention to hide buttons was just to emphasize the primary action - Select. The context menu actions do not clutter the screen, so they are harmless in this sense.

**Comment by alexbudarov** [comment]
1) If lookup screen is opened as a dialog - then entity editor can't be opened other way than in dialog mode. If editor is not adapted to a small dialog size - its layout lookss buggy.

2) Calling screen can be not prepared to a lookup action changing the list of possible options (create or remove an entity).
E.g. in a LookupPickerField - the list of options in a popup is not automatically updated.

These are more like problems which QA engineers love to post, but rarely bother users.
But sometimes we can make the system better by reducing number of things a user can do.
