### ISSUE TITLE
Scrollable mode for Layout element in screens

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#248]
Enable developers to set AUTO height for layout element if they need scrollbars for the entire Window.

Can be enabled in any window as:
```
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd"
        class="com.haulmont.refapp.web.ui.demo.DemoScreen"
        caption="Demo">

    <layout height="AUTO">
        <textField caption="Demo"/>
        <textField caption="Demo"/>
        <textField caption="Demo"/>
    </layout>
</window>
```

ER: If we resize browser window, scrollbars will be shown:

![image.png](https://images.zenhubusercontent.com/5ae3309c4b5806bc2bd0e8d8/4694b3d2-d11c-4861-a019-a9fd0c767a9c)

**Comment by jreznot** [comment]
Relates to #1172
