### ISSUE TITLE
SuggestionField.showSuggestions method invocation is ignored

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2485]
### Environment

- Platform version: 7.0.11+
- Caused by: https://github.com/cuba-platform/cuba/issues/2430

### Description of the bug or enhancement

- Minimal reproducible example

```
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd"
        caption="Sandbox">

    <layout spacing="true">
        <hbox spacing="true">
            <suggestionField id="suggestionField"/>
            <button id="btn" caption="Show Suggestions"/>
        </hbox>
    </layout>
</window>
```

```
import com.haulmont.cuba.gui.Route;
import com.haulmont.cuba.gui.components.Button;
import com.haulmont.cuba.gui.components.SuggestionField;
import com.haulmont.cuba.gui.screen.*;

import javax.inject.Inject;
import java.util.Arrays;

@UiController("sandbox")
@UiDescriptor("sandbox.xml")
@Route("sandbox")
@LoadDataBeforeShow
public class Sandbox extends StandardLookup {
    @Inject
    private SuggestionField<String> suggestionField;

    @Subscribe("btn")
    public void onBtnClick(Button.ClickEvent event) {
        suggestionField.showSuggestions(Arrays.asList("One", "Two", "Three", "Four"));
    }
}
```

1. Open the screen
2. Click the **Show Suggestions** button

- Expected behavior

Suggestion popup is shown.

- Actual behavior

No suggestion popup is shown.

----

Source: https://www.cuba-platform.com/discuss/t/showsuggestions-not-working/10441

### Updates
When a `showSuggestions' is called, the suggestion popup will appear.

### QA
* Check the above case for SuggestionField and SuggestionPickerField;
* Check the case from a [related issue](https://github.com/cuba-platform/cuba/issues/2430)

**Comment by skatova** [comment]
Since https://github.com/cuba-platform/cuba/issues/2430 committed down to version 6.10, this issue must also be fixed in version 6.10.
