### ISSUE TITLE
How to clear GUI Screen cache

### ISSUE THREAD

**Issue by Nagasam123** [cuba-platform/cuba#2494]
Hi, 
I am trying to upload a file using uploadFileField,
I need to clear its value when I press clear button, in addAfterValueClearListener() if i assign file = null, then also it is taking old file value, so is their any property where I can clear cache in GUI Screen ?

Thanks,
Naga

**Comment by alexbudarov** [comment]
Hi,
Please direct your questions regarding the CUBA platform to the support forum:
https://www.cuba-platform.com/discuss/
