### ISSUE TITLE
Provide Select all / Deselect all in DataGrid column control

### ISSUE THREAD

**Issue by GlebDurygin** [cuba-platform/cuba#2505]
### Environment

- Platform version: 7.2

### Description of the bug or enhancement
Provide Select all / Deselect all in DataGrid column control as done for the [Table](https://github.com/cuba-platform/cuba/issues/776)

### Updates
The `DataGrid`and `TreeDataGrid` components have an ability to select (show) / deselect (hide) all columns. The column selector menu has two new items:
* `Select all` - shows all table columns;
* `Deselect all` - hides all columns. For `TreeDataGrid` hides all columns except hierarchy columns.

![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/30bc6097-9827-4a09-85c7-58b0aa4c28f5)

### Usage example DataGrid
![grid-selectall](https://user-images.githubusercontent.com/35256248/68767002-6247da00-0639-11ea-9663-9a5528ad623a.gif)

### QA
Check that `Select all` and `Deselect all` buttons work correctly for `DataGrid` and `TreeDataGrid`.

**Comment by skatova** [comment]
The **Select all** action for `TreeDataGrid` must not hide the hierarchy column

**Comment by GlebDurygin** [comment]
Issue description has updated

**Comment by skatova** [comment]
The **Сolumn collapsing menu** must be hidden if the `Columns Collapsing Allowed` attribute is `false`.
![image](https://user-images.githubusercontent.com/53561930/70029215-03360f00-15c0-11ea-94d2-e27e1937766b.png)

**Comment by skatova** [comment]
The very first entity's attribute is not present in the Column Collapsing menu

![image](https://user-images.githubusercontent.com/53561930/70216375-d49f6c00-1758-11ea-869c-81a09502f4f8.png)

**Comment by skatova** [comment]
Fixed in #2588
