### ISSUE TITLE
Add @StudioDelegate "set applicable when" method to standard actions

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2506]
CUBA version: 7.2 snapshot.
Relates to #2462.

### Description of the bug or enhancement
It is a popular customization for EditAction, RemoveAction - to add condition for "isApplicableWhen()".
E.g. UserBrowser does not allow user to remove him/herself.

Let's add a @StudioDelegate method to standard parameterized actions to override standard "isApplicableWhen()" behavior.

**Comment by knstvk** [comment]
There is already `enabledRule` delegate which does exactly this:

```
@Install(to = "petsTable.edit", subject = "enabledRule")
private boolean petsTableEditEnabledRule() {
    return petsTable.getSingleSelected() != null && petsTable.getSingleSelected().getName().startsWith("a");
}
```

**Comment by alexbudarov** [comment]
@knstvk shouldn't we annotate that method?

**Comment by knstvk** [comment]
@alexbudarov ok, see #2531
