### ISSUE TITLE
Automatically set app.home if running on Tomcat

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2511]
### Environment
- Platform version: tested on 7.1.1

### Description of the bug or enhancement
Platform uses "app.home" to write various temporary configuration files, e.g. persistence.xml, uploaded files on GUI layer etc.
Currently platform requires user to specify this property. Otherwise it takes some default directory and if it's not writeable - application start fails.

In AWS Elastic Beanstalk service (Tomcat platform) the layout is organized so that default directory is not writeable.

I have tested that if you set up an Environment property in the Beanstalk application environment:
> app.home = /usr/share/tomcat8/work/app_home

which is equivalent to ${catalina.base}/work/app_home
then application starts successfully.

It would be nice to allow newbie users to skip this step. Automatically determine that we are running under Beanstalk and set app.home to a sane value.

Suggestion: add *app.home* autodetection for Beanstalk service:

If *app.home* system property is __not__ set
and *catalina.base* system property is set
and *RDS_HOSTNAME* system property is also set (every CUBA app needs an RDS database. Docs: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/java-rds.html)

then assume that we are running in AWS Elastic Beanstalk and assign
> app.home = ${catalina.base}/work/app_home

**Comment by alexbudarov** [comment]
I would also kindly suggest that ${catalina.base}/work/app_home is a good default value for app.home inside of any tomcat server (if catalina.base is set), because this value is used by Tomcat itself internally.

**Comment by knstvk** [comment]
Note that `LogbackConfigurator` implemented in #2319 won't find a `logback.xml` in app home because it comes into play before the system property is set.

**Comment by knstvk** [comment]
QA: try to deploy WAR to a stock Tomcat without any modifications. When run, it should print a warning about `app.home` automatically set and create `tomcat/work/app_home` directory.

**Comment by alexbudarov** [comment]
> Note that LogbackConfigurator implemented in #2319 won't find a logback.xml in app home because it comes into play before the system property is set.

At least for Beanstalk there is no ability to put local configuration files to the file system, so it is not a problem.
