### ISSUE TITLE
Dynamically changing an aggregatable attribute does not work for a Table

### ISSUE THREAD

**Issue by GlebDurygin** [cuba-platform/cuba#2517]
### Environment

- Platform version: 6.10+
- Client type: Web

### Description of the bug or enhancement
See the forum [topic](https://www.cuba-platform.ru/discuss/t/problema-pri-dinamicheskom-otklyuchenii-agregaczii-v-tablicze/3609)

- Minimal reproducible example
1. Set attribute `aggregatable = true` for `Table`
2. Add aggregation column
3. Add `Checkbox` or `Button` to change `aggregatable` attribute value

- Expected behavior
When changing the value of  `aggregatable` attribute, the aggregated row is displayed when the value is `true`, and hidden when `false`.

- Actual behavior
The aggregated row is always displayed.

### Updates
The aggregation rows are hidden if the `aggregatable` property is `false`.

### QA
Check the above case for `Table`, `GroupTable` and `TreeTable`.

**Comment by gogosofta** [comment]
there's another bug coming from this fix - when aggregatable is set to true in design time, the aggregated row shows on screen invokation and then immediately hides.

**Comment by dtsaryov** [comment]
Hello @gogosofta 

Thank you for reporting the problem. We're already working on it: #2578
