### ISSUE TITLE
Menu of suggestionField pop up is visible when focus transfers to another window

### ISSUE THREAD

**Issue by axgurt** [cuba-platform/cuba#2519]
### Environment

- Platform version: 6.10.13
- Client type: Web

### Description of the bug or enhancement
Web suggestion filed menu is rendered over modal dialogs and other components, even when it is not needed anymore.

Can be reproduced with network throttling like slow 3G in project with cuba-platform-ui-tests on master with the following patch
[Menu_of_suggestionField_pop_up_should_be_hidden.zip](https://github.com/cuba-platform/cuba/files/3792171/Menu_of_suggestionField_pop_up_should_be_hidden.zip)

Similar issue is here: https://github.com/cuba-platform/cuba/issues/2430

Bug looks as 
![image](https://user-images.githubusercontent.com/18262741/67919252-16b51b00-fbb9-11e9-925f-dfb62785e605.png)

### Updates
Web suggestion filed menu is rendered over modal dialogs and other components, only when it is inside the active window.

### QA
Check the above case (add the patch to the  cuba-platform-ui-tests project)

**Comment by natfirst** [comment]
Another patch:
if `focusComponet` attribute in the opened screen is set to the component other than text component, that the focus stays in the SuggestionField and the problem is reproduced.
[issue_with_focus_component.zip](https://github.com/cuba-platform/cuba/files/3793284/issue_with_focus_component.zip)

**Comment by axgurt** [comment]
It also reproduces with text component. See attachment:
[issue_with_textfield_input_focus_component.zip](https://github.com/cuba-platform/cuba/files/3793377/issue_with_textfield_input_focus_component.zip)
![image](https://user-images.githubusercontent.com/18262741/67940629-8218e000-fbed-11e9-9d07-c34fe0dd6360.png)
