### ISSUE TITLE
Ability to use locales with "script" property in cuba.availableLocales

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2524]
### Description of the bug or enhancement
see forum topic
https://www.cuba-platform.com/discuss/t/serbina-latin-language-settings/10578/3

Locale can consist of these parts:
- language
- country
- variant
- script
- ... maybe others, not an expert

We use org.apache.commons.lang3.LocaleUtils#toLocale method to parse cuba.availableLocales.
It does NOT allow to specify script.

And the com.haulmont.cuba.core.sys.AvailableLocalesFactory class which performs locale parsing - can't be overriden at all.

Example of locale is Serbian Latin.
Its "IETF BCP 47" standard code is "sr-Latn".
https://tools.ietf.org/html/bcp47

If we would add an option to use java.util.Locale#forLanguageTag method to parse the locale string - it uses "IETF BCP 47" and it can parse Serbian Latin locale.

**Comment by soraksh** [comment]
Now `script` property supported for available locales. If you want to use locale that includes `script` you should define locale using language tag, e.g. `sr-Latn`. Message pack for such locale should also use language tag, e.g. `messages_sr-Latn.properties`.

Examples of supported locales and associated message packs:
`sr` - `messages_sr.properties`
`sr-Latn` -  `messages_sr-Latn.properties`
`en_US` -  `messages_en_US.properties`
`ja_JP_JP` -  `messages_ja_JP_JP.properties`

**Comment by Mihail063** [comment]
Serbian Latin is not included if the standard code `sr-Latn` is used in the locale properties
