### ISSUE TITLE
Filter conditions on legacy screens are logged to query body instead of 'conditions' 

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#2530]
Maybe this should be resolved as "known issue".

See also #2458

### Environment

 Platform version: 7.0.13, 7.1.2 after  #2458 was fixed

### Description of the bug or enhancement

- Minimal reproducible example
1. Create a project on PLatform 6.10.x
2. Create some entity and standard screens for it.
3. Migrate to 7.0.13
4. Open Administration->Server log. Switch to the Options tab
5. Select eclipselink.slq logger and set DEBUG level for it
![image](https://user-images.githubusercontent.com/19840141/68305310-e4c41d00-00c0-11ea-8778-bb278e4a2e00.png)
6. Open the entity browse - screen. Where a Filer exists.
7. Adjust some filter conditions 
![image](https://user-images.githubusercontent.com/19840141/68306849-b72ca300-00c3-11ea-8b3c-6f004103a516.png)
8. Perform a search by this filter
9. Check in app.log the JPQL which is logged by RdbmsStore

- Actual behavior
In the log: The filter condition is written to the query body. And 'conditions = null' there:
```
com.haulmont.cuba.core.app.RdbmsStore - loadList: metaClass=filtertest$Master, view=com.company.filtertest.entity.Master/master-view, query=Query{queryString='select e from filtertest$Master e where e.masterStr like :component_filter_masterStr84982 ESCAPE '\'', condition=null, sort=null, firstResult=0, maxResults=50}, max=50
```

**Comment by knstvk** [comment]
This is the correct behavior.
