### ISSUE TITLE
Simplify adding resources to the current screen page

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#2535]
### Environment
- Platform version: 7.2
- Client type: Web

### Description of the bug or enhancement
To add some CSS or JS files that should be used with the current `Screen` we need to create Js component or do some other complicated stuff.
The layout of the screen is based on `VerticalLayout`. We can extend this component and implement the `HasDependencies` interface, which Vaadin will appropriately handle for this screen. Then we can provide for this public API in the `Window`.

----

Required for: #2455

**Comment by glebfox** [comment]
### Solution

The new helper class has been added In the **web** module - `ScreenDependencyUtils`. Its methods are identical to `JavaScriptComponent` methods for adding dependencies:

* `setScreenDependencies(FrameOwner frameOwner, List<ClientDependency> dependencies)`
* `addScreenDependencies(FrameOwner frameOwner, String... dependencies)`
* `addScreenDependency(FrameOwner frameOwner, String path, Dependency.Type type)`
* `List<ClientDependency> getScreenDependencies(FrameOwner frameOwner)`

**Example:**
```
@Subscribe
public void onInit(InitEvent event) {
    ScreenDependencyUtils.addScreenDependency(this, "webjar://jquery:jquery.min.js", Dependency.Type.JAVASCRIPT);
}
```

As the result the following import will be adde to the page header:
```
<script src="http://localhost:8080/cuba/VAADIN/webjars/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
```

**For QA:**

1. Check that dependency can be added to any screen, i.e. legacy window/frame, screen/fragment.
2. Check that a particular dependency is added only once, i.e. if we open the same screen several times, a dependency is added once.
