### ISSUE TITLE
RemoteClientInfo.address must consider X-Forwarded-For value

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#2538]
### Environment

- Platform version: 7.1

### Description of the bug or enhancement

This is required for correct detecting of the client IP when the core app is behind a reverse proxy.
See [forum topic](https://www.cuba-platform.com/discuss/t/how-to-be-sure-only-authorized-client-apps-can-perform-calls-on-app-core-jar/10617).

**Comment by alexbudarov** [comment]
Please look at this ticket: #788

We should not duplicate the job of application servers which already implemented x-forwarded-for substitution.

Tomcat - use RemoteIpValve:
Note how complex the logic described in javadocs is!
http://tomcat.apache.org/tomcat-8.5-doc/config/valve.html#Remote_IP_Valve
https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/RemoteIpValve.html

Jetty - use ForwardedRequestCustomizer:
https://www.eclipse.org/jetty/documentation/9.4.x/configuring-connectors.html#_proxy_load_balancer_connection_configuration
