### ISSUE TITLE
Update mybatis dependency to 3.3.0

### ISSUE THREAD

**Issue by dmitrykiru** [cuba-platform/cuba#2542]
### Environment

- Platform version: 6.10

### Description of the bug or enhancement

Recently we faced the issue described at the https://github.com/mybatis/mybatis-3/issues/224. 
The solution is to update mybatis dependency to [3.3.0](https://blog.mybatis.org/2015/05/mybatis-330-released.html) or [3.3.1](https://blog.mybatis.org/2016/02/mybatis-331-and-mybatis-spring-124.html)

Is it possible to receive these changes in **6.10.15**? It would be very convenient for us.

Thanks.

**Comment by andreysubbotin** [comment]
For QA: check that `tomcat/shared/lib` contains `mybatis-3.3.1.jar`
