### ISSUE TITLE
Boolean values of embedded entities are not committed

### ISSUE THREAD

**Issue by dkz** [cuba-platform/cuba#2561]
### Environment

- Platform version: 6.10.14
- Database: PostgreSQL

### Description of the bug or enhancement

Sample project is attached: [embedded-boolean.zip](https://github.com/cuba-platform/cuba/files/3868128/embedded-boolean.zip)
Project consists of a single `TargetEntity` entity and embedded `EmbeddedBoolean` entity (generated with cuba-cli).

Steps to reproduce bug:
* Create an `TargetEntity` instance with `embedded.value = true`
* Edit the same entity, set `embedded.value = false`
* Commit, reopen screen

Outcomes:
- Expected: `embedded.value` is set to `false`
- Actual: `embedded.value` is still `true`

I.e. data service seems to ignore changes in embedded entity and value cannot be switched to false from UI.

**Comment by soraksh** [comment]
This situation does not look like a bug, but editor screen in the attached project looks not quite correct. It has only a datasource for the parent entity, but an embedded entity must have its own nested datasource inside parent datasource . If you add one, then everything works correctly and embedded entities are committed.
