### ISSUE TITLE
Add a way to disable automatic suggestions in SourceCodeEditor after a dot is typed

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#2564]
If a suggester is added to the `SourceCodeEditor`:
```java
sourceCodeEditor.setSuggester((source, text, cursorPosition) -> ...);
```
then suggestions will be displayed when the user enters the dot (`.`). This should be optional because in some cases suggestions must be displayed only after the user pressed `Ctrl + Space` explicitly.

**Comment by Flaurite** [comment]
### Changes
Added new property for `SourceCodeEditor` - `suggestOnDot`. It will enable/disable suggesting options after dot character - "." Default value is true. 

Example:
```
<sourceCodeEditor id="sourceCode"
                  height="200px"
                  width="200px"
                  suggestOnDot="false"/>
```
![sourcecode](https://user-images.githubusercontent.com/22093943/70056969-cab12800-15f5-11ea-8601-b495aa3f7f2b.gif)
### For QA
Download demo project: [dev-sourcecode.zip](https://github.com/cuba-platform/cuba/files/3916939/dev-sourcecode.zip) and try new attribute.
