### ISSUE TITLE
The time field is displayed for the DateField component regardless of the dateFormat attribute

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2567]
### Environment

- Platform version: 7.0.0+

### Description of the bug or enhancement

According to the doc:
> You can change the date and time format using the `dateFormat` attribute. An attribute value can be either a format string itself or a key in a message pack (if the value starts with msg://).
The format is defined by rules of the SimpleDateFormat class (http://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html). **If there are no H or h characters in the format, the time field will not be displayed.**

- Minimal reproducible example

```
<dateField dateFormat="MM/yy"/>
```

- Expected behavior

![image](https://user-images.githubusercontent.com/6077149/69712766-d051ce00-111c-11ea-8da8-5703f47a950a.png)

- Actual behavior

<img width="195" alt="Screenshot 2019-11-27 at 13 50 24" src="https://user-images.githubusercontent.com/6077149/69712808-e19ada80-111c-11ea-8103-8c7640336860.png">

### Updates
The `DateField` has a default `dateFormat` value = `dd/MM/yyyy HH:mm`. The `resolution` attribute does not have a default value. The `resolution` attribute takes precedence over `dateFormat` attribute. If the `resolution` is set less than a `DAY`, then the time field will always be displayed, regardless of the `dateFormat` attribute value.

* The default `dateFormat` is `dd/MM/yyyy HH:mm`:
`DateField` and `TimeField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/31f2223f-9a94-45da-a86c-3b0b9555937d)
* `Resolution` is set to `MIN` and the default `dateFormat` is `dd/MM/yyyy HH:mm`:
`DateField` and `TimeField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/38418335-c35e-4430-a499-a688b19f566e)
* `Resolution` is set to `DAY` and the default `dateFormat` is `dd/MM/yyyy HH:mm`:
Only `DateField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/7f767516-be60-4c3b-8b2d-0f00db8e5953)
* Resolution is set to `YEAR` and the default `dateFormat` is `dd/MM/yyyy HH:mm`:
Only `DateField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/864ec453-01ab-4387-bdf7-63a80ca8ff1f)
* The `resolution` is not set and `dateFormat` is set to `dd/MM/yyyy HH:mm`.
`DateField` and `TimeField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/c9c1983f-d747-4c81-863f-a061728770a7)
* The `resolution` is not set and `dateFormat` is set to `dd/MM/yyyy`
Only `DateField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/a29c6828-366e-428e-a8ff-4fcc3fe8059b)
* The `resolution` is not set and `dateFormat` is set to `yyyy`.
Only `DateField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/805e94ff-d0f8-4ee4-9420-fc17c7bb6f38)
* `Resolution` is set to `MIN` and `dateFormat` is set to `dd/MM/yyyy`.
`DateField` and `TimeField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/f6d124d7-42f4-43e0-bc14-e8696ea80935)
* `Resolution` is set to `MIN` and `dateFormat` is set to `yyyy`.
`DateField` and `TimeField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/ce1bb671-62f5-401e-b975-66aee86e8036)
* `Resolution` is set to `DAY` and `dateFormat` is set to `dd/MM/yyyy HH:mm`.
Only `DateField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/eda88c6a-90cf-420d-a3cf-4e0d09574c78)
* `Resolution` is set to `YEAR` and `dateFormat` is set to `dd/MM/yyyy HH:mm`.
Only `DateField` will be displayed.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/74d7a74c-3a90-419b-8959-fecba2baf700)

### QA
Check the above cases.

**Comment by natfirst** [comment]
The following cases work incorrectly, the time field is displayed:
1. Resolution is set to MIN and dateFormat is set to `dd/MM/yyyy`.
Only DateField will be displayed.

2. Resolution is set to MIN and dateFormat is set to `yyyy`.
Only DateField will be displayed.
