### ISSUE TITLE
frame properties subtag is missing from XSD

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2568]
### Environment
- Platform version: 7.1.2

### Description of the bug or enhancement
Ticket #437 adds support for frame parameters for legacy screens. It was intentional: otherwise why would anyone add support to pass datasources as parameters?

But `<frame>` -> `<properties>` subtag is missing from XSD.

This code works in runtime but is highlighted as incorrect by IDE:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<window xmlns="http://schemas.haulmont.com/cuba/window.xsd"
        class="com.company.param2.web.screens.legacy.LegacyScreen"
        messagesPack="com.company.param2.web.screens"
        caption="msg://caption">
    <dsContext>
        <datasource id="userDs" class="com.haulmont.cuba.security.entity.User" view="_minimal"/>
    </dsContext>
    <dialogMode height="600"
                width="800"/>
    <layout>
        <label id="titleLabel" width="200px" value="initial title" stylename="h2"/>
        <frame screen="param2_LegacyFrame">
            <properties>
                <property name="userDatasource" ref="userDs"/>
                <property name="supportProgressPercent" value="0.9"/>
            </properties>
        </frame>
    </layout>
</window>
```
![image](https://user-images.githubusercontent.com/6158807/69720480-237f4d00-112c-11ea-9834-950afe874427.png)

**Comment by dtsaryov** [comment]
"Properties" mechanism will not be supported for legacy API
