### ISSUE TITLE
Table aggregation row disappears

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#2578]
Caused by #2517

### Environment

- Platform version: 6.10
- Browser: Any

### Description of the bug or enhancement

![gt-aggregation-row.gif_2.gif](https://images.zenhubusercontent.com/5aec35b64b5806bc2bd1bf1e/e3891f66-ef74-4eb8-8987-5e11fa3cb9c2)

### QA

Please check all tables in all popular browsers with all available themes. Test different table configurations (groupings, aggregations, column widths, etc). Table columns misalign is also fixed

Checklist:

Tables:
- [ ] Table
- [ ] GroupTable
- [ ] TreeTable

Browsers:
- [ ] Chrome
- [ ] FF
- [ ] Edge
- [ ] IE11
- [ ] Safari

Themes:
- [ ] halo
- [ ] hover
- [ ] havana

Table features:
- [ ] aggregation (configure, show/hide dynamically)
- [ ] groups (add/remove groups in runtime)
- [ ] scrolls (vertical / horizontal)
- [ ] columns width
- [ ] show/hide columns
- [ ] zoom (system / browser)

### Test project

[tables-test.zip](https://app.zenhub.com/files/54624511/b8641a92-22a7-4034-bff2-eee6b8cd058d/download)

**Comment by Mihail063** [comment]
Case 1 

1. Set the aggregatable property to false by button
2. Create a new item
3. Set the aggregatable property to true

AR: Aggregation row displayed incorrectly
![изображение](https://user-images.githubusercontent.com/24281695/71002426-b17da080-20f8-11ea-8beb-83d93191de5e.png)
Also, this behavior repeating when switching between application tab

Case 2
Table: Group Table

1. Set the aggregatable property to false by button
2. Hide several columns 
3. Set the aggregatable property to true

AR: Table header displayed incorrectly
![изображение](https://user-images.githubusercontent.com/24281695/71008944-e989e100-2102-11ea-8f4a-97d568df8671.png)

Case 3
Table: Group Table

1. Set the aggregatable property to false by button
2. Drag&Drop any column to the grouping area
3. Set the aggregatable property to true

AR: Table header displayed incorrectly

![agregation row](https://user-images.githubusercontent.com/24281695/71069444-2fda5100-2192-11ea-989e-bd60c0e71ced.gif)

Case 4
Table: Group Table

1. Set the aggregatable property to false by button
2. Expand any row
3. Set the aggregatable property to true

AR: Table header displayed incorrectly
![изображение](https://user-images.githubusercontent.com/24281695/71070830-fc4cf600-2194-11ea-9326-fb58936fe23c.png)
Also, this behavior repeating when switching between application tab

**Comment by dtsaryov** [comment]
> Case 5
Aggregatable row is not showed manually unless `aggregatable ="true"` is set in the screen descriptor

It will not be fixed for now. Moved to another issue: #2603
