### ISSUE TITLE
Ability to define prefix and suffix icons for TextField

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2586]
### Description of the bug or enhancement

It would be useful to provide the ability to define prefix and suffix icons for TextField, so that the purpose of a field can be described without a caption, e.g. email, username, password, etc.

Additionally, provide a dom tree that can be styled, e.g. to achieve the following results:

![Screenshot 2019-12-09 at 11 08 30](https://user-images.githubusercontent.com/6077149/70414995-168c2300-1a75-11ea-8af2-7c22f3306157.png)

![Screenshot 2019-12-09 at 11 08 37](https://user-images.githubusercontent.com/6077149/70414999-17bd5000-1a75-11ea-936a-6d77442af8b8.png)

![Screenshot 2019-12-09 at 11 16 34](https://user-images.githubusercontent.com/6077149/70415131-623ecc80-1a75-11ea-9fd8-9b1fbea123b5.png)

### Updates
The cases described above can be solved using existing styles:
* **Prefix icon**
```
<textField id="textField" icon="font-icon:USER" stylename="inline-icon"/>
```
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/2f85d03d-5380-44c7-bc62-bdba6a826a41)
* **Suffix icon**
```
<textField id="textField" icon="font-icon:USER" stylename="inline-icon suffix-icon"/>
```
```
  .v-slot-suffix-icon > .v-caption-on-top {
    position: relative;

    .v-caption-suffix-icon > .v-icon {
      left: auto;
      right: 1px;
    }

    .v-textfield-suffix-icon {
      padding-left: round($v-unit-size/4);
      padding-right: $v-unit-size;
    }
  }
```
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/3902f1b9-2413-4728-a6ac-1fca5a15746d)

* **Prefix icon with border**
```
<textField id="textField" icon="font-icon:USER" stylename="inline-icon border-right"/>
```
```
  .v-slot-border-right {
    .v-caption-border-right > .v-icon {
      border-right: 1px solid first-color(valo-border());
    }

    .v-textfield-border-right {
      padding-left: $v-unit-size + round($v-unit-size/4);
    }
  }
```
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/cc09ab85-ae3e-437b-9bfa-77c51b0ef01c)

* **Suffix icon with border**
```
<textField id="textField" icon="font-icon:USER" stylename="inline-icon suffix-icon border-left"/>
```
```
  .v-slot-suffix-icon > .v-caption-on-top {
    position: relative;

    .v-caption-suffix-icon > .v-icon {
      left: auto;
      right: 1px;
    }

    .v-textfield-suffix-icon {
      padding-left: round($v-unit-size/4);
      padding-right: $v-unit-size;
    }
  }

  .v-slot-border-left {
    .v-caption-border-left > .v-icon {
      border-left: 1px solid first-color(valo-border());
    }

    .v-textfield-border-left {
      padding-right: $v-unit-size + round($v-unit-size/4);
    }
  }
```
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/e9ee9706-f10b-4af0-af93-aa52b5537fc6)

**Comment by dtsaryov** [comment]
Consider the following built in style name:

`HaloTheme#TEXTFIELD_INLINE_ICON`
