### ISSUE TITLE
Inform user about incorrect behavior when View contains recursively nested properties

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#2587]
### Environment
- Platform version: 7.1
- Client type: Web

### Description of the bug or enhancement
If user defined the following view:
```
<view entity="reporting$TaskSpan" name="taskSpan-view" extends="_local">
    <property name="task" view="_minimal">
        <property name="start"/>
        <property name="taskSpan" view="_minimal">
            <property name="task"/>
        </property>
    </property>
</view>
```
where property `task` is list of entities, it will load all `TaskSpan`, but `Task` will be loaded only for first `TaskSpan`.

- Minimal reproducible example
1. Download attached project: [reporting.zip](https://github.com/cuba-platform/cuba/files/3938280/reporting.zip)

2. Create two `TaskSpan` with one `Task`
3. Open `Gantt` screen.

**AR**
We will see `Task` only for first `TaskSpan`

**Comment by soraksh** [comment]
It was decided to fix problem instead of inform about it.
