### ISSUE TITLE
[TreeDataGrid] columns' collapsible state isn't updated when hierarchyColumn is changed

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2588]
### Environment

- Platform version: 7.0.0

### Description of the bug or enhancement

- Minimal reproducible example

```
<window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd"
        caption="Sandbox">

    <data>
        <collection id="groupsDc"
                    class="com.haulmont.cuba.security.entity.Group"
                    view="group.browse">
            <loader id="groupsLoader">
                <query>
                    select g from sec$Group g order by g.name
                </query>
            </loader>
        </collection>
    </data>

    <layout spacing="true">
        <treeDataGrid id="treeDataGrid"
                      settingsEnabled="false"
                      dataContainer="groupsDc"
                      hierarchyProperty="parent"
                      height="100%"
                      width="100%">
            <columns>
                <column property="name"/>
                <column property="parent"/>
            </columns>
            <buttonsPanel>
                <button id="btn" caption="Set Hierarchy Column"/>
            </buttonsPanel>
        </treeDataGrid>
    </layout>
</window>
```

```
@Inject
private TreeDataGrid<Group> treeDataGrid;

@Subscribe("btn")
public void onBtnClick(Button.ClickEvent event) {
    treeDataGrid.setHierarchyColumn("parent");
}
```

Case 1:

1. Open a screen
2. All columns except a hierarchy column can be collapsed (in our case only **parent**):

![Screenshot 2019-12-17 at 17 05 42](https://user-images.githubusercontent.com/6077149/70998094-f05b2880-20ef-11ea-852f-94651f056f5c.png)

3. Reorder columns so that the parent becomes the first column and the hierarchy column at the same time. This is valid because if the hierarchy column isn't set explicitly, we set the first column as the hierarchy column.

- Expected behavior

The **name** column can be collapsed and **parent** can't as it became a hierarchy column.

- Actual behavior

No columns can be collapsed

![Screenshot 2019-12-17 at 17 05 55](https://user-images.githubusercontent.com/6077149/70997994-a5411580-20ef-11ea-8707-6d9c2d73ef79.png)

Case 2:

1 and 2 the same (see above)
3. Make the parent column as hierarchy column programmatically, i.e. explicitly.

- Expected behavior

The **name** column can be collapsed and **parent** can't as it became a hierarchy column.

- Actual behavior

No columns can be collapsed

![Screenshot 2019-12-17 at 17 06 36](https://user-images.githubusercontent.com/6077149/70998298-6d869d80-20f0-11ea-9500-60c79db26801.png)

---

P.S. in fact, it's a Vaadin bug.

**Comment by GlebDurygin** [comment]
* Case 1
During `TreeDataGrid` component loading, the first column always becomes not hidable. If a `hierarchyColumn` is specified, the state for the first column is not updated and it remains not hidable.

* Case 2
If no `hierarchyColumn` is specified, only the first column will be not hidable. If you move other columns to the first place, then they will also become not hidable, but the state of other columns will not be updated. And as a result, all the columns will become not hidable.
