### ISSUE TITLE
Unexpected behavior of  MethodsCache with setters

### ISSUE THREAD

**Issue by invviz** [cuba-platform/cuba#2591]
### Environment

- Platform version: 7.1

### Description of the bug or enhancement

I have two examples of MethodsCash class unexpected behavior.

1) I have some static method 
```
public static void setSomeVar(Integer i)
```
this method does not have annotation @Metaproperty and does not relate to any metaproperty. It is just a simple static method with the name starting with 'set'. But when I try to save entity I get an exception "Can not use the static method 'setSomeVar' with instance".

2) I have the property 
```
@Column(name = "AMOUNT")
protected BigDecimal amount;
```
and I want to create 3 setters that will use different param types:
```
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public void setAmount(Double amount) {
        this.amount = BigDecimal.valueOf(amount);
    }

    public void setAmount(Integer amount) {
        this.amount = BigDecimal.valueOf(amount);
    }
```
As I understand MethodsCache use the last setter (with Integer parameter) and I get an exception at runtime "Can not cast BigDecimal to Integer".

**Comment by soraksh** [comment]
Now setters with different param types should work fine and static setters/getters will be ignored by `MethodsCash` (won't work with `setValue()` and `getValue()` methods).
