### ISSUE TITLE
cuba.dataSource.jdbcUrl looks like unused app propety

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#2598]
See #2315

### Environment

 Platform version: 7.2-snapshot

### Description of the bug or enhancement
1) Create a new project on 7.2
2) change the main DataStore from JNDI to application
3) open *app.properties* in core - module

cuba.dataSource.jdbcUrl looks like it is not used. Other Connection properties look like they are used somewhere

![image](https://user-images.githubusercontent.com/19840141/70886900-0e446280-1ff6-11ea-9667-e27b50511233.png)

**Comment by alexbudarov** [comment]
It is more task for Studio.
See various tickets: https://youtrack.cuba-platform.com/issues/STUDIO?q=%22implicit%20usage%22
