### ISSUE TITLE
Nullability when using CUBA API in Kotlin code

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2602]
### Environment

- Platform version: 7.2
- Language: Kotlin

### Description of the bug or enhancement
E.g. generate BeforeDetachEntityListener. In Kotlin it looks like this:
```
@Component(PersonDetachListener.NAME)
class PersonDetachListener: BeforeDetachEntityListener<Office> {
    companion object {
        const val NAME = "kot_PersonDetachListener"
    }
    @Inject
    private lateinit var timeSource: TimeSource
    override fun onBeforeDetach(entity: Office?, entityManager: EntityManager?) {
        entity?.createTs = timeSource.currentTimestamp()
    }
}
```

It is obvious that neither office nor entityManager are going to be null. But we have to use "?." or "!!" to deal with nullable variables, because Kotlin doesn't know about our conventions.

Options how to deal with nullabilty:
- Provide nullability info with JSR 305
- use standard Nullable / Nonnull
- use spring annotation NonNullApi
- develop own annotation (ask shustanov)

**Comment by knstvk** [comment]
What we have got:

```
class CustomerEntityListener : BeforeInsertEntityListener<Customer>, BeforeUpdateEntityListener<Customer> {
    // correct
    override fun onBeforeInsert(entity: Customer, entityManager: EntityManager) {
    }
```

```
class CustomerBrowse1 : StandardLookup<Customer>() {
    @Install(to = "customersTable", subject = "rowStyleProvider")
    private fun customersTableRowStyleProvider(customer: Customer? /*incorrect*/): String? /*correct*/ {
        //
    }
```
