### ISSUE TITLE
Ability to create dynamic attribute with Attribute type = enum class 

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#262]
1) создать в проекте enum
2) через UI создать динамический аттрибут  с этим enum-ом

Результат: создать динамический аттритбут по енум-классу в проекте возможности нет,
Когда выбираем Attribute type = Entity - там только сущности
Когда выбираем Enum - должны задавать значения через запятую 

---
Original issue: https://youtrack.haulmont.com/issue/PL-7847

**Comment by knstvk** [comment]
Need more motivation.
