### ISSUE TITLE
Screen-level actions ignore enabledRule

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#2627]
Relates to #2608

### Environment

- Platform version: 7.2
- Client type: Web

### Description of the bug or enhancement

Example:

Descriptor

```XML
    <actions>
        <action id="showReport" shortcut="CTRL-SHIFT-U"/>
    </actions>
    <layout>
        <button caption="Show report" action="showReport"/>
```

Controller:

```Java
    @Install(to = "showReport", subject = "enabledRule")
    protected boolean showReportEnabledRule() {
        return false;
    }
```

But enabledRule is never called, and button & action remain accessible.

**Comment by MuppetGate** [comment]
Not sure how to vote to fix the problem, but it does seem very inconsistent. It works for dataContainers, but when you apply it anywhere else, it doesn’t work, without warning you that it just doesn’t work.

I think the correct behaviour should trigger the rule whenever an event is fired in the window, but that might cause quite a lot of overhead, or might be difficult to code in the framework (haven’t looked at the code in a while, so I’m guessing).

Going back to what I did to solve the problem: I called action.refreshstate() in the event listener for every component where the enableRule needed calling.

So how about adding an optional parameter to the annotation that would give a list of the components that need to be observed by the rule call? For example:


```
 @Install(to = "addProcessAction", subject = "enabledRule" observe="[processContainerDc, processDateTextField]")
    private fun addProcessActionEnabledRule(): Boolean {

        return true

    }

```
That might work, but there are a couple of immediate problems I can see:

1. The IDE would probably need to allow you to add a rule to any component you wish to observe.
2. You don’t want to run the rule if the field has failed validation.

**Comment by GlebDurygin** [comment]
@MuppetGate thank you for your reply. We will discuss your proposal and let you know the result of the discussion.

**Comment by Flaurite** [comment]
Hello @MuppetGate,

thank you for the proposed solution. Unfortunately, `@Install` annotation is too general for adding action-specific attributes. And it would be very complicated to manage observers for the action.

We came to the conclusion that this problem will not be fixed. In the screen controller only the developer knows from which event the given action will depend on and will refresh the state accordingly.
