### ISSUE TITLE
borderless style of the groupBox is broken

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#2629]
<img width="425" alt="Screenshot 2020-01-13 at 18 16 05" src="https://user-images.githubusercontent.com/7888486/72262849-2cbb6f00-3631-11ea-979d-697c5110ab6f.png">

**Comment by GlebDurygin** [comment]
The predefined styles for `GroupBox` should be used combined with the `showAsPanel` attribute set to `true`.
