### ISSUE TITLE
UI components should be focusable and have an outline in read-only mode

### ISSUE THREAD

**Issue by GlebDurygin** [cuba-platform/cuba#2630]
### Description of the bug or enhancement
Relates to #625
**Read-only components summary table**

Component | Focusable in read-only mode
:------------- | :-------------:
CheckBox | **false**
CheckBoxGroup | **false**
ColorPicker | true
CurrencyField | true
DateField | true
DatePicker | true
FieldGroup | true
FileUploadField | true
Form | true
LookupField | **false**
LookupPickerField | **false**
MaskedField | true
OptionsGroup | **false**
OptionsList | **false**
PasswordField | true
PickerField | true
RadioButtonGroup | **false**
ResizableTextArea | true
RichTextArea | **false**
SearchField | **false**
SearchPickerField | **false**
Slider | **false**
SourceCodeEditor | **false**
SuggestionField | true
SuggestionPickerField | true
TextArea | true
TextField | true
TimeField | true
TokenList | nothing to focus
TwinColumn | **false**

### Updates
The following UI components have become focusable and have an outline in read-only mode:

Component | Appearance in read-only mode
:------------- | :-------------:
CheckBox | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/e341bdc7-9438-4587-a747-3e36c1b6464b)
CheckBoxGroup | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/85570bc6-b971-4764-a8ec-bf5aa55e98a3)
LookupField | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/38100985-5356-40b4-88ea-a432f514c50b)
LookupPickerField | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/ea91937d-e5e4-447b-bbc6-e177cc7afd9d)
OptionsGroup | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/08936db3-27c0-426b-ab0e-b6a1d036ba8e)
OptionsList | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/81f7a359-d020-4f81-a74b-562f743cd5f9)
RadioButtonGroup | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/fd3e11c3-c872-4675-a68b-bca290efff1f)
RichTextArea | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/1a8a7566-3b38-4675-9e3d-9efa05ac5f84)
SearchField | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/9685012f-3555-4b16-a904-3fc2ae2c5550)
SearchPickerField | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/99bf7380-7b43-4b6d-ad49-cfb4671d3380)
Slider | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/c39fb5c4-4d90-426f-95b5-d824b942f514)
SourceCodeEditor | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/3fee324f-78bc-4ebb-be30-d20a8b24f006)
TwinColumn | ![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/894dde75-4abf-4cb0-8f54-544ee724fcd1)

#### Test project
[read-only-ui-components.zip](https://github.com/cuba-platform/cuba/files/4086016/read-only-ui-components.zip)

### QA
Check the above components in read-only mode

**Comment by Mihail063** [comment]
Case 1 
CheckBox, CheckBoxGroup does not have an outline in read-only module in IE and Edge.

Case 2 
Browser: IE, Edge

1. Open UI Components screen 
2. Select any item in the OptionsGroup
![изображение](https://user-images.githubusercontent.com/24281695/73352215-1ad10180-42aa-11ea-88e8-048d3004317d.png)
3. Click on read-only button
![изображение](https://user-images.githubusercontent.com/24281695/73352239-24f30000-42aa-11ea-8343-6bb9679290ba.png)
4. Click on the different item in the OptionsGroup

AR: Selected item was reset
![изображение](https://user-images.githubusercontent.com/24281695/73352268-2d4b3b00-42aa-11ea-9ba3-8b25ecb7bdbd.png)
