### ISSUE TITLE
User substitution lookup layout is broken

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#2636]
### Environment

- Platform version: 7.2-SNAPSHOT

### Description of the bug or enhancement

- Create new project on CUBA 7.2
- Create new user
- Add the new user as a substitution to admin

AR:

The users lookup in the left bottom corner of the screen looks like this:

<img width="266" alt="изображение" src="https://user-images.githubusercontent.com/7888486/72521498-f837f500-3874-11ea-8fef-93a9a4f2ca26.png">

**Comment by dtsaryov** [comment]
Will be fixed in #2456
