### ISSUE TITLE
RefreshAction doesn't clear modified state of DataContext

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2646]
### Environment

- Platform version: 7.1.3

### Description of the bug or enhancement

- Minimal reproducible example

[refresh-action.zip](https://github.com/cuba-platform/cuba/files/4089574/refresh-action.zip)

0. Create a browser screen for an entity.
1. Define the `<data>` element without the `readOnly` attribute.
2. Add the **Refresh** action for a table.
3. Modify some entities programmatically. // `getScreenData().getDataContext().hasChanges()` returns `true`
4. Invoke the **Refresh** action.

- Expected behavior

`getScreenData().getDataContext().hasChanges()` returns `false`

- Actual behavior

`getScreenData().getDataContext().hasChanges()` returns `true`

**Comment by knstvk** [comment]
QA: test on the attached project.
