### ISSUE TITLE
Dependent dynamic attributes

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#265]
When you can filter values for some attribute, based on another attribute in the same category.

---
Original issue: https://youtrack.haulmont.com/issue/PL-7880

**Comment by invviz** [comment]
Now you can specify which attributes the current attribute depends on. When changing the value of one of these attributes, either the script for calculating the attribute value or the script for calculating the list of possible values will be recalculated.

"Depends on" attributes can be specified on the "Calculated values and options" tab of the Attribute editor window.
