### ISSUE TITLE
Default app-login-window looks bad when locale selection is enabled

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#2653]
### Environment

- Platform version: 7.2 
See #2455
1) In Studio create a new app-login-window
2) in project properties add a couple of locales and enable locale selection
3) start the application 
4) look at the left bottom corner where the 'powered by CUBA' and locale selection are located

Probably due to "powered by CUBA" is written from a lowercase letter and it is left-aligned it looks not pretty.

![image](https://user-images.githubusercontent.com/19840141/72969778-a399fa00-3ddf-11ea-86a6-c906d1a663f6.png)

**Comment by web-devel** [comment]
Also add responsive breakpoint  for mobile devices.
See feedback from support [forum](https://www.cuba-platform.ru/discuss/t/login-screen-with-branding-image/3872)
