### ISSUE TITLE
RememberMe token expiration incorrect calculation

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#2654]
See RememberMe mechanism rework #2163

### Environment

- Platform version: 7.2beta1 

### Description of the bug or enhancement

- Minimal reproducible example
1) Set cuba.rememberMeExpirationTimeoutSec = 60
2) Start the application
3) Login with "Remember me" enabled
4) Close the application Tab
5) immediately remove JSESSIONID cookie
6) Open the application URL

 Actual behavior
Login screen appears.

Expiration dates for cookies are correct.
But Platform logic does not work properly.
The time in seconds is added to time in millis in the calculation logic.

![image](https://user-images.githubusercontent.com/19840141/72982563-cab0f580-3df8-11ea-8f15-6da7cc035257.png)

**Comment by dtsaryov** [comment]
Will be fixed in #2163
