### ISSUE TITLE
Support for Java 8 Date/Time API in DatatypeFormatter

### ISSUE THREAD

**Issue by mariodavid** [cuba-platform/cuba#2662]
### Environment

- Platform version: 7.0 - 7.2

### Description of the bug or enhancement
The `DatatypeFormatter` bean has convenience methods for formatting a `java.util.Date`: [public String formatDate(@Nullable Date value)](https://github.com/cuba-platform/cuba/blob/master/modules/global/src/com/haulmont/cuba/core/global/DatatypeFormatter.java#L53).

When using Java 8 Date/Time API via `LocalDate` there is no equivalent of that method in the `DatatypeFormatter`. 

Currently, the only way to format a `LocalDate` e.g.  is by using the `DatatypeRegistry` directly like this:

```
public String formatDate(@Nullable LocalDate value) {
    return datatypeRegistry.getNN(LocalDate.class).format(value, uss.getLocale());
}
```

The idea is to provide additional convenience methods for all Java 8 Date/Time APIs.

**Comment by gorbunkov** [comment]
New methods have been added to `DatatypeFormatter`:
* formatLocalDate
* formatLocalDateTime
* formatLocalTime
* formatOffsetDateTime
* formatOffsetTime
* parseLocalDate
* parseLocalTime
* parseLocalDateTime
* parseOffsetDateTime
* parseOffsetTime
