### ISSUE TITLE
Improve TestContainer and Studio tests template to override beans in tests easier

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2672]
### Environment
CUBA 7.2 beta
Working sample project: attached
[cuba72tests.zip](https://github.com/cuba-platform/cuba/files/4132976/cuba72tests.zip)

### Description of the bug or enhancement
See forum topic: https://www.cuba-platform.com/discuss/t/cuba-7-overriding-bean-in-integration-tests/11130/10

See com.company.cuba72tests.core.SampleIntegrationTest in sample project.

When writing app-core integration tests it is often necessary to override bean implementations (e.g. integration gates).
Sometimes project or project's tests also override CUBA infrastructure beans.

Currently it's not obvious for beginners how to set up overriding in tests.

1) To override beans in tests, you have to:
- create test-spring.xml
- create test-app.properties
- put "cuba.springContextConfig = +project-spring.xml project-tests-spring.xml" to test-app.properties
- mention test-app.properties it in the Cuba72testsTestContainer class

2) If you want to override beans mentioned in the CUBA's com/haulmont/cuba/testsupport/test-spring.xml (Emailer, UserSessionSource, ClusterManager) - things get even worse.
Because it's hardcoded in the com.haulmont.cuba.testsupport.TestContainer that CUBA's test-spring.xml is the last spring context file in the chain.

What we can do to make start easier:
- provide extension points in TestContainer class
- extend Studio's integration tests template

**Comment by gorbunkov** [comment]
Studio issue: https://youtrack.cuba-platform.com/issue/STUDIO-7869
