### ISSUE TITLE
TextField style inline-icon works incorrectly when a field has alignment

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#2676]
### Environment
- Platform version: 7.1
- Client type: Web
### Description of the bug or enhancement
- Minimal reproducible example
You can try the following layout:
```
<layout width="100%" height="AUTO">
    <textField id="field1"
               align="MIDDLE_CENTER"
               icon="ANGLE_DOUBLE_DOWN"
               stylename="inline-icon"/>
    <textField id="field2"
               align="MIDDLE_CENTER"
               icon="ANGLE_DOUBLE_UP"
               stylename="inline-icon"/>
</layout>
```
- Actual behavior
![image](https://user-images.githubusercontent.com/22093943/73652062-5a7b5d00-469f-11ea-9977-98dad85ee3d7.png)

### Solution
* **Font icon**
![image](https://user-images.githubusercontent.com/35256248/74510225-c3bf6380-4f1c-11ea-9c40-91a1ff51c86e.png)
* **Image icon**
![image](https://user-images.githubusercontent.com/35256248/74510276-df2a6e80-4f1c-11ea-9213-a14b36ab546d.png)

### QA
Check the above case with font and image icons (png, svg, etc.)

**Comment by Flaurite** [comment]
Also, pls check Havana theme. Icons are misaligned to down:
![image](https://user-images.githubusercontent.com/22093943/73659758-5146bc00-46b0-11ea-996f-38607f03f018.png)

**Comment by skatova** [comment]
The problem still reproduced
