### ISSUE TITLE
Properties  file with BOM  can't be read correctly

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/cuba#2681]
### Environment

- Platform version: 6.8

### Description of the bug or enhancement

If a properties file is edited with windows Notepad,  it will be inserted  a BOM . In this case, the property at first line will not be read correctly.
For example,in screenshot  below,  this file edited with Notepad,the 'cuba.web.externalAuthentication' property will not works.

![image](https://user-images.githubusercontent.com/1725996/73932196-d03c2e80-4914-11ea-9560-eb0088cf9657.png)

Suggest  enhance the reading of properties file, check if there is BOM in properties file.

**Comment by knstvk** [comment]
Fixed in https://github.com/cuba-platform/cuba/issues/1827
