### ISSUE TITLE
Annoying autocomplete in LookupField in Chrome

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#271]
See: 
- https://bugs.chromium.org/p/chromium/issues/detail?id=468153
- https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
- https://bugs.chromium.org/p/chromium/issues/detail?id=587466

**Comment by jreznot** [comment]
Will be fixed with Vaadin 8.4.4
See https://github.com/vaadin/framework/compare/8.4.3...8.4.4

**Comment by natfirst** [comment]
Still reproduce
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/5a97eda5-b813-40d4-9195-ac4213bf93da)

**Comment by glebfox** [comment]
Fixed in https://github.com/cuba-platform/cuba/issues/2075
