### ISSUE TITLE
ScreenComponentAccess annotation has wrong attributes

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#2713]
Right now, the `@ScreenComponentAccess` annotation has two attributes:

* allow
* deny

But in the role UI editor the permission to screen component access may have one of 3 values:

* read-only
* hide
* edit

The `@ScreenComponentAccess` similar to the `@EntityAttributeAccess` should have the following attributes:

```java
@ScreenComponentAccess(
    deny = {"attr1", "attr2"}, 
    view = {"attr3", "attr4"}, 
    modify = {"attr5", "attr6"}
)
```

**Comment by andreysubbotin** [comment]
For QA: check UI component permissions for design and runtime roles
