### ISSUE TITLE
User with denying role and necessary read permissions cannot view the permissions on RoleEdit screen

### ISSUE THREAD

**Issue by GlebDurygin** [cuba-platform/cuba#2718]
### Environment

- Platform version: 7.1+

### Description of the bug or enhancement

Forum topic - https://www.cuba-platform.com/discuss/t/how-to-create-an-internal-audit-role/11428

**Case 1**

- Minimal reproducible example

1) Create denying role with following permissions for screens:
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/8f683468-7cca-4a0e-9ac0-d35f8f1a7d8a)
and for entities:
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/a074ff5e-d76f-49d2-a251-c86235d561f5)
2) Create an **audit** user with password **audit**
3) Login as **audit** user
4) Open Role browser
5) Open `AuditRole`

- Expected behavior
The permission frames should be shown for **audit** user

- Actual behavior
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/43dd06e6-7364-455e-a061-eda8b0b24ca1)

The column with `sec$Target` type is not visible because the `security.isEntityAttrReadPermitted()` method in `WebAbstractTable#getInitialVisibleColumnIds` returns `false`. This is due to the fact that the `metadata` cannot find `sec$Target` class and throws exception (see `UserSessionManager#convertToExtendedEntityTarget`), therefore the `sec$Target` class is not added to the list of permissions.

#### Possible solution 1:
Change the implementation of the `UserSessionManager#convertToExtendedEntityTarget` method to the following:
```
protected String convertToExtendedEntityTarget(Permission permission) {
    if (permission.getType() == PermissionType.ENTITY_OP || permission.getType() == PermissionType.ENTITY_ATTR) {
        String target = permission.getTarget();
        int pos = target.indexOf(Permission.TARGET_PATH_DELIMETER);
        if (pos > -1) {
            String entityName = target.substring(0, pos);
            MetaClass originalClass = metadata.getClass(entityName);
            if (originalClass != null) {
                Class extendedClass = metadata.getExtendedEntities().getExtendedClass(originalClass);
                if (extendedClass != null) {
                    MetaClass extMetaClass = metadata.getClassNN(extendedClass);
                    return extMetaClass.getName() + Permission.TARGET_PATH_DELIMETER + target.substring(pos + 1);
                }
            }
        }
    }
    return null;
}
```
#### Possible solution 2:
Move `Target` classes from `gui-metadata.xml` to `metadata.xml`

#### Test project
[internal-audit-role.zip](https://github.com/cuba-platform/cuba/files/4230066/internal-audit-role.zip)

**Case 2**

- Minimal reproducible example

1) Create a role **role** and add rights: for a Sreens tab set **allow** for **Application**, **Roles**, for a **Entities** tab set **allow [all]** for an entity **Role**, for a **Attributes** tab set **modify [all]** for an entity **Role**
2) Create an **user** user with password **user**, add a role **role**
3) Login as **user** user
4) Open Role browser
5) Click Create or select a row and click Edit

- Expected behavior
User can create new role and edit others

- Actual behavior
Access denied

**Comment by Mihail063** [comment]
Case 2 still reproduece

**Comment by soraksh** [comment]
Case 2 is actually not a bug. You should allow Role Editor screen for user to let him edit roles. Otherwise he cannot open editor screen.
