### ISSUE TITLE
Toggling editable mode in dateField with custom resolution resets value

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/cuba#2719]
See the [demo project](https://github.com/cuba-platform/cuba/files/4230575/untitled2.zip)

* Open Application -> DemoEntity.browse2 -> Edit some entity.
* Input date to the second dateField and press `CopyDate`.
* Use check box which toggles editable mode of top date field.

AR: date field value in editable mode resets to some unrelated

See the [topic](https://www.cuba-platform.com/discuss/t/datefield-pick-bug/11489) on the support forum.

**Comment by Flaurite** [comment]
Fixed in Vaadin 8.10 version: https://github.com/vaadin/framework/issues/11864

**Comment by Flaurite** [comment]
Related to: [cuba-platform/cuba#2740](https://github.com/cuba-platform/cuba/issues/2740)

**Comment by Flaurite** [comment]
### For QA
In addition to the above case, pls check the following:
1) Add dateField to the screen:
```
<dateField id="dateField"
           rangeStart="2020-03-15"
           caption="DateField"/>
```
2) Open screen and click on dateField button to show popup. It should be shown.
