### ISSUE TITLE
Add logo icon in SVG format

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#2728]
### Environment
- Platform version: 7.2
- Client type: Web

### Description of the bug or enhancement
The main idea is to add the SVG variant of a logo but does not change the links in themes that point at the png icon for backward compatibility.

### For QA
1. Create new project;
2. In main message pack change: app-icon-login.png -> app-icon-login.svg. It occures, because Studio does not change project template. It will be fixed later.
3. Check that logo and "powered by" icons are svg.
4. Check havana, hover or halo theme that logo icon is shown correctly (there is no some unusual scaling). Check in other browsers (Safari, IE11, Edge, Chrome, Firefox).

**Comment by natfirst** [comment]
Icon is too big in havana theme:
![image](https://user-images.githubusercontent.com/17950251/75441298-da32d980-5976-11ea-979d-0e7b7c98c1ae.png)

**Comment by natfirst** [comment]
Icon is blurred in havana theme
![image](https://user-images.githubusercontent.com/17950251/75443082-1fa4d600-597a-11ea-834f-56977813ef23.png)
