### ISSUE TITLE
Unable to add tab with null child component

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#273]
Following code throws NullPointerException:

```
tabSheet.addTab("tabCaption", null);
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-8030

## Updates
The above code throws `IllegalArgumentException` with an error message "Child component cannot be null"

## QA
Check the above case

**Comment by jreznot** [comment]
Let's simply throw a correct `IllegalArgumentException` with explanation.
