### ISSUE TITLE
CollectionPropertyContainerImpl.replaceItem() does not replaces the item in underlying collection property

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#2733]
### Environment

- Platform version: 7.1.4

### Description of the bug or enhancement

As a result, the object graph can get inconsistent which leads to the problem described in [this forum post](https://www.cuba-platform.com/discuss/t/problems-using-datacontext-merge-t-entity/11169/4).

**Comment by knstvk** [comment]
QA: smoke-test composition editing.

**Comment by natfirst** [comment]
1. Use demo project from topic
2. Create master, save
3. Open for editing, add one detain
*A.R.* Rows are duplicated
![image](https://user-images.githubusercontent.com/17950251/75454380-c5624000-598e-11ea-942e-1000f9116d60.png)

4. Delete all added details, click OK
5. Open master for editing
*A.R.* Details will be displayed in the table
