### ISSUE TITLE
Add troubleshooting info for "Service xxx is not registered in LocalServiceDirectory" errors

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2736]
### Description of the bug or enhancement
Example topic, as many others:
https://www.cuba-platform.com/discuss/t/http-localhost-8080-app-error/11569?u=alexbudarov

Last exception in chain has the following message:
```
java.lang.IllegalArgumentException: Service app-core/cuba_LocalizedMessageService is not registered in LocalServiceDirectory
```

Newbies often don't understand that they should search for other error message before in the log file.
Other problem is that Tomcat writes startup errors to several log files: catalina.log, localhost.log, catalina.out. It makes troubleshooting longer.

I think we can provider better troubleshooting information, at least for single-war and fast-deployment (that is: for LocalServiceProxy between web and core).

1) If middleware fails to start - register in some shared-lib class full fail stack trace (and web context name).

2) Register web context names of all successfully started middlewares.

3) Before context start, for debugging purposes, explicitly write log message with: cuba.webContextName, servletContext.getContextPath() and singleWar flag.
Now it's often not obvious which web app given log messages correspond to.

4) In situation "Service app-core/cuba_LocalizedMessageService is not registered in LocalServiceDirectory" add more information to the exception:
- list of successfully started middleware context-names (case: wrong cuba.webContextName or cuba.connectionUrlList properties)
- attach remembered fail stack trace if target middleware failed to start. Ideally - attach as exception cause.

**Comment by knstvk** [comment]
Related to #2377, #225

**Comment by alexbudarov** [comment]
Yet another case of the:
> I see some internal "Service XXX is not regigtered in LocalServiceDirectory" error in the log and I don't bother myself to dig further

https://www.cuba-platform.com/discuss/t/no-answer-for-access-token-request/11618/9?u=alexbudarov

**Comment by alexbudarov** [comment]
Another one "Caused by: java.lang.IllegalArgumentException: Service app-core/cuba_TrustedClientService is not registered in LocalServiceDirectory"

https://www.cuba-platform.ru/discuss/t/oshibka-unable-to-login-as-anonymous/3999

**Comment by alexbudarov** [comment]
What was done:
1) Added info messages on server start, to help analyzing web context names by server logs:
```
(example for single war)
19:18:59.145 INFO  c.h.c.c.s.s.SingleAppCoreServletListener- Single WAR core initializing, servlet context path: /app
19:18:59.173 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - Initializing 'core' block, servlet context path: /app
...
19:18:59.296 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - cuba.webContextName: app-core

...
19:19:08.942 INFO  c.h.c.w.s.s.SingleAppWebServletListener - Single WAR web initializing, servlet context path: /app
19:19:08.958 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - Initializing 'web' block, servlet context path: /app
...
19:19:08.984 INFO  c.h.c.c.s.AbstractWebAppContextLoader   - cuba.webContextName: app

```

2) When opening login screen, try to ping middleware first before obtaining anonymous session.
To distinguish between problems "middleware is not accessible" and "Unable login as anonymous!".

3) Distinguish four types of "Service xxx is not registered in LocalServiceDirectory" occuring for local service invocation (cuba.useLocalServiceInvocation = true and types of deployment: fast deployment, single war, single uber jar).
Formulate better error messages for each situation:
- Middleware works but myapp_MyService is really not registered (e.g. not marked as @Service)
- Middleware startup failed
- Not coordinated values "cuba.connectionUrlList" on web and "cuba.webContextName" on core
- Middleware is not found at all among web apps

4) Display exception stack trace in the "Unexpected error" startup screen.
If middleware startup failed then stack trace includes startup fail exception.
![image](https://user-images.githubusercontent.com/6158807/77181634-0c9ea500-6ae5-11ea-94f1-84831b897108.png)

**Comment by alexbudarov** [comment]
QA
Check:
- fast-deployment with local service invocation enabled
- single war
- single uber jar

Situations:
- startup success
- various middleware startup errors. 

E.g.
- malformed core spring.xml
- inaccessible main data store
- database update failed
- cuba.webContextName in core module was changed without changing cuba.connectionUrlList
- app-core is deleted from tomcat at all

"Unexpected error" startup screen should show adequate information.
If cuba.web.productionMode is set to true, then all details should be hidden in UI.
