### ISSUE TITLE
TimeField does not apply error style when it is required

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#2748]
# Environment
- Platform version: 7.2.0
- Client type: Web
### Description of the bug or enhancement
- Minimal reproducible example
1) Add timeField to the screen
2) Make it required: required=true

- Actual behavior
![image](https://user-images.githubusercontent.com/22093943/75956430-52e2ea00-5ed1-11ea-86ab-2206819b3410.png)

Related to: [cuba-platform/cuba#2347](https://github.com/cuba-platform/cuba/issues/2347)

### For QA
In addition to above case. Pls check the following:
1) Add timeField to the screen (not required, just timeField)
2) Enter value
3) Then try to clear it
Make sure that there is no NPE.

**Comment by glebfox** [comment]
Also, check that `TimeField` with `Am/Pm` field has the correct `required` styles.
