### ISSUE TITLE
Large table with lots of columns is deformated with screen scaling

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#2764]
### Environment

- Platform version: 7.2.1
- Browser:  Google Chrome 80.0.3987.132
- Operating system: Windows 10

### Description of the bug or enhancement

- Minimal reproducible example
Use the sample project:
[https://app.zenhub.com/files/54624511/2f9a0fd6-65b0-4cb0-b596-f69fed92097d/download](https://app.zenhub.com/files/54624511/2f9a0fd6-65b0-4cb0-b596-f69fed92097d/download)

There is an entity with lots of properties and standard CRUD screens for it.

1) Change the scale of the screen to 125%
2) Set browser scale to 110%
3) Start the application 
4) Open Chrome *not in fullscreen* mode
5) Open Application -> GreatEnt browser

- Actual behavior
 7.2, design of tables not correct
![image](https://user-images.githubusercontent.com/22093943/76734510-839e0b80-677c-11ea-909a-30cd066a7e60.png)

**Comment by Flaurite** [comment]
### Changes
In some cases when we scroll to the right we can see misalignement columns on one pixel. This problem does not have any simple fix and won't be fixed.
### For QA
In all browser:
1. Check Table, GroupTable, TreeTable with above case and in normal scaling.
2. For GroupTable try to group columns and ungroup - there should be no misalignment
3. Try to add aggregation, generated column and make sure it works fine.
4. Your cases..
