### ISSUE TITLE
The parameter field is not changed to list, when changing the filter operator to 'in' if the filter was edited

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#2771]
### Environment

- Platform version: 7.1.5, 7.2-SNAPSHOT
- Windows 10
- Google chrome  80.0.3987.132

### Description of the bug or enhancement

- Minimal reproducible example
1) Open Administration-Users
2) Add some condition to filter. By the "Created At" field, for instance. See the operator is "=" and the field allows input of only a single value.
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/f0617a01-1af4-4e7c-9837-288d3b39676f)
3) Open the filter editor
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/191d933d-b085-4454-b045-6dcd1243d8f1)

4) Do not change anything - just press Cancel
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/897569d0-6eb4-4973-8d0d-783ada6da03a)
5) Then change the operator from "=" to "in"

- Actual behavior
The parameter field left the same as for a single value, however, the list is expected here.
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/76a7db9a-2cd7-4326-8ded-75419266c552)

**Comment by Flaurite** [comment]
### For QA
Additionally please check case from this issue: [cuba-platform/cuba#2242](https://github.com/cuba-platform/cuba/issues/2242).
