### ISSUE TITLE
Implement CalendarDayClickEvent

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2772]
### Description of the bug or enhancement

Implement a click listener on a calendar surface that provides information about date and time (for weekly and day view).

---

See: https://www.cuba-platform.com/discuss/t/a-couple-of-calendar-control-questions/11620

**Comment by Flaurite** [comment]
### Changes

Added new event for Calendar: `CalendarDayClickEvent<V>`. It works both for MONTH view and for WEEK view (day view). 

To add listener use:
```
Subscription addDayClickListener(Consumer<CalendarDayClickEvent<V>> listener);
```

The event object will return date with time (if calendar value type supports). MONTH view does not provide a time value.

### For QA
1. Check new that new event works;
2. Check it with other events;
3. Make sure that it works in all browsers;
4. Your cases
