### ISSUE TITLE
Saved Parameter Values Cleared Out When Changing Operator

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/cuba#2773]
See https://www.cuba-platform.com/discuss/t/saved-parameter-values-cleared-out-when-changing-operator/11720

### Environment

- Platform version: 7.1.5  (does not occur in 7.2)

### Description of the bug or enhancement

- Minimal reproducible example
Use the project [https://app.zenhub.com/files/54624511/4e94f795-29a7-4e28-bb49-3cd4c1837c8d/download](https://app.zenhub.com/files/54624511/4e94f795-29a7-4e28-bb49-3cd4c1837c8d/download)

1) Open Linkers browser
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/ab996f74-fe65-4431-aec8-dfffac484678)
2) Open the *saved with values* filter "fwithvalues"
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/a2016d84-b0dc-4c91-ae8a-ea1543636326)
3) change the operator of any condition to "In"

- Actual behavior 
At the moment the operator is changed (and the field is changed to List) the saved values of some other fields are cleared too.
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/3b7ec51d-1792-4f91-b0b3-19bc751f2cef)
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/3660cab1-680d-430c-a76f-7caa66b2aeac)

**Comment by Flaurite** [comment]
Migrate fix from: [cuba-platform/cuba#2539](https://github.com/cuba-platform/cuba/issues/2539)
