### ISSUE TITLE
Add 'addItems' method to CollectionContainer and it's realizations

### ISSUE THREAD

**Issue by DukeKan** [cuba-platform/cuba#2810]
### Environment

- Platform version: 7.1.3
- Client type: Web

### Description of the bug or enhancement
Now CollectionContainer  contains only 'setItems' method for including items to the container. It would be helpful to add method for adding items to the container, for instance:

`void addItems(@Nullable Collection<E> entities);`

**Comment by knstvk** [comment]
Use `getMutableItems().add()` for this purpose.
