### ISSUE TITLE
Specific, UI tabs are not available in Role editor if Multitenancy addon used in project

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2819]
### Environment

- Platform version: 7.2.3
- Forum topic https://www.cuba-platform.com/discuss/t/generic-filter-which-screens-entities-and-attributes-for-a-security-role-need-to-be-set/12046

### Description of the bug or enhancement

1. Create a new project
2. Run the app, create a new Role, check, that all tabs are available (Screens, Entities, Attributes, Specific, UI)
3. Add Multitenancy addon v.2.0.0
4. Update DB and run the app again
5. Open role for editing or create a new one

*A.R.* Specific, UI tabs are not available
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/aff77bbd-1187-4088-bafb-06d02497519b)

**Comment by andreysubbotin** [comment]
Duplicate: cuba-platform/multitenancy-addon#42
