### ISSUE TITLE
Remove "S" generic parameter from ScreenFacet and its descendants

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2824]
### Environment

- Platform version: 7.2

### Description of the bug or enhancement
ScreenFacet, EditorScreenFacet and LookupScreenFacet are parameterized with "S extends Screen" parameter.

This parameter is not used anywhere in the API (events, delegates, other methods called by developer).

One might think that S can be used to create method delegates, accepting screen instance and calling S's methods.
But there are no such events or delegates. AfterShowEvent and AfterCloseEvent accept raw Screen class.
Screen parameters are implemented through separate collection: 
com.haulmont.cuba.gui.components.ScreenFacet#setProperties and com.haulmont.cuba.gui.components.ScreenFacet#setOptionsProvider

So this parameter makes Studio's and developer's work harder and does not add any value.

It would be great just to remove it.

**Comment by web-devel** [comment]
Consider the following example:

```
    @Inject
    private ScreenFacet<TestScreen> testScreen;

    @Subscribe("openTestScreenBtn")
    public void onOpenTestScreenClick(Button.ClickEvent event) {
        testScreen.show()
                .setNum(42);
    }
```

There are `show()` and `create()` methods which return screen instance. Those can be used to open screens programmatically since declarative `onButton` and `onAction` are quite limited.
