### ISSUE TITLE
Nested objects don't receive null values when merged into DataContext

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#2828]
### Environment

- Platform version: 7.2.3

### Description of the bug or enhancement

Origin: https://www.cuba-platform.ru/discuss/t/zagruzchik-na-ekrane-ne-vsegda-zagruzhaet-aktualnye-znacheniya-atributov-zakazannyh-v-predstavlenii/4191

[testnullattribute.zip](https://github.com/cuba-platform/cuba/files/4485459/testnullattribute.zip)

- Minimal reproducible example

1. Open **Schedule Editor**
2. Open **Entity Inspector** and load **Orders**
2.1. Edit an **order** with no **Delivery Date** and commit
3. Go back to the opened **Schedule Editor** and refresh **Schedule Items** table
_Result:_ the table displays entered **Delivery Date**
4. Go back to the **Entity Inspector**
4.1. Edit the same **Order**
4.2. Remove **Delivery Date** and commit
5. Go back to the opened **Schedule Editor** and refresh **Schedule Items** table

- Expected behavior

The table displays no **Delivery Date** for the edited Order.

- Actual behavior

The table still displays **Delivery Date** for the edited Order. Note that `order.version` has changed.

**Comment by knstvk** [comment]
To QA: check editing of compositions.
