### ISSUE TITLE
Design time role might not work for services

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#2830]
### Environment

- Platform version: 7.2.3
- Client type: Web
- Browser: Chrome
- Database: HSQL
- Operating system: Windows 10

### Description of the bug or enhancement

STR: 
* Checkout application from https://github.com/cuba-platform/sample-session-planner/tree/designtime_security  and run it. Create one speaker and one session for this speaker. 
* Create user "homer" and assign only one role - Participant. This role has read-only permissions for sessions and speakers
* Log in to the application using user "homer" 
* Open "Sessions" window and move session in the calendar. Switch to the second tab

ER:
* Session should not be changed

AR: 
* Session start time and end time changed

**Comment by aleksey-stukalov** [comment]
It is expected behaviour when using `DataManager` on the core module. Check `com.haulmont.cuba.core.global.DataManager#secure` if it is required to apply security on the server side.
