### ISSUE TITLE
Ubuntu 20.04 cuba 7.2.1 Hotkey (ctrl+tab)

### ISSUE THREAD

**Issue by aosivt** [cuba-platform/cuba#2835]
### Environment

- Platform version: 7.2.1 
- Client type: Portal
- Browser: Chrome, etc.
- Database: PostgreSQL
- Operating system: Ubuntu 20.04 Linux 

### Description of the bug or enhancement

Добрый день.
При использовании cuba plugin idea jetbrains в ОС Ubuntu 20.04 происходит отключение клавиатуры после использовании переключения между вкладками открытых файлов (ctr+tab).
В ранних версиях ubuntu такой проблемы нет (19.10). 

[100_sys_log.txt](https://github.com/cuba-platform/cuba/files/4500882/100_sys_log.txt)

**Comment by alexbudarov** [comment]
Hi,
You are using an outdated plugin version (12.3).
Please update your CUBA plugin to the latest release that supports IDEA 2020.1: release 13.2.

**Comment by aosivt** [comment]
Добрый день. Установил последнее обновление но ошибка так и проявляет себя
- т.е. дело все таки не в обновлении.
Как можно решить данную проблему?

пн, 20 апр. 2020 г. в 13:51, Alexander <notifications@github.com>:

**Comment by alexbudarov** [comment]
Please report Studio-related problems to the forum:
https://www.cuba-platform.ru/discuss/
https://www.cuba-platform.com/discuss/

Also please attach error stack trace, obtained with latest Studio plugin version (13.2).

**Comment by aosivt** [comment]
[idea.log](https://github.com/cuba-platform/cuba/files/4503267/idea.log)

**Comment by alexbudarov** [comment]
I don't see CUBA-plugin-related exceptions in this log file.

**Comment by aosivt** [comment]
Добрый день, Александр.

По данному вопросу уже было обращение в компанию jetbrains (#2588574) и при оценки логов было выявлено, что после установки плагина cuba проявляется данная ошибка. Таким образом создал данное обращение в вашу компанию.
В том то и дело, что на 19.10, данная ошибка не возникает, в отличие от 20.04.

This issue has already been addressed to the company jetbrains (#2588574) and when evaluating logs, it was found that after installing the Cuba plugin, this error appears. This is how I created this request to your company.
The thing is that on 19.10, this error does not occur, unlike 20.04.

**Comment by alexbudarov** [comment]
Hi @aosivt 
Please create topic on the russian forum: https://www.cuba-platform.ru/discuss/

This is an issue tracker for the framework. Studio-related problems should be discussed on the forum. I won't answer to this github issue anymore.

Please attach to the forum topic the following information:
- idea.log log file
- Information from the CUBA -> Welcome -> Product Versions -> Copy screen.
- error from the syslog, after you have updated the plugin. Previous syslog does not provide valuable information, because plugin version 12.3 did not support IDEA 2020.1 at all.

**Comment by alexbudarov** [comment]
P.S. I personally right now am working from the Ubuntu 20.04 machine:

```
alexander@alexander-home:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

I don't have any problems, that's why I assume that the problem is not related to the Ubuntu version, and need extra information.
