### ISSUE TITLE
The "related" attribute in MetaProperty should trim spaces

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#2837]
The code below causes exception in runtime because space is not trimmed. And there is a property ```duration``` defined in the entity.

```java
    @MetaProperty(related = "startDate, duration")
    public LocalDateTime getEndDate() {
        return (startDate == null || duration == null)?null:startDate.plusHours(duration);
    }
```

### Environment

- Platform version: 7.2.3 

CUBA Platform version: 7.2.3
CUBA Studio plugin version: 13.2-191
IntelliJ version: CUBA Studio 2019.2

**Comment by knstvk** [comment]
The `related` annotation attribute is defined as an array, but in the docs and in the implementation it assumes a comma-separated string. Make all this consistent without breaking compatibility.
