### ISSUE TITLE
Implement method com.haulmont.cuba.core.global.Security#isSuperUser

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#284]
The method will allow to detect if the user is super user.
Platform should use the method in :
- com.haulmont.cuba.security.global.UserSession#isPermitted(com.haulmont.cuba.security.entity.PermissionType, java.lang.String, int)
- com.haulmont.cuba.security.sys.UserSessionManager#compilePermissions
- com.haulmont.reports.gui.ReportGuiManager#checkRoles

---
Original issue: https://youtrack.haulmont.com/issue/PL-8085

**Comment by knstvk** [comment]
It's unclear what SuperUser is. A user with no restrictive permissions?
