### ISSUE TITLE
View action button stays inactive after selecting an item in the table for composition entity

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2840]
### Environment

- Platform version: 7.2.3
- Forum link: https://www.cuba-platform.com/discuss/t/security-role-for-composition-not-working-correctly/12040

### Description of the bug or enhancement

- See attached project
- Two entities Pallete and PalleteItem with ONE_TO_MANY composition and generated screens
- Run project, login with test/1 user (this user has read-only permission for these entities)
- Open Pallete browser, open item for view
- Select PalleteItem

*A.R.* View button will be inactive

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/b8f61c0b-2d8e-44d5-b367-397de2c45d33)

[demo-role.zip](https://app.zenhub.com/files/54624511/2514f156-f644-47c0-aaa6-7014ca3b7169/download)

**Comment by gb91757** [comment]
Is there any way I can start to look at this issue?  Has the area of code been identified so I can start to look for myself?

**Comment by glebfox** [comment]
Caused by: #2459
