### ISSUE TITLE
Add StudioProperty annotations to SecuredListAction

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#2845]
### Environment
- Platform version: 7.2

### Description of the bug or enhancement
com.haulmont.cuba.gui.actions.list.SecuredListAction
constraintCode and constraintOperationType properties are working fine for EditAction, RemoveAction etc.
They also exist in XSD.

But these properties currently don't appear in Studio's component inspector panel because they are not annotated.

**Comment by maistrenkoIulia** [comment]
need to revert changes.
will be implemented on Studio side

**Comment by alexbudarov** [comment]
I didn't realize that annotated properties will be added to XML as sub-tags of the "properties" tag.
So now with annotations we have duplication of the same attributes: xml attributes and sub-tags generated by Studio.

**Comment by alexbudarov** [comment]
created https://youtrack.haulmont.com/issue/STUDIO-8927 instead
