### ISSUE TITLE
Lack of logic in localization of the error messages, which appears when a session is expired

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#285]
See https://www.cuba-platform.ru/support/topic/ошибки-локализации-и-локали

*Case One:*
1) create a project only with English 
2) start the project
3) open the UI in Russian-localized browser
4) Press F12 and find the javascript which contains comErrMsg, authErrMsg, sessExpMsg

The messages are on the Russian language.
If the session expires, the corresponding error message will be displayed on Russian

5) Refresh the page(F5)
6) Press F12 and find the javascript which contains comErrMsg, authErrMsg, sessExpMsg

AR: The messages are on English. 

*Case Two:*
1) enable the second (Russian) language
2) create two users: User1, with Russian, User2, with English
3) open the UI in Russian-localized browser
4) log in by the user with English language
5) wait for the session expiration

AR: the error message is on Russian.

Press the message -> the page is refreshed and the error messages are on English from the moment

ER: The error message should not depend on the user.

Note: authErrorMsg is not localized(not presented in the CUBA messages_ru.properties)

---
Original issue: https://youtrack.haulmont.com/issue/PL-8095

**Comment by natfirst** [comment]
Problems reproduced in both cases

**Comment by natfirst** [comment]
Reopened: still reproduced

**Comment by dtsaryov** [comment]
Studio issue to impove locales editor dialog [YouTrack](https://youtrack.cuba-platform.com/issue/STUDIO-6672)
