### ISSUE TITLE
Add card value to the groupBoxStylename enumeration in layout.xsd 

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/cuba#2859]
### Environment

- Platform version: 7.1
- Operating system: Windows

### Description of the bug or enhancement

The `groupBox` component has a predefined stylename value in XML - **card **.

### QA

Check that the user can set a **card** stylename value in XML.

**Comment by Flaurite** [comment]
GroupBox does not have predefined "card" style. See: [documentation#706](https://github.com/cuba-platform/documentation/issues/706).
