### ISSUE TITLE
Cannot edit default value of a filter field if it is a reference

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#2873]
### Environment

- Platform version: 7.2.4

### Description of the bug or enhancement

See the project attached. You cannot select Order value for the default filter on the Customer browse screen.
[defaultfiltervalue.zip](https://github.com/cuba-platform/cuba/files/4605729/defaultfiltervalue.zip)

**Comment by bresche** [comment]
I tried it in platform version 7.1.6 and 7.2.4. The bug is in both versions. Do you fix it in version 7.1?

**Comment by knstvk** [comment]
@bresche Yes, I have changed Milestone to 7.1.
