### ISSUE TITLE
Enter key Does not work in RichTextArea if any opened screen contains Enter shortcut

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#2874]
### Environment
- Platform version: 7.2
- Client type: Web
### Description of the bug or enhancement
- Minimal reproducible example

Download attached project: [richdemo.zip](https://github.com/cuba-platform/cuba/files/4615981/richdemo.zip)
1. Open CustomerBrowse screen;
2. Create Customer;
3. In the opened editor try to type in RichTextArea then press "Enter" to move the carriage to the next row.
- Expected behavior
Carriage is moved to the next row
- Actual behavior
Carriage **is not** moved and ValueChangeEvent is fired.

### Technical details
It turns out that "Enter" key combination belongs to the Edit action in the CustomerBrowse screen.
When we press enter on RichTextArea above shortcut is fired on the client-side. It takes the current connector which is RichTextAreaConnector and calls flush(). But when flush() is called RichTextAreaConnector sends value to the server-side which fire ValueChangeEvent.

**Comment by pakuda** [comment]
Hi, is there any news on this one ? Thanks !

**Comment by Flaurite** [comment]
Hello @pakuda,
Sorry for the long delay. We will try to fix it in the next bugfix release (7.2.6), but we cannot guarantee it, because this is a component's architecture bug (at first glance).

**Comment by pakuda** [comment]
Thanks for the update @Flaurite !

**Comment by maistrenkoIulia** [comment]
TC1:
edit existed customer ->type in RichTextArea -> press "Enter" - OK
TC2:
create new customer ->type in RichTextArea ->press "Enter" - NOK (reproduced)
versions 7.2-snapshot, 7.3-snapshot
