### ISSUE TITLE
Dynamic attribute editor. Wrong position of context help icon in Safari

### ISSUE THREAD

**Issue by WildChildCode** [cuba-platform/cuba#2877]
### Environment

- Platform version: 7.1.4, 7.2-SNAPSHOT (have not tried other versions)
- Client type: Web
- Browser: Safari 13.1
- Database: PostgreSQL 11
- Operating system: macOS 10.15.4
- Screen Resolution: 1440x900

### Description of the bug or enhancement

Wrong position of validation script's context help icon on attribute editor's "General" tab.
![DynAttrEditor](https://user-images.githubusercontent.com/8769220/81787534-4357d100-9512-11ea-8540-56474e33971e.png)

### QA
Check the correct display of the context help icon for the different components inside the `Form` and `FieldGroup` components. Try to set different values of `captionPosition` XML attribute of `Form` component. Check this case for all themes.

**Comment by maistrenkoIulia** [comment]
for 7.3-SNAPSHOT - OK
for 7.2-SNAPSHOT - **NOK** (reproduced)
