### ISSUE TITLE
Сursor highlight does not turn off in Desktop in SourceCodeEditor

### ISSUE THREAD

**Issue by Aknodl** [cuba-platform/cuba#2879]
- Platform version: 6.10.16

### Description of the bug or enhancement

![image](https://user-images.githubusercontent.com/56048116/81945076-aa5ab000-960e-11ea-81e3-a84f0673ff65.png)
![image](https://user-images.githubusercontent.com/56048116/81945152-c3636100-960e-11ea-9be2-0e618b5de512.png)

**Comment by natfirst** [comment]
For QA: have to use the old version of Studio for testing.
1. Download Studio v.6.10.3 from https://www.cuba-platform.com/download/previous-studio/
2. Create a new project on a related platform version
3. Create a desktop module in the project
![image](https://user-images.githubusercontent.com/17950251/87536451-325e4400-c6aa-11ea-9ba6-035bb8dc4180.png)
4. Create a screen in a desktop module and add a code
![image](https://user-images.githubusercontent.com/17950251/87536538-53269980-c6aa-11ea-960f-ac4fc393b60d.png)
5. Click Run - Deploy desktop WebStart and wait for a while
![image](https://user-images.githubusercontent.com/17950251/87536651-7cdfc080-c6aa-11ea-8194-21b2b74af402.png)
6. Start the app 
![image](https://user-images.githubusercontent.com/17950251/87536820-c4664c80-c6aa-11ea-99fe-4408240e53de.png)
7. Download desktop client by clicking on the link and start it. Agree with the risk of starting the application.
![image](https://user-images.githubusercontent.com/17950251/87536961-f081cd80-c6aa-11ea-888e-b2e9cb2808f1.png)
