### ISSUE TITLE
textField: When the input value of the text box is greater than 1000, the split character , is converted to 2

### ISSUE THREAD

**Issue by 12315jack** [cuba-platform/cuba#2881]
#2881Environment
- Platform version: 7.2.2

- Client type: web
- Browser: Chrome
- Database: PostgreSQL
- Operating system: Windows

### Description of the bug or enhancement

when i edit input 11111 finsied it will be change to 112111
![image](https://user-images.githubusercontent.com/9072519/82026733-bb1a2d00-96c5-11ea-8e99-ce46af212af2.png)
![image](https://user-images.githubusercontent.com/9072519/82026776-cc633980-96c5-11ea-9ee7-798942cde872.png)
![image](https://user-images.githubusercontent.com/9072519/82026925-07fe0380-96c6-11ea-96fc-6a7bd0ed6bb7.png)

**Comment by knstvk** [comment]
What is in your localized data format settings? Please provide the following lines from your main message pack:
```
numberDecimalSeparator=.
numberGroupingSeparator=,
integerFormat=#
decimalFormat=#,##0.###
```
