### ISSUE TITLE
NullPointerException in ListPrintForm action

### ISSUE THREAD

**Issue by Patapata3** [cuba-platform/cuba#2882]
### Environment

- Platform version: 7.2.4 

- Client type: Web
- Browser: Mozilla Firefox
- Database: PostgreSQL
- Operating system: Windows

### Description of the bug or enhancement

When trying to use ListPrintForm action for printing report for all elements of a GroupTable with propertyContainer as its dataContainer it throws a NullPointerException. The reason is, in printAll() method it tries to get a loader from the table's container, but property containers don't have loaders. Therefore, the loader's value is null, and when trying to access data via this loader it throws NullPointerException

**Comment by Flaurite** [comment]
### For QA
You can use this demo project: [reportnpe.zip](https://github.com/cuba-platform/cuba/files/4675834/reportnpe.zip)
