### ISSUE TITLE
Wrong default type token of DateField

### ISSUE THREAD

**Issue by alexander-shustanov** [cuba-platform/cuba#2900]
`com.haulmont.cuba.gui.components.DateField#TYPE_DEFAULT` uses java.sql.Date, but in `com.haulmont.cuba.web.gui.components.WebDateField#constructModelValue` the `java.util.Date` is used as default type. It leads to wrong injection type in CUBA Studio.

### Environment

- Platform version: 7.2.4

**Comment by knstvk** [comment]
QA: check that Studio injects a standalone DateField (not connected to an entity attribute) with `java.util.Date` type parameter.
