### ISSUE TITLE
Support HTML rendering items in Tree

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#2916]
### Environment
- Platform version: 7.2
- Client type: Web

### Description of the bug or enhancement
Vaadin Tree provides ability to set content mode as HTML:
```
com.vaadin.ui.Tree#setContentMode(ContentMode);
```

----
### Changes
Tree has new feature `ContentMode`. It allows to configure how the item captions will be shown: with HTML, simple text or preformatted text.

New attribute in XML:
```
<tree id="groupsTree"
      contentMode="PREFORMATTED"
      ...
```
New Java API:
- `ContentMode getContentMode();`
- `void setContentMode(ContentMode contentMode);`

### How to test
You can check new feature with this project: [demo.zip](https://github.com/cuba-platform/cuba/files/5157129/demo.zip)
Open _App Groups_ screen

**Comment by alexbudarov** [comment]
studio https://youtrack.cuba-platform.com/issue/STUDIO-8884
