### ISSUE TITLE
EclipseLink does not order inserts properly for JOINED inheritance and a reference to non-root entity

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#293]
See https://www.cuba-platform.com/support/topic/cascade-insert-problem
See https://www.cuba-platform.com/support/topic/using-a-non-mapped-superclass-breaks-my-entity-listener

Entity1 has JOINED inheritance strategy
Entity2 is inherited from Entity1
Entity3 has a reference to Entity2

When we commit all new objects in one transaction, EclipseLink inserts Entit1, then Entity3 - at this moment foreign key violation occurs because Entity2 is not yet inserted.

---
Original issue: https://youtrack.haulmont.com/issue/PL-8135

**Comment by andreysubbotin** [comment]
Set `cuba.hasMultipleTableConstraintDependency` to true
