### ISSUE TITLE
If action is hidden by role permissions button bound to this action should not be displayed in the screen

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2935]
### Environment

- Platform version: 7.2.4
- Forum issue https://www.cuba-platform.ru/discuss/t/problema-pri-ispolzovanii-constraintoperationtype-i-constraintcode/4425

### Description of the bug or enhancement

1. Create some browser screen with table
2. Add custom action and bound it to a button on this screen
3. Create a role that hides this custom action (see status action)
![image](https://user-images.githubusercontent.com/17950251/86477885-6193bd80-bd5a-11ea-8a11-1f25faf79ee8.png)
4. Assign this role for some test user
5. Open screen

*A.R.*  Button is not hide

**Comment by soraksh** [comment]
It seems this is not a bug, but wrong configuration of role permissions. According to the documentation, permissions for actions must be associated with the component holding the action:

> To configure permission for an action, specify the component, holding the action, and then the action identifier in angle brackets. For example: customersTable\<changeGrade\>.

See [documentation](https://doc.cuba-platform.com/manual-7.2/permissions.html). So to hide button for action `statuss` for table `someTable` name of the component in permission must be `someTable<statuss>`.
