### ISSUE TITLE
In some cases user has to use Browser's "back" button twice (not once as expected) to let it work

### ISSUE THREAD

**Issue by WildChildCode** [cuba-platform/cuba#2954]
### Environment

- Platform version: 7.2.6
- Browser: **Chrome**, **Firefox** (dev. ed.), **Edge**, **IExplorer 11**, **Safari**, **Yandex**
- Database: PostgreSQL
- Operating system: Windows 10, macOS 10.15.4

### Description of the bug or enhancement
- Scope
In different circumstances (
mostly when app restores UI) when user click on "back" button for the first time it do nothing. But if user does it agan - it works as expected. This is true for **both** BACK_ONLY and URL_ROUTES Url Handling Modes.
- Test project
[navigation.zip](https://github.com/cuba-platform/cuba/files/4902649/navigation.zip)
It contains extended MainScreen as HistoryBackHandler just to show notification when user clicks on "back" button (or pushes backspace). It is used to reproduce the beheaviour for cuba.web.urlHandlingMode=BACK_ONLY.
- Minimal reproducible example

1. Open new tab. 
2. Open app.
3. Login.
4. Click "Back" browser button.

  - Expected behavior
Notification "Used 'Back' browser function" is shown (for BACK_ONLY mode) **or**
Browser goes to starting page (for URL_ROUTES mode)
- Actual behavior 
Nothing is happen

- Two other cases with the same behaviour

Case 1
1. Log out from previous session.
2. Open new tab. 
3. Open app.
4. Login.
5. Open new tab. 
6. Open app.
7. Click anywhere on empty space in app window (if you don't - app will not handle actions, and browser returns to starting page on next step).
8. Click "Back" browser button.

Case 2
1. Log out from previous session.
2. Open new tab. 
3. Open app.
4. Login as **admin**.
5. Switch to substituted user "test".
6. Click to "Application" menu.
7. Click on "Dummies" item. 
8. Click "Back" browser button after loading screen.

----
### For QA

1. Check cases **only for BACK_ONLY** mode.
2. Check in all supported browsers (Firefox, Safari, Chrome, Opera, EDGE, IE11)

**Comment by Flaurite** [comment]
Hello, @WildChildCode !

We have fixed bug with BACK_ONLY mode. Note that this mode also hides notification if it is shown.

As for the URL_ROUTES, it is considered a correct behavior. We do not allow a return to the Login screen after successful authentication. See:
```
com.haulmont.cuba.web.sys.navigation.accessfilter.CubaLoginScreenFilter
com.haulmont.cuba.web.sys.navigation.HistoryNavigator#handleHistoryBackward()
com.haulmont.cuba.web.sys.navigation.UrlChangeHandler#navigationAllowed()
```
And documentation: [url_navigation_filter](https://doc.cuba-platform.com/manual-7.2/url_routing.html#url_navigation_filter)

**Comment by maistrenkoIulia** [comment]
platform version: 7.2-SNAPSHOT
browsers: chrome, ie, edge, firefox
TC from ticket body N 1, 2 - ok
TC: login ->navigate to Dummies browser -> Backspace -> wait till notification disappeares -> navigate to LegacyDummy browser -> Backspace
ER: notification
AR: no notifiation
(applicable for chrome, ie, edge, firefox)

platform version: 7.3-SNAPSHOT
TC1, TC2 - NOK (chrome v. 84.0.4147.89,  firefox v.78.0.2 (64-битный), IE v.11.0.9600.19596)

**Comment by WildChildCode** [comment]
Hello @Flaurite !
Thanks a lot for the info.

**Comment by maistrenkoIulia** [comment]
tested and passed for chrome, ie, edge, firefox

**Comment by natfirst** [comment]
tested and passed for safari
