### ISSUE TITLE
Generated columns are not hidden by the new security mechanism

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2979]
### Environment

- Platform version: 7.2
- Forum issue https://www.cuba-platform.ru/discuss/t/vyklyuchenie-otobrazheniya-generiruemogo-stolbcza-dlya-roli/4593
### Description of the bug or enhancement

1. Create a role (does not matter design-time or in Roles screen)
2. Do not allow to read or modify the Default Role attribute of the Role entity
3. Add permission to open Roles browser
4. Assign this role to some user
5. Login with this user and open Roles browser

*E.R.* Default Role column does not displayed in Roles table
*A.R.* Default Role column is displayed.

Try this case on platform 7.1.7 - everything works as expected.

### Result
Fixed Default Role column behaviour only

**Comment by andreysubbotin** [comment]
Generated columns are never hidden by security rules. You must explicitly check security rules for them before adding them to the table. The problem relates only to the Default Role column because the column has become generated since version 7.2
