### ISSUE TITLE
Cannot compile custom datasource with Groovy

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#298]
>Abstract method 'groovy.lang.MetaClass getMetaClass()' is not implemented but a method of the same name but different return type is defined: method 'com.haulmont.chile.core.model.MetaClass getMetaClass()'

Rename `Datasource.getMetaClass()`?

---
Original issue: https://youtrack.haulmont.com/issue/PL-8171

**Comment by knstvk** [comment]
Resolved in #474
