### ISSUE TITLE
Screen with a lot of fields loads very slowly because of slow validators loading

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#2997]
### Environment

- Platform version: 7.2.7
- Demo project [slow-loading-screen.zip](https://github.com/cuba-platform/cuba/files/5062029/slow-loading-screen.zip)
- Forum issue https://www.cuba-platform.com/discuss/t/edit-screen-with-about-35-fields-is-very-slow/13236

### Description of the bug or enhancement
1. Create an entity with 36 fields. Add some validations
2. Create a browser and editor for this entity
3. Run the app and try to open editor (BigEntity in demo project)
4. Check the loading time using Java VisualVM

*A.R.* Loading validators takes most of the time
![image](https://user-images.githubusercontent.com/17950251/90004481-cd950a00-dca6-11ea-840d-811465f3955f.png)
![image](https://user-images.githubusercontent.com/17950251/90004535-df76ad00-dca6-11ea-9b29-c0859e735597.png)
![image](https://user-images.githubusercontent.com/17950251/90004642-0503b680-dca7-11ea-95af-0cc63e85025b.png)

**Comment by andreysubbotin** [comment]
Only the first opening is slow about 300ms (validators are cached)
