### ISSUE TITLE
eclipselink-2.6.2.cuba4.jar is not exists

### ISSUE THREAD

**Issue by ouyangjia** [cuba-platform/cuba#3]
in https://repo.cuba-platform.com/content/groups/work/com/haulmont/thirdparty/eclipselink
cannot find eclipselink-2.6.2.cuba4.jar

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':cuba-web:compile'.
> Could not find com.haulmont.thirdparty:eclipselink:2.6.2.cuba4.
  Searched in the following locations:
      file:/Users/ouyangjia/.m2/repository/com/haulmont/thirdparty/eclipselink/2.6.2.cuba4/eclipselink-2.6.2.cuba4.pom
      file:/Users/ouyangjia/.m2/repository/com/haulmont/thirdparty/eclipselink/2.6.2.cuba4/eclipselink-2.6.2.cuba4.jar
      https://repo.cuba-platform.com/content/groups/work/com/haulmont/thirdparty/eclipselink/2.6.2.cuba4/eclipselink-2.6.2.cuba4.pom
      https://repo.cuba-platform.com/content/groups/work/com/haulmont/thirdparty/eclipselink/2.6.2.cuba4/eclipselink-2.6.2.cuba4.jar
  Required by:
      com.haulmont.cuba:cuba-web:6.2-SNAPSHOT
      com.haulmont.cuba:cuba-web:6.2-SNAPSHOT > com.haulmont.cuba:cuba-shared-lib:6.2-SNAPSHOT
      com.haulmont.cuba:cuba-web:6.2-SNAPSHOT > com.haulmont.cuba:cuba-gui:6.2-SNAPSHOT
      com.haulmont.cuba:cuba-web:6.2-SNAPSHOT > com.haulmont.cuba:cuba-web-auth:6.2-SNAPSHOT
      com.haulmont.cuba:cuba-web:6.2-SNAPSHOT > com.haulmont.cuba:cuba-rest-api:6.2-SNAPSHOT
      com.haulmont.cuba:cuba-web:6.2-SNAPSHOT > com.haulmont.cuba:cuba-gui:6.2-SNAPSHOT > com.haulmont.cuba:cuba-client:6.2-SNAPSHOT
      com.haulmont.cuba:cuba-web:6.2-SNAPSHOT > com.haulmont.cuba:cuba-web-auth:6.2-SNAPSHOT > com.haulmont.cuba:cuba-global:6.2-SNAPSHOT

**Comment by knstvk** [comment]
Fixed
