### ISSUE TITLE
Domain model description does not contain enums that are not used in entities

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#3002]
### Environment

- Platform version: 7.2
- Forum issue: https://www.cuba-platform.ru/discuss/t/oshibka-pri-rabote-rest-metoda-rest-v2-metadata-enums/4725/4

### Description of the bug or enhancement

1. Create several enums in the project
2. Create an entity with enum attribute - use one of the created enums as a type
3. Open Help-Data Model

*A.R* List will contain only enums used in entities
```
com.company.fle.entity.UsedEnum
com.haulmont.cuba.core.app.dynamicattributes.PropertyType
com.haulmont.cuba.core.entity.FtsChangeType
com.haulmont.cuba.core.entity.ScheduledTaskDefinedBy
com.haulmont.cuba.core.entity.SchedulingType
com.haulmont.cuba.core.global.ClientType
com.haulmont.cuba.core.global.SendingStatus
com.haulmont.cuba.security.entity.ConstraintCheckType
com.haulmont.cuba.security.entity.ConstraintOperationType
com.haulmont.cuba.security.entity.EntityLogItem$Type
com.haulmont.cuba.security.entity.PermissionType
com.haulmont.cuba.security.entity.RoleType
com.haulmont.cuba.security.entity.SessionAction
```
*E.R.* List should contain all enums
OneEnum and TwoEnum
![image](https://user-images.githubusercontent.com/17950251/90510051-5a3e3d00-e16b-11ea-9624-acef49f44a02.png)

**Comment by knstvk** [comment]
Works as designed, but should be stated in the docs. Please create an issue for the REST documentation.
