### ISSUE TITLE
Query with 'OR' operator might work incorrectly if search conditions are specified for multiple associated entities

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#301]
1) Create an entity, name it *"First"* add a field to it, name the field "firstField"
2) Create an entity, name it *"Second"* add a field to it, name the field "secondField
3) Create an entity, name it *"Master"*, add many_to_one links to "First' and "Second"
4) Create a view for the "Master" entity: include links
5) Create screens for all the entities, for *"Master"* - by ''master-view''

5) start the application
6) create several instances of *"First"* and *"Second"*
7) create an instance of *"Master"*, link it ''only'' with *"First"*

8) On the *"Master"* browse screen create a filter with a custom condition.
```
{E}.firstLink.firstField like ? or {E}.secondLink.secondField like ?
```

9) Try to find the instance created on the 7th step, specify appropriate search conditions

*AR:* No rows found. The query is like follows. If the *"Master'* entity has no link to both: "First" and "Second" (t1.SECOND_LINK_ID  is null), no rows are found by the SQL query.

```
query=select e from testshot$Master e where e.firstLink.firstField like :component_filter_pdEcouCCgd75873 
or e.secondLink.secondField like :component_filter_pdEcouCCgd75873, max=50

SELECT t1.ID AS a1, t1.DELETE_TS AS a2, t1.DELETED_BY AS a3, t1.MASTER_FIELD AS a4, t1.VERSION AS a5, t1.FIRST_LINK_ID AS a6, t1.SECOND_LINK_ID AS a7, t0.ID AS a8, t0.DELETE_TS AS a9, t0.DELETED_BY AS a10, t0.VERSION AS a11, t2.ID AS a12, t2.DELETE_TS AS a13, t2.DELETED_BY AS a14, t2.VERSION AS a15 
FROM TESTSHOT_FIRST t0, TESTSHOT_SECOND t2, TESTSHOT_MASTER t1 
WHERE (((LOWER(t0.FIRST_FIELD) LIKE ? OR LOWER(t2.SECOND_FIELD) LIKE ?) AND (t1.DELETE_TS IS NULL)) 

AND (((    t0.ID = t1.FIRST_LINK_ID   ) AND (t0.DELETE_TS IS NULL)) 
AND ((   t2.ID = t1.SECOND_LINK_ID   ) AND (t2.DELETE_TS IS NULL)))) LIMIT ?, ?

bind => [%second%, %second%, 0, 50]
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-8189

**Comment by andreysubbotin** [comment]
Use left join for `e.firstLink.firstField`, otherwise eclipselink generates inner join in the SQL query
