### ISSUE TITLE
Unsupported field: DayOfWeek in a search filter

### ISSUE THREAD

**Issue by Flaeros** [cuba-platform/cuba#3019]
#2847 # Environment

- Platform version: 7.2.7

### Description of the bug or enhancement

Field marked with @Temporal(TemporalType.TIMESTAMP) causes mentioned exception when user creates search filter by this field in a browse screen.

**Comment by plakhov** [comment]
The bug reproduced only if `dateTimeFormat `property end with EE, for example
`dateTimeFormat = yyyy-MM-dd HH:mm EE`
