### ISSUE TITLE
Role does not give permission to "date" attribute

### ISSUE THREAD

**Issue by bartekspitza** [cuba-platform/cuba#3020]
### Environment

- Platform version: 7.2.4
- Client type: Web
- Browser: Chrome
- Database: MySQL

### Bug

When creating a role at design time using `AnnotatedRoleDefinition` and giving access to all attributes with `@EntityAttributeAccess(entityClass = MyEntity.class, modify = "*")`, the role does not gave permissions to an attribute named "date" of type `LocalDateTime` of the `MyEntity` class

**Comment by gorbunkov** [comment]
Hi @bartekspitza , 
I couldn't reproduce your error. I created a role, assigned it to the user and could successfully edit the "date" attribute. What did you mean by *Role does not give permission*? You cannot edit the entity in a standard editor? What exceptions do you get?
It will also be helpful if you attach a zip archive with a small demo project and a sequence of steps that demonstrate the case.

**Comment by bartekspitza** [comment]
@gorbunkov 

Hi, I successfully reproduced the error in this demo by starting the application, creating a user and assigning the "Recruiter" role to it and then logging in with the user. The attribute "date" is not visible in the `demo_CandidateEvent.browse` screen table or `demo_CandidateEvent.edit` form.

[demo.zip](https://github.com/cuba-platform/cuba/files/5154713/demo.zip)

**Comment by gorbunkov** [comment]
Try to update your project to the latest cuba version (7.2.7). It looks like the error was fixed in https://github.com/cuba-platform/cuba/issues/2869

**Comment by bartekspitza** [comment]
Updated to 7.2.7 and indeed it has been solved. Should have tried upgrading first, my bad.

**Comment by gorbunkov** [comment]
No problem:) Anyway, thank you for reporting the problem
