### ISSUE TITLE
Support XSLX export in Excel action

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/cuba#3033]
### Environment

- Platform version: 7.2.x

### Description of the enhancement

Excel action should support XLSX export. 

Default export behaviour between XLS and XLSX should be configurable in web application properties. XLS export should be enabled by default in CUBA 7.2.x. CUBA 7.3.x should have XLSX export by default.

Excel action should has API to select XLS or XLSX export.

**Comment by maistrenkoIulia** [comment]
1. for 7.2-snapshot need to change  
```
@Property("cuba.gui.defaultExcelExportFormat")
    @Default("xlsx") 
```
to
```
@Property("cuba.gui.defaultExcelExportFormat")
    @Default("xls")
```

2. Now there are 3 values for exportFormat (xlsx, xls, default). but for 7.2 xls is default and for xls is default. is it nessessary to create extra DAFAULT attribute?
![image](https://user-images.githubusercontent.com/66992566/94917099-f70d2d80-04c0-11eb-89ca-27038e40e396.png)

**Comment by maistrenkoIulia** [comment]
also need to update description in ` @StudioAction` for `ExcelAction `(now it displayes in studio during add action) for 7.3 only
ER: "Exports a list of entities to XLSX file"
AR: "Exports a list of entities to XLS file"
