### ISSUE TITLE
Incorrect displaying of filter fields in case collapse->expand side menu

### ISSUE THREAD

**Issue by maistrenkoIulia** [cuba-platform/cuba#3040]
related forum item https://www.cuba-platform.ru/discuss/t/problema-s-pereschetom-shiriny-kolonok-pri-ispolzovanii-collapsed-main-menu/4777

### Environment

CUBA Platform version: 7.2.8
CUBA Studio plugin version: 15.0.SNAPSHOT2572-202
IntelliJ version: IntelliJ IDEA 2020.2 (Community Edition)

### Description of the bug or enhancement

- Minimal reproducible example
[menu.zip](https://github.com/cuba-platform/cuba/files/5255352/menu.zip)
run attached project -> users browser -> select filter 'collapsed side menu'
collapse side menu -> expand side menu

- Expected behavior

filter fields should be displayed with appropriate view

- Actual behavior see screen

![image](https://user-images.githubusercontent.com/66992566/93767195-b09a1200-fc28-11ea-9f4f-527e92642a11.png)

**Comment by GlebDurygin** [comment]
Unfortunately, the ability to collapse and expand menu is only intended to be used before opening the screen. 
When the screen is open, internal components may incorrectly calculate their width when the menu is collapsed and expanded.
