### ISSUE TITLE
Slow screen loading and high CPU usage in case of many components

### ISSUE THREAD

**Issue by Ilya-c** [cuba-platform/cuba#3053]
### Environment

- Platform version: 7.2-SNAPSHOT

### Description of the bug or enhancement

Our project has editor screens with many components: labels, text fields etc. Currently we have big performance problems with opening such screens.
Root of the problem is autowiring web components to the spring context, introduced in the ticket https://github.com/cuba-platform/cuba/issues/1351 

For example in our case method WebUiComponents#create() is executed approx. 300 times (which leads to the autowiring 300 beans -  WebUiComponents#autowireContext) during the screen components loading, increasing time by 714 ms according to the perfstat logs and visualVm:
![image](https://user-images.githubusercontent.com/6366861/95075187-d511e600-0720-11eb-9f2b-a0ae82b43288.png)

Also to prove that this is a huge problem for us, i've attached a .nps snapshot ([autowireProblem.zip](https://github.com/cuba-platform/cuba/files/5327116/autowireProblem.zip) captured using jvisualvm) from the test environment during performance test execution (opening main window and editor multiple times with several threads were performed).

In this snapshot you can see that the 6 sec from the 12 (snapshot time) cpu is spend executing create() method
![image](https://user-images.githubusercontent.com/6366861/95075673-a9dbc680-0721-11eb-97e5-ac7a979e6675.png)

**Comment by andreysubbotin** [comment]
https://github.com/spring-projects/spring-framework/pull/24485
https://github.com/spring-projects/spring-framework/issues/23905
https://github.com/spring-projects/spring-framework/issues/24980
