### ISSUE TITLE
Right-align RowsCount if there is no ButtonsPanel

### ISSUE THREAD

**Issue by GlebDurygin** [cuba-platform/cuba#3073]
### Environment

- Platform version: 7.2 + 

### Description of the bug or enhancement

In CUBA 7.2, the `ButtonsPanel` is based on a `FlowLayout` (#178). When the list component does not have a buttons panel, the rowsCount component is left-aligned.

- Expected behavior
The rowsCount component must always be right-aligned.
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/f3faed5e-af87-412b-a4ad-9c54ad03fce3)
- Actual behavior
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/8805e45b-bf08-4aa4-b4d0-a088bd7e73d4)

### QA
Check the above case for all inheritors of the `ListComponent`.

**Comment by maistrenkoIulia** [comment]
reproduced for 7.2-snapshot, 7.3-snapshot
![image](https://user-images.githubusercontent.com/66992566/98332282-d54f1b00-2017-11eb-83b1-f0d3f740cbb0.png)
[align.zip](https://github.com/cuba-platform/cuba/files/5499448/align.zip)
