### ISSUE TITLE
DataGrid inside the SplitPanel does not load data when scrolling in Safari browser

### ISSUE THREAD

**Issue by GlebDurygin** [cuba-platform/cuba#3078]
### Environment

- Platform version: 7.2.9
- Browser: Safari 14.0

### Description of the bug or enhancement

Forum topic: https://www.cuba-platform.ru/discuss/t/datagrid-split-problema-otobrazheniya-v-safari/5036

- Minimal reproducible example

Test project - [https://app.zenhub.com/files/54624511/b84f5cde-1c13-4ada-a645-c011a23e203e/download](https://app.zenhub.com/files/54624511/b84f5cde-1c13-4ada-a645-c011a23e203e/download)

1) Create a screen with `SplitPanel` that contains `DataGrid` with many records.
```
        <split id="split" orientation="horizontal" pos="80" width="100%">
            <dataGrid id="clientsTable"
                      width="100%"
                      dataContainer="clientsDc">
                <actions>
                    <action id="create" type="create"/>
                    <action id="edit" type="edit"/>
                    <action id="remove" type="remove"/>
                </actions>
                <columns>
                    <column id="name" property="name"/>
                    <column id="phone" property="phone"/>
                    <column id="company" property="company"/>
                    <column id="email" property="email"/>
                </columns>
                <rowsCount/>
                <buttonsPanel id="buttonsPanel"
                              alwaysVisible="true">
                    <button id="createBtn" action="clientsTable.create"/>
                    <button id="editBtn" action="clientsTable.edit"/>
                    <button id="removeBtn" action="clientsTable.remove"/>
                </buttonsPanel>
            </dataGrid>
            <vbox margin="true" spacing="true">
                <label value="msg://addressBtnCaption"/>
            </vbox>
        </split>
```
2) Open screen in Safari browser
3) Try to scroll the `DataGrid` to the last item

- Expected behavior
![Снимок экрана 2020-11-03 в 14.48.16.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/94e79e58-3cad-467a-9671-21b8c7f6ff1d)
- Actual behavior
![Снимок экрана 2020-11-03 в 14.47.52.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/a5f155c2-8618-4a19-92aa-7f0cb34867c7)

**Comment by glebfox** [comment]
Can't reproduce. Nonetheless, the layout is incorrect. Both split panel and DataGrid has `AUTO` height instead of `100%`.
