### ISSUE TITLE
Add before action performed handler to RemoveAction

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#3081]
### Environment
- Platform version: 7.2
- Client type: Web

### Description
Legacy action has `BeforeActionPerformedHandler` which is used for preventing further actions.

New `com.haulmont.cuba.gui.actions.list.RemoveAction` supports such functionality in the RemoveOperation but doesn't have API for setting/getting handler.

**Comment by knstvk** [comment]
You don't need it, just override the action and call `execute()` after the interaction. 
See an example in https://doc.cuba-platform.com/manual-7.2/RemoveAction.html:
```
@Named("customersTable.remove")
private RemoveAction customersTableRemove;

@Subscribe("customersTable.remove")
public void onCustomersTableRemove(Action.ActionPerformedEvent event) {
    customersTableRemove.setConfirmation(false);
    dialogs.createOptionDialog()
            .withCaption("My fancy confirm dialog")
            .withMessage("Do you really want to remove the customer?")
            .withActions(
                    new DialogAction(DialogAction.Type.YES)
                            .withHandler(e -> customersTableRemove.execute()), // execute action
                    new DialogAction(DialogAction.Type.NO)
            )
            .show();
}
```
