### ISSUE TITLE
cuba.backgroundWorker.maxActiveTasksCount does not work

### ISSUE THREAD

**Issue by SevostyanovArseny** [cuba-platform/cuba#3097]
### Environment

- Platform version: 6.2+

### Description of the bug or enhancement

```com.haulmont.cuba.web.gui.executors.impl.WebBackgroundWorker#executorService``` has ```LinkedBlockingQueue``` with ```Integer.MAX_VALUE``` capacity as a work queue, therefore new worker threads will never be added (since standard java ```ThreadPoolExecutor``` does not add new worker threads until its queue is full)

**Comment by andreysubbotin** [comment]
We can't make a scalable thread pool executor with threads from min to max based on workload. So we use fixed thread pool as a solution. 
Properties `cuba.backgroundWorker.minBackgroundThreadsCount` and `cuba.backgroundWorker.maxActiveTasksCount` are depricated now. Only cuba.backgroundWorker.minBackgroundThreadsCount` property works.

Use property `cuba.backgroundWorker.backgroundThreadsCount` for background tasks configuration.
