### ISSUE TITLE
AbstractBeansMetadata doesn't return spring beans without interface as available

### ISSUE THREAD

**Issue by artemy63** [cuba-platform/cuba#3098]
### Environment

- Platform version: 7.3-SNAPSHOT
- BProc add-on vrsion: 1.1-SNAPSHOT

### Description of the bug or enhancement

Test case: 
1. Install BProc add-on 
2. Add into your code base spring bean which implement some interface
```//global module
public interface SomeService {
    void doSomething();
}

//core module
@Service("myapp_SomeService")
public class SomeServiceBean implements SomeService {
    @Override
    public void doSomething() {
        ...
    }
}
```
3. Add into your code base spring bean without interface
```//core module
@Component("myapp_ConsideredAsNotAvailableBean")
public class ConsideredAsNotAvailableBean {
    public void doSomething() {
       ...
    }
}
```
4. Go to BProc modeler and add new ServiceTask
5. Choose as "Type" `Spring bean` and check list availabe beans

ER: Both  "myapp_SomeService" and "myapp_ConsiderAsNotAvailableBean" presented in `Bean name` list
AR: Only bean with interface "myapp_SomeService" presented

Root cause of that behavior in logic of `com.haulmont.cuba.core.app.AbstractBeansMetadata#getAvailableBeans` method which checks presence of available methods for all candidate beans. Internally it deletegates to `com.haulmont.cuba.core.app.AbstractBeansMetadata#getAvailableMethods` which firstly checks interfaces for bean. If there are no any interfaces - bean will not included in result. 
Interesting that this method has [checking ](https://github.com/cuba-platform/cuba/blob/master/modules/core/src/com/haulmont/cuba/core/app/AbstractBeansMetadata.java#L96)for methods of bean itself but it never will reached if bean has no any interface. I guess it mistake.

**Comment by artemy63** [comment]
See PR https://github.com/cuba-platform/cuba/pull/3099 which solves the problem above

**Comment by knstvk** [comment]
It's not a mistake - this method is also used in Scheduled Tasks and the requirement that the invoking bean must have an interface is deliberate and documented: https://doc.cuba-platform.com/manual-7.2/scheduled_tasks_cuba_reg.html

So if we really need a full list of beans - create a new method for it. The current `getAvailableMethods` should work as is.

**Comment by artemy63** [comment]
```Beans without an interface are not supported.```

Sorry, my mistake in that case, will close PL
