### ISSUE TITLE
Permissions are not checked for screens defined by a class

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#310]
1) Create a new user 
2) Assign to the user a role which denies access to the application log ("logWindow").
3) Modify some entity editor: add the button which opens the "logWindow". Like this:

```
   @Override
    public void init(Map<String, Object> params) {
        Button viewLog = new WebButton();

        viewLog.setAction(new AbstractAction("logAction") {
            @Override
            public void actionPerform(Component component) {
                openWindow("logWindow", WindowManager.OpenType.DIALOG);

            }
        });
        this.add(viewLog, 3);
        super.init(params);
    }
```

4) Log in to the application by the user to whom the "logWindow" is denied 
5) Open the "logWindow"  by clicking the button

*AR*: the Application log viewer is opened. Permissions are not checked for screens defined by a class.

---
Original issue: https://youtrack.haulmont.com/issue/PL-8248

**Comment by jreznot** [comment]
Does not make sense since 7.0
