### ISSUE TITLE
Entity changes are not displayed in comparison table for entity snapshots mechanism 

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#3105]
### Environment

- Platform version: 7.2.10
- Docs link https://doc.cuba-platform.com/manual-7.2/entity_snapshots_view.html
- Demo project [testCuba.zip](https://github.com/cuba-platform/cuba/files/5617335/testCuba.zip)
- Forum issue https://www.cuba-platform.com/discuss/t/entity-snapshot-view-and-rest-api/14215

### Description of the bug or enhancement

1. Set up entity snapshots mechanism in the project (or use demo project)
2. Run the app, open TestEntity browser and create an instance
3. Change the instance, save changes, reopen editor

*A.R.* The comparison table is not displayed
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/8f0a5ecb-4181-4bb3-b375-a697269b04a1)

**Comment by glebfox** [comment]
The provided demo project has an incorrect layout. You can check it using the **Analyze Layout** action
<img width="610" alt="Screenshot 2020-12-16 at 15 29 39" src="https://user-images.githubusercontent.com/6077149/102343478-0bd36a80-3fb4-11eb-8fc9-4a683033c89e.png">

`<layout expand="tabSheet" spacing="true">` fixes the problem
<img width="1409" alt="Screenshot 2020-12-16 at 15 28 01" src="https://user-images.githubusercontent.com/6077149/102343988-ae8be900-3fb4-11eb-9f74-792545c6236d.png">

Pay attention that `diff-view.xml` requires plenty of space to display all controls

<img width="700" alt="Screenshot 2020-12-16 at 15 28 12" src="https://user-images.githubusercontent.com/6077149/102343863-8603ef00-3fb4-11eb-98cf-c82d0118de14.png">
