### ISSUE TITLE
Error during use NEW keyword for enum in loader query

### ISSUE THREAD

**Issue by maistrenkoIulia** [cuba-platform/cuba#3117]
see https://www.cuba-platform.com/discuss/t/enum-and-the-keyword-new-in-screen-xml/14177
[enums.zip](https://github.com/cuba-platform/cuba/files/5671449/enums.zip)

### Environment
CUBA Platform version: 7.2.10
CUBA Studio plugin version: 15.0.SNAPSHOT2679-202
IntelliJ version: IntelliJ IDEA 2020.2.4 (Community Edition)

### Description of the bug or enhancement

- Minimal reproducible example

1. Launch attached project
2. Open Cars browser
ER: browser should be opened successfully and cars with status New, On_sale should be displayed
AR:
```
JpqlSyntaxException: Errors found for input jpql:[select e from enums_Car e                     where e.status = @enum(com.company.enums.entity.Status.NEW)                     or e.status = @enum(com.company.enums.entity.Status.ON_SALE)]
CommonErrorNode [<unexpected: [@33,53:53='.',<68>,1:53], resync=e.status = @enum(com.company.enums.entity.Status.NEW)>]
```

**Comment by grenjen** [comment]
I just stumbled over the same error. In my case the error appears with the collection loader query

`<![CDATA[select e from Department e where e.campaignType = @enum(com.company.DepartmentCampaignType.WEEK)]]>`

while

`<![CDATA[select e from Department e where e.campaignType = @enum(com.company.DepartmentCampaignType.CITY)]]>`

works perfectly fine. In case it helps finding the cause of this unexpected behavior, here the enumeration class code:

```
enum class DepartmentCampaignType(private val id: String) : EnumClass<String> {
    WEEK("WEEK"),
    CITY("CITY");

    override fun getId() = id

    companion object {

        @JvmStatic
        fun fromId(id: String): DepartmentCampaignType? = values().find { it.id == id }
    }
}
```

**Comment by jbwmcarter** [comment]
I have encountered the same issue but my enum is called GROUP.

NEW, WEEK, GROUP.

Could it be failing on use of JPQL reserved words?

**Comment by maistrenkoIulia** [comment]
reproduced on 
CUBA Platform version: 7.2-SNAPSHOT
CUBA Studio plugin version: 15.0.SNAPSHOT2727-202
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

**Comment by maistrenkoIulia** [comment]
7.3 - ok
7.2 - NOK
[enums.zip](https://github.com/cuba-platform/cuba/files/6776682/enums.zip)
