### ISSUE TITLE
Cleanup com.haulmont.cuba.core.global package from non-infrastructure classes and interfaces

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#312]
Now it contains various classes and interfaces without any reason to group them:
* Move Email* classes to email sub-package
* Move *Helper classes to util sub-package
* Remove PasswordHashDescriptor as unused
* Move QueryParser to com.haulmont.cuba.core.sys
* Move *Exception to exception sub-package

---
Original issue: https://youtrack.haulmont.com/issue/PL-8254

**Comment by knstvk** [comment]
Too minor issue to introduce breaking changes.
Email* classes will go away when we extract an emailing app component.
PasswordHashDescriptor is already removed.
