### ISSUE TITLE
Last group in cuba.uniqueConstraintViolationPattern pattern is ignored

### ISSUE THREAD

**Issue by daring2** [cuba-platform/cuba#3130]
### Environment

- Platform version: 7.2.10

### Description of the bug or enhancement

The last group in cuba.uniqueConstraintViolationPattern regex pattern is ignored. The problem can be reproduced in project [sample-library-cuba7](https://github.com/daring2/sample-library-cuba7).

Steps to reproduce:
1. Add an unique constrain to Book.name attribute
2. Open "Application Properties" screen.
3. Find property `cuba.uniqueConstraintViolationPattern` and open edit dialog.
4. Apply regex value with multiple groups, for example:
```ERROR: conflicting key value violates exclusion constraint "(.+)"|integrity constraint violation: unique constraint or index violation[:;]? ([^\s]+)```
5. Save changes.
6. Try to create a book with duplicate name.

Expected behavior: Error message "Unique constraint violation occurred (IDX_LIBRARY_BOOK_UNIQ_NAME)" is shown.
Actual behavior: Error message "Unique constraint violation occurred" without constraint name is shown.

**Comment by knstvk** [comment]
Will merge into 7.2 after releasing 7.2.11
