### ISSUE TITLE
Incorrect conversion for OffsetDateTime insertable=false,updatable=false attribute

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#3133]
### Environment
- Platform version: 7.2.11
- Database: PostgreSQL

### Description of the bug or enhancement
Sample project - attached
[offdt.zip](https://github.com/cuba-platform/cuba/files/5754733/offdt.zip)

I have two OffsetDateTime fields in the entity. One of them is filled with current timestamp by triggers and has insertable=false, updatable=false attrs.
Another is filled with lifecycle callbacks.
```
// filled with lifecycle callbacks
    @Column(name = "UPDATE_DATE")
    private OffsetDateTime updateDate;

// filled with trigger
    @Column(name = "CHANGE_DATE", insertable = false, updatable = false)
    private OffsetDateTime changeDate;
```

In the browser you can see that displayed value for trigger-filled attribute is wrong (today is 2020/12/30):
![image](https://user-images.githubusercontent.com/6158807/103364373-0d824f80-4ad7-11eb-850a-db2e2a611703.png)

In the pgAdmin both columns are correct:
![image](https://user-images.githubusercontent.com/6158807/103364517-7f5a9900-4ad7-11eb-9b4b-415b8d55bc8f.png)

I debugged the code, and the incorrect conversion from java.sql.Timestamp to OffsetDateTime happens here:
org.eclipse.persistence.internal.helper.ConversionManager#convertObjectToOffsetDateTime
This method is called only for non-updatable attribute for some reason.

#### Cause:
Because of  some reason, eclipselink does not set `org.eclipse.persistence.internal.helper.DatabaseField#type` for readonly fields which used for optimized type conversion, so this fields are converted through ConversionManager, that had bug with 12/24-h format.

#### Changes:
Incorrect conversion inside `org.eclipse.persistence.internal.helper.ConversionManager#convertObjectToOffsetDateTime`
has been fixed.

#### QA Notes:
It is better to check after 12:00, because problem was related to incorrect 12h-24h format usage and was not appear when this formats have the same value.

**Comment by DartVerder** [comment]
the month in the change date is also displayed incorrectly
![image](https://user-images.githubusercontent.com/69783839/124428635-0423b980-dd7e-11eb-8f45-6b430485d3d2.png)
