### ISSUE TITLE
Hot Deploy does not work with @Component beans injected in screens

### ISSUE THREAD

**Issue by alexander-shustanov** [cuba-platform/cuba#3141]
https://www.cuba-platform.ru/discuss/t/oshibka-inekczii-web-binov-posle-hotdeploy/5326

### Environment

- Platform version: 7.2.11

[untitled.zip](https://github.com/cuba-platform/cuba/files/5850240/untitled.zip)

Steps:

1. Start application
2. Open screen
3. Change string in TheBean.java, press Ctrl+S
4. Reopen screen in the application

AR:
Exception

**Comment by andreysubbotin** [comment]
CUBA supports hot-deploy only for beans with API interface when you inject API interface in a screen. Also, CUBA Studio should generate a trigger for bean reload.
