### ISSUE TITLE
Message key bug for Kotlin enums with additional methods

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#3156]
### Environment

- Platform version: 7.2.11

### Description of the bug or enhancement
see attached project: 
[kenum2.zip](https://github.com/cuba-platform/cuba/files/5986545/kenum2.zip)

If you create enum in Kotlin with additional overridden methods, you can observe glitch with localized messages in running application:

```
enum class TaxType(private val id: String) : EnumClass<String> {
    VAT("V") {
        override fun someMethod(): String = "Hello A"
    },

    NO_TAX("N") {
        override fun someMethod(): String = "Hello B"
    },
    SIMPLIFIED("S") {
        override fun someMethod(): String = "Hello S"
    };

    override fun getId() = id

    abstract fun someMethod() :String

    companion object {

        @JvmStatic
        fun fromId(id: String): TaxType? = TaxType.values().find { it.id == id }
    }
}
```

![image](https://user-images.githubusercontent.com/6158807/108026409-bfeb8300-7041-11eb-837a-a825dfd5ddd8.png)

Message keys are formed in a strange way.

**Comment by klaus7** [comment]
The problem is probably the `com.haulmont.cuba.core.sys.AbstractMessages#enumSubclassPattern`

**Comment by artemglinov** [comment]
The actual changeset is here https://github.com/cuba-platform/cuba/commit/f7e52f58269a527cdcb3144c5552b1a67be325e2.
