### ISSUE TITLE
Date fields are not displayed on the browser screen

### ISSUE THREAD

**Issue by skatova** [cuba-platform/cuba#3158]
### Environment

- Platform version: 7.2.11
- Forum issue: https://www.cuba-platform.com/discuss/t/problem-with-datefield-after-upgrade-to-7-2-11/14692
- See demo project CUBA.zip from forum issue

### Description of the bug or enhancement

- Minimal reproducible example
1. Download the attached demo project from forum issue and run the application
2. Open Datenverwaltung ->Mitarbeiter
3. Start to create a new entry
4. Fill in required fields and try to set date fields ```Eintritt``` and ```Austritt```
5. Click OK

- Expected behavior
Date fields filled and saved

- Actual behavior
Date fields are not displayed

![image](https://user-images.githubusercontent.com/53561930/109281684-0a38e500-7836-11eb-90d2-4929603610c5.png)

![testdate](https://user-images.githubusercontent.com/53561930/109281499-d231a200-7835-11eb-9f7f-d2b0186a5125.gif)

However, if you open an entry for editing, the fields will be filled

![image](https://user-images.githubusercontent.com/53561930/109280651-c0033400-7834-11eb-9cc1-96f890a9f60b.png)

**Comment by dtaimanov** [comment]
It was problem with messages.properties in project, see https://www.cuba-platform.com/discuss/t/problem-with-datefield-after-upgrade-to-7-2-11/14692/23
