### ISSUE TITLE
Value of dynamic attribute hasn`t been calculated in case Recalculation Values script is set

### ISSUE THREAD

**Issue by maistrenkoIulia** [cuba-platform/cuba#3164]
### Environment

http://cubadev:9072/app/#main

### Description of the bug or enhancement

TC:
Dynamic Attributes>Create category for Car (ref_Car) entity
Create first attr
Create second attr >Calculated Values and Options>
set Depends on = first
 Recalculation Values script = if (entity.getValue("+1first") == null) return 1 else return entity.getValue("+1first").length()
Apply changes
Cars>create new Car
set value in 'first' attr
ER: value of second attr has to be calcuated autometically
AR: value of second attr is empty

![image](https://user-images.githubusercontent.com/66992566/111164767-ce34ac80-85b7-11eb-8c57-f0718d0cb79d.png)

**Comment by bulgakovea** [comment]
Fixed recalculation for dynattr attached to legacy screen. 
Now the RuntimePropertiesFrame does not fully support recalculation.

**Comment by bulgakovea** [comment]
Case 1:
1. Create cuba project
2. Create entity, legacy editor and browser screen for entity
3. Start app, create dynattr category and 2 attributes for created entity
For ex.:
1 attribute - String testAttr
2 attribute - Integer, with recalculation script = return entity.getValue("+testAttr").length();
4. Set editor screen in attributes visibility tab. Save attributes, category and apply changes.
5. Open entity editor and change 1 attr value;
ER: Second attribute value changed

Case 2:
1. Create cuba project
2. Create entity, legacy editor and browser screen for entity
3.  Configure editor screen according to [Categorized Entities](https://doc.cuba-platform.com/manual-6.9/categorized_entity.html) doc. guide
4. Start app, create dynattr category and 2 attributes for created entity (can be the same as in the example above, but without screens in Visibility tab)
5. Open editor screen and change 1 attr value
ER:  Second attribute value didn't change
