### ISSUE TITLE
Validation script of dynamic attr doesn`t work in case value of attr isn`t filled

### ISSUE THREAD

**Issue by maistrenkoIulia** [cuba-platform/cuba#3165]
### Environment
http://cubadev:9072/app/#main/10
### Description of the bug or enhancement

- Minimal reproducible example
for ref_Car entity create dynamic attr Integer type
set Validation script = if (value != 3) return "the value '\${value}' is incorrect"
Apply changes
Cars browser>create don`t fill dymanic attr -> Save changes

- Expected behavior
Validation should be appeare
- Actual behavior
No validation

**Comment by bulgakovea** [comment]
Actually, this behaviour is expected - validation works only for filled fields.
If it is required to validate an attribute, it is necessary to set the "required" flag
