### ISSUE TITLE
Error using TwinColumn

### ISSUE THREAD

**Issue by smunir** [cuba-platform/cuba#3172]
### Environment

- Platform version: Mac Sur
- Client type: Web
- Browser: Safari

### Description of the bug or enhancement

I have to use TwinColumn for a M-M relationship, did exactly as given in documentation but it's not working and keep on giving error:

```
<twinColumn id="twinColumn"
    addAllBtnEnabled="true"
    dataContainer="entitiesDc"
    property="name"
    optionsContainer="systemEntitiesDc"/>
```
gives 
<img width="482" alt="Screen Shot 2021-04-03 at 4 05 32 AM" src="https://user-images.githubusercontent.com/4279499/113460672-f4b96b00-9432-11eb-8290-b8719f5a4ad7.png">

whereas 

```
<twinColumn id="twinColumn"
    addAllBtnEnabled="true"
    dataContainer="entitiesDc"
    optionsContainer="systemEntitiesDc"/>
```
gives 
<img width="488" alt="Screen Shot 2021-04-03 at 4 04 31 AM" src="https://user-images.githubusercontent.com/4279499/113460614-cfc4f800-9432-11eb-9979-6fd69f8ccecf.png">
SystemEntity class: 

```
@Table(name = "SYSTEM_ENTITY")
@Entity(name = "sibgo_SystemEntity")
@NamePattern("%s|name")
public class SystemEntity extends BaseIntegerIdEntity {
    private static final long serialVersionUID = 1123213288743562333L;

    @NotNull
    @Column(name = "NAME", nullable = false, length = 100)
    private String name;

    @NotNull
    @Column(name = "JAVA_TYPE", nullable = false, unique = true)
    private String javaType;

    @ManyToMany(mappedBy = "entities")
    @NotNull
    @OrderBy("code ASC")
    private List<SystemVariable> systemVariables;
    ...
}
```

**Comment by owlet1997** [comment]
Hi, @smunir . 

In fact the problem occurs due incorrect example of using `Twin column` in [documentation](https://doc.cuba-platform.com/manual-7.2/gui_TwinColumn.html):
![image](https://user-images.githubusercontent.com/45730069/114539898-ff130a80-9c65-11eb-987e-6d21d08e291d.png)
In this example you should use `orderDc` as `dataContainer` and `products` as `property`. 

Also pay attention to set `instanceName` to your entity in entity designer, for example:
![image](https://user-images.githubusercontent.com/45730069/114540337-721c8100-9c66-11eb-859a-32230965403b.png)
This `instanceName` will be displayed in `TwinColumn`.

[Issue ](https://github.com/cuba-platform/documentation/issues/784)for documentation has been creating.

Thanks for reporting the problem.

Regards, 
Nadezhda.
