### ISSUE TITLE
Table with borderless, no-lines styles still have some lines

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#3188]
post: https://stackoverflow.com/questions/67499349/how-can-i-change-the-design-of-default-elements-in-cuba-platform/67516418#67516418

### Environment

- Platform version: 7.2
- Theme: hover

### Description of the bug or enhancement
- Open sampler: https://demo10.cuba-platform.com/sampler/#main/0/sample?id=styles-table
- Turn on borderless, no-horizontal-lines, no-vertical-lines styles

Expected: no borders, no lines inside

Actual: there are still borders: in the right, bottom, and lines in the header.

![image](https://user-images.githubusercontent.com/6158807/118104497-42d76c00-b3ec-11eb-976f-d41af3088377.png)

## Solution

* `no-vertical-lines` correctly removes header and footer vertical lines:
before
![Screenshot 2021-06-24 at 12 37 02](https://user-images.githubusercontent.com/6077149/123231060-e5edcc00-d4e8-11eb-847d-fb6dbacb240b.png)
after
![Screenshot 2021-06-24 at 12 33 09](https://user-images.githubusercontent.com/6077149/123230500-5c3dfe80-d4e8-11eb-940d-eac205e86e60.png)

* `borderless` correctly removes inner border
before
![Screenshot 2021-06-24 at 12 37 45](https://user-images.githubusercontent.com/6077149/123231166-0158d700-d4e9-11eb-8313-4449083abbb7.png)
after
![Screenshot 2021-06-24 at 12 35 47](https://user-images.githubusercontent.com/6077149/123230953-cd7db180-d4e8-11eb-8697-1778db39bd46.png)

**Pay attention** that `no-horizontal-lines` doesn't remove line between header/footer and table body by design:
![Screenshot 2021-06-24 at 12 31 24](https://user-images.githubusercontent.com/6077149/123231360-2f3e1b80-d4e9-11eb-9ef0-442fc45bbaa7.png)

**Pay attention** that nether `no-vertical-lines` nor `no-horizontal-lines` don't remove inner border by design:
![Screenshot 2021-06-24 at 12 28 27](https://user-images.githubusercontent.com/6077149/123231796-9360df80-d4e9-11eb-8906-101d949d1d5f.png)

**Comment by maistrenkoIulia** [comment]
reproduced on CUBA Platform version: 7.2-SNAPSHOT
CUBA Studio plugin version: 15.0.SNAPSHOT2727-202
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)
[bordless.zip](https://github.com/cuba-platform/cuba/files/6740774/bordless.zip)

![image](https://user-images.githubusercontent.com/66992566/123959182-eee60e00-d9be-11eb-8fd2-e3069def7d62.png)

**Comment by maistrenkoIulia** [comment]
7.2-snapshot  - ok
7.3-snapshot -nok
![image](https://user-images.githubusercontent.com/66992566/123967487-69b32700-d9c7-11eb-8643-00e15facf639.png)
CUBA Platform version: 7.3-SNAPSHOT
CUBA Studio plugin version: 15.0.SNAPSHOT2727-202
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)
[bordless.zip](https://github.com/cuba-platform/cuba/files/6741190/bordless.zip)

**Comment by glebfox** [comment]
@maistrenkoIulia create a separate issue for `DataGrid`.
