### ISSUE TITLE
[DataGrid] Columns selected by SelectAll action aren't saved in user settings

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#3189]
### Description of the bug or enhancement

- Minimal reproducible example

[demo.zip](https://github.com/cuba-platform/cuba/files/6471889/demo.zip)

. Open Students browser
. Invoke the Select All action from the column collapsing menu
. Close and reopen the screen

- Expected behavior
All columns are shown

- Actual behavior
The columns set remain the same

Also check table

**Comment by Harikrishnadhas** [comment]
Same issue with DeSelectAll as well, Please check that too.
