### ISSUE TITLE
DataGrid item details are disappeared after removing an item

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#3192]
### Environment
- Platform version: 7.2
- Client type: Web

### Description of the bug or enhancement
Forum RU: [topic](https://www.cuba-platform.ru/discuss/t/posle-udaleniya-elementa-soderzhanie-detalej-datagrid-propadaet/5704)

#### Minimal reproducible example
1. Download attached project: [datagrid.zip](https://github.com/cuba-platform/cuba/files/6507636/datagrid.zip)
2. Open the "datagrid_" screen and try to remove an item.

- Expected behavior
Entity details are shown.
- Actual behavior
Empty space instead of details.

**Comment by Flaurite** [comment]
Vaadin fixed the problem in 8.12.0 version: https://github.com/vaadin/framework/issues/12106

**Comment by Flaurite** [comment]
Backported commit **partly** fixes the issue.

Wait the following Vaadin issues:
- https://github.com/vaadin/framework/issues/12211
- https://github.com/vaadin/framework/issues/12328

**Comment by owlet1997** [comment]
- [ ] version 7.2
- [ ] version 7.3
