### ISSUE TITLE
Presentation mechanism does not work

### ISSUE THREAD

**Issue by natfirst** [cuba-platform/cuba#3195]
### Environment

- Platform version: 7.2.13
- Forum issue https://forum.cuba-platform.com/t/does-not-record-presentations-on-a-group-table/15267

### Description of the bug or enhancement

1. Create an entity with several attributes
2. Generate standard screens
3. [Enable](https://doc.cuba-platform.com/manual-7.2/gui_Table.html#gui_Table_presentations) [presentation](https://doc.cuba-platform.com/manual-7.2/gui_presentations.html) mechanism in table
4. Run the app.
5. Set up two presentations, make one default, try to switch between them, reopen the screen

*A.R.* Nothing happens, the presentation does not apply
*E.R.* Default presentation should be applied on the screen opening. Table columns set should change when switching between presentations

**Comment by Flaurite** [comment]
Unfortunately, cannot reproduce the problem. I can suggest that the `settingsEnabled` attribute was set to "false" so "presentations" cannot be saved and applied correctly.
