### ISSUE TITLE
Incorrect importing entities with embedded entities

### ISSUE THREAD

**Issue by TiratoRZaK** [cuba-platform/cuba#3196]
### Environment

- Platform version: 7.2.13
- Database: PostgreSQL

### Description of the bug or enhancement

The entity has a embedded entity and is exported using the Entity Inspector to a JSON file. In the JSON file, the fields are filled in with the correct values. But when importing, an error appears on the same screen, signaling that the fields defined in the embedded entity are null.
- Create an entity that has a embedded entity with required fields
- Open the entity inspector for the created entity
- Create an instance of an entity with the fields fully filled in
- Use the "Export" button to export an instance of an entity to a JSON file
- Open the file and change the entity ID
- Use the "Import" button to import the created JSON file

**Comment by owlet1997** [comment]
- [ ] version 7.3 
- [ ] version 7.2
