### ISSUE TITLE
Issues with attribute starting with one lowercase letter

### ISSUE THREAD

**Issue by Gasloff** [cuba-platform/cuba#3197]
CUBA Platform version: 7.2.13

Create project, add entity
Add attribute starting with one lowercase letter. E.g. aField.
Studio generates getter and setter for this attribute according to Java Bean Convention:
`getaField`
`setaField`
 
See  [JetBrains forum](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206879995-bean-naming-conventions-getter-setter) for details.

Add standard screens for the entity.
Run application.

With such getter and setter names editor screen has some issues: the form field for an `aField` property is not editable.
There are some other issues faced by forum user, see https://www.cuba-platform.ru/discuss/t/studio-mozhet-generirovat-nekorrektnye-gettery-i-settery/5744 (Russian)

**Comment by andreysubbotin** [comment]
https://github.com/cuba-platform/cuba-gradle-plugin/issues/154
