### ISSUE TITLE
LinkButton with primary=true displays as regular button

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#3203]
```
<linkButton primary="true" caption="Link Button"/>
```

AR:
<img width="112" alt="Screenshot 2021-07-05 at 11 25 58" src="https://user-images.githubusercontent.com/6077149/124433706-1bfe3c00-dd84-11eb-8e1e-f6fdb2ed0bb8.png">

ER:
<img width="111" alt="Screenshot 2021-07-05 at 11 47 28" src="https://user-images.githubusercontent.com/6077149/124436246-d3944d80-dd86-11eb-87a2-e5b9ecf07d8f.png">

**Comment by owlet1997** [comment]
Case: 
- theme `hover`

**AR**
![image](https://user-images.githubusercontent.com/45730069/124557314-6a760e00-de4a-11eb-87d1-58d485d22926.png)

**ER**:
![image](https://user-images.githubusercontent.com/45730069/124557386-7e217480-de4a-11eb-83a5-186f2c587237.png)
