### ISSUE TITLE
Add minHeight and minWidth attributes to Table and DataGrid

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#3209]
### Description of the bug or enhancement
In Table and DataGrid content is not visible when the browser tab has small sizes:
![image](https://user-images.githubusercontent.com/22093943/125409520-06fd5a80-e3cd-11eb-9628-6e0b9dbeb3f7.png)

Table and DataGrid should provide ability to set minHeight and minWidth without extending theme.

### Changes

Added new attributes:
- minHeight
- minWidth

to `Table`, `GroupTable`, `TreeTable`, `DataGrid`, `TreeDataGrid`. For instance:
```
<groupTable id="table"
            width="100%"
            minHeight="200px"
            minWidth="400px"
```

Added new interface `HasMinSize`:
```
Float getMinHeight();
SizeUnit getMinHeightSizeUnit();
void setMinHeight(String);

Float getMinWidth();
SizeUnit getMinWidthSizeUnit();
void setMinWidth(String);
```

**Note** that minWidth and minHeight is set not to the composition but to the Table and Grid.

### QA
Check tables and dataGrids above with new attributes: `minHeight` and `minWidth`.

**Comment by konyashkina** [comment]
Tested on: 

1. CUBA Platform version: 7.3-SNAPSHOT
CUBA Studio plugin version: 15.4-202 

2. CUBA Platform version: 7.2-SNAPSHOT
CUBA Studio plugin version: 15.4-202

IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
