### ISSUE TITLE
Table Deselect All action takes lots of time to perform

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba#3212]
### Environment
- Platform version: 7.2
- Client type: Web

### Description of the bug or enhancement
See RU forum: [topic](https://www.cuba-platform.ru/discuss/t/group-table-skryt-vse-stolbczy-umiraet-esli-tablicza-s-bolshim-chislom-kolonok-i-strok/5843).

"Deselect All" requires too much time to perform when table has a lot of column (tested on 260 columns).
The main problem is "Deselect All" loops every column action and triggers column adjustment.

### QA
1. Add to the table 260 columns: [260.txt](https://github.com/cuba-platform/cuba/files/6877974/260.txt)

2. Click on "Deselect All". It should take about 1-2 seconds (depends on hardware)

**Comment by konyashkina** [comment]
Tested on 

1. CUBA Platform version: 7.2-SNAPSHOT
CUBA Studio plugin version: 15.4-202

2. CUBA Platform version: 7.3-SNAPSHOT
CUBA Studio plugin version: 15.4-202

IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
Chrome 92.0.4515.107, Firefox 90.0.2
