### ISSUE TITLE
enabledRule handler does not work for popupButton on groupTable

### ISSUE THREAD

**Issue by lovtsovaik** [cuba-platform/cuba#3227]
see forum topic https://forum.cuba-platform.com/t/enabledrule-handler-does-not-work-for-popupbutton-on-grouptable/15642

### Environment

Platform version: 7.2.15
Studio plugin version: 15.6-202

### Description of the bug or enhancement
- Create an entity Book
- Create some attributes
- Create browser (with groupTable) and editor screens
- Open browser descriptor
- Add refresh action to actions list
`<action id="excel" type="excel"/>`
- Add popup button in the buttons panel
```
                <popupButton id="reviewPopupButton" caption="popup">
                    <actions>
                        <action id="booksTable.excel" type="excel"/>
                        <action id="popupAction" caption="popupAction"/>
                    </actions>
                </popupButton>
```
- Open browser controller
- Add enabledRule event handler to popup actions (see also #3226 for correct action definition):
 ```
    @Install(to = "reviewPopupButton.popupAction", subject = "enabledRule")
    private boolean reviewPopupButtonPopupActionEnabledRule() {
        notifications.create(Notifications.NotificationType.WARNING)
                .withCaption("reviewPopupButton.popupAction")
                .show();
        return false;
    }

    @Install(to = "booksTable.excel", subject = "enabledRule")
    private boolean reviewPopupButtonBooksTableExelEnabledRule() {
        notifications.create(Notifications.NotificationType.WARNING)
                .withCaption("booksTable.exel")
                .show();
        return false;
    }
```
- Run the application
- Open Browser screen
*here you'll see the notification from booksTable.exel action handler, close it*
- Click popup button

**Expected behavior**
Both actions are unavailable, notifications about both handlers are shown.

**Actual behavior**
popupAction is available, and no notifications from it
![image](https://user-images.githubusercontent.com/73226373/132021250-80de93e6-65f3-4cf0-bb1a-b0e2c5354349.png)

**Comment by glebfox** [comment]
Actions check their `enabledRule` when the `Action.refreshState()`method is invoked. Table only refreshes actions directly added to it, i.e. actions table nows about. In the case above `<action id="popupAction" caption="popupAction"/>` belongs only to `PopupButton` thus no `refreshState()` is called for it. Either make it table action or subscribe to Table's `SelectionEvent` and call `refreshState()` manually.
