### ISSUE TITLE
Upgrade to Vaadin 8.14

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#3245]
### Environment

- Platform version: 7.2.16

### Description of the bug or enhancement

Upgrade to latest Vaadin 8.14 to fix security vulnerabilities.

### QA
While perform testing open devtools of your browser tab to check exceptions. Make a smoke test in Sampler:
- Check components, especially: DataGrid, Table, Calendar, DateField, DatePicker.
- Check charts, maps, pivotTable, layouts.

**Comment by reznikova21** [comment]
Errors found:

**Test сase 1:** 
Maps > Heat Map

 **Test сase 2:** 
Predefined styles > Styles >  Misc 

**Test case 3:**
Containers > Accordion > Simple Accordion

**Test case 4:**
Containers > Accordion > Lazy tab in Accordion

**Comment by Flaurite** [comment]
"Test case 1" is reproduced in v7.2.16 too. Created an issue in the maps add-on. **Will be fixed in next releases.**

Cases 2 - 4 has the same problem described in https://github.com/cuba-platform/cuba/issues/3249. **Will be fixed in next releases.**
