### ISSUE TITLE
Entity inspector exports composition collections with a _minimal view

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#3262]
### Environment

- Platform version: 7.2.18

### Description of the bug or enhancement

1. Create an entity with a composition collection, e.g. `Order -> OrderLines`. The `OrderLine` entity must have several attributes.

1. Create an entity instance.

1. Open the entity inspector screen and export the `Order` instance.

AR: In the JSON file the orderLines collection will contain items where only attributes from the instance name are present.

ER: composition collection items should be exported with the _local view. Probably, the associations should be loaded there as well.

Forum: https://forum.cuba-platform.com/t/problems-with-json-import-export-and-compositions/16150

### Implemented:
Local and system properties has been added to export view for composition entities.

~~Also we need to check this issue in Jmix.~~ -> checked: no such problem.

**Comment by rusiaikinat** [comment]
https://github.com/cuba-platform/cuba/issues/3290#issue-1441704457  The deleted entity is restored during import JSON #3290
