### ISSUE TITLE
Use java.util.function.Consumer<T> with Event class instead of listener interfaces

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#327]
Implement new EventRouter mechanism for Event based firing not depending on listener interfaces, name it FunctionalEventRouter
Provide style guide on implementing UI components with events
Each event should be subclass of java.util.EventObject and has source object

See prototype here: https://github.com/strangeway-org/event-router

:link: Related links: {"relates to:": "https://youtrack.haulmont.com/issue/PL-8125", "is required for:": "https://youtrack.haulmont.com/issue/PL-8299"}

Also, we could move add/remove methods from components to interfaces, as it is done in Vaadin Flow: 
- https://github.com/vaadin/flow/commit/8bc7c8729179cefb1277ba1f50417af4ffab79a9
---
Original issue: https://youtrack.haulmont.com/issue/PL-8412

**Comment by jreznot** [comment]
Example:
```
public interface EditableChangeNotifier {
    default Subscription addEditableChangeListener(EditableChangeListener listener) {
        return ((EventPublisher) this).subscribe(EditableChangeEvent.class, listener);
    }

    default void removeEditableChangeListener(EditableChangeListener listener) {
        return ((EventPublisher) this).unsubscribe(EditableChangeEvent.class, listener);
    }
...
}
```
