### ISSUE TITLE
Changes of collection attributes are not saved to Entity Log

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#329]
1) create an entity "Master"
2) create an entity "Detail"
3) create an entity "Slave"
4) create one_to_many association "Master" with "Slaves"
5) create composition "Master" with "Details"
6) for all the entities create views with links 
7) create standard screens by the views

8) start the application server
9) adjust Entity log for the "Master" entity to write all changes (*including association and composition*) automatically
10) create an instance of "Master"
11) create several "Details"
12) create several "Slaves" and associate them with "Master"
13) view the entity log for The "Master" entity

AR: No changes in "slaves" and "details" attributes registered, not depending the Collection type.

---
Original issue: https://youtrack.haulmont.com/issue/PL-8422

**Comment by knstvk** [comment]
Collection attributes are not available in EntityLog anymore.
