### ISSUE TITLE
Long classpath leads to Cuba gradle tasks fails in Windows

### ISSUE THREAD

**Issue by igisho** [cuba-platform/cuba#3298]
### Environment

- Platform version: 7.2.20 (originally was trying in 7.2.8, but neither works) 

- Client type: Web
- Browser: Chrome
- Database: HSQL
- Operating system: Windows

### Description of the bug

1. Create new cuba project 
2. Add bunch of dependencies: appComponent("com.haulmont.cuba:cuba-global:$cubaVersion")
    appComponent("com.haulmont.reports:reports-global:$cubaVersion")
    appComponent('com.haulmont.addon.restapi:restapi-global:7.2.6')
    appComponent('com.haulmont.addon.emailtemplates:yet-global:1.4.2')
    appComponent('com.haulmont.addon.helium:helium-global:0.4.0')
    appComponent('de.diedavids.cuba.dataimport:dataimport-global:0.14.1')
    appComponent('de.diedavids.cuba.dblocalization:dblocalization-global:0.4.0')
    appComponent('com.haulmont.addon.dnd:cuba-dnd-global:1.7.0')
3. Try to run (everything works)
4. Add  appComponent('com.haulmont.addon.tour:tour-global:1.3.0') dependency
5. Try to run > CreateProcess error=206, The filename or extension is too long

Execution failed for task ':app-web-toolkit:buildWidgetSet'.
> A problem occurred starting process 'command 'C:\Users\igor.sovcik\.jdks\liberica-11.0.18\bin\java.exe''

**Comment by gorbunkov** [comment]
Seems to be fixed in https://github.com/cuba-platform/cuba-gradle-plugin/issues/14
Try adding the shortClasspath=true property to the CubaWidgetSetBuilding task as described in the [issue comment](https://github.com/cuba-platform/cuba-gradle-plugin/issues/14#issuecomment-723885755).

**Comment by igisho** [comment]
@gorbunkov Works well with native "marketplace dependencies" but if you add more dependencies to "global" module you get same error. For example add dependencies to global module: compile 'org.fusesource.jansi:jansi:1.8'
        compile 'com.google.api-client:google-api-client:1.23.0'
        compile 'com.google.oauth-client:google-oauth-client-jetty:1.23.0'
        compile 'com.google.apis:google-api-services-drive:v3-rev110-1.23.0'
        compile 'com.google.apis:google-api-services-docs:v1-rev20190827-1.30.1'
        compile 'org.bitbucket.b_c:jose4j:0.6.3'
        compile 'com.jcabi:jcabi-aspects:0.22.5'

**Comment by igisho** [comment]
@gorbunkov thank you, worked like charm had to upgrade platform to 7.2.10 (i was avoiding this for several reasons) but this and also "shortClassPath = true" fixed issue.
