### ISSUE TITLE
Tabbing between fields works incorrectly.

### ISSUE THREAD

**Issue by AndreyLednev** [cuba-platform/cuba#3299]
In Cuba 5 I can use the "tab" key to move down into each input box, but in Cuba 7 this doesn't work. Because tab doesn't work I click into the next input box but the cursor does not follow my click so I have to click twice to get the cursor to follow

https://github.com/cuba-platform/cuba/assets/6077149/6f116303-63eb-427d-af15-7a6ff53a7ab8

**Comment by glebfox** [comment]
Duplicates: https://github.com/cuba-platform/cuba/issues/2712

---

The workaround is: replace non-editable columns by generated column with `Label` or `Table.PlainTextCell`:
```
table.addGeneratedColumn("name", entity -> new Table.PlainTextCell(entity.getName()));
```
