### ISSUE TITLE
Newline in markdown within a paragraph should not cause hard break in rendered HTML

### ISSUE THREAD

**Issue by anothernode** [cuba-platform/cuba#33]
CUBA Studio automatically shows the rendered output of any `README.md` in the project root if present, which is really cool by the way.

I have one small problem with the rendered output though: Newlines within a paragraph in the markdown source get rendered as hard breaks in the HTML output (`<br>`), as demonstrated below.

So, a markdown source like this...
![screen shot 2018-02-16 at 17 48 34](https://user-images.githubusercontent.com/3286144/36319333-e44ad804-1342-11e8-8ef6-ec67ef51d912.png)

...gets rendered like this:
![screen shot 2018-02-16 at 17 44 46](https://user-images.githubusercontent.com/3286144/36319368-02566912-1343-11e8-8c3d-93e9eba4f7a4.png)

I think this does not comply with the [CommonMark specification](http://spec.commonmark.org/0.28/#soft-line-breaks), but more importantly it makes the READMEs I write for my CUBA projects look worse than they should, because I prefer not using soft wrapping in my code (including markdown).

It's obviously a minor and purely esthetic issue, but I would be very pleased if this could be fixed.

**Comment by knstvk** [comment]
Right now we use YouTrack as a main issue tracker. Please see https://youtrack.cuba-platform.com/issue/STUDIO-4402.

**Comment by comru** [comment]
Hi @anothernode ! Studio processed markdown source in accordance with the ![GitHub](https://gist.github.com/shaunlebron/746476e6e7a4d698b373) rules. Most likely you have two or more spaces after the separated line.

**Comment by anothernode** [comment]
Hi @comru, thanks for your reply!

The first screenshot I added to the issue shows the markdown source opened in Atom editor with the "Show Invisibles" option enabled. That symbol that looks like an "L", but mirror-inverted and turned by 90 degree (you have to look closely, it's light grey on dark grey...) is Atom's representation of a single newline character. If there were additional whitespaces they would be visible, too.

The link that you posted shows the correct behavior in the second example. There is newline between "Hello" and "World" in the source, but not in the output. But this is not what CUBA Studio is doing, CUBA Studio would render this as:
```
Hello<br>
World
```

**Comment by jreznot** [comment]
Newlines are handled in accordance to PegDown logic. We do not manage this.

**Comment by anothernode** [comment]
Do you mean [this PegDown](https://github.com/sirthias/pegdown)?

That project is apparently deprecated and unmaintained. So there are no upstream fixes to be expected.

I guess Markdown rendering will unfortunately remain broken in CUBA Studio then 😞

**Comment by jreznot** [comment]
Actually,
In the new Studio version we will use embedded Intellij Idea Markdown plugin, I hope it will be better

**Comment by anothernode** [comment]
I see, that sounds good then! Looking forward to it. Thanks for letting me know!
