### ISSUE TITLE
Aggregation for DataGrid component

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#330]
Aggregation for DataGrid component

---
Original issue: https://youtrack.haulmont.com/issue/PL-8428

**Comment by Flaurite** [comment]
### Changes

`DataGrid` and `TreeDataGrid` support aggregation.
![image](https://user-images.githubusercontent.com/22093943/69849688-dd92c800-1296-11ea-9aff-13e652902568.png)

### Description
To enable aggregation in `DataGrid` you need to define: `aggregatable="true"` attribute and add `aggegation` element to some column. The functionality of aggregation is the same as for table. It means that you can use `strategyClass`, `valueDescription` and `formatter` for the aggregation.

XML Example:
```
<dataGrid id="testsDataGrid"
          aggregationPosition="BOTTOM"
          aggregatable="true">
    <columns>
        <column property="integerProperty">
            <aggregation strategyClass="com.company.test.MyStrategyClass"
                         valueDescription="msg://myValueDescription">
                <formatter class="com.company.test.MyFormatter"/>
            </aggregation>
        </column>
        ...
    </columns>
    ...
</dataGrid>
```
It is also available to change position of aggregated row using `aggregationPosition` attribute with two options: `TOP` and `BOTTOM`. Default value is `TOP`.

### Java API

Enable/disable and check aggregation:
- `dataGrid.setAggregatable(Boolean);`
- `dataGrid.isAggregatable();`

Set/get aggregation row position:
- `// DataGrid.AggregationPosition is an interface with TOP and BOTTOM values`
`dataGrid.setAggregationPosition(DataGrid.AggregationPosition);` // default value is TOP
- `dataGrid.getAggregationPosition();`

Get aggregation results:
- `dataGrid.getAggregationResults(); // returns Map<String, Object>`

### For QA
Download demo project:
For DataGrid and TreeDataGrid
1. Check aggregation row is shown
1.1 Try to change value from inline editor, make sure that aggregation value is updated.
1.2 Check 2.1 step on the mac (probably we have floated issue with updating aggregation values)
2. Try to enable/disable aggregation in runtime. Aggregation row must be hidden (for disabled) and shown (for enabled).
3. Try to change in runtime data container with container that does not support aggregation. Aggregation row must be hidden
4. Try to add headers when `aggregationPosition="TOP"` (append, prepend, at index). Aggregation row must be at the same position.
5. The same as 4 for footers.
