### ISSUE TITLE
Implement notification stacking for TRAY NotificationType

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#344]
When multiple tray notification messages are shown within a short period of time, they are shown at the same position (over each other), which makes the messages unreadable. We need to show TRAY notifications as a stack.

See: http://materializecss.com/dialogs.html

Vaadin issue: https://github.com/vaadin/framework/issues/676

---
Original issue: https://youtrack.haulmont.com/issue/PL-8531

**Comment by jreznot** [comment]
Implemented in Studio 6

**Comment by glebfox** [comment]
The stacking logic takes into account all notifications regardless of their type. Also, it's possible that notifications are showed outside visible screen area. 

![image.png](https://images.zenhubusercontent.com/5893814951aa2c3057735b6a/339f510e-2eb7-487d-a6d1-fe84fb12df92)

**Comment by Flaurite** [comment]
For QA: try simultaneously show TRAY and HUMANIZED notifications

**Comment by myatlevEvg** [comment]
In case of using new notification api and defining ``` .setStyleName
for notification stacking does not work

**Comment by Flaurite** [comment]
For QA:
1. Try show tray with `setStyleName()`;
2. Try show tray simultaneously: bottom_left, bottom_center, bottom_right plus humanized notification;
3. Try use old and new API together;
4. Check your cases.
