### ISSUE TITLE
studio generated app-component.xml missing property value

### ISSUE THREAD

**Issue by vmitache** [cuba-platform/cuba#35]
<property name="cuba.rest.servicesConfig"
                  value="+<package-name>/rest-services.xml"/>
Cuba Studio not adding the above property in web module section of "app-component,xml" , so component declared rest services are unavailable ..

**Comment by knstvk** [comment]
Thank you for reporting the problem. We have created an issue: https://youtrack.cuba-platform.com/issue/STUDIO-4423
