### ISSUE TITLE
Security constraint doesn't work for entities in nested collection / field

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#356]
In the Refapp:
Create a constraint like the one on the screenshot for the Repair entity.
Create a car, create a couple of repairs - some must start with A, some mustn't
If the user belonging to the access group that allows to view only repairs with description starting with 'A' opens the Car editor, he will see all repairs - constraint won't be applied. In the meantime in the Repairs browser constraint is applied.

---
Original issue: https://youtrack.haulmont.com/issue/PL-8616

**Comment by knstvk** [comment]
Use in-memory constraints for it.
