### ISSUE TITLE
Add copy button to copy system information scripts to clipboard

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#357]
Add copy button to copy system information and system information scripts to clipboard

---
Original issue: https://youtrack.haulmont.com/issue/PL-8617

**Comment by SemenSofronov** [comment]
Now it is possible to copy the scripts by clicking on the copy button. To copy from table you still need to use selection.

**Comment by jreznot** [comment]
Please check if this button is shown in Desktop. It should be hiddent

**Comment by natfirst** [comment]
Button should not be displayed in desktop

![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/bec003a6-6680-4f13-8606-4b6c4fc842a5)

**Comment by natfirst** [comment]
The button is still displayed in the desktop

**Comment by SemenSofronov** [comment]
Now, when you press the buttons to create scripts in the web client, a new button is displayed for copying the generated scripts to the clipboard.

![image](https://user-images.githubusercontent.com/13303883/43066385-97976154-8e75-11e8-89ff-657ad779f590.png)

Added lines to the main message package for displaying messages when you hover over the copy button, copied successfully and copying failed.
