### ISSUE TITLE
Implement ability to setup interactive help scenario for UI screen

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#358]
When user opens the UI screen he/she has ability to see it in tutorial/help mode, when the main scenario for this screen is shown on the same screen.

For example, if we open user editor the system will show that we need to fill name, surname, login, password, group, add roles and then click button OK.

Also it might be useful to setup "go-through" scenario with opening another screens.

For complex and not obvious screens the described scenario will provide to user the vision of developer/designer.

**Comment by jreznot** [comment]
Idea for app component

**Comment by jreznot** [comment]
Will be released as add-on.

**Comment by pribavkindenis** [comment]
Implemented as add-on.
