### ISSUE TITLE
IntelliJ not showing Gradle tools window

### ISSUE THREAD

**Issue by Zynde** [cuba-platform/cuba#36]
Hi,

I'm using the latest Studio and have created a simple application. When I click on the IDE button to open the project in IntelliJ that seem to work and open the project. However I cannot open the Gradle tools window in IntelliJ. The only way I can get Graddle to function correctly in IntelliJ is to close the project and import it which does seem to detect it as a Gradle project then I can see the Gradle Tools. Doing it this way also seems to fix some dependency issues I was having too.

Is this an issue with CUBA or my setup?

**Comment by jreznot** [comment]
Hi,

Unfortunately, we do not support integration with Gradle in Intellij yet. Studio generates .ipr files automatically when you click IDE thus there is no need to use standard integration.

For questions and discussions please use our forum: https://www.cuba-platform.com/discuss/
