### ISSUE TITLE
LDAP in Platform 6.8.3

### ISSUE THREAD

**Issue by koca2000** [cuba-platform/cuba#38]
Hi! I was testing LDAP login in 6.8.1. Everything works as it supposed to, but in platform 6.8.3 is bug. When user enter wrong password login is succesful and when he enter right password it says he entered wrong password.

I think that problem is with double negation in links below.
https://github.com/cuba-platform/cuba/blob/616a854dbd6be2a6f247e2bf2e5be6ae7c4eac30/modules/web/src/com/haulmont/cuba/web/security/ldap/LdapLoginProvider.java#L131

https://github.com/cuba-platform/cuba/blob/616a854dbd6be2a6f247e2bf2e5be6ae7c4eac30/modules/web/src/com/haulmont/cuba/web/security/ldap/LdapLoginProvider.java#L82

**Comment by jreznot** [comment]
Hi,
Thank you for the bug report, will fix it as soon as possible

**Comment by jreznot** [comment]
See the progress here: https://youtrack.cuba-platform.com/issue/PL-10529

**Comment by jreznot** [comment]
The fix will be available in build 6.8.4
