### ISSUE TITLE
'Show charts' report screen should show notification if the charts component isn't included in the application

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#382]
'Show charts' report screen should show notification if the charts component isn't included in the application

---
Original issue: https://youtrack.haulmont.com/issue/PL-8828

**Comment by knstvk** [comment]
Issue moved to [cuba-platform/reports #76](https://github.com/cuba-platform/reports/issues/76) via [**ZenHub**](https://www.zenhub.com/)
