### ISSUE TITLE
FormLayout

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#383]
FieldGroup "layout like" companion with simple API
* Multicolumn
* Flexible 
* Consistent API

**Comment by glebfox** [comment]
The new component provides functionality similar to FildGroup:

* Captions positioning: `TOP`, `LEFT`
* Group components by columns
* Components can obtain a `dataContainer` from a Form, i.e. a component can only define the `property` attribute

The main difference is that **Form** contains the components themselves, not abstract *fields* and doesn't support *datasources*, instead the new *data containers* are used.

The nested **column** element can define

* The width of the nested components
* The width of the nested component captions
