### ISSUE TITLE
Default values for attributes in data model

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#390]
See:
https://www.cuba-platform.com/support/topic/default-value-in-defining-entity
https://www.cuba-platform.com/support/topic/setting-an-initial-value-for-an-associated-entity-in-a-dropdown

---
Original issue: https://youtrack.haulmont.com/issue/PL-8863

**Comment by knstvk** [comment]
See https://youtrack.cuba-platform.com/issue/STUDIO-3817
