### ISSUE TITLE
Move cuba-idp to separate application component

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#411]
Move cuba-idp to separate application component

### Updates

New app property is added into CUBA:

`cuba.web.externalHttpFilterByPassUrls`

It is used by IDP app component to pass its URL to CUBA HttpFilter in a parent application.

Value of this property can be got with `WebConfig#getExternalHttpFilterBypassUrls()` method.

### QA

Check SSO sample from documentation: [link](https://doc.cuba-platform.com/manual-6.10/sso_example.html)

Check this sample with all deployment options:

- Standard
- Two WARs
- Single WAR
- Two UberJARs
- Single UberJAR

Check IDP configuration app properties described in documentation: [link](https://doc.cuba-platform.com/manual-6.10/sso.html).

---
Original issue: https://youtrack.haulmont.com/issue/PL-8991

**Comment by myatlevEvg** [comment]
Reopen.
Address of idp can't be reached.
![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/7dae3234-0334-450c-9715-5f80bde9219b)

**Comment by dtsaryov** [comment]
The problem is related to this issue: [idp-addon](https://github.com/cuba-platform/idp-addon/issues/2)
