### ISSUE TITLE
When embedded attribute is not filled during instance creation, it could not be filled afterward

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#415]
See also https://www.cuba-platform.com/support/topic/embedded-entity-failure

1) Create embeddable entity
2) Create another entity and embedded attribute - embed the entity from the previous step
3) Create standard screens for the entity
4) Start the server
5) Create a new instance of the entity not filling fields of embedded entity. Save
6) Reopen the entity instance and fill fields of the embedded entity. Save
7) Reopen the entity instance

AR: field are empty as the instance of the embedded entity was not created.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9002

**Comment by andreysubbotin** [comment]
Fixed in cuba-platform/cuba/issues/1081
