### ISSUE TITLE
PostCommit in EntityCombinedScreen

### ISSUE THREAD

**Issue by Zynde** [cuba-platform/cuba#42]
I don't know if this is an issue or a wish.

I have an **EntityCombinedScreen** where I would like to add some functionality to a **PostCommit**. I currently do this in screens that Extend from AbstractEditor but I can't seem to do this from an EntityCombinedScreen.

I'm thinking that in the **save** method of the EntityCombinedScreen class in the Platform code just after the commit statement there could be a call for PostCommit. 

I don't know if it would be possible or wise to override the save method like this in the screen that extends EntityCombinedScreen

    @Override
    public void save() {
        super.save();
        
        //DO MY POST COMMIT ACTIONS HERE
    }

**Comment by knstvk** [comment]
Thank you for the idea. I've created an issuein our internal bug tracker: https://youtrack.cuba-platform.com/issue/PL-10692
Right now you can override `save()` as you mentioned - it should work fine, just call super in the beginning.
