### ISSUE TITLE
Entity relation field cannot be named as "object"

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#421]
1) Create two entities - Entity1 and Entity2 
2) Entity2 is a field mapped with @ManyToOne relation to Entity1
3) Name the field instance of Entity2 annotated with @ManyToOne as "object"
4) Create a service returning List of Entity1 related to Entity2.
Example of a JPQL query:
loadContext.setQueryString("SELECT er FROM prj$Entity1 er WHERE er.object.id = :objectOfEntity2")
.setParameter("objectOfEntity2", objectOfEntity2);
ER: the JPQL should be successfully parsed
AR: JPQL doesn't get parsed and error is thrown.

If the field is renamed to something other than "object" JPQL query is getting parsed successfully

---
Original issue: https://youtrack.haulmont.com/issue/PL-9037

**Comment by andreysubbotin** [comment]
Fixed in https://youtrack.haulmont.com/issue/PL-10243
Releases: 6.9.0 and 6.8.4.
