### ISSUE TITLE
Pass properties from menu to screen and fragment opened declaratively

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#437]
Example from Grails: http://docs.grails.org/3.1.1/ref/Tags/render.html

We should provide something like properties of Fragment that can be set from XML:
```XML
<fragment id="commentsFragment"
          screen="demo_CommentsFragment">
    <properties>
        <!--values-->
        <property name="message" value="msg://loginWindow.welcomeLabel"/>
        <property name="compactMode" value="true"/>
        <property name="pageSize" value="10"/>
        <!--references-->
        <property name="itemsTable" ref="itemsTable"/>
        <property name="orderDc" ref="orderDc"/>
    </properties>
</fragment>
```

Here, we are using properties that correspond to public setters in Fragment controller:
```Java
@UiController("demo_CommentsFragment")
@UiDescriptor("comments-fragment.xml")
public class CommentsFragment extends ScreenFragment {

    // values
    private String message;
    private int pageSize;
    private boolean compactMode;
    // references
    private InstanceContainer orderDc;
    private Table itemsTable;

    public void setMessage(String message) {
        this.message = message;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    public void setCompactMode(boolean compactMode) {
        this.compactMode = compactMode;
    }

    public void setOrderDc(InstanceContainer orderDc) {
        this.orderDc = orderDc;
    }

    public void setItemsTable(Table itemsTable) {
        this.itemsTable = itemsTable;
    }
}
```

All setters must be called after `init` and before `show`

## Updates

A way to pass declarative properties to screens and screen fragments is introduced.
It enables to set a set of primitive values that will be injected into controller via setters declared in Java Beans syntax - they are public methods with single parameter named as "set" + capitalized property name:

```Java
public class Bar {
    private int myProperty;

    public void setMyProperty(int value) {
        this.myProperty = value;
    }
}
```

In addition to primitive values it is available to pass id of component, datasource or data container located in owning screen.

### Passing properties to screen

Declare properties in menu config to pass them into screen:

```XML
<item id="sec$User.browse">
    <properties>
        <property name="stringProperty" value="Hello World!"/>
        <property name="intProperty" value="42"/>
    </properties>
</item>
<item screen="sec$User.edit">
    <properties>
        <!-- Entity will be loaded and injected via built in setEntityToEdit method, because it satisfies required conditions -->
        <property name="entityToEdit"
                  entityClass="com.haulmont.cuba.security.entity.User"
                  entityId="60885987-1b61-4247-94c7-dff348347f93"
                  entityView="user.edit"/>

        <!-- Entity will be injected via setTestUser method -->
        <property name="testUser"
                  entityClass="com.haulmont.cuba.security.entity.User"
                  entityId="anotherId"/>
    </properties>
</item>
```

They will be injected if screen controller has corresponding setters:
```Java
private String stringProperty;
private int intProperty;

// inject "Hello World" here
public void setStringProperty(String value) {
   this.stringProperty = value;
}

// inject "42" here
public void setIntProperty(int value) {
   this.intProperty = value;
}
```

### Passing properties to screen fragment

Unlike screens components, datasources and data containers can be passed to screen fragments. The difference is that `value` attribute is used for primitives and `ref` attribute is used for references:

```XML
<dsContext>
    <groupDatasource id="usersDs" ... />
</dsContext>

<layout>
    <!-- Screen Layout -->

    <table id="testTable" ... />

    <fragment screen="sample_TestFragment">
        <properties>
            <property name="booleanProperty" value="true"/>
            <property name="doubleProperty" value="3.14159"/>
            <property name="usersDs" ref="usersDs"/>
            <property name="usersTable" ref="usersTable"/>
        </properties>
    </fragment>
</layout>
```

They will be injected into screen fragment in the following way:

```Java
private Boolean booleanProperty;
private double doubleProperty;

private CollectionDatasource usersDs;
private Table usersTable;

// "true" will be injected here
public void setBooleanProperty(Boolean value) {
    this.booleanProperty = value;
}

// "3.14159" will be injected here
public void setDoubleProperty(double value) {
    this.doubleProperty = value;
}

// "usersDs" will be injected here
public void setUsersDs(CollectionDatasource ds) {
    this.usersDs = ds;
}

// "usersTable" will be injected here
public void setUsersTable(Table table) {
    this.usersTable = table;
}
```

### Lifecycle

These injections are performed after `init` and before `show`.

### QA

Checklist:
- [x] Passing properties to screens - primitives and entities
- [ ] Passing properties to screen fragments - primitives and refs (ids of components, datasources, data containers)
- [x] Properties are injected if "field + setter" pair is declared in parent class (check that properties passing considers inheritance)
- [x] Wrong usage is logged or exceptions are thrown (empty property name/value/ref)

**Comment by jreznot** [comment]
The same for menu commands with type screen.

**Comment by dtsaryov** [comment]
Studio issue: [YouTrack](https://youtrack.cuba-platform.com/issue/STUDIO-6099)

**Comment by natfirst** [comment]
Show all problems as exceptions, do not only add information about problems in log, it is not obvious

**Comment by natfirst** [comment]
Case with the fragment does not work

In the attached project open New Screen, check that the value of doubleProperty does not set in the text field.

[pass-prop.zip](https://github.com/cuba-platform/cuba/files/3285767/pass-prop.zip)
