### ISSUE TITLE
EntityCombinedScreen bug in frames and TabSheets

### ISSUE THREAD

**Issue by Zynde** [cuba-platform/cuba#44]
Hi,

I think there is an issue with using a Combined Screen within a TabSheet.

I'll try to explain.

I have a screen with multiple tabs. In a tab I have placed a frame with a Combined Browse/Edit screen. When I switch to the tab containing the combined screen a lot of the elements go in to read only mode.

What is happening is this.

In the EntityCombinedScreen there is a method getTabSheet which looks for a TabSheet component with a specific ID "tabSheet". When getTabSheet() is called from within initEditComponents it actually locates the TabSheet in the parent frame which happens to be called "tabSheet" the sets everything to readonly. 

The getTabSheet call ends up in ComponentHelper.getFrameComponent with the correct frame as a parameter and the id = "tabSheet". Since the CombinedScreen has no TabSheet or component with id "tabSheet" the code drops in to frame.getFrame().getComponent(id) which locates the TabSheet with id "tabSheet" in the parent frame.

So I guess why, if you want to find a component of a Frame using ComponentHelper.getFrameComponent would it traverse up the tree to check parents?

Is there a method to check ONLY children and not traverse backwards to parents?

This kind of makes combined screens a bit unusable in frames. I suspect a workaround might be to either add a dummy tabsheet to the combined screen or give the parent screen's TabSheet an id other than "tabSheet"

**Comment by knstvk** [comment]
Using screens in frames is not supported.
