### ISSUE TITLE
Button declarative invoke methods become available for external use of Window controller

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#440]
If we declare invoke method:
```
<button caption="msg://editable" invoke="switchEditable"/>
```

```
public void switchEditable() {
    switchableEditable.setEditable(!switchableEditable.isEditable());
}
```

These methods become a part of public API of Window controller and visible if we use openWindow with cast to controller type

---
Original issue: https://youtrack.haulmont.com/issue/PL-9154

**Comment by jreznot** [comment]
Is not an issue anymore, due to #196
