### ISSUE TITLE
Vaadin 8

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#444]
Vaadin 8

:link: Related links: {"relates to:": "https://youtrack.haulmont.com/issue/PL-9166", "is required for:": "https://youtrack.haulmont.com/issue/PL-8814"}

---
Original issue: https://youtrack.haulmont.com/issue/PL-9168

**Comment by jreznot** [comment]
Closing this because the main migration finished. Now we will create separate related issues.

**Comment by glebfox** [comment]
Fixed: https://github.com/cuba-platform/cuba/commit/d7867f6e097ce6898aedc3b98e368a41b20485ec
