### ISSUE TITLE
Use SLF4J for Vaadin and Atmosphere Framework

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#445]
Use SLF4J everywhere if it is possible

https://www.cuba-platform.com/support/topic/slf4j-logging-everywhere

Alternative ways:

* http://adfinmunich.blogspot.ru/2012/03/how-to-configure-tomcat-to-use-slf4j.html
* http://hwellmann.blogspot.ru/2012/11/logging-with-slf4j-and-logback-in.html

---
Original issue: https://youtrack.haulmont.com/issue/PL-9169

**Comment by jreznot** [comment]
Already done for Atmosphere and Vaadin

**Comment by jreznot** [comment]
Now logging from Vaadin should go to app.log and can be disabled with logback.xml settings
