### ISSUE TITLE
Cannot set some dates to DateField depending on time zone

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#446]
Cannot set 01-01-1970 to DateField if time zone is UTC+00:00 Dublin, Lisbon, London

https://github.com/vaadin/framework/issues/8881

---
Original issue: https://youtrack.haulmont.com/issue/PL-9178

**Comment by glebfox** [comment]
Since Vaadin completely reimplemented date fields in Vaadin 8, the issue is no longer relevant
