### ISSUE TITLE
Filling current month and year after entering a day in DateField

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#447]
See https://www.cuba-platform.com/support/topic/date-custom-datatype#comment-6455

Probably we could make this a standard functionality which is turned on by a component attribute like `autocomplete="true"`

### Updates
The `DateField` component has a new boolean attribute `autofill`. If this attribute is enabled, then `DateField` automatically fills the current month and year after entering the day. If the attribute is disabled, then `DateField` resets value when the date is not fully entered.
Also if `autofill` attribute is enabled and `rangeStart` or `rangeEnd` have set, then DateField considers `rangeStart` and `rangeEnd` when fills value.

![autofill.gif](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/da8f841e-cad2-497e-9b9b-9bc8ef1bcc52)

#### Test case 1
* Set `autofill = true`
* Enter only a day
**Expected behaviour**  
The component value will look like this: `enteredDay/currentMonth/currentYear`
#### Test case 2
* Set `autofill = true`
* Enter only day and month
**Expected behaviour**  
The component value will look like this: `enteredDay/enteredMonth/currentYear`
#### Test case 3
* Set `autofill = true`
* Enter only invalid day
**Expected behaviour**  
The component value will be empty
#### Test case 4
* Set `autofill = true`
* Enter only invalid month
**Expected behaviour**  
The component value will be empty
#### Test case 5
* Set `autofill = true`
* Set `rangeStart`
* Enter a day before the  rangeStart's date
**Expected behavior**  
The component value will be filled to rangeStart
#### Test case 6
* Set `autofill = true`
* Set `rangeEnd`
* Enter a day after the  rangeEnd's date
**Expected behavior**  
The component value will be filled to rangeEnd

**Comment by GlebDurygin** [comment]
### Case
#### Description
The attribute `autofill` does not take into account the value of the year.
#### Minimal reproducible example
* Set `autofill = true`
* Set `rangeEnd = 31/12/2019`
* Enter value `01/01/2020`

#### Expected behavior
The component value will be filled to `rangeEnd` i.e. `31/12/2019`
#### Actual behavior
The component value is `01/01/2020`
