### ISSUE TITLE
SplitPanel dockable mode doesn't work if there is space before Split component

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#450]
SplitPanel dockable mode doesn't work if there is space before Split component

Original issue: https://youtrack.haulmont.com/issue/PL-9185

---

### How to test

1. Add before SplitPanel some components that will takes some space.
 Add to SplitPanel dockMode=LEFT. 
Open screen and click on the dock button. It should be replaced to absolute left position and dock button should be turned to the right.
Click on the dock button again. It should be replaced to the previous position.
2. Check that "dock" button changes its direction only near with absolute left or right position (depends on dockMode).

3. Same case, but with dockMode=RIGHT.
4. All above cases, but without components before SplitPanel.

5. It should work in all browsers.

For testing you can use following layout:
```
<hbox width="100%" height="100%" expand="splitPanel" stylename="card">
    <vbox stylename="card" width="300px" height="100%">
        <split id="innerSplitPanel" height="100%" width="100%" orientation="horizontal" dockable="true" dockMode="LEFT">
            <button width="100px" height="100px" caption="LEFT"/>
            <button width="100px" height="100px" caption="RIGHT"/>
        </split>
    </vbox>
    <split height="100%" width="300px" dockMode="RIGHT" orientation="horizontal" dockable="true">
        <button width="100px" height="100px" caption="LEFT"/>
        <button width="100px" height="100px" caption="RIGHT"/>
    </split>
    <split id="splitPanel" height="100%" orientation="horizontal" dockable="true" dockMode="RIGHT">
        <button width="100px" height="100px" caption="LEFT"/>
        <button width="100px" height="100px" caption="RIGHT"/>
    </split>
</hbox>
```

**Comment by mortozakhan** [comment]
I vote for fixing this bug. Looking forward for the resolution asap.
Mortoza

**Comment by ccorrear** [comment]
I vote for fixing this bug. 
Thanks

**Comment by sospinar5** [comment]
I also vote to correct this error.
Thanks.
