### ISSUE TITLE
Make @dateBefore and other time macros work with "now" argument

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#455]
Make @dateBefore and other time macros work with "now" argument

---
Original issue: https://youtrack.haulmont.com/issue/PL-9203

**Comment by soraksh** [comment]
"now" argument available for @dateBefore, @dateAfter and @dateEquals. Expression should be like: select d from sales$Doc where @dateAfter(d.createTs, now). You can use + or - to set days offset (now+1 / now-1).
