### ISSUE TITLE
Security configuration auto-import

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#465]
Security configuration (roles and permissions, groups and constraints) in CUBA apps is being set up in run-time via UI.
In applications with a complex security you want to persist such configuration and propagate changes reliable.

Currently you can achieve this by:
1. Creating a bean which will import changes on startup from json.
2. Using database update scripts (not a good practice at all).

Consider to built in auto-export mechanism to a platform.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9241

See also https://www.cuba-platform.com/discuss/t/constraints-and-access-groups-where-to-start/7800

**Comment by knstvk** [comment]
Will be implemented in #2172
