### ISSUE TITLE
More reliable security objects

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#466]
Since security is managed via UI it's quite fragile and inconvenient to reference security entities from code.
Consider to:
* add `code` attribute to `Role` and `Group` in order to be referenced easily from source code;
* add an ability to make any security object read-only (prevent changes in run time);

Also, an API for building security objects in code would be helpful. Studio could generate code on this API by current database content.
 
---
Original issue: https://youtrack.haulmont.com/issue/PL-9245

**Comment by knstvk** [comment]
Implemented in #2172
