### ISSUE TITLE
UniqueConstraintViolationHandler.doHandle() behaves incorrectly when several matcher groups created

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#477]
1) create an entity with *unique field*
2) create standard screens for it
3) customize the unique index violation message as written for instance here: https://www.cuba-platform.com/support/topic/unique-index-custom-exception-handler
4) specify the pattern which will lead to ''matcher.groupCount()'' > 1

On MSSQL could use the following expression
```
cuba.uniqueConstraintViolationPattern =  The duplicate key value is ((.+))
```

5) start the application
6) try to create several instances with the same value of the unique field

AR: the default message without constraint definition appears 

 !image.png!

See the ''doHandle()'' method of UniqueConstraintViolationHandler.

 !image2.png!

---
Original issue: https://youtrack.haulmont.com/issue/PL-9317

**Comment by knstvk** [comment]
Do not use regexp with multiple groups.
