### ISSUE TITLE
Breadcrumbs overflow window content if they have many opened windows

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#492]
Breadcrumbs overflow window content if they have many opened windows

![image](https://user-images.githubusercontent.com/1066152/57790169-40819f00-774b-11e9-9c30-f287b8abd5eb.png)

See also https://www.cuba-platform.ru/support/topic/путь-к-окну-наезжает-на-содержимое

## Updates
The `Breadcrumbs` can be wrapped in multiple rows if there are many new windows open and the content does not fit on one row.
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/9251c272-3f30-4140-aeb9-eb34d04b0e9d)

### Test project
[breadcrumbs.zip](https://github.com/cuba-platform/cuba/files/3231681/breadcrumbs.zip)

## QA
* Check the above case with different screen settings (fullscreen, etc.)
* Check the above case in different browsers (`Firefox`, `Chrome`, `Opera`, `Safari`, `Edge`, `IE11`).
Pay particular attention to checking the browser IE11.

**Comment by jreznot** [comment]
@glebfox Could you please check if we can fix this in the near future for 6.10 and 7.1 ?

**Comment by GlebDurygin** [comment]
Add flex-box usage for `Breadcrumbs`

Isuue description has updated
