### ISSUE TITLE
Abilty to view email content and to resend email

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#495]
Users ask us:
> What if I need to look, what content of particular email was sent to our client previously? How can I do it?

For short text emails - body content is already available on "email history" screen. But big HTML emails are unreadable there.

There can be several ways how to do it:
1) Using "admin email address" EmailerConfig#getAdminAddress to constantly receive a copy for all emails;

2) Creating "view email content" feature on Email history screen.
Viewing html content does not look a trivial task.

3) Creating "resend to..." feature on Email history screen.
If being created, it should have a security permission.

Default "send to" address can be a current user's email.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9425

**Comment by knstvk** [comment]
Item 2 has been implemented.

**Comment by mortoza** [comment]
I vote for the option to resend the unsent emails

**Comment by gglcrash** [comment]
Back to implementation due to additional field for resend email address.
