### ISSUE TITLE
Switch to KRYO

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#507]
Fix PL-9459 and PL-9455

See bug: https://github.com/EsotericSoftware/kryo/issues/528

:link: Related links: {"is blocked by:": "https://youtrack.haulmont.com/issue/PL-10644", "relates to:": "https://youtrack.haulmont.com/issue/PL-9459"}

---
Original issue: https://youtrack.haulmont.com/issue/PL-9466

**Comment by andreysubbotin** [comment]
Fixed in cuba-platform/cuba/issues/742
