### ISSUE TITLE
RefApp data model test doesn't work with hsql 2.3.5

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#520]
RefApp data model test doesn't work with hsql 2.3.5

---
Original issue: https://youtrack.haulmont.com/issue/PL-9550

**Comment by knstvk** [comment]
Issue moved to [cuba-platform/refapp #2](https://github.com/cuba-platform/refapp/issues/2) via [**ZenHub**](https://www.zenhub.com/)
