### ISSUE TITLE
Excel Export does not consider aggregation style

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#524]
When there is a Table with an aggregation and the aggregationStyle is set to "BOTTOM" and there is an excel export available in the table, the resulting excel file does add the aggregation row at the top.

Think about some kind of a config toggle in the screen XML that allows users activating aggregation output or now.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9569

**Comment by alexander-shustanov** [comment]
ExcelExporter now considers aggragation style.
Added exportAggregation flag to ExcelAction to make able user to turn off exporting aggregation row.
