### ISSUE TITLE
Pack widgetsets to JAR files

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#542]
Pack widgesets to JAR files

Studio migration issue: [YouTrack](https://youtrack.cuba-platform.com/issue/STUDIO-4720).

### Updates

Widgetset is deployed and served from JAR now.

### QA

Make sure that the project can be successfully created and started and when it has a `web-toolkit` module, and when it does not have it.

Check all deployment options:
- Standard
- WAR
- Single WAR
- UberJAR
- Single UberJAR

All these options are supported in RefApp.

Check that a widgetset can be debugged:
1. Invoke in console when app is running: `gradlew debugWidgetSet`
2. Open the following url: `http://localhost:8080/app/?superdevmode`

An app should be correctly opened after widgetset compilation.

#### Recommended testing scenario

1. Create an app based on 6.10 platform version and add `charts` addon.
2. Add all deployment options via CUBA Studio (generate WAR deployment, copy Gradle task, change to single WAR. Same way for UberJAR)
3. Backup the project and change version of CUBA to `7.0-SNAPSHOT`
4. Check all deployment options
5. Open a project based on 6.10 and add web-tookit module
6. (Optional, but desirable) Add custom widget
7. Change version to `7.0-SNAPSHOT`
8. Check all deployment options

| Test Table | Standard | WAR  | Single WAR  | UberJAR | Single UberJAR |
|---|---|---|---|---|---|
| No `web-toolkit`, no `charts`  |   |   |   |   |
| No `web-toolkit`, `charts`       |   |   |   |   |
| `web-toolkit`, no `charts`       |   |   |   |   |
| `web-toolkit`, `charts`            |   |   |   |   |

You can create your own projects or use these one:

[wtj-test-cases.zip](https://github.com/cuba-platform/cuba/files/2388560/wtj-test-cases.zip)

---
Original issue: https://youtrack.haulmont.com/issue/PL-9666

**Comment by dtsaryov** [comment]
There is a problem with UberJAR deployment of projects that don't have `web-toolkit` module - pre-built widgetset is located in wrong place that leads to failed widgetset loading.
