### ISSUE TITLE
Add coloring to Server Log stack frames

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#550]
When you view exception stack traces in Server Log - often you need to find problematic place in the code.
But often it is hard to find a stack frame where *your* code starts after chain of reflection proxies. Or where your code ends before long CUBA / ORM / JDBC Driver stack call chain.

As an example, IntelliJ IDEA has stack frame folding for "non-interesting" classes. You can find the list of packages in Settings -> Editor -> General -> Console group.

In Server Log window we could just apply different colors to different stack frames, based on package.

As a couple if ideas, I've attached two images how it could look like:
1 - fading out proxy frames
2 - highlighting "my project's" code frames (need to somehow automatically determine application package name).

Such styling can be turned on/off by clicking a checkbox, if necessary, next to Auto Refresh.

It is questionable, whether com.haulmont.cuba or org.springframework or org.apache.catalina should be faded out, normal or highlighted?

![fade-out-proxies](https://user-images.githubusercontent.com/1066152/41188941-878f55a2-6bd7-11e8-8248-9b538126f08c.png)

---
Original issue: https://youtrack.haulmont.com/issue/PL-9699

**Comment by jreznot** [comment]
Provide DB config property that will contain patterns that should be grayed

**Comment by SemenSofronov** [comment]
Now a few rows are highlighted in Server Log stack frames based on patterns defined in the `WebConfig.java`

**Comment by natfirst** [comment]
Please, write to Javadoc that this property has the type of the regular expression. Also, escape all spec symbols in the default line (such as . and $)
