### ISSUE TITLE
doLoginByRememberMe using with externalAuthentication allows to login, if user is deleted at external authentication system

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#551]
cuba.web.externalAuthenticationProviderClass=com.haulmont.cuba.web.auth.LdapAuthProvider
cuba.web.externalAuthentication = true

1. Login with user from ldap, check ''remember me''.
2. Delete user or change his password in ldap.
3. Relogin.

AR:
 You login successfully.
ER:
 Login fails.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9702

**Comment by jreznot** [comment]
You have to sync "active" flag of user manually or with ldap-addon: https://github.com/cuba-platform/ldap-addon
