### ISSUE TITLE
REST API: configurable anonymous access to specific entities

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#553]
App developer should be able to specify an entity and a list of methods (GET/POST/...) to allow anonymous access.

Example: online store.
Entity: product - anonymous GET.
Entity: shopping cart item - anonymous GET and POST.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9708

**Comment by gorbunkov** [comment]
A developer can define a role for the _anonymous_ user
