### ISSUE TITLE
Rework FileUploadField API

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#57]
Старый API был сделан как обертка вокруг ваадиновского компонента и сейчас, после изменения архитектуры CUBA-приложений, устарел. Закачка файлов на средний слой стала двухступенчатой и требует написания громоздкого кода в контроллере экрана.

Варианты использования FileUploadField
(возможно, есть и другие)

1) Закачать файл на клиентский слой, обработать его прямо на клиентском слое (в контроллере экрана) и удалить.
Пример: редактор отчетов

2) Закачать файл на средний слой, обработать его в соответствии с какой-то бизнес-логикой и опять же удалить. Не сохранять его на постоянку в file storage.
Примеры:
- импорт данных из excel. Файл закачивается через форму, и вызывается какой-то сервис, который открывает файл через HSSF и импортирует данные. Файл после окончания импорта не нужен.
- импорт отчетов.

3) Закачать файл в file storage для постоянного хранения. Связанный с ним FileDescriptor связать с моделью данных проекта и сохранить в БД (возможно, по коммиту экрана).
Пример: закачка всяких документов и картинок через CUBA-экраны для хранения и последующего просмотра / скачивания.

Возможности, которые должен предоставлять FileUploadField (мое ИМХО):

- Встроенный показ прогресса, из коробки, без необходимости писать контроллере background tasks.
-- отключаемый (пока что для веб-UI бесполезно)
-- с возможностью отмены закачки

- Встроенные нотификации пользователю в случае ошибок, как минимум:
-- file is too big,
-- ошибка закачки на клиент,
-- ошибка закачки на сервер,
-- закачка отменена пользователем

- Для use-cases № 2 и 3 - автоматический и прозрачный аплоад на сервер, чтобы после завершения аплоада возвращался готовый FileDescriptor, который можно либо открывать как поток на среднем слое, либо сохранять в БД. Для этих вариантов использования какие-то промежуточные действия, оповещения на UI-слое не нужны.

- Для use-case № 3 - интеграция с datasources
- (Минорное) Возможность задавать лимит по объему для каждого поля отдельно
- В далекой перспективе - показ прогресса и для web-закачки (может когда позволит HTML 5).

---
Original issue: https://youtrack.haulmont.com/issue/PL-1756

**Comment by jreznot** [comment]
Partially done in https://youtrack.haulmont.com/issue/PL-1709
