### ISSUE TITLE
Declarative way to set sorting on column of Table / DataGrid

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#572]
See https://www.cuba-platform.com/support/topic/cannot-declare-initial-table-sorting-by-columns-in-xml

---
### Changes
**Table, GroupTable, TreeTable, DataGrid, TreeDataGrid** have attribute: `sort` in column with options:
- DESCENDING
- ASCENDING
```
<columns>
    <column property="name" sort="DESCENDING"/>
</columns>
```
It means that column will be sorted according to the option after init event. **Pay attention to `settingsEnabled`**, if settings are enabled it can resort column using settings value.

Only one column can be sorted at the same time, so if you do **stuff like this**:
```
<columns>
    <column property="name" sort="DESCENDING"/>
    <column property="parent" sort="ASCENDING"/>
</columns>
```
**You will get an exception.**

---
### How to test
Repeat all steps for all components excepting GroupTable.

_It will be useful if you set settingsEnabled to false._
1. Set sort, dataContainer and LoadDataBeforeShow - sort should be applied
2. Set sort, dataContainer, remove LoadDataBeforeShow. Open screen, by click on button load data - sort should be applied.
3. Set sort, metaClass, LoadDataBeforeShow. Open screen, by click on button set not empty container - sort should be applied
4. Repeat with datasource

Only for Table
5. Use conditions from 1) step. By click on button sort programmatically another column. Make sure that container value change event is invoked only once.

Other:
6. Try to break a feature with your cases (e.g. set null to `setItems()` or smth else)

**Comment by Flaurite** [comment]
When we simultaneously use `sort` and `sortable="false"` attributes the column is sorted. However, while we see the sort icon on the column we cannot sort it from UI. Need to show an exception.
