### ISSUE TITLE
New UI screen controller concept

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#575]
It should look like this:
```
@UiController("user-browse")
@UiDescriptor("user-browse.xml")
public class UserBrowse extends StandardLookup {
    @Inject
    private TextField textField;

    public UserBrowse() {

    }

    @Order(12)
    @Subscribe
    private void onInit(InitEvent event) {

    }

    @Order(10)
    @Subscribe
    private void onInit2(InitEvent event) {

    }

    @Subscribe
    private void onReady(ReadyEvent event) {

    }

    @Subscribe("textField")
    private void onTextChange(TextInputField.TextChangeEvent e) {

    }
}
```

Inspired by Java FX and Vaadin 10: https://vaadin.com/blog/vaadin-flow-the-next-piece-of-vaadin-10-is-now-in-developer-preview

Proposed implementation details:

`Screen` becomes mandatory annotation for new-style screens with optional String `id` attribute.
We will implement custom Spring Framework support for this annotation and reimplement ControllerDependencyInjector with Spring, thus Spring will scan and find screens during start-up and register them in WindowConfig.
For the old-style screens we provide compatibility logic that will be implemented in AbstractWindow / AbstractFrame classes and load all the screens.xml screens to as before

Since 7.0 we will be able to open a screen using the following code:
```
Window<UserList> userList = windowManager.open(UserList.class);
UserList controller = userList.getController(); // do something with controller API

**Comment by jreznot** [comment]
Relates to #337 and #195
