### ISSUE TITLE
JPQL: cannot execute subselect on field of extended entity

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#598]
There is no way to execute subquery on field of extended entity. 

===First problem===

Keyword 'AS' in from section of subquery for extended entities sticks to neighbour words.

*Steps:*
1. Open RefApp and go to Administration -> JMXConsole -> Search by object name: "PersistenceManager"
1. Invoke java.lang.String jpqlLoadList() with parameter: {code:lang=java}select a from wf$Assignment a where exists(select aa from a.attachments AS aa)```

 
*ER:* 
  Invoked succesful without any exceptions
*AR*:  {code:lang=java}com.haulmont.cuba.core.sys.jpql.JpqlSyntaxException: Errors found for input jpql:[select a from ref$ExtAssignment a where exists (select aa from a.attachmentsASaa)]
CommonErrorNode [<mismatched token: [@24,80:80=')',<32>,1:80], resync=a.attachmentsASaa>]
```

However simular query for unextended entity works fine: {code:lang=java} select u from sec$User u  where exists(select ur.role from u.userRoles AS ur) ```


===Second problem===

Qeyword 'AS' is mandatory in subquery from clause with associated path expression (JPA2Parser.java: 6924), however according to grammar of the Java Persistence Query Language it can be absent. see 'subselect_identification_variable_declaration' in https://docs.oracle.com/javaee/6/tutorial/doc/bnbuf.html

So query without 'AS' cannot be parsed: {code:lang=java}
//query
select a from wf$Assignment a where exists(select aa from a.attachments aa)
//result
com.haulmont.cuba.core.sys.jpql.JpqlSyntaxException: Errors found for input jpql:[select a from wf$Assignment a where exists(select aa from a.attachments aa)]
CommonErrorNode [<mismatched token: [@24,72:73='aa',<56>,1:72], resync=a.attachments aa>]```




---
Original issue: https://youtrack.haulmont.com/issue/PL-9895

**Comment by andreysubbotin** [comment]
fixed in cuba-platform/cuba#388
