### ISSUE TITLE
Autocalculated dynamic attributes

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#611]
Sometimes there is a need to calculate some field (boolean, string or numeric without redeployment). 

Proposal for implementation
Make read-only, not persistent, auto-calculated dynamic attributes, so user can define groovy script by given entity {E}.

---
Original issue: https://youtrack.haulmont.com/issue/PL-9987

**Comment by ovchinnikovsp** [comment]
1. can we do 'Not persistent' as an option which will be setup during the attribute configuration?
2. It make sense to pass also all the other dynamic attributes with values to the script. Example: after user entered amount(dynamic attr) need to show the amount in another currency(another dynamic attr)

**Comment by invviz** [comment]
Added new tab for dynamic attributes. There you can specify the "depends on" attributes and the Groovy script for calculating the attributes. The attribute value will be automatically recalculated after changing the values of one of the “depends on” attributes.

Recalculation works only with the following web components: Form, DynamicAttributesPanel.

**Comment by natfirst** [comment]
Add crossfield validation to the `Recalculation value script` and `Attribute depends on` fields: if `Recalculation value script` field is filled with text, then the `Attribute depends on` field also should be set

**Comment by natfirst** [comment]
Message key for the Russian localization differs from English. Because of this notification shows English body in Russian localization
