### ISSUE TITLE
Add ability to schedule immediate execution of scheduled task

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#615]
Like a button in a scheduled tasks table
By pressing the button user tells the system to execute the task ASAP ignoring the delay/cron expression.

Useful for development or situations where the next execution is far away but the functionality has to be checked immediately.
Currently, user has to use workarounds (JMX console/temporal switch to Period/Delay scheduling type)

---
Original issue: https://youtrack.haulmont.com/issue/PL-9998

**Comment by jreznot** [comment]
Duplicates #760
