### ISSUE TITLE
Add ability to define listeners for windows for init, ready and so on right before opening

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#618]
See example below:

```
openWindow(...)
   .addInitHandler(window -> window.getFieldGroup().getFieldComponent(...).setMandatory(true));
   .addCloseHandler(...)
```

And so on.

---
Original issue: https://youtrack.haulmont.com/issue/PL-10008

**Comment by jreznot** [comment]
Is not relevant anymore, since 7.0 Screens can expose `addInitListener` / `addAfterInitListener` / etc methods.
