### ISSUE TITLE
User can remove file by FileUploadField when user has no permissions to delete FileDescriptor

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#622]
### First scenario
*Prerequisites*
```
cuba.entityAttributePermissionChecking = true 
```

Scenario to reproduce:
1. Import roles (Role accepts restrictions for FileDescriptor (all operations denied))
1. Create user with name Test. Assign the role "TestRole"
1. Create entity A and upload file for it
1. Login by the user (Test).
1. Open screen A.browser
1. Select entity and open the edit screen
1. Click the delete button

AR: User can delete file
ER: User can not delete file

### Second scenario
*Prerequisites*
```
cuba.entityAttributePermissionChecking = false (default behavior) 
```

Scenario to reproduce:
1. Import roles (Role accepts restrictions for FileDescriptor (all operations denied))
1. Create user with name Test. Assign the role "TestRole"
1. Create entity A and upload file for it
1. Login by the user (Test).
1. Open screen A.browser
1. Select entity and open the edit screen
1. Try to download file

AR: User can download file
ER: User can not download file

Documentation:
```
cuba.entityAttributePermissionChecking

If set to false, turns off checking entity attribute permissions on Middleware.
Default value: false
Stored in the database.
Used in the Middleware block.
```

:link: Related links: {"relates to:": "https://youtrack.haulmont.com/issue/PL-9935"}

---
Original issue: https://youtrack.haulmont.com/issue/PL-10013

### Test project

[fileuploadfield-filedescriptor.zip](https://github.com/cuba-platform/cuba/files/3199043/fileuploadfield-filedescriptor.zip)

## QA

Check the work of the`FileUploadField` component: 
- when setting permissions on `FileDescriptor`
- when setting permissions on the property (`FileDescriptor`) of a `TestEntity`
- when choosing the Standard / Denying TestRole

**Comment by GlebDurygin** [comment]
Reopen
Move FileDescriptor's permissions checks from `CubaFileUploadWrapper` to a `WebFileUploadField`

**Comment by GlebDurygin** [comment]
The description has been updated
