### ISSUE TITLE
Reset "Use by default" presentation option when working as substituted user

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#623]
Test case:
- login as 'user1', open browser, save table presentation with "Use by default" but with no "Available for all users" options;
- substitute 'user2', open browser;
- return to 'user1', open browser.

E.R: "Use by default" option is not reset
A.R.: Reset option

---
Original issue: https://youtrack.haulmont.com/issue/PL-10021

**Comment by andreysubbotin** [comment]
Problem is actual only for Thesis project. Change behaviour in the Thesis project.
