### ISSUE TITLE
Read-only input components should have an outline

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#624]
Read-only input components should have an outline.

Relates to #2630

Available input components:
* ColorPicker
* CurrencyField
* DateField
* DatePicker
* MaskedField
* TimeField
* PasswordField
* PickerField
* ResizableTextArea
* SuggestionField
* SuggestionPickerField
* TextArea
* TextField

### Updates
Read-only input components have an outline. For example `TextField` component:
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/b5cb19ee-edc6-4f4f-ab19-f30aa7118814)

### QA
Check that in the read-only mode, the above components have an outline.

**Comment by glebfox** [comment]
Probably in Vaadin 8.9 this problem is fixed.

**Comment by Mihail063** [comment]
The following components also have no outline:

- CurrencyField
- DateField
- LookupField
- LookupPickerField
- MaskedField
- PickerField
- SuggestionField
- SuggestionPickerField
- TimeField
- OptionsList
- TextArea
- TwinColumn
- Form
- FieldForm
- CheckBox
- CheckBoxGroup
- OptionsGroup

**Comment by GlebDurygin** [comment]
Other components will be implemented in #2631

**Comment by Mihail063** [comment]
Browser: IE 11

Case 1

1. Create a new screen 
2. Add any field to the screen (for example TextField)
3. Run the project and open the screen
4. Click on the DatePicker 

AR: DatePicker does noе have the outline

Case 2

1. Create a new screen 
2. Add any field to the screen (for example TextField)
3. Set editable="false" for the field

AR: Cursor exists as for editable fields
![изображение](https://user-images.githubusercontent.com/24281695/72972024-1c9b5080-3de4-11ea-9261-602c4e1a0c11.png)

**Comment by GlebDurygin** [comment]
> Case 2
> 
> 1. Create a new screen 
> 2. Add any field to the screen (for example TextField)
> 3. Set editable="false" for the field
> 
> AR: Cursor exists as for editable fields
> ![изображение](https://user-images.githubusercontent.com/24281695/72972024-1c9b5080-3de4-11ea-9261-602c4e1a0c11.png)

This is an Internet Explorer bug. The `readonly` attribute for `input` element does not work as in different browsers.
