### ISSUE TITLE
Unfetched exception after editor closing if view of browser (or any related table datasource) contains any reference attributes which not included to editor view

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#629]
1) Create browser screen for entity with view which contains any reference attribute 
2) Create editor screen with view which doesn't contain that reference screen
3) Add edit action in browser

It fails with unfetched exception in table cache refresh for that reference attribute after saving changes in editor.
(line 285 in EditAction on  datasource.updateItem(editedItem) as edited item here with view from editor)
It can be not only browser but any table and any EditAction (or any descendant) which open editor with view that doesn't contain all reference attributes of the target list comonent datasource.

It doesn't reproduced for not reference attributes because after calling commit in DataSupplire in editor screen method getDataManager().commit(instance, view) returns entity with all local attributes and also with all system attribute even if they not appeared in the editor view

---
Original issue: https://youtrack.haulmont.com/issue/PL-10048

**Comment by knstvk** [comment]
Fixed in https://youtrack.haulmont.com/issue/PL-3817
