### ISSUE TITLE
Change the login of anonymous user

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#633]
"anonymous" user login represents its internal purpose (to create anonymous sessions) rather than the fact that it is an account used by the system

Admins get scared seeing it in production and remove it, afraid of the anonymous access to the system.
System should prohibit removing the user if its login equals to the cuba.anonymousLogin as the anonymous user is mandatory for middleware to start.

---
Original issue: https://youtrack.haulmont.com/issue/PL-10068

**Comment by jreznot** [comment]
At the moment, users cannot remove `anonymous` from UI
