### ISSUE TITLE
FieldGroup's field addition usability

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#639]
Field doesn't have property or caption set if it has been added programmatically. Platform manual (https://doc.cuba-platform.com/manual-6.7-ru/manual.html#vaadin_addon_sample) doesn't describes this or describes just addition(like property already got from id; caption - from class property caption, see CustomerEdit class definition in chapter from link above).

Now it takes four strings to add field with caption (see patch for refapp 6.6):
```
FieldGroup.FieldConfig countField = switchableEditable.createField("count");
countField.setProperty("count");
countField.setCaption(messageTools.getPropertyCaption(testDs.getMetaClass(),"count"));
switchableEditable.addField(countField);
```

This code can be reduced to single line in case of such default behaviour: taking property from id (if it is valid property name) and caption from metaclass property caption inside platform code.

E.g, like in cuba manual: https://doc.cuba-platform.com/manual-6.7-ru/manual.html#vaadin_addon_sample , just:
```switchableEditable.addField(switchableEditable.createField("count"));```

See additional details in patch

So, *there are two proposals:*
* --Set "property" from "id" (if "property" hasn't been specified)-- - ok, it's completely separate attributes
* Set "caption" from caption of entity field if "caption" hasn't been specified

---
Original issue: https://youtrack.haulmont.com/issue/PL-10097

**Comment by jreznot** [comment]
Is not required anymore, since Form component introduced as a replacement for FieldGroup
