### ISSUE TITLE
Maintenance Mode/Draining mode for web-application

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#64]
At login screen show CAUTION about maintenance work and do not login new users to system.
For active users show CAUTION icon beside login name at right-up corner of app window.
Allow set maintenance mode from JMX.

---
Original issue: https://youtrack.haulmont.com/issue/PL-1940

**Comment by jreznot** [comment]
Could be easily implemented as app-component as shown here: https://doc.cuba-platform.com/manual-6.8/login.html#login_events
```
@Component
public class MaintenanceModeValve {
    private volatile boolean maintenance = true;

    public boolean isMaintenance() {
        return maintenance;
    }

    public void setMaintenance(boolean maintenance) {
        this.maintenance = maintenance;
    }

    @EventListener
    private void onBeforeLogin(BeforeLoginEvent event) throws LoginException {
        if (maintenance && event.getCredentials() instanceof AbstractClientCredentials) {
            throw new LoginException("Sorry, system is unavailable");
        }
    }
}
```
