### ISSUE TITLE
Add predefined styles for the DataGrid component

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#645]
Depends on: https://github.com/vaadin/framework/issues/8514

Such as the Table component has:

* Stripes
* Vertical Lines
* Horizontal Lines
* etc.

See https://demo.vaadin.com/valo-theme/#!tables

---
Original issue: https://youtrack.haulmont.com/issue/PL-10134

**Comment by Flaurite** [comment]
### Changes

Added the following styles:

1) borderless;
2) no-horizontal-lines;
3) no-vertical-lines;
4) no-stripes.

#### Borderless:
![image](https://user-images.githubusercontent.com/22093943/65243604-ac10ba00-daf9-11e9-8dea-caa5a5a39efc.png)

#### No vertical lines
![image](https://user-images.githubusercontent.com/22093943/65243618-b632b880-daf9-11e9-9359-da91c17a2b87.png)

#### No horizontal lines
![image](https://user-images.githubusercontent.com/22093943/65243642-c3e83e00-daf9-11e9-8208-034d0ea23117.png)

#### No stripes
![image](https://user-images.githubusercontent.com/22093943/65243741-fabe5400-daf9-11e9-910a-bf4328470fe9.png)

### For QA
1. Use DataGrid and TreeDataGrid.
2. While checking style, try to use Inline editor, select some records, add footer, header and other stuff. Make sure that everything is fine.

3. Especially for Safari. Add footer and try to change styles (`borderless`, `no-horizontal-lines`, `no-vertical-lines`)  at runtime. Make sure that footer is not disappeared.
4. Especially for Chrome.  For `no-horizontal-lines` and `no-vertical-lines` check that
`.v-sa:not(.v-ch) .v-grid-body .v-grid-row > td` is not applied.

5. Check all styles in all browsers (Chrome, Opera, FireFox, Safari, Edge, IE11) in all themes (Halo, Havana, Hover)

Use demo project: 
[dev-datastylegrid.zip](https://github.com/cuba-platform/cuba/files/3631227/dev-datastylegrid.zip)
