### ISSUE TITLE
Support for Spring environment profiles

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#66]
Sometimes it's necessary to instantiate different spring beans in depend on environment.
Spring has special mechanism for such cases. You can either declare profile dependent configuration in xml:

```
<beans profile="dev">
   ...
</beans>

<beans profile="production">
   ...
</beans>
```
or use Annotation:
```
@Profile
```
For further info see http://blog.springsource.com/2011/02/11/spring-framework-3-1-m1-released/

The following code adds profiles support. Active profile(s) could be declared via application property *spring.profiles.active*

```
    protected void initAppContext() {
        String configProperty = AppContext.getProperty(SPRING_CONTEXT_CONFIG);
        if (org.apache.commons.lang.StringUtils.isBlank(configProperty)) {
            throw new IllegalStateException("Missing " + SPRING_CONTEXT_CONFIG + " application property");
        }

        StrTokenizer tokenizer = new StrTokenizer(configProperty);
        String[] locations = tokenizer.getTokenArray();
        String[] environmentProfiles = StringUtils.commaDelimitedListToStringArray(
                AppContext.getProperty(AbstractEnvironment.ACTIVE_PROFILES_PROPERTY_NAME));

        ClassPathXmlApplicationContext appContext = new ClassPathXmlApplicationContext();
        appContext.setConfigLocations(locations);
        if (ArrayUtils.isNotEmpty(environmentProfiles)) {
            appContext.getEnvironment().setActiveProfiles(environmentProfiles);
        }
        appContext.afterPropertiesSet();

        AppContext.setApplicationContext(appContext);
    }
```

---
Original issue: https://youtrack.haulmont.com/issue/PL-2216

**Comment by jreznot** [comment]
See also forum discussion https://www.cuba-platform.com/discuss/t/runtime-environments-for-applications/1278

**Comment by jreznot** [comment]
It requires changes in all the Spring contexts: core / web / rest / portal / etc

**Comment by andreysubbotin** [comment]
Implementation details:
- Read property `spring.profiles.active` from system properties (like `-Dspring.profiles.active=`) or from a web.xml `context-param` element
- A property contains names of spring profiles. 
- Apply spring profiles while starting an application context (`AbstractAppContextLoader`). 
- In addition to the main properties of the application, load properties that are specified for the specific profile. For each property file in `appPropertiesConfig` try to find a properties file for the specific profile (by name pattern: `app-${profile}.properties`) and loads properties from the file.
-

**Comment by gglcrash** [comment]
Spring profiles usage is now available according to the above-mentioned details.
Spring beans with, for example, «dev» profile will be initialized if they have @Profile(«dev») annotation or if they are registered in xml configuration like this:
&lt;beans profile="dev"&gt;
   ...
&lt;/beans&gt;
Also, all profile-related properties should be loaded.

Simple test-case:
1) Create bean under the profile
2) Specify this profile in the web.xml
3) Check that some code will be executed during bean initialization

**Comment by natfirst** [comment]
Reopened.
This step is not working:
CreateDB/UpdateDB Gradle tasks use spring profiles from core module web.xml (or from system property) while configuring DB connection.

**Comment by natfirst** [comment]
1. Properties file for the specific profile must be named by name pattern: `${profile}-app.properties` 
2. The additional file should be placed in the same package as the base `app.properties file`
3. Only application properties that define the database type and connection parameters can be set in the additional properties file (see https://doc.cuba-platform.com/manual-7.2/db_connection.html)
4. In order to run CreateDB/UpdateDB Gradle tasks for the different spring profiles set `spring.profiles.active` property from system properties (like `-Dspring.profiles.active=`)
