### ISSUE TITLE
Entity data set can't load values if it uses some field from entity e.g. entity#lines

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#660]
https://www.cuba-platform.ru/discuss/t/formirovanie-otcheta-s-pomoshhyu-html-shablona/1224

---
Original issue: https://youtrack.haulmont.com/issue/PL-10224

**Comment by andreysubbotin** [comment]
Issue moved to [cuba-platform/reports #89](https://github.com/cuba-platform/reports/issues/89) via [**ZenHub**](https://www.zenhub.com/)
