### ISSUE TITLE
CubaUberJarBuilding is up-to-date when you change logback.xml and run build from Studio 

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#677]
1.  Set up the Uber JAR
1.  Generate logback configuration file using Studio
1.  Run buldUberJar task from Studio
1.  Open logback.xml in Idea for editing
1.  Add some changes and save it
1.  Run buldUberJar task from Studio

**Comment by andreysubbotin** [comment]
Test for new CUBA Studio
