### ISSUE TITLE
Localize system attributes on the EntityRestore screen

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#678]
Check a topic on the support forum: [https://www.cuba-platform.com/discuss/t/entityrestore-sys-property-localization/3488 link]

### Updates:

Columns with system attributes have description now:

![image](https://user-images.githubusercontent.com/6183810/41189568-f7f0de48-6be0-11e8-9304-34881e3df0a6.png)

---
Original issue: https://youtrack.haulmont.com/issue/PL-10317

**Comment by natfirst** [comment]
1. Open refapp
2. In Entity Restore screen select Car entity
3. Description will be not localized
![notLocalized.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/1b5cc416-7dc2-4f1a-bb89-5b05960e5d9d)
