### ISSUE TITLE
MSSQL init scripts do not match model

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#679]
Reproduce using Studio.
#Create a project 
#Open project properties and adjust connection to some MSSQL DBMS. Select MS SQL 2005
#Create Database
#Create a custom DB (with MSSQL stub)
#Adjust connection to the custom DB - select the same database as on the 2-nd step
#Generate Db scripts

AR: Studio generates 73 update scripts.
Main cases:
*Table column without 'not null' constraint
!image.png!  !image3.png!
*Extra column 'CREATE_TS' and 'CREATED_BY'
!image2.png!
*Lack of indexes for @ManyToOne association. For instance: EntityLogItem -> User, Filter_User -> User, etc

*Check other supported RDBMS*

---
Original issue: https://youtrack.haulmont.com/issue/PL-10335

**Comment by Mihail063** [comment]
Created a new [Studio issue](https://youtrack.cuba-platform.com/issue/STUDIO-6420). Check Test request after fixed it

**Comment by Mihail063** [comment]
Generating a lot of update scripts for CUBA entities after creating a custom database is a bug. Created a new [Studio issue](https://youtrack.cuba-platform.com/issue/STUDIO-7858).
Main cases were fixed
