### ISSUE TITLE
Use original Maven group and artifact ids for EclipseLink

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#680]
https://www.cuba-platform.com/discuss/t/6-8-java-lang-securityexception-prevents-tomcat-startup/3531/7
#Use original MVN group and artifact ids for EclipseLink
#Use the original JAR names

---
Original issue: https://youtrack.haulmont.com/issue/PL-10337

**Comment by andreysubbotin** [comment]
Fixed in #910
