### ISSUE TITLE
Sequence with long name can't be generated on the Oracle database

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#687]
https://www.cuba-platform.ru/discuss/t/problemy-posle-obnovleniya-na-6-8-0/1362
ORA-00972

---
Original issue: https://youtrack.haulmont.com/issue/PL-10386

**Comment by andreysubbotin** [comment]
Introduce annotation `@IdSequence`. You can setup sequence name in the database for the entity e.g.
```
@Entity(name = "test$NumberIdSeqNameSecond")
@IdSequence(name = "seq_number_id_name")
public class NumberIdSeqNameSecond extends BaseLongIdEntity
```
By default sequence is not cached, so each sequence value is acquired from database. But you can enable sequence caching by setting property `cached = true`, e.g.
`@IdSequence(name = "seq_number_id_name", cached = true)`
