### ISSUE TITLE
Optionally do not return entity JSON for REST API entity create and update operations

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#691]
Or limit the response by the view

---
Original issue: https://youtrack.haulmont.com/issue/PL-10399

**Comment by gorbunkov** [comment]
One of solutions may be:
1. Change the default behavior ad do not return the JSON in the response body
2. If the client needs the response body with the entity JSON, it should explicitly pass the "Accept" header with the "application/json" value

**Comment by gorbunkov** [comment]
JSON will be limited by the view. See https://github.com/cuba-platform/restapi/issues/28
