### ISSUE TITLE
Header of GroupTable has wrong height after grouping

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#694]
# First problem - big header

## Test case:

1. Open any screen that contains `GroupTable` with 100% width (and columns should have undefined width);
2. Add a lot of entities to this table or resize a screen to enable scrolling in the table;
3. Group by some property by drag-n-drop.

**Important:** the last column should be not ordered

![image](https://user-images.githubusercontent.com/6183810/43439508-8e02e1d8-94a4-11e8-86db-06b6ccc6cfb4.png)

### Second case

1. Open `Test Samples -> GroupTable` in the refapp;
2. Add grouping by by unit;
3. Collapse all rows.

**Important:** the last column should be not ordered

![image](https://user-images.githubusercontent.com/6183810/43518434-217a8030-959d-11e8-8f96-0d957a4fdd29.png)

# Second problem - overlapped sorting indicator

Sorting indicator for the last column is overlapped in case of Table has vertical scrolling:

![image](https://user-images.githubusercontent.com/6183810/43519140-5001f382-959f-11e8-961f-85049e3e2e7e.png)

But it is not overlapped if there is no vertical scrolling:

![image](https://user-images.githubusercontent.com/6183810/43519241-a7cce1a8-959f-11e8-8c7c-d4b7bd107126.png)

# Third problem - "Freezed" header

1. Create aggregatable `GroupTable`;
2. Group by some property;
3. Try to resize some column;

An example based on `model-browse-frame` from RefApp:

```XML
<dsContext>
    <groupDatasource id="modelsDs"
                     class="com.haulmont.refapp.core.entity.Model"
                     view="_local">
        <query>select m from ref$Model m order by m.manufacturer, m.name</query>
    </groupDatasource>
</dsContext>

<layout expand="modelsTable" spacing="true">
    <groupTable id="modelsTable" width="100%" multiselect="true" aggregatable="true">
        <columns>
            <column id="manufacturer"/>
            <column id="name"/>
            <column id="numberOfSeats"/>
            <column id="launchYear">
                <aggregation type="MAX"/>
            </column>
        </columns>
        <rows datasource="modelsDs"/>
    </groupTable>
</layout>
```

Result:

![image](https://user-images.githubusercontent.com/6183810/43521211-69262890-95a6-11e8-945a-948de9e9f7cb.png)

## Testing

Check also old test cases:

- [PL-9504](https://youtrack.cuba-platform.com/issue/PL-9504)
- [PL-9793](https://youtrack.cuba-platform.com/issue/PL-9793)
- [PL-9403](https://youtrack.cuba-platform.com/issue/PL-9403)

Check also with high DPI screen

Almost all issues have patches for RefApp, but there is a patch for everything:

[Header_of_GroupTable_has_wrong_height_after_grouping_#694.zip](https://github.com/cuba-platform/cuba/files/2249386/Header_of_GroupTable_has_wrong_height_after_grouping_.694.zip)

---
Original issue: https://youtrack.haulmont.com/issue/PL-10415

**Comment by natfirst** [comment]
Sorting indicator has a strange behaviour, please, rollback this fix.
![jump.gif](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/a97d7efd-6a45-48c9-87f9-8f95d78e8f41)

**Comment by dtsaryov** [comment]
This glitch is also present in previous version:

![glitch](https://user-images.githubusercontent.com/6183810/43645339-9e8c1cd6-9742-11e8-9a9b-0e8b5d88195c.gif)

The problem is moved to issue mentioned above
