### ISSUE TITLE
RowLevelSecurityException on saving previously saved entity

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#696]
There are 2 entites:

The first: 
{code:lang=java}
@Entity(name = "security$ParentEntity")
public class ParentEntity extends StandardEntity {
    @Column(name = "NAME")
    protected String name;

    @OneToMany(mappedBy = "parent")
    protected List<ChildEntity> children;
}
```


The second:
{code:lang=java}
@Entity(name = "security$ChildEntity")
public class ChildEntity extends StandardEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PARENT_ID")
    protected ParentEntity parent;

}
```

Child entity has constraints and cuba.dataManagerChecksSecurityOnMiddleware = true

If create and save Parent and Child, then Parent resaving will possible only after the reload entity by dataManager.reload(), otherwise will be thrown

```
Could not read security token from entity com.company.security.entity.ParentEntity-591dcdbc-5bd6-7b37-7922-d3daeaa9c890 [detached], even though there are active constraints for the related entities.
```

For example, the next code will throw RowLevelSecurityException 
{code:lang=java}
ParentEntity parent = metadata.create(ParentEntity.class);
ChildEntity child = metadata.create(ChildEntity.class);
child.setParent(parent);
parent = dataManager.commit(new CommitContext(parent, child))//Get saved parent

parent.setName("name");
dataManager.commit(parent); //Throws exception
```

A test project in the attachment.

---
Original issue: https://youtrack.haulmont.com/issue/PL-10424

**Comment by andreysubbotin** [comment]
If the entity is filtered by RLS, do not remove it from commit result

**Comment by andreysubbotin** [comment]
Unit Tests: 
master: https://git.haulmont.com/platform/refapp/commit/f49e3bc45d0052992f9ba75f8b278185101d78e7
release_6_9: 
https://git.haulmont.com/platform/refapp/commit/33eb85e9d8136a9d2f3c27ec70cc796756315191
