### ISSUE TITLE
Ability to use local.app.properties with UberJAR

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#697]
Currently, there is no way to use `local.app.properties` with UberJar on production server

---
Original issue: https://youtrack.haulmont.com/issue/PL-10440

**Comment by gglcrash** [comment]
https://github.com/cuba-platform/cuba-gradle-plugin/commit/a18f55835511abb9e9a0e8cc5300eb0294b5fa89

Ability to use local.app.properties with UberJAR was implemented.
Properties file (local.app.properties) should be located at the **${app.home}/conf/${module}/ directory**, where ${app.home} - home directory of the application and ${module} - corresponding module, for example:
_/usr/admin/application/conf/app/local.app.properties_ 
or
_/usr/tmpUser/conf/app-core/local.app.properties_

**Comment by alexbudarov** [comment]
@knstvk shouldn't we use here the same local.app.properties file for both "app" and "app-core" modules, like in single WAR?

**Comment by knstvk** [comment]
> @knstvk shouldn't we use here the same local.app.properties file for both "app" and "app-core" modules, like in single WAR?

Agree, it should be as simple as adding `local.app.properties` to app home.

**Comment by knstvk** [comment]
UberJAR will read local.app.properties from app home if its web.xml is correct, see https://youtrack.cuba-platform.com/issue/STUDIO-6936
