### ISSUE TITLE
Scrolling doesn't work for Table header in case of disabled Table

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#705]
A topic on the support forum: https://www.cuba-platform.ru/discuss/t/gorizontalnyj-skroll-u-table-i-grouptable/1377

Reproduces on CUBA 6.5+

---
Original issue: https://youtrack.haulmont.com/issue/PL-10473

## Updates
If the table is disabled, then the scroll bar works for the table body and for table header.

![table-header-scroll](https://user-images.githubusercontent.com/35256248/64537156-571bb980-d32b-11e9-9670-c2e218fe3ed3.gif)

## QA
Check that scrolling also working for table header in case of disabled `Table`, `GroupTable` or `TreeTable`.

**Comment by Mihail063** [comment]
Scrolling doesn't work for table header in case of disabled `TreeTable`.

**Comment by GlebDurygin** [comment]
### Updates
If the `TreeTable` is disabled, then the scroll bar works for the table body and for table header.
