### ISSUE TITLE
Swagger documentation is not generated correctly for overloaded REST service methods

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#707]
In case of some REST service has few methods with the same name but with different parameters (overloaded methods) we cannot generate correct Swagger documentation due to restrictions in the Swagger 2.0 Specification (GitHub issue: https://github.com/OAI/OpenAPI-Specification/issues/182).

Will be fixed when [https://github.com/swagger-api/swagger-core swagger-core] will be released with 2.0.0 version

---
Original issue: https://youtrack.haulmont.com/issue/PL-10487

**Comment by dtsaryov** [comment]
Moved to REST API Addon issue: [cuba-platform/restapi#1](https://github.com/cuba-platform/restapi/issues/1)
