### ISSUE TITLE
Add an ability to set popup position for the PopupView component

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#713]
A topic on the support forum: https://www.cuba-platform.com/discuss/t/define-a-place-on-a-frame-where-popupview-will-be-shown/4030

---
Original issue: https://youtrack.haulmont.com/issue/PL-10506

## Updates
The `PopupView` has new methods to set popup position:
* `void setPopupPosition(int top, int left)` - sets the popup position;
* `void setPopupPositionTop(int top)` - sets the top popup position;
* `void setPopupPositionLeft(int left)` - sets the left popup position
* `void setPopupPosition(PopupPosition position)` - sets the popup position using standard values.

And the component has new methods to get popup position:
* `int getPopupPositionTop()` - returns the top popup position;
* `int getPopupPositionLeft()` - returns the left popup position;
* `PopupPosition getPopupPosition()` - returns the top popup position or null if position is set via `setPopupPosition(PopupPosition position)`.

The standard values for popup position:
* DEFAULT, (In the middle of the minimized value)
* TOP_LEFT,
* TOP_CENTER,
* TOP_RIGHT,
* MIDDLE_LEFT,
* MIDDLE_CENTER,
* MIDDLE_RIGHT,
* BOTTOM_LEFT,
* BOTTOM_CENTER,
* BOTTOM_RIGHT;

If the popup position is set using the standard values, the left and top values will be reset and vice versa. Also, the popup will be displayed  with a slight indentation. User can disable this indent by overriding `$popup-horizontal-margin` and `$popup-vertical-margin` variables in styles.

### Test project
[popupview-popup-position.zip](https://github.com/cuba-platform/cuba/files/3508457/popupview-popup-position.zip)

## QA
Check the popup position setting using standard values and by entering custom values.

**Comment by Mihail063** [comment]
1. Open the attachment in issue project
2. Set Popup Position (0, 0) for the PopupView
3. Run the project and open the screen
4. Show PopupView
![изображение](https://user-images.githubusercontent.com/24281695/69142179-b3474a80-0adf-11ea-9d8f-6cca82d0bcc0.png)
2. setPopupPosition(PopupView.PopupPosition.TOP_LEFT)
![изображение](https://user-images.githubusercontent.com/24281695/69142288-ebe72400-0adf-11ea-9a27-6b39c7894238.png)
AR: The results of the two methods should look similar

**Comment by GlebDurygin** [comment]
The above case is not reproduced.

If the user sets the `PopupView` position using `setPopupPosition(0, 0)`, the popup will be displayed in the upper left corner.

![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/268c7941-16f7-4aa7-80f3-0ce11242bf30)

If the user sets the `PopupView` position using `setPopupPosition(PopupView.PopupPosition.TOP_LEFT)`, the popup will be displayed in the upper left corner with a slight indentation. User can disable this indent by overriding `$popup-horizontal-margin` and `$popup-vertical-margin` variables in styles.

![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/5c6273c5-bd40-439a-8364-3fad5031774e)
