### ISSUE TITLE
New UI component data binding API

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#718]
New UI component data binding API

1. All UI fields now have type parameter:
```
LookupField<User>, TextField<Integer>, etc
```

2. 
All previous datasources still working (Old screens only).
`setDatasource()` method deprecated;

New data container will work only in new screens.

Value Source interface (components with value, e.g. TextField):
- XML dataContainer property
- programmatically `setValueSource()`

Options interface (LookupField, OptionsList, RadioButtonGrup, CheckBoxGroup):
- XML optionsContainer
- programmatically `setOptions()`

Items interface (Table, Tree, DataGrid):
- XML dataContainer
- programmatically `setItems()`

**Breaking changes**:

If you have used auto cast with value in Fields:
```
LookupField lookupField;
...
User user = lookupField.getValue();
```

This code will not be compiled in version 7.0.

You have to provide explicit type for field:
```
LookupField<User> lookupField;
```

**Comment by jreznot** [comment]
Major rework and design are finished, closing this

**Comment by natfirst** [comment]
Wait until this [issue](https://github.com/cuba-platform/cuba/issues/719) is fixed
