### ISSUE TITLE
Show currently running schedulers in scheduled tasks screen

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#720]
Sherlock has many long schedulers which do their work in the night or early morning. Nightly run can last up to several hours.

For some system maintenance operations we would like to know - whether there are any schedulers running right now. Because we might don't want to interrupt them or they might interfere with our actions.

So it would be good to have a sub-screen or dialog in Scheduled Tasks which shows schedulers which are running at the moment.
Information to show: bean/method name etc, start time, host name and so on.

---
Original issue: https://youtrack.haulmont.com/issue/PL-10525

## Updates
The `Scheduled Tasks` screen has a new button `Running tasks` for displaying currently running scheduled tasks.

![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/5273302e-575d-4689-8603-ae63d6d7f9ac)

The `Scheduled Running Tasks` screen has a button `Refresh` for updating the list of running scheduled tasks. The table contains the columns: beanName, methodName, className, scriptName, userName, startDate, permittedServers, methodParametersString, description.

![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/913e60db-ae28-4426-a8e7-4b943f90d678)

## QA
* Check that scheduled tasks on the `Scheduled Running Screen` are displayed correctly - only current running tasks are displayed.

**Comment by natfirst** [comment]
Get rid of the additional Refresh button in the Buttons panel
![image](https://user-images.githubusercontent.com/17950251/66760410-17f50100-eeb3-11e9-8226-1282e5ba0500.png)
