### ISSUE TITLE
Expose an API to change the theme

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#721]
A topic on the support forum: https://www.cuba-platform.com/discuss/t/change-themes-at-runtime/4053 

A user has only one way to set the theme of UI - he should use Vaadin API: `com.vaadin.ui.UI#setTheme`

**Comment by dtsaryov** [comment]
It seems that no API required - it correctly works with solution proposed in issue description. All available themes can be found via `ThemeConstantsRepository` bean and its method `getAvailableThemes()`.
