### ISSUE TITLE
Add an ability to setup web resources cache time

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#722]
## Updates

Two config properties are added:
- `WebConfig.getWebResourcesCacheTime()` (app property: `cuba.web.resourcesCacheTime`) 
Enables to configure whether web resources should be cached or not. Zero cache time disables caching at all. Value is in seconds

- `WebConfig.getWebJarResourcesCacheTime` (app property: `cuba.web.webJarResourcesCacheTime`) 
Enables to configure whether WebJar resources should be cached or not. Zero cache time disables caching at all. Value is in seconds

#### Custom caching time

1. Setup caching in the following way:
```
# web-app.properties

cuba.web.resourcesCacheTime = 136
cuba.web.webJarResourcesCacheTime = 631
```
2. Run an app
3. Check that custom caching configuration works correctly via Browser development tools:

Web resource
![caching_web_res](https://user-images.githubusercontent.com/6183810/45147907-1b5d8980-b1d7-11e8-9162-2cd13c67e0e8.png)

WebJar resource (`External Files` -> `Upload Many`)
![caching_webjar_res](https://user-images.githubusercontent.com/6183810/45148071-7c855d00-b1d7-11e8-9453-422e50876d45.png)

#### Cache check

1. Configure cache time about 1 min and run app
2. Check that all resources are cached for the next min in case of page refresh (F5)
3. Check that all resources are reloaded after 1 min passed in case of page refresh (F5)

Cached resources:
![cached](https://user-images.githubusercontent.com/6183810/45148498-70e66600-b1d8-11e8-8057-968a9b64c044.png)

#### Disabled cache

Configure caching in the following way:
```
# web-app.properties

cuba.web.resourcesCacheTime = 0
cuba.web.webJarResourcesCacheTime = 0
```

Check that resources are reloaded always. 

Please note that some resources can be still cached (for example, `styles.scss`). They will not be reloaded until changed. This case can be check with theme modifying - extend some theme, hot deploy it with Gradle task (`deployTheme` / `deployThemes`). Changes should be applied without "hard refresh" (Ctrl + F5), just with refresh (F5).

#### Disabled cache and production mode

1. Enable production mode and disable caching:
```
# web-app.properties

cuba.web.productionMode = true
cuba.web.webJarResourcesCacheTime = 0
```

2. Run app and open a screen that uses some WebJar resource
3. Check logs - a message about disabled cache in production mode should be there

---
Original issue: https://youtrack.haulmont.com/issue/PL-10536

**Comment by dtsaryov** [comment]
Duplicates #425
