### ISSUE TITLE
Swagger schema errors

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#723]
A topic on the support forum: [https://www.cuba-platform.com/discuss/t/swagger-schema-errors/4128 link]

---
Original issue: https://youtrack.haulmont.com/issue/PL-10537

**Comment by dtsaryov** [comment]
Moved to REST API Addon issue: [cuba-platform/restapi#2](https://github.com/cuba-platform/restapi/issues/2)
