### ISSUE TITLE
Move REST v1 to app component

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#727]
It seems that it is time to get rid of it in the core framework.

### Updates

REST v1 is extracted as app component: [JPA Web API](https://github.com/cuba-platform/jpawebapi)

### QA

Checkout the addon and install it locally: `gradlew assemble install` or use private Nexus repository

Checklist:

- [ ] CORS configuring
- [ ] All functions described in documentation work correctly both for **web** and **portal** modules
- [ ] Old URL mappings ([Docs 6.5](https://doc.cuba-platform.com/manual-6.5/rest_api.html))  are used - `{host:port}/app/dispatch/api/*` - for web, `{host:port}/app-portal/api/*` - for portal
- [ ] App component features work for all deployment options (Standard, WAR / Single WAR, UberJAR / Single UberJAR)

**Comment by dtsaryov** [comment]
REST v1 is extracted as app component: [JPA Web API](https://github.com/cuba-platform/jpawebapi).
