### ISSUE TITLE
Add an ability to obtain metadata for enumerations that are used as field datatypes

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#729]
A topic on the support forum: [https://www.cuba-platform.com/discuss/t/cuba-platform-rest-api-anomalies/4129 link]

---
Original issue: https://youtrack.haulmont.com/issue/PL-10564

**Comment by gorbunkov** [comment]
`PropertyType` and `ClientType` enums mentioned in the forum topic implement the `EnumClass` interface in the latest release. So I see no value in the issue now.
