### ISSUE TITLE
Code completion in Edit Condition screen does not overwrite entered part of attribute name

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#737]
Preconditions:
1. Menu > Administration > Entity Inspector
2. select some 'Entity Type'
3. Click by link 'Add search condition'
4. click 'Create new' then 'Select' button

Test case:
1. In field 'Where' of 'Edit Conditions' browse insert next text "{E}.i" (without quotes)
2. Press Ctrl + Spase, click by 'id' item

ER: attribute 'id' is replaced in 'Where' field
AR:  attribute 'id' is added in 'Where' field

---
Original issue: https://youtrack.haulmont.com/issue/PL-10624

**Comment by soraksh** [comment]
Same problem as https://github.com/cuba-platform/cuba/issues/1015
