### ISSUE TITLE
Kryo incorrectly deserializes HashSet instances

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#742]
https://github.com/EsotericSoftware/kryo/issues/528

---
Original issue: https://youtrack.haulmont.com/issue/PL-10644

**Comment by alexbudarov** [comment]
@andreysubbotin Can we fix it for ourselves?

**Comment by andreysubbotin** [comment]
For QA: test https://youtrack.cuba-platform.com/issue/PL-9459, change Order#lines from List to Set for testing purpose and enable KRYO serialization by setting: `cuba.serialization.impl = com.haulmont.cuba.core.sys.serialization.KryoSerialization` in the core and web properties
