### ISSUE TITLE
Implicitly add columns to table

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#746]
The current need to list explicitly all columns to be shown in a table has certain drawbacks:
1) extra code in screen layout, which in most cases duplicates view.
2) need to remember to add/remove columns to a table when model changes (esp. if done outside of Studio). 
3) it is very frequent when a developer forgets to add certain columns actually required by user

Solution:
Add something like the following to the table:
 
1) <includeColumns = “local”> 
Automatically adds columns depending on value: 
all – everything listed in view except system attributes (from StandardEntity)
local – all local attributes except system attributes (from StandardEntity)
local_with_system - ...
all_with_system - ...
 
2) <exclude column = ”createTs” />
Prevents displaying a column.
 
3) The "column" attribute remains as is as an explicit rule, overriding the implicit ones listed above. Thus this guarantees full back compatibility.
 
I assume the most frequent cases will be "all" or "local" with explicitly listing system/non-local attributes.

----
### Changes
Now there is another way to set columns in list component. We don't have to set them manually, it is enough to define a specific property in `columns` element and columns will be loaded.

Element `columns` in `Table, GroupTable, TreeTable, DataGrid, TreeDataGrid` has the following attributes: 
- `includeAll` - load all elements from the view that is defined in dataContainer or dataspurce..
- `exclude` - comma separated columns that should not be loaded to the list component. (e.g. `exclude="name, date"`)

If view contains another related entity it will load the whole entity as a property. It means that if you want to show, e.g. "address.street" you have to define it manually:
```
<columns includeAll="true">
    <column id="address.street"/>
</columns>
```
if view is null `includeAll` will load all properties from a given a entity and its ancestors.

### Examples
1. Will show all properties from the view in `customersDc`. If view contains system properties they will be shown too.
```
<groupTable id="groupTable"
            width="100%"
            height="100%"
            dataContainer="customersDc">
    <columns includeAll="true"/>
</groupTable>
```
2. Will show all properties excluding "name" and "order":
```
<groupTable id="groupTable" 
            width="100%"
            height="100%"
            dataContainer="customersDc">
    <columns includeAll="true" exclude="name, order"/>
</groupTable>
```
3. Will add specific attributes to the defined column and will group by "address" column.
```
<groupTable id="groupTable"
            width="100%"
            height="100%" 
            dataContainer="customersDc">
    <columns includeAll="true">
        <group>
            <column id="address"/>
        </group>
        <column id="name" sortable="false"/>
    </columns>
</groupTable>
```

### How to test
1. Make sure that you can use dynamic attributes with this feature:
- Try to add dynamic attributes to the table manually: 
```
<columns includeAll="true">
    <column id="+OrderCondition"/>
</columns>
```
- Add from UI (add screen with given table to "visibility"). It should add column with dynamic attribute.
2. Try some samples with datasource.
3. Check how it works with non-persistent entity;
4. Do not specify view, try to use `includeAll`
5. Try all new properties with `DataGrid`

**Comment by myatlevEvg** [comment]
Implement only "includeAll" and "exclude" properties.
