### ISSUE TITLE
Add the 'removeAll' method to the CalendarEventProvider

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#751]
https://www.cuba-platform.com/discuss/t/calendar-how-to-clear-all-events/4531/3

---
Original issue: https://youtrack.haulmont.com/issue/PL-10674

----
#### Changes
Now `EventProvider` in the Calendar component has a `removeAllEvents()` method. It will remove all events in the event provider list.

**How to use**
```
calendar.getEventProvider().removeAllEvents();
```

**Comment by natfirst** [comment]
Please, add more information about the method usage to the JavaDoc. 
For example, this method can not be used to delete events if they were in datasource.
