### ISSUE TITLE
Save UI component settings only if users change them

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#753]
At the moment settings of GroupBox / Table always saved on screen close

Original issue: https://youtrack.haulmont.com/issue/PL-10677

### Description
Components that implements `HasSettings`:
- Table, GroupTable, TreeTable
- DataGrid, TreeDataGrid
- Filter
- GroupBox
- ResizableTextArea
- SplitPanel

#### **If settings aren't changed, they will not be saved** 

**1. Table, GroupTable, TreeTable**
Table, TreeTable has following settings:
- Column visible
- Column sort
- Column resize
- Column reorder
- TextSelection
- Presentations
  
 GroupTable has the same things and additional:
- group column
  
**2. DataGrid, TreeDataGrid**
DataGrid, TreeDataGrid has:
- Column visible
- Column sort
- Column resize
- Column reorder
  
**3. GroupBox**
GroupBox has:
- GroupBox expanded
It always saves setting if **user** changes expanded
  
**4. ResizableTextArea**
ResizableTextArea has:
- width
- height

**5. SplitPanel**
SplitPanel has:
- position 
It always saves setting if **user** changes position

**6. Filter**
Filter has:
- expanded
- max result value (it does not save null value)
- default filter
- applyDefault

**Comment by natfirst** [comment]
1. Create a report with the table template
2. Open Show Reports Table screen
3. Run the report
4. Switch to another screen and then return
```
java.lang.StackOverflowError
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.isCommonTableSettingsChanged(WebAbstractTable.java:1994)
	at com.haulmont.cuba.web.gui.components.WebAbstractTable.isDefaultTableSettingsChanged(WebAbstractTable.java:2044)
```
