### ISSUE TITLE
Ignore accents in LookupField like components

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#755]
A topic on support forum: [link](https://www.cuba-platform.com/discuss/t/search-in-lookup-fields/4107)

Words with accents are incorrectly filtered for inputs without accents.

---
Original issue: https://youtrack.haulmont.com/issue/PL-10679

**Comment by dtsaryov** [comment]
Demo: [cuba-labs/lookupfield-filterpredicate](https://github.com/cuba-labs/lookupfield-filterpredicate).
