### ISSUE TITLE
Update FontAwesome in Vaadin with new icons

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#757]
* [x] Remove deprecated flag from FontAwesome enum
* [x] Introduce missing icons and update font files in Vaadin Fork
* [x] Check if there are two loaded fonts on web page: FontAwesome and VaadinIcons, we need only FontAwesome

---
Original issue: https://youtrack.haulmont.com/issue/PL-10687
---

### For QA

1. Check all icons from `CubaIcon` set.
2. Check them in halo and hover themes.

**Comment by jreznot** [comment]
We should disable Vaadin icons using SCSS variable:

It is defined in `_fonts.scss`:
```
/// Include VaadinIcons. They are included in Valo
/// since Vaadin Framework version 8.0 (#7979)
/// https://vaadin.com/icons

$v-icons: true !default;
```
