### ISSUE TITLE
False positive log message for Table Column "changing editable in runtime not supported"

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#76]
12:54:44,725 WARN  [Table] Changing editable for column in runtime is not supported

В такси в редакторе тарифов это используется.
И работает без глюков - наверное последующими вызовами сбрасывается кэш ячеек или что-то в этом роде.

---
Original issue: https://youtrack.haulmont.com/issue/PL-3616

**Comment by jreznot** [comment]
Obsolete
