### ISSUE TITLE
ClassCastException on hot-deploy of controller that is used from code

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#770]
Example:
```
UserBrowser screen = (UserBrowser) openWindow("user-browser");
```

If UserBrowser is changed then Studio hot deploys only UserBrowser class but not the classes that depend on UserBrowser.

As a workaround we have to restart the application or hot deploy all required classes manually from Intellij Idea.

Related Studio issue: https://youtrack.cuba-platform.com/issue/STUDIO-3951

**Comment by glaschenko** [comment]
Hot deploy also fails if we modify a bean, which inherits another class.

**Comment by knstvk** [comment]
Fixed by improving hot-deploy in Studio, see related issue.
