### ISSUE TITLE
IconProvider for value of PickerField

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#773]
See this demo: https://github.com/cuba-labs/colored-svg-icons

Implement
```Java
interface OptionIconProvider<T> {
    String getItemIcon(T item);
}
```

This icon will be automatically updated on value change

## Updates
The `PickerField` and `SuggestionPickerField` have the new methods:
* `setOptionCaptionProvider(Function<? super V, String> optionIconProvider)` - it provides you to set optionIconProvider to component.
* `Function<? super V, String> getOptionIconProvider()` - get optionIconProvider.
The `optionIconProvider` accepts the current value with the type set in the component. And returns a string - path to the icon. The icon sets inside the PickerField

![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/efe852c0-92d1-444f-91d4-afc4f12c3203)
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/0bdaaeb2-dd71-43c9-86aa-765b9e40d7bf)
## QA

To check `PickerField` and `SuggestionPickerField`: 
* Set icon for `PickerField` and set `iconProvider`. Both icons should be installed
```Java
pickerField.setIcon("icons/cancel.png");
pickerField.setOptionIconProvider(value -> "icons/add.png");
suggestionPickerField.setIcon("icons/chain.png");
suggestionPickerField.setOptionIconProvider(value -> "icons/cancel.png");
```
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/efe852c0-92d1-444f-91d4-afc4f12c3203)
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/0bdaaeb2-dd71-43c9-86aa-765b9e40d7bf)

* Set `iconProvider`, remove `iconProvider` and set icon. The inline style should be reset and the icon should be on the top of PickerField
```Java
pickerField.setOptionIconProvider(value -> null);
pickerField.setIcon("icons/cancel.png");
```
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/17ff094c-a377-449b-b102-283f6a9773da)

* Set icon and pass to `setOptionIconProvider` null value. The icon should stay
```Java
pickerField.setIcon("icons/add.png");
pickerField.setOptionIconProvider(null);
```
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/7e6433c8-6e75-4bac-b90d-b982d3dcac72)

* Set in iconProvider wrong path to the icon. The inline style should apply, but instead of the icon will be an empty place.
```Java
pickerField.setOptionIconProvider(value -> "wrong_path");
```
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/3dea50c0-3c8e-49cf-99fe-f3e79865fb65)

* Set in iconProvider a function. The "chain" icon should be installed when a field value equals null, else "cancel" icon should be installed.
```Java
@Inject
private SuggestionPickerField<User> suggestionPickerField;
@Inject
private PickerField<User> pickerField;

protected String generateIcon(User user) {
   return (user!= null) ? "icons/cancel.png" : "icons/chain.png";
}

@Subscribe
private void onInit(InitEvent event) {
        suggestionPickerField.setIcon("icons/add.png");
        pickerField.setIcon("icons/add.png");

        pickerField.setOptionIconProvider(this::generateIcon);
        suggestionPickerField.setOptionIconProvider(this::generateIcon);
}
```
When field value is null
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/ea4a7abf-994b-46c7-9a67-641c278f9bac)
When field value is not null
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/2b090d3f-e93c-4f7c-baa0-43b7fb31203a)

**Comment by myatlevEvg** [comment]
Reopen.
First case:
When you set the icon by ```pickerField.setOptionIconProvider(value -> "icons/close.png");``` icon doesn't display.

Second case:
1) Set icon to PickerField by ```pickerField.setIcon("icons/add.png");```
2) Open the screen
3) Select any instance by PickerField
AR: Icon disappear after returning from Edit screen.

**Comment by jreznot** [comment]
There is a known issue in SuggestionPickerField
