### ISSUE TITLE
EntityManager.flush() breaks cascade deletion policy

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#785]
see patch for refapp 6.8

```
public class UserRole extends StandardEntity {
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "USER_ID")
    @OnDeleteInverse(DeletePolicy.CASCADE)
    private User user;
   ...

}

...

    User user = dataManager.load(new LoadContext<>(User.class).setId(userId));

    persistence.runInTransaction(em -> {
        em.remove(user);
        em.flush();
    });
```

UserRoles are expected to be soft-deleted with their User.
But if I put em.flush() after removing User - cascade deletion does not trigger.
If I comment em.flush() statement - test passes successfully.

---
Original issue: https://youtrack.haulmont.com/issue/PL-10741

**Comment by knstvk** [comment]
The same happens when using `TransactionalDataManager.save()`
