### ISSUE TITLE
User Filter looks cutted after applying "Search by role"

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#789]
This problem doesn't depend on visibility of Filter border ( `borderVisible` property ).

Reproduces only in Firefox (Edge & Chrome work good).

Halo:

![image](https://user-images.githubusercontent.com/1066152/46358306-c9920d00-c677-11e8-94ff-8ea55529e29f.png)

Havana:

![image](https://user-images.githubusercontent.com/1066152/46358314-cd259400-c677-11e8-85ae-25ba1c349081.png)

**Comment by Flaurite** [comment]
Can't reproduce in: 6.9, 6.10, 7.0
