### ISSUE TITLE
Determining remote IP address by remote client layers

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#792]
Do not trust IP address passed from non-trusted environments

**Comment by jreznot** [comment]
Now if users access the system from Desktop client IP address passed in credentials is not taken into account and replaced with IP address of Desktop client.

Also, non-trusted clients cannot access TrustedClientService and IdpService even if they pass correct trusted client password.

**Comment by alexbudarov** [comment]
@jreznot 
> Make sure that you enabled "cuba.checkServiceCallFromTrustedIp" application property on the middleware.

What is "cuba.checkServiceCallFromTrustedIp"? I can't find this string with search in path in 6.8.
