### ISSUE TITLE
Support collections of dynamic attributes in RuntimePropertiesFrame

### ISSUE THREAD

**Issue by rapekas** [cuba-platform/cuba#798]
Support collections of dynamic attributes in `RuntimePropertiesFrame`.

**Comment by natfirst** [comment]
1. Create categorized entity and screens for it with runtimePropFrame
2. Create collection dynamic attribute with Integer type for this entity
3. Open entity screen for editing, select category
4. Add two or more attributes by list editor
5. Try to save the entity

*A.R.* Invalid number format notification appears
*E.R* Entity item should be saved without alerts

The same problem occurs with Double type.
