### ISSUE TITLE
Complicated JPQL query with one-to-one related entities returns no results

### ISSUE THREAD

**Issue by dtaimanov** [cuba-platform/cuba#803]
### Environment

- Platform version: 6.8 
- Project: RefApp 6.8
- Database: Postgresql
- Operating system: Linux

### Problem
Complicated queries with ````where```` statement like

```` where((dc.driver is not null and false = true)or(dc.driver is null and false = false)) ````

returns empty result list while appropriate entity exists. This problem doesn't affect all types of relations between entities but one-to-one type at least.

It seems to be incorrect transformation to SQL.

#### Steps:
1. Use RefApp 6.8
1. Apply patch [ref6_8.patch.zip](https://github.com/cuba-platform/cuba/files/1957680/ref6_8.patch.zip)
1. Restart project
1. Go to Administration -> JMX Console -> Object Name: 'PersistenceManager'
1. Type 
````select dc from ref$DriverCallsign dc where((dc.driver is not null and false = true)or(dc.driver is null and false = false))```` 
into 'jpqlLoadList()' field and press 'Invoke'
#### Expected result:
- Returned one entity (Callsign 'ORPHAN')
#### Actual result:
- No entity returned

**Comment by andreysubbotin** [comment]
EclipseLink JPA provider uses inner join for paths like `dc.driver`, so you can explicitly specify left join in JPQL query:
```
select dc from ref$DriverCallsign dc left join dc.driver d where((d.id is not null and false = true)or(d.id is null and false = false))
```
