### ISSUE TITLE
Extension-friendly DeclarativeColumnGenerator

### ISSUE THREAD

**Issue by ikuchmin** [cuba-platform/cuba#804]
Currently you need to override `GroupTableLoader`, `TreeTableLoader`, `TableLoader` If you wanna change default behavior for DeclarativeColumnGenerator.

https://github.com/cuba-platform/cuba/blob/5c268e51f1f462568b14e55fe990be0a636bc5e3/modules/gui/src/com/haulmont/cuba/gui/xml/layout/loaders/AbstractTableLoader.java#L162

**Comment by jreznot** [comment]
Does not make sense since 7.0
