### ISSUE TITLE
Partial localization of extended screens

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba#824]
### Environment

- Platform version: 6.8.5+

### Description of the bug or enhancement

Localization to additional languages (not EN/RU) is not picked for several strings when a standard CUBA screen is extended. 

WTR:

See, for example, User editor in the attached sample.
![image](https://user-images.githubusercontent.com/11287637/42512842-a4055144-8466-11e8-83b0-3270424bc496.png)

One of the possible reasons: these messages are in the message pack which is different from this screen's pack. Possible solution: replace message key by path+key.

1) user-edit.xml

Actual:
`<field id="passw" custom="true" caption="msg://password"/>`

Expected:
`<field id="passw" custom="true" caption="msg://com.haulmont.cuba.gui/app.security.user.password"/>`

Actual:
`<field id="confirmPassw" custom="true" caption="msg://confirmPassword"/>`

Expected:
`<field id="passw" custom="true" caption="msg://com.haulmont.cuba.gui/app.security.user.confirmPassword"/>`

2) sending-message-browse.xml

Actual:
```
<column id="dateSent">
    <formatter class="com.haulmont.cuba.gui.components.formatters.DateFormatter" 
                       format="msg://dateTimeWithSeconds"/>
</column>
```

```
<column id="updateTs">
    <formatter class="com.haulmont.cuba.gui.components.formatters.DateFormatter"
                       format="msg://dateTimeWithSeconds"/>
</column>
```

Expected:
```
<column id="dateSent">
    <formatter class="com.haulmont.cuba.gui.components.formatters.DateFormatter" 
                       format="msg://com.haulmont.cuba.gui/dateTimeWithSeconds"/>
</column>
```

```
<column id="updateTs">
    <formatter class="com.haulmont.cuba.gui.components.formatters.DateFormatter"
                       format="msg://com.haulmont.cuba.gui/dateTimeWithSeconds"/>
</column>
```

3) change-password-dialog.xml
add paths to all messages

The [existent workaround](https://www.cuba-platform.com/discuss/t/extending-screen-resets-caption-locale/4402) does not help in all cases, see the [forum issue](https://www.cuba-platform.com/discuss/t/french-translation-applied-partially-on-extended-user-screen/4865/4?u=shiryaeva) and the test project attached:

[loctest.zip](https://github.com/cuba-platform/cuba/files/2180528/loctest.zip)

**Comment by jreznot** [comment]
For correct screen extension we have to create both `messages.properties` and `messages_ru.properties` files. If we have many locales and then extend screen Studio creates them automatically.

**Comment by jreznot** [comment]
You have not localized messages that belong to UserEditor screen. Add them to `com/company/loctest/web/screens/messages_fr.properties`:

```
password = Mot de passe
confirmPassword = Mot de passe (+)
loginMsg = Login is not set (FR)
createCaption = New User (FR)
roleName = Role name (FR)
localizedRoleName = Localized role (FR)
```

Sample works as expected, closing the issue.

Demo with fixes: [https://app.zenhub.com/files/54624511/a6a94ed8-ff18-42b9-ad13-f4ef18af908f/download](https://app.zenhub.com/files/54624511/a6a94ed8-ff18-42b9-ad13-f4ef18af908f/download)
