### ISSUE TITLE
DataManager.getCount throws NPE if query is not defined in LoadContext

### ISSUE THREAD

**Issue by ym-shepelev** [cuba-platform/cuba#834]
Environment
- Platform version: 6.8

Description
Sometimes it is useful to perform simple operations via DataManager without defining a query to make it applicable for different entity classes. For example, we can load the entity without query, setting only its ID in LoadContext. But we cannot do the same with DataManager.getCount.

See the patch for refapp (release_6_8):
[NPE_in_getCount.zip](https://github.com/cuba-platform/cuba/files/1990868/NPE_in_getCount.zip)
It works as follows: on the Colour browser, for any selected Colour, it performs two method calls: loadColourWithId(UUID id) and getCountOfColoursWithId(UUID id). 
Both methods don't define a query: only entity class and id are set in LoadContext. But the first one works as it should: it loads an entity, and the second one throws NPE because of query == null.

Steps:
1. Open Colours browser.
2. Create any Colour.
3. Select it.

**ER:** no exceptions. 
**AR:** java.lang.NullPointerException
	at com.haulmont.cuba.core.app.RdbmsStore.getCount(RdbmsStore.java:281)
	at com.haulmont.cuba.core.app.DataManagerBean.getCount(DataManagerBean.java:98)
        ...
        at com.haulmont.cuba.client.sys.DataManagerClientImpl.getCount(DataManagerClientImpl.java:58)
	at com.haulmont.refapp.gui.app.colour.ColourBrowser.getCountOfColoursWithId(ColourBrowser.java:83)
        ...

**Comment by knstvk** [comment]
Fixed in #953
