### ISSUE TITLE
User session log is not updated when REST API token is revoked

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#841]
@haulmont-git commented on [Tue Nov 28 2017](https://github.com/cuba-platform/charts/issues/19)

User session log is not updated when REST API token is revoked

---
Original issue: https://youtrack.haulmont.com/issue/PL-10086

**Comment by gorbunkov** [comment]
Already fixed in the https://youtrack.cuba-platform.com/issue/PL-10635
