### ISSUE TITLE
Incorrect display of scrolling for Token List with fixed width

### ISSUE THREAD

**Issue by zudba** [cuba-platform/cuba#848]
### Environment

- Platform version: 6.8.7
- Client type:  Web, Desktop

### Description of the bug or enhancement

Scrolling for items with long caps is incorrectly displayed if the Token List components have a fixed width.

### Steps:
1. Apply the patch to the RefApp
2. Add a user with a long name

#### On the Desktop Client:
1. Go to the screen "Test Samples" -> "TokenList"
2. Select the created user from the list

A.R.: The selected user name doesn't fit, there is no scrolling, the delete button of the selected item is missing
E.R.: The selected user name doesn't  fit, but scrolling is available, with the ability to delete the selected item

#### On the Web Client:

1. Change the Visual Theme to "Havana"
2. Go to the screen "Test Samples" -> "TokenList"
3. Select the created user from the list

A.R: The selected user name doesn't fit, there is a double scrolling

![image](https://user-images.githubusercontent.com/6183810/45691508-de47ae80-bb69-11e8-9db6-0a641c8878de.png)

E.R.: The selected user doesn't fit, the standard scrolling of the component appears

RefApp patch: [tokenlist.zip](https://github.com/cuba-platform/cuba/files/2000836/tokenlist.zip)

Note: the problem with the web client reproduces only in Google Chrome browser

**Comment by alexbudarov** [comment]
Up.

Is it possible to fix this bug in 6.8?

**Comment by dtsaryov** [comment]
@alexbudarov 

will try to fix if you need it

**Comment by alexbudarov** [comment]
@dtsaryov yes please, we have this token list layout problem in one of often used screens.

**Comment by dtsaryov** [comment]
@myatlevEvg 

Desktop problem is fixed in cuba-platform/cuba#819, check only problem in web.
