### ISSUE TITLE
Login field is duplicates on sec$User creation screen in Entity Inspector

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#851]
1) Create a project
2) Start the application server
3) Open Administration - Entity Inspector
4) Select the sec$User entity
5) Click the Create button
AR: Login field displaying two times
Affected version: 6.8+

![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/95cc3d09-2410-4d06-a1ed-992e0c496ac2)

**Comment by jreznot** [comment]
It is login and loginLowerCase system property. They have the same caption.
