### ISSUE TITLE
CubaEntityListViewBehavior should return a promise from the remove method

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#858]
- Platform version: 6.9

- Client type: Polymer

### Description of the bug or enhancement

`CubaEntityListViewBehavior` has `remove` method that invokes `remove` method of `<cuba-entities>` but it doesn't return a promise returned by `<cuba-entities>`

**Comment by jreznot** [comment]
Please move to the appropriate repository

**Comment by dtsaryov** [comment]
Issue is moved to [cuba-elements/cuba-ui](https://github.com/cuba-elements/cuba-ui).
