### ISSUE TITLE
Components bound to datasource with compound property path do not receive value updates

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#86]
Consider this micro-patch to refapp 5.1.

There are two fields for country now in the driver editor.

When you change value in the first field, second gets updated.
When you change second one - first does not receive value update.

That is, if you have
field.setDatasource(ds, "address.country")

If country changes - field does not receive an update.
If address changes - field does not receive an update.
Only if item in ds changes - then field receives an update.

This is a big API problem for developers.
After some experience with datasources, everyone strongly believes that datasources do always work. 
In this property path case only half of functionality works, and half - does not.

This leads to most developers not being able to understand why field does not receive updates, without external advice.

---
Original issue: https://youtrack.haulmont.com/issue/PL-4075

**Comment by knstvk** [comment]
Relates to #474

**Comment by knstvk** [comment]
Fixed for new data API in c30b3e3
