### ISSUE TITLE
Boolean string value instead of checkbox in Entity Inspector  screen

### ISSUE THREAD

**Issue by pctF** [cuba-platform/cuba#864]
In my opinion it would be more logical to use string value TRUE/FALSE/NULL in entity inspector screen for Booleans since it is administration screen and checkbox have no support for null- value visualisation.
Forum discuss: 
https://www.cuba-platform.ru/discuss/t/inspektor-sushhnostej-otobrazhenie-boolean-znachenij-v-tekstovom-vide/1682

- Platform version: 6.8.* 

- Client type:  Web, Desktop

**Comment by Flaurite** [comment]
Check range is datatype
