### ISSUE TITLE
Add more strong password hashing algorithm

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#868]
Use BCrypt for passwords by default

http://techblog.bozho.net/the-hash-challenge/

Also, use special stored salt in SEC_USER table

**Comment by jreznot** [comment]
For instance, we could use bcrypt: https://en.wikipedia.org/wiki/Bcrypt

**Comment by andreysubbotin** [comment]
Migration path: create database or set `cuba.passwordEncryptionModule=cuba_Sha1EncryptionModule` in the all app.properties files in your project
