### ISSUE TITLE
Attribute security token is encrypted for all entities regardless of settings

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#874]
### Environment
- Platform version: 6.8 snapshot

### Description of the bug or enhancement
Apply this patch to refapp 6.8:
[refapp-attribute-security.txt](https://github.com/cuba-platform/cuba/files/2027098/refapp-attribute-security.txt)

It sets this property:
> cuba.useSpringApplicationEventsToSetupAttributeAccess = false

and disables overridden com.haulmont.refapp.core.RefAppAttributeSecuritySupport bean.

Refapp only defines SetupAttributeAccessHandler beans for these entities: Address, Callsign, Car, Driver, Place.
So I expect that no attribute security support stuff will be executed for sec$User entities, right?

- Launch server
- Put breakpoint to line of com.haulmont.cuba.core.sys.SecurityTokenManager#writeSecurityToken with "cipher.doFinal".
Breakpoint props: Suspend = None, Evaluate and log = entity
- Open menu Administration -> Users

Expected: debugger outputs nothing
Actual:
`
com.haulmont.cuba.security.entity.FilterEntity-b61d18cb-e79a-46f3-b16d-eaf4aebb10dd [managed]
com.haulmont.cuba.security.entity.User-60885987-1b61-4247-94c7-dff348347f93 [managed]
com.haulmont.cuba.security.entity.User-60885987-1b61-4247-94c7-dff348347f93 [managed]
com.haulmont.cuba.security.entity.Group-0fa2b1a5-1d68-4d69-9fbd-dff348347f93 [managed]
com.haulmont.cuba.security.entity.User-a405db59-e674-4f63-8afe-269dda788fe8 [managed]
com.haulmont.cuba.security.entity.Group-0fa2b1a5-1d68-4d69-9fbd-dff348347f93 [managed]
com.haulmont.cuba.security.entity.User-a33e5ab0-da5a-11e1-be55-230d351c6ac3 [managed]
com.haulmont.cuba.security.entity.Group-0fa2b1a5-1d68-4d69-9fbd-dff348347f93 [managed]
`
It encrypts and writes security tokens for all entities loaded by DataManager.

**Comment by andreysubbotin** [comment]
Problem is actual only for 6.8
