### ISSUE TITLE
Use more clear exception message in case of not enhanced entities

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#875]
### Environment

- Platform version: 7.0

### Description of the bug or enhancement

If user run tests that work with entities via Intellij IDEA he will get an exception with not clear message:

```
javax.persistence.PersistenceException: Exception [EclipseLink-6114] (Eclipse Persistence Services - 2.6.2.cuba22): org.eclipse.persistence.exceptions.QueryException
Exception Description: You must define a fetch group manager at descriptor (com.haulmont.cuba.security.entity.Group) in order to set a fetch group on the query (null)
Query: ReadObjectQuery(referenceClass=Group sql="SELECT ID, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, NAME, UPDATE_TS, UPDATED_BY, VERSION, PARENT_ID FROM SEC_GROUP WHERE ((ID = ?) AND (DELETE_TS IS NULL))")
FetchGroup(){deleteTs, name, deletedBy}

	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:551)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:401)
	at com.haulmont.cuba.core.sys.QueryImpl.getResultFromCache(QueryImpl.java:633)
	...
```
This exception is thrown because Intellij IDEA uses not enhanced versions of entities.

It is suggested to catch this exception in `QueryImpl` and tell user that he should enable the following setting in IDE: `Build, Execution, Deployment` -> `Build Tools` -> `Gradle` -> `Runner` -> `Delegate IDE build/run actions to gradle`.

Check this post: [Gradle Goodness: Delegate Build And Run Actions To Gradle In IntelliJ IDEA](https://mrhaki.blogspot.ru/2016/11/gradle-goodness-delegate-build-and-run.html).

Related issue: [Compatibility with Intellij Gradle plugin](https://github.com/cuba-platform/cuba/issues/814).

**Comment by andreysubbotin** [comment]
Throw exception if entity isn't enhanced while execute `QueryImpl.getResultList`, `QueryImpl.getSingleResult` and `QueryImpl.getFirstResult`

**Comment by soraksh** [comment]
It was decided to throw an exception at the application start. See [#1926](https://github.com/cuba-platform/cuba/issues/1926).
