### ISSUE TITLE
Why attribute access support is disabled in refapp?

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#882]
### Environment
- Platform version: refapp 6.8

### Description of the bug or enhancement
This bean: com.haulmont.refapp.core.RefAppAttributeSecuritySupport
overrides platform behavior and disables some part of attribute access functionality when you launch server.

It makes difficult to reproduce attribute access-related problems. You're trying to do something but it works on refapp while not working in real world. Or visa versa.

**Comment by knstvk** [comment]
Issue moved to [cuba-platform/refapp #1](https://github.com/cuba-platform/refapp/issues/1) via [**ZenHub**](https://www.zenhub.com/)
