### ISSUE TITLE
Enabling 'groovy support' causes desktop app to fail

### ISSUE THREAD

**Issue by robaho** [cuba-platform/cuba#885]
see https://www.cuba-platform.com/discuss/t/duplicate-classes-in-jar-prevent-desktop-client-from-working/5135

**Comment by jreznot** [comment]
It is the new behavior of Gradle in case of merged source sets. Gradle recommends that we use separate source folders for different languages.

**Comment by jreznot** [comment]
I've created issue in Studio: https://youtrack.cuba-platform.com/issue/STUDIO-4632
Closing this.
