### ISSUE TITLE
Support images in LookupField/LookupPickerField

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba#887]
### Description of the enhancement

Add support for images in LookupField/LookupPickerField, similarly to existing icons support (see Vaadin ComboBox ItemIconGenerator). 

For instance, we want to load images from database.

[Forum source link](https://www.cuba-platform.ru/discuss/t/kartinka-v-lookupfield-ili-searchfield/1713)

## Updates
The `LookupField`, `LookupPickerField` and `SearchPickerField` have the new methods:
* `setOptionImageProvider(Function<? super V, Resource> optionImageProvider)` - it provides you to set optionImageProvider to component.
* `Function<? super V, Resource> getOptionImageProvider()` - get optionImageProvider.
The `optionImageProvider` accepts the current value with the type set in the component. And returns an image Resource. The image sets inside the component.

`LookupField`
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/641f0087-d674-4022-aa62-8be019e4286e)
`LookupPickerField`
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/88aaf128-186a-45eb-8ecc-350ae90695bb)
`SearchPickerField`
![изображение.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/176342e0-7127-4d86-9846-3e300b2f3348)

The resource can be of the type: `ThemeResource`, `FileDescriptorResource`, `FileResource`, `StreamResource`, `ClasspathResource`, `UrlResource`, `RelativePathResource` and etc.

### Test project
[option-image-provider.zip](https://github.com/cuba-platform/cuba/files/3309696/option-image-provider.zip)

## QA
Check the installation of various types of resources for components `LookupField`, `LookupPickerField` and `SearchPickerField`.

**Comment by knstvk** [comment]
@GlebDurygin what about SuggestionPickerField?

**Comment by ovchinnikovsp** [comment]
@GlebDurygin It would be really good to have the support of the images in the SuggestionField\SuggestionPickerField as they are replaced the old components SearchField/SearchPickerField, which had such ability.
