### ISSUE TITLE
Implement the ability to move constraints to other access groups

### ISSUE THREAD

**Issue by oshiryaeva** [cuba-platform/cuba#897]
Add a button "Move to group" and/or a lookup in the Constraint editor
![constraint](https://user-images.githubusercontent.com/11287637/40656905-fedccfd8-6356-11e8-8982-4a8cc5a3ac96.png)
![constraint2](https://user-images.githubusercontent.com/11287637/40656906-034ba59e-6357-11e8-8c65-b226e69517c7.png)

**Comment by jreznot** [comment]
We will not introduce `group` attribute in constraint editor, but will implement "Move to group" button on constraints tab.
