### ISSUE TITLE
Add logging for gradle uploadArchives task as it was in the past

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#901]
### Description of the bug or enhancement
Old gradle versions (2.1) used to write convenient log messages during uploadArchives:
```
[:xxxx-global:uploadArchives] Uploading: com/haulmont/xxxx/xxxx-global/43-SNAPSHOT/xxxx-global-43-20180529.072117-34.jar
to repository remote at http://zzzz.com/nexus/content/repositories/snapshots
[11:21:18]
```
These messages can be used to assure that we have set correct artifact version, group, name, and upload repository.

New gradle versions do not log such messages.
Can we return them back in CUBA gradle plugin?

**Comment by jreznot** [comment]
Issue moved to [cuba-platform/cuba-gradle-plugin #36](https://github.com/cuba-platform/cuba-gradle-plugin/issues/36) via [**ZenHub**](https://www.zenhub.com/)
