### ISSUE TITLE
'ORA-00932' occurs when filtering by dynamic attribute with type String

### ISSUE THREAD

**Issue by feoktistov-v** [cuba-platform/cuba#907]
### Environment

- Platform version: 5.9 
- Database: ORACLE

### Description of the bug or enhancement
Error happens: "SQLSyntaxErrorException: ORA-00932: inconsistent datatypes: expected - got CLOB"

**Comment by jreznot** [comment]
Is it reproduced on the latest version ? 6.8 / 6.9 ?

**Comment by andreysubbotin** [comment]
String value has VARCHAR type in the ORACLE DB
