### ISSUE TITLE
Don't paint red * after required field

### ISSUE THREAD

**Issue by leonnash23** [cuba-platform/cuba#908]
### Environment

- Platform version: 6.8
- Client type: Web

### Description of the bug or enhancement

1. Create a new application.
2. Create a new screen. 
3. Put TextField into SplitPanel. Make TextField required. 
4. Start app.
5. Help -> Settings -> Visual Theme -> Choose havana. Relogin for apply changes.
6. Open screen with TextField and SplitPanel.

- Expected behavior
Red * after the TextField.
- Actual behavior
Red * after the TextField is missing :C

**Comment by jreznot** [comment]
SplitPanel does not paint captions, descriptions and required for left/right panel components. Use intermediate vbox component. Put your TextField inside this vbox.

**Comment by leonnash23** [comment]
@jreznot а ты хорош
