### ISSUE TITLE
Docking Split Panel not working correctly

### ISSUE THREAD

**Issue by Zynde** [cuba-platform/cuba#918]
### Environment

- Platform version: 6.8.9
- Client type: Web
- Browser: only tried Chrome
- Database: HSQLDB
- Operating system: macOS

### Description of the bug or enhancement

The new Split Panel Docking doesn't seem to work fully. I have added a Split Panel on the MainWindow and have the Left containing the WorkArea and the Right containing the Folders Pane. I set the right to dock. This works fine. If you minimize the Panel with the Dock button and logout then log back in the dock button doesn't expand the window. You have to manually drag the window to resize it again.

**Comment by dtsaryov** [comment]
@Zynde could you try to reproduce the issue again?

And if it still can be reproduced please clarify what exactly doesn't work. Now it remembers the last position and uses it after re-login.
