### ISSUE TITLE
Support required indicator for layout components

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#92]
The following components must have ability to show the required indicator:
* HBoxLayout
* VBoxLayout
* CssLayout
* FlowBoxLayout
* ScrollBoxLayout
* GridLayout
* GroupBoxLayout
* HtmlBox

**Comment by glebfox** [comment]
The components above implements the `HasRequiredIndicator` interface, i.e. their have the following methods:
* `isRequiredIndicatorVisible()`
* `setRequiredIndicatorVisible(boolean visible)`

Bear in mind that required indicator is displayed only if `$v-show-required-indicators: true` is specified in a theme defaults (the same as for the `required` property).

`GroupBoxLayout` displays required indicator only if `caption` is specified.
