### ISSUE TITLE
Introduce application property to disable PerformanceLogInterceptor

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#920]
At the moment, `PerformanceLogInterceptor` always applied if bean method has `@PerformanceLog` annotation. Let's introduce application property to disable this aspect if needed for performance reasons.

**Comment by soraksh** [comment]
To disable `PerformanceLogInterceptor` add to app.properties file property `cuba.performanceLogDisabled` with value `true`. To enable it again delete this property or set value to `false`.
