### ISSUE TITLE
Create new theme or update the old one

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba#932]
Halo theme is too faded

[Theme - sketches.zip](https://github.com/cuba-platform/cuba/files/2149412/Theme.-.sketches.zip)

Issues to be addressed

- [x] Default colors
- [x] Variables / modes / mixins
- [x] Icons
- [x] Compatibility with all the standard app components

Do not forget about SASS doc comments for all new variables

### Table of Contents

- [Updates](#updates)
  - [General description](#description)
  - [Brand new Login Form](#loginform)
  - [Compact main TabSheet](#compactts)
  - ["Friendly" filter](#friendlyfilter)
  - [Highlighed primary actions](#primary)
  - [Selection & Hover in table view components](#selectionhover)
  - [Increased size of popup and context menu items](#popupcontextmenusuze)
  - [Increased size of CheckBox & OptionsGroup components](#checkboxoptionsgroupsize)
  - [Increased size of dialog window headers](#dialogwindow)
  - [Bold fonts](#boldfonts)
- [Affected components list](#affected)

- [Introduced SCSS variables suggested for using](#variables)
  - [Button](#buttonscss)
  - [CheckBox](#checkboxscss)
  - [DataGrid](#datagridscss)
  - [Generic filter](#filterscss)
  - [Login window](#loginwindowscss)
  - [Main TabSheet](#maintsscss)
  - [Menu (default main menu)](#mainmenuscss)
  - [OptionsGroup](#optionsgroupscss)
  - [SideMenu](#sidemenuscss)
  - [Table](#tablescss)
  - [TabSheet](#tabsheetscss)
  - [Window](#windowscss)
- [Checking ToDo](#check)

<a name="updates"/>

# Updates

There are all updates related to the new theme called `hover`.
<a name="description"/>

### General description

- The new theme has a flat design without shades, bevels, etc.
- Increased space between components makes UI more lightweight & clear
- Emphasis on actions and primary elements

![hover_theme](https://user-images.githubusercontent.com/6183810/43566941-35948594-9641-11e8-954d-e16caf29edfe.png)

<a name="loginform"/>

### Brand new Login Form

A new login form is created both for `halo` and `hover` themes:

![image](https://user-images.githubusercontent.com/6183810/43305451-e7be0a1e-9188-11e8-9845-fc48097490d9.png)

The login form is also changed in the `havana` theme but it looks according to the theme.

<a name="compactts"/>

### Compact main TabSheet

Tabs now have no margins and paddings; highlighted active tab.

![image](https://user-images.githubusercontent.com/6183810/43306487-65075b62-918c-11e8-88da-ab92ee1e5a65.png)

<a name="friendlyfilter"/>

### "Friendly" filter

![image](https://user-images.githubusercontent.com/6183810/43306637-d5ab7628-918c-11e8-99d4-db193defde19.png)

<a name="primary"/>

### Highlighed primary actions

This feature can be used in custom screens by setting the `primary` attribute for `<action/>` or `<button/>` in XML or with fluent API for the `BaseAction` inheritors programmatically:
```Java
action
    .withPrimary(true)
    .withCaption(getMessage("actionCaption"))
    .withHandler(e ->
        showNotification(...));
```

![pr_act_dialog](https://user-images.githubusercontent.com/6183810/43307429-49f1c314-918f-11e8-8d14-2ccbf8326d3d.png)

<a name="selectionhover"/>

### Selection & Hover in table view components

Tables and DataGrid components highlight hovered item now:

![table_hover](https://user-images.githubusercontent.com/6183810/43306312-c46bdf8e-918b-11e8-8512-ac818bace2e5.png)

<a name="popupcontextmenusuze"/>

### Increased size of popup and context menu items

![popup_items](https://user-images.githubusercontent.com/6183810/43308105-6e031da0-9191-11e8-921d-a2a9619cd58a.png)

<a name="checkboxoptionsgroupsize"/>

### Increased size of CheckBox & OptionsGroup components

![image](https://user-images.githubusercontent.com/6183810/43308783-adb1715c-9193-11e8-8147-22a6ca642142.png)

<a name="dialogwindow"/>

### Increased size of dialog window headers

![image](https://user-images.githubusercontent.com/6183810/43308925-3e1cece4-9194-11e8-9c20-b8610cd05ad8.png)

<a name="boldfonts"/>

### Bold fonts

Bold font style is used for additional emphasis for:
- buttons
- dialog headers
- main menus (default and side menu)
- table view component headers (Table & DataGrid)

<a name="affected"/>

## Affected components list

- button
- checkbox
- context menu
- data grid
- generic filter
- login window
- main menus
- main window
- managed tabsheet (as main tabsheet)
- options group
- popup button
- sidemenu
- table
- tabsheet
- window

<a name="variables"/>

## Introduced SCSS variables suggested for using

<a name="buttonscss"/>

### Button

- `$cuba-button-font-weight` - button caption font weight
- `$cuba-highlight-primary-action` - whether button that has primary action or marked as primary itself should be highlighted (boolean)

<a name="checkboxscss"/>

### CheckBox

- `$cuba-checkbox-size` - size of checkbox in pixels

<a name="datagridscss"/>

### DataGrid

- `$cuba-datagrid-header-font-weight` - font weight of datagrid header
- `$cuba-datagrid-highlight-hover-row` - whether hovered row should be colored (boolean)

<a name="filterscss"/>

### Generic filter

- `$cuba-filter-friendly-search-button` - whether filter search button should have "friendly" style (boolean)

<a name="loginwindowscss"/>

### Login window

- `$cuba-login-btn-background` - login window button background
- `$cuba-login-btn-font-weight` - login window button font weight
- `$cuba-login-btn-height` - login window button height
- `$cuba-login-btn-width` - login window button width
- `$cuba-login-caption-font-size` - login window caption font size
- `$cuba-login-caption-font-weight` - login window caption font weight
- `$cuba-login-logo-height` - login window logo height
- `$cuba-login-username-height` - login window user name field height
- `$cuba-login-password-height` - login window password field height

<a name="maintsscss"/>

### Main TabSheet

- `$cuba-maintabsheet-selected-tab-font-weight` - main tabsheet selected tab font weight
- `$cuba-maintabsheet-tabcontainer-background-color` - main tabsheet tab container background color
- `$cuba-maintabsheet-tab-margin-left` - distance between tabs in main tabsheet

<a name="mainmenuscss"/>

### Menu (default main menu)

- `$cuba-menubar-menuitem-font-weight` - menu items font weight
- `$cuba-menubar-submenu-item-font-weight` - submenu items font weight

<a name="optionsgroupscss"/>

### OptionsGroup

- `$cuba-optiongroup-size` - size of options group in pixels

<a name="sidemenuscss"/>

### SideMenu

- `$cuba-sidemenu-background-color` - sidemenu background color
- `$cuba-sidemenu-item-font-weight` - sidemenu items font weight
- `$cuba-sidemenu-separate-items` - whether sidemenu items should be separated with lines (boolean)
- `$cuba-sidemenu-timezone-font-weight` - sidemenu timezone indicator font weight
- `$cuba-sidemenu-title-font-size` - sidemenu title font size
- `$cuba-sidemenu-title-font-weight` - sidemenu title font weight
- `$cuba-sidemenu-title-gradient` - whether a gradient should be used as a background for sidemenu title (boolean)
- `$cuba-sidemenu-userindicator-font-weight` - sidemenu user indicator font weight

<a name="tablescss"/>

### Table

- `$cuba-table-header-font-weight` - table header font weight
- `$cuba-table-highlight-hover-row` - whether hovered row should be colored (boolean)

<a name="tabsheetscss"/>

### TabSheet

- `$cuba-tabsheet-tab-caption-selected-color` - tabsheet selected tab caption color
- `$cuba-tabsheet-tab-border-selected-color` - tabsheet selected tab bottom border color

<a name="windowscss"/>

### Window

- `$cuba-window-modal-header-font-weight` - modal window header font weight
- `$cuba-window-modal-header-height` modal window header height

<a name="check"/>

## Checking ToDo:

- [ ] `halo` looks as usual (sizes, backgrounds, borders, font style)
- [ ] consistent appearence in the new theme
- [ ] different browsers

**Comment by jreznot** [comment]
Additional sketches

[additional-sketches.zip](https://github.com/cuba-platform/cuba/files/2183960/additional-sketches.zip)

**Comment by jreznot** [comment]
Updates sketches 
[cuba-flat-theme-draft.zip](https://github.com/cuba-platform/cuba/files/2202509/cuba-flat-theme-draft.zip)

**Comment by jreznot** [comment]
We have decided to include this into 6.10 release

**Comment by natfirst** [comment]
OptionsGroup component selection shadow (all browsers). Open Test Samples > OptionsGroup component:
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/199415ba-04f7-4cfa-9984-59d2d7d9ad45)

**Comment by natfirst** [comment]
There are no differences between the enabled and disabled CheckBox
Disabled:
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/93564d1d-d51b-4ee8-aec9-31d727c79181)
Enabled:
![image.png](https://images.zenhubusercontent.com/5ae335564b5806bc2bd0e9cf/296602b1-ac12-4d63-9397-2f3fc2a30e78)

**Comment by dtsaryov** [comment]
@natfirst please check that in case of `cuba.localeSelectVisible` is false the "Remember Me" checkbox is not misaligned:

![image](https://user-images.githubusercontent.com/6183810/43720339-45466102-99a1-11e8-8420-d0cb22a6df11.png)
