### ISSUE TITLE
CubaWarBuilding task must rename file specified in logbackConfigurationFile parameter to logback.xml

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/cuba#943]
### Environment

- Platform version: 6.8+

**Comment by andreysubbotin** [comment]
Issue moved to [cuba-platform/cuba-gradle-plugin #41](https://github.com/cuba-platform/cuba-gradle-plugin/issues/41) via [**ZenHub**](https://www.zenhub.com/)
