### ISSUE TITLE
Do not trigger buttons and menu items if they are not accessible for user because of modal windows

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#948]
Now in the platform user interface, many components are available to interactions with them even if they are not accessible for user because of modal dialog windows. We should ignore incorrect access to disabled components.

It can help avoid many of situations with two or more dialog windows like in [this](https://www.cuba-platform.ru/discuss/t/cuba-studio-se-6-8-5-izmenenie-multiple-open-v-svojstvah-okna-v-studio-ne-vliyaet-na-atribut-multipleopen-v-razmetke-ekrana/1773) forum topic.

There are two main problem situations:

- repetitive click on button that shows modal dialog
- advanced users try to hide modal curtain with CSS hacks and click on menu / buttons

**Comment by jreznot** [comment]
Relates to #183

**Comment by jreznot** [comment]
List of entry points that check if UI component is accessible for user:

- Button / LinkButton click
- Shortcuts (for instance in OptionDialog / Window - Ctrl-Enter, ESC)
- Window breadcrumbs
- TabSheet close button
- Dialog Window close button
- Double click in Table / Tree / DataGrid
- Menu item click - AppMenu / SideMenu
- Menu item shortcuts if they are assigned

In case of ignored action the application will print to log messages like:
```
DEBUG com.haulmont.cuba.web.gui.WebWindow - Ignore shortcut action because Window is inaccessible for user
```
