### ISSUE TITLE
Query and ID should not be mandatory for LoadContext

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#953]
When LoadContext is created it is required to specify either query or ID so loading will work. API is not clear enough for it. For example, this code is valid:
```
        LoadContext<Person> personsCtx = LoadContext.create(Person.class)
                .setView("person-view");
        return dataManager.loadList(personsCtx);
```

As a developer I expect that this query will return me all persons, but instead I got an exception. So it would be nice to return full list similar to query 
```
select p from Person p
```

Or create overloaded methods like:

```
    public static <E extends Entity> LoadContext<E> create(Class<E> entityClass, Query query)

    public static <E extends Entity> LoadContext<E> create(Class<E> entityClass, Object id)

```
as well as change corresponding constructors to avoid mandatory setters on LoadContext creation.

### Environment

- Platform version: 6.9.0

**Comment by knstvk** [comment]
More clear API has been added recently, see http://files.cuba-platform.com/cuba/release-notes/6.9/#misc
