### ISSUE TITLE
Custom filter component condition name lost the alignment with the checkbox when adding another condition from the list

### ISSUE THREAD

**Issue by myatlevEvg** [cuba-platform/cuba#957]
1) Open any screen with the filter component
2) Click Add search condition and then Create new
3) Create any condition and save it
4) Click Add search condition and select one from the list

AR: ![image.png](https://images.zenhubusercontent.com/5ae4196d4b5806bc2bd0fcf9/6226a9d9-ade1-431d-ba53-894e8de99fe5)

**Comment by Flaurite** [comment]
There is no correct fixes to solve this problem

**Comment by Flaurite** [comment]
Please, check all browsers with "Hover", "Halo" and "Havana"
