### ISSUE TITLE
Get rid of Vaadin add-ons dependencies

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/cuba#958]
Embed add-ons code to Platform with original copyrights.

- [x] [popupbutton](https://github.com/henrikerola/PopupButton)
- [x] [aceeditor](https://github.com/ahn/vaadin-aceeditor)
- [x] [dragdroplayouts](https://github.com/parttio/dragdroplayouts)
- [x] [vaadin-context-menu](https://github.com/vaadin/context-menu)

**Comment by natfirst** [comment]
Try to set the mode to the AceEditor:
```
<sourceCodeEditor id="sourceCodeEditor" mode="SQL"/>
```
Exception in the log:
```
16:47:19.716 INFO  com.vaadin.server.VaadinServlet - Requested resource 
[/VAADIN/resources/ace/mode-sql.js] not found from filesystem or through class loader. 
Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.
```
