### ISSUE TITLE
Exception when getting date formatting mask for locale different than OS locale

### ISSUE THREAD

**Issue by belyaev-andrey** [cuba-platform/cuba#967]
### Environment

- Platform version: 6.9.0 
- Client type: Web
- Browser: Chrome 67.0.3396.87 
- Database: HSSQL
- Operating system: Windows 10 Pro

### Description of the bug

Exception is thrown for web date selector component if locale is not present in OS locale list. 

- Minimal reproducible example can be found at https://github.com/belyaev-andrey/mask-test 
1. Open the project in CUBA and run it on OS with English (en) locale.  
2. Open the app at http://localhost:8080/app address using your browser
3. Enter default username and password (admin/cuba)
4. In the main menu open Anlage->Personen form 

- Expected behavior: Person browsing form and editor are open (partly localized maybe) with default date formatting mask. 

- Additional steps: enabling locale in app properties by uncommenting property cuba.availableLocales with English language fixes the issue. 

- Actual behavior: Exception is thrown - 
```
java.lang.IllegalArgumentException: Not found format strings for locale de
	at com.haulmont.cuba.core.sys.FormatStringsRegistryImpl.getFormatStringsNN(FormatStringsRegistryImpl.java:48)
	at com.haulmont.chile.core.datatypes.Datatypes.getFormatStringsNN(Datatypes.java:50)
	at com.haulmont.cuba.web.gui.components.WebDateField.<init>(WebDateField.java:89)
```

**Comment by glebfox** [comment]
@belyaev-andrey the demo project is no longer available, could you please provide either steps to reproduce or demo project

**Comment by belyaev-andrey** [comment]
[mask-test.zip](https://github.com/cuba-platform/cuba/files/3201808/mask-test.zip)
The sample project is attached, but cannot reproduce the issue now. Looks like it was somehow fixed.
