### ISSUE TITLE
BulkEditor.setEnabled() method doesn't change the state of the action in the table context menu

### ISSUE THREAD

**Issue by gorbunkov** [cuba-platform/cuba#970]
Add a BulkEditor component to the screen.
Specify its "enable" property in the screen xml descriptor to "false"
In the java controller set the "enable" property to true (bulkEditor.setEnabled(true))
AR the bultEditor button will become enabled, but an action in the context menu of the table component will remain disabled.
----
### For QA
Steps to reproduce:
1. Apply patch for refapp 
[bulkEditor_reproduce.zip](https://github.com/cuba-platform/cuba/files/2155105/bulkEditor_reproduce.zip)
2. Open screen: _Tests -> Sample Prototype_
3. Try to select a few rows
4. Do right click to show context menu
5. BulkEdit action must be enabled.

**Comment by Flaurite** [comment]
It is not a bug. BulkEditor component and BulkEditorAction is different things.
For given problem use should use:
```
Action action = table.getAction("bulkEdit");
if (selected > 1) {
    if (action != null) {
        action.setEnabled(true);
    }
} else {
    if (action != null) {
        action.setEnabled(false);
    }
}
```
