### ISSUE TITLE
QueryCache cluster messages are sent even when query cache is disabled

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba#988]
### Environment

- Platform version: 6.8 snapshot
- Middleware cluster

### Description of the bug or enhancement
- Open refapp project
- Add to refapp-app.properties:
> cuba.queryCache.enabled = false

- Launch refapp.
- Put breakpoint to first line of com.haulmont.cuba.core.app.ClusterManager#send
Suspend = none
Evaluate and log = message

- Go to Callsign browser. Create several callsigns.
Expected: no overhead related to query cache

Actual:
Every time when callsign is created - a cluster message appears:
```
com.haulmont.cuba.core.sys.entitycache.QueryCacheManager$InvalidateQueryCacheMsg@1cdd61ae
com.haulmont.cuba.core.sys.entitycache.QueryCacheManager$InvalidateQueryCacheMsg@7e388b7a
com.haulmont.cuba.core.sys.entitycache.QueryCacheManager$InvalidateQueryCacheMsg@43db9f74
```

On our test cluster (which is restarted every night) it leads to impressive ClusterManager stats:
```
Class: com.haulmont.cuba.core.sys.entitycache.QueryCacheManager$InvalidateQueryCacheMsg; received: 113858, 15000426 bytes; sent: 37495, 4751278 bytes
Class: com.haulmont.cuba.security.app.UserSessions$UserSessionInfo; received: 1004, 1251480 bytes; sent: 839, 1052126 bytes
```
QueryCacheMsg traffic is 10 times more than user sessions.

**Comment by alexbudarov** [comment]
Also, just a observation: cluster message is NOT sent when Callsign is being edited or removed. It leads me to suspision that query cache synchronization does not wok for edit / remove.

**Comment by andreysubbotin** [comment]
com.haulmont.cuba.core.sys.entitycache.EntityCacheConnection invalidates query cache for UPDATE and DELETE operations in the cluster
