### ISSUE TITLE
Login button does nothing in Firefox

### ISSUE THREAD

**Issue by dtsaryov** [cuba-platform/cuba#990]
### Environment

- Platform version: 6.8.5
- Client type: Polymer
- Browser: Firefox
- Operating system: Windows (probably, not only Windows)

### Description of the bug or enhancement

1. Create new application and add `polymer-client` module.
2. Run app and open Polymer UI.
3. Fill login form and click button.

E.R. Successfully logged in
A.R. Nothing happens. There is no any request in developer console.

**Comment by natfirst** [comment]
Same behaviour in Safari

**Comment by web-devel** [comment]
Polyfill [issue](webcomponentsjs/issues/958)
Works in latest Safari with native Shadow Dom support
